classdef QuadrupedGraphicsTestSupport
    %QUADRUPEDGRAPHICSTESTSUPPORT Deterministic local graphics test data.
    methods (Static)
        function value = fixture()
            root = fullfile(lmz.util.ProjectPaths.tests(), 'fixtures', ...
                'graphics', 'slip_quadruped');
            value = lmz.io.SafeJson.read(fullfile(root, ...
                'source_geometry_r2025b_macos_arm64.json'), 'Root', root);
        end

        function value = fingerprint(array)
            linear = array(:);
            value = [sum(linear); sum(abs(linear)); ...
                sum(linear.^2); sum((1:numel(linear)).' .* linear)];
        end

        function simulation = simulation(backFraction)
            if nargin < 1, backFraction = 0.4; end
            time = [0; 0.3; 1];
            states = [ ...
                1.0 0.8 1.2 0 0.1 0 0.2 0 -0.15 0 0.25 0 -0.1 0; ...
                1.2 0.8 1.2 0 0.1 0 0.2 0 -0.15 0 0.25 0 -0.1 0; ...
                1.8 0.8 1.2 0 0.1 0 0.2 0 -0.15 0 0.25 0 -0.1 0];
            modes = struct('back_left', [false; true; false], ...
                'front_left', [false; true; false], ...
                'back_right', [false; false; false], ...
                'front_right', [false; false; false], 'period', 1);
            parameters = struct('k_leg', 20, 'k_swing', 5, ...
                'J_pitch', 0.1, 'l_leg', 1, 'phi_neutral', 0, ...
                'l_b', backFraction, 'k_r_leg', 1);
            names = {'BL_TD','BL_LO','FL_TD','FL_LO', ...
                'BR_TD','BR_LO','FR_TD','FR_LO','APEX'};
            times = [0.1 0.4 0.2 0.5 0.6 0.9 0.7 0.95 1];
            records = repmat(struct('Name', '', 'Time', 0, ...
                'State', zeros(1, 14), 'PreState', zeros(1, 14), ...
                'PostState', zeros(1, 14)), 9, 1);
            for index = 1:9
                records(index).Name = names{index};
                records(index).Time = times(index);
            end
            forces = zeros(3, 12);
            forces(:, 5:8) = repmat([1 2 3 4], 3, 1);
            forces(:, 9:12) = repmat([10 20 30 40], 3, 1);
            simulation = lmz.api.SimulationResult(time, ...
                lmzmodels.slip_quadruped.PhysicalStateSchema.create(), ...
                states, modes, struct('stride_period', 1), parameters, ...
                struct('source', 'quadruped-graphics-test'), ...
                struct('sourceCommit', ...
                '2c106101383ecee1b2a9d695efe09fbd72d5718a'), ...
                'EventRecords', records, 'GroundReactionForces', forces);
        end

        function profile = profile(identifier)
            if nargin < 1, identifier = 'research_legacy'; end
            root = fullfile(lmz.util.ProjectPaths.catalog(), 'slip_quadruped');
            config = lmz.viz.GraphicsConfig.fromJson( ...
                fullfile(root, 'graphics.lmz.json'), root, ...
                lmz.util.ProjectPaths.models(), 'lmzmodels');
            profile = config.getProfile(identifier);
        end
    end
end
