classdef TestQuadrupedResearchLegGeometry < matlab.unittest.TestCase
    methods (Test)
        function exactCompoundTopologyAndLocalSpring(testCase)
            geometry = lmzmodels.slip_quadruped.ResearchLegGeometry. ...
                compute([0 0], 1, 1, 0);
            testCase.verifyEqual(geometry.Spring1.Vertices(1:2, :), ...
                [-0.09 -0.4; 0.09 -0.4], 'AbsTol', 1e-15);
            testCase.verifyEqual(geometry.Spring1.Vertices(end, :), ...
                [-0.09 -0.8], 'AbsTol', 1e-15);
            testCase.verifyEqual(geometry.Spring1.Faces, ...
                [(1:14).', (2:15).']);
            testCase.verifyEqual(geometry.Spring2.Faces, ...
                [(1:2:13).', (2:2:14).']);
            testCase.verifySize(geometry.UpperBackground.Vertices, [26 2]);
            testCase.verifySize(geometry.UpperShading.Vertices, [60 2]);
            testCase.verifySize(geometry.Lower.Vertices, [54 2]);
            testCase.verifyEqual(geometry.UpperShading.Faces, ...
                [1 12; 3 9; 57 15; 54 18; 51 21; 48 24; 45 28; 42 31]);
        end

        function completeArrayFingerprintsMatchFixture(testCase)
            fixture = QuadrupedGraphicsTestSupport.fixture();
            canonical = fixture.canonical;
            geometry = lmzmodels.slip_quadruped.ResearchLegGeometry.compute( ...
                canonical.legAttachment, canonical.legCurrentLength, ...
                canonical.legRestLength, canonical.legAbsoluteAngle);
            names = {'Spring1','UpperBackground','UpperShading', ...
                'UpperOutline','Lower','Spring2'};
            for index = 1:numel(names)
                name = names{index};
                expectedVertices = ...
                    fixture.fingerprints.(['leg' name 'Vertices']);
                expectedFaces = fixture.fingerprints.(['leg' name 'Faces']);
                testCase.verifyEqual( ...
                    QuadrupedGraphicsTestSupport.fingerprint( ...
                    geometry.(name).Vertices), expectedVertices, ...
                    'RelTol', 3e-14, 'AbsTol', 1e-11);
                testCase.verifyEqual( ...
                    QuadrupedGraphicsTestSupport.fingerprint( ...
                    geometry.(name).Faces), expectedFaces, 'AbsTol', 0);
            end
        end

        function strictSourceContactAndSingleWrapArePreserved(testCase)
            contact = @(time, td, lo) ...
                lmzmodels.slip_quadruped.ResearchLegGeometry. ...
                isContact(time, td, lo, 1);
            testCase.verifyFalse(contact(0.1, 0.1, 0.4));
            testCase.verifyTrue(contact(0.2, 0.1, 0.4));
            testCase.verifyFalse(contact(0.4, 0.1, 0.4));
            testCase.verifyTrue(contact(0.9, 0.8, 0.2));
            testCase.verifyTrue(contact(0.1, 0.8, 0.2));
            testCase.verifyFalse(contact(0.5, 0.8, 0.2));
            testCase.verifyFalse(contact(0.5, 0.3, 0.3));
            testCase.verifyEqual( ...
                lmzmodels.slip_quadruped.ResearchLegGeometry.wrapOnce(-0.1, 1), ...
                0.9, 'AbsTol', 1e-15);
            testCase.verifyEqual( ...
                lmzmodels.slip_quadruped.ResearchLegGeometry.wrapOnce(1.1, 1), ...
                0.1, 'AbsTol', 1e-15);
        end

        function namedSimulationFrameUsesSourceStanceLength(testCase)
            simulation = QuadrupedGraphicsTestSupport.simulation();
            frame = lmzmodels.slip_quadruped.ResearchLegGeometry.frame( ...
                simulation, 2);
            testCase.verifyEqual(frame.Contact, [true true false false]);
            expected = frame.Attachments(1:2, 2).' ./ ...
                cos(frame.AbsoluteAngles(1:2));
            testCase.verifyEqual(frame.Lengths(1:2), expected, ...
                'AbsTol', 1e-14);
            testCase.verifyEqual(frame.Lengths(3:4), [1 1], 'AbsTol', 0);
            testCase.verifyEqual(frame.Feet(1:2, 2), [0; 0], ...
                'AbsTol', 1e-14);
            testCase.verifyEqual(frame.Schedule.tAPEX, 1);
        end
    end
end
