classdef TestGraphicsConfigValidation < matlab.unittest.TestCase
    methods (Test)
        function acceptsValidatedDeclarativeConfiguration(testCase)
            [folder,cleanup]=fixtureFolder();
            value=validConfig();writeJson(fullfile(folder,'graphics.lmz.json'),value);
            config=lmz.viz.GraphicsConfig.fromJson( ...
                fullfile(folder,'graphics.lmz.json'),folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels');
            testCase.verifyEqual(config.SchemaVersion,'1.0.0');
            testCase.verifyEqual(config.defaultForMaturity('tutorial'),'clean_generic');
            testCase.verifyEqual(config.getProfile('clean_generic').Style.lineWidth,2);
            config.validateContract({'world','body'},{});
            clear cleanup
        end

        function rejectsTraversalAndUntrustedRenderer(testCase)
            [folder,cleanup]=fixtureFolder();value=validConfig();
            value.profiles.styleFile='../outside.json';
            testCase.verifyError(@()lmz.viz.GraphicsConfig(value,folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels'),'lmz:Path:Traversal');
            value=validConfig();value.profiles.rendererClass='other.UntrustedRenderer';
            testCase.verifyError(@()lmz.viz.GraphicsConfig(value,folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels'), ...
                'lmz:Graphics:UntrustedRenderer');
            value=validConfig();
            value.profiles.rendererClass='lmzmodels.slip_quadruped.Model';
            testCase.verifyError(@()lmz.viz.GraphicsConfig(value,folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels'), ...
                'lmz:Graphics:RendererContract');
            clear cleanup
        end

        function rejectsDuplicateMissingAndIncompatibleDefaults(testCase)
            [folder,cleanup]=fixtureFolder();value=validConfig();
            value.profiles=[value.profiles value.profiles];
            testCase.verifyError(@()lmz.viz.GraphicsConfig(value,folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels'), ...
                'lmz:Graphics:DuplicateProfile');
            value=validConfig();value.defaultProfileByMaturity.tutorial='absent';
            testCase.verifyError(@()lmz.viz.GraphicsConfig(value,folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels'), ...
                'lmz:Graphics:MissingDefaultProfile');
            value=validConfig();value.profiles.maturities={'validated'};
            testCase.verifyError(@()lmz.viz.GraphicsConfig(value,folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels'), ...
                'lmz:Graphics:DefaultProfileMaturity');
            clear cleanup
        end

        function rejectsInvalidStyleAndCamera(testCase)
            [folder,cleanup]=fixtureFolder();value=validConfig();
            writeJson(fullfile(folder,'style.json'),struct('primaryColor',[2 0 0]));
            testCase.verifyError(@()lmz.viz.GraphicsConfig(value,folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels'),'lmz:Graphics:Color');
            writeJson(fullfile(folder,'style.json'),struct('lineWidth',2));
            value.profiles.camera.xLimits=[1 1];
            testCase.verifyError(@()lmz.viz.GraphicsConfig(value,folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels'), ...
                'lmz:Graphics:CameraLimits');
            value=validConfig();value.profiles.camera.followWindow=[1 -1];
            testCase.verifyError(@()lmz.viz.GraphicsConfig(value,folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels'), ...
                'lmz:Graphics:CameraValue');
            value=validConfig();value.profiles.layers={'ground','ground'};
            testCase.verifyError(@()lmz.viz.GraphicsConfig(value,folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels'), ...
                'lmz:Graphics:LayerType');
            clear cleanup
        end

        function bindsRequiredNamesToModelContract(testCase)
            [folder,cleanup]=fixtureFolder();value=validConfig();
            value.requiredParameters={'leg_length'};
            config=lmz.viz.GraphicsConfig(value,folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels');
            config.validateContract({'world','body'},{'leg_length'});
            testCase.verifyError(@()config.validateContract({'world'}, ...
                {'leg_length'}),'lmz:Graphics:UnknownRequiredFrame');
            testCase.verifyError(@()config.validateContract( ...
                {'world','body'},{}), ...
                'lmz:Graphics:UnknownRequiredParameter');
            clear cleanup
        end

        function rejectsIncompleteMaturityAndColorTable(testCase)
            [folder,cleanup]=fixtureFolder();value=validConfig();
            value.defaultProfileByMaturity=rmfield( ...
                value.defaultProfileByMaturity,'validated');
            testCase.verifyError(@()lmz.viz.GraphicsConfig(value,folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels'), ...
                'lmz:Graphics:DefaultMaturity');
            value=validConfig();
            writeJson(fullfile(folder,'style.json'), ...
                struct('faceColors',[1 1 1;2 0 0]));
            testCase.verifyError(@()lmz.viz.GraphicsConfig(value,folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels'), ...
                'lmz:Graphics:Color');
            clear cleanup
        end

        function rejectsInvalidRecordingFrameCountAndBackground(testCase)
            [folder,cleanup]=fixtureFolder();value=validConfig();
            value.profiles.recordingProfile.frameCount=1;
            testCase.verifyError(@()lmz.viz.GraphicsConfig(value,folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels'), ...
                'lmz:Graphics:RecordingFrameCount');
            value=validConfig();value.profiles.recordingProfile.frameCount=2.5;
            testCase.verifyError(@()lmz.viz.GraphicsConfig(value,folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels'), ...
                'lmz:Graphics:RecordingFrameCount');
            value=validConfig();
            value.profiles.recordingProfile.backgroundColor=[1 1 1 1];
            testCase.verifyError(@()lmz.viz.GraphicsConfig(value,folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels'), ...
                'lmz:Graphics:Color');
            value=validConfig();
            value.profiles.recordingProfile.backgroundColor=[0 0 2];
            testCase.verifyError(@()lmz.viz.GraphicsConfig(value,folder, ...
                lmz.util.ProjectPaths.models(),'lmzmodels'), ...
                'lmz:Graphics:Color');
            clear cleanup
        end
    end
end

function [folder,cleanup]=fixtureFolder()
folder=tempname;mkdir(folder);cleanup=onCleanup(@()removeFolder(folder));
scene=struct('schemaVersion','1.0.0','frames',{{'world','body'}}, ...
    'primitives',{{struct('type','marker','frame','body')}});
writeJson(fullfile(folder,'scene.lmz.json'),scene);
writeJson(fullfile(folder,'style.json'),struct('lineWidth',2, ...
    'primaryColor',[0.1 0.2 0.3]));
end

function value=validConfig()
profile=struct('id','clean_generic','label','Clean generic', ...
    'rendererClass','lmz.viz.SceneRenderer2D', ...
    'sceneFile','scene.lmz.json','styleFile','style.json', ...
    'camera',struct('xLimits',[-1 1],'yLimits',[-0.1 2], ...
    'dataAspectRatio',[1 1 1],'follow',false), ...
    'axis',struct('equal',true,'grid',false,'visible',true, ...
    'backgroundColor',[1 1 1]),'layers',{{'ground','model'}}, ...
    'overlays',{{}},'plotProfile','clean_generic', ...
    'recordingProfile',struct('frameCount',10,'fps',20,'dpi',100), ...
    'maturities',{{'tutorial','compatibility','validated','experimental'}});
defaults=struct('tutorial','clean_generic','compatibility','clean_generic', ...
    'validated','clean_generic','experimental','clean_generic');
value=struct('schemaVersion','1.0.0', ...
    'defaultProfileByMaturity',defaults,'requiredFrames',{{'world','body'}}, ...
    'requiredParameters',{{}},'profiles',profile);
end

function writeJson(path,value)
file=fopen(path,'w');assert(file>=0);cleanup=onCleanup(@()fclose(file));
fwrite(file,lmz.compat.Json.encode(value,true),'char');clear cleanup
end
function removeFolder(folder)
if exist(folder,'dir')==7,rmdir(folder,'s');end
end
