classdef TestQuadrupedResearchGroundGeometry < matlab.unittest.TestCase
    methods (Test)
        function sourceMeshCountsFacesAndExtents(testCase)
            geometry = lmzmodels.slip_quadruped.ResearchGroundGeometry.compute();
            testCase.verifyEqual(geometry.Summary.vertexCount, 20002);
            testCase.verifyEqual(geometry.Summary.faceCount, 5001);
            testCase.verifyEqual(geometry.Summary.stripeCount, 5000);
            testCase.verifyEqual(geometry.Hatch.Faces(1, :), ...
                [1 2 20001 20002]);
            testCase.verifyEqual(geometry.Hatch.Faces(2, :), ...
                [2 5002 10002 15002]);
            testCase.verifyEqual(geometry.Hatch.Faces(end, :), ...
                [5001 10001 15001 20001]);
            testCase.verifyEqual(geometry.Summary.xExtent, [-50.1 200.01], ...
                'AbsTol', 1e-12);
            testCase.verifyEqual(geometry.Summary.yExtent, [-0.11 0], ...
                'AbsTol', 1e-15);
        end

        function completeMeshFingerprintsMatchFixture(testCase)
            fixture = QuadrupedGraphicsTestSupport.fixture();
            geometry = lmzmodels.slip_quadruped.ResearchGroundGeometry.compute();
            expected = fixture.fingerprints;
            testCase.verifyEqual(QuadrupedGraphicsTestSupport.fingerprint( ...
                geometry.Field.Vertices), expected.groundFieldVertices, ...
                'AbsTol', 0);
            testCase.verifyEqual(QuadrupedGraphicsTestSupport.fingerprint( ...
                geometry.Hatch.Vertices), expected.groundHatchVertices, ...
                'RelTol', 2e-13, 'AbsTol', 2e-3);
            testCase.verifyEqual(QuadrupedGraphicsTestSupport.fingerprint( ...
                geometry.Hatch.Faces), expected.groundHatchFaces, ...
                'RelTol', 1e-15, 'AbsTol', 0);
        end
    end
end
