classdef TestQuadrupedResearchPhaseDiagramGeometry < matlab.unittest.TestCase
    methods (Test)
        function boxLabelsAndBarOrderingMatchSource(testCase)
            fixture = QuadrupedGraphicsTestSupport.fixture();
            geometry = lmzmodels.slip_quadruped.ResearchPhaseDiagramGeometry. ...
                compute(fixture.canonical.bodyX, fixture.canonical.schedule);
            testCase.verifyEqual(geometry.Box.Vertices, ...
                [1.4 1.59; 2.42 1.59; 2.42 1.91; 1.4 1.91], ...
                'AbsTol', 1e-15);
            testCase.verifyEqual(geometry.TextLabels, {'LH','LF','RF','RH'});
            testCase.verifyEqual(geometry.TextPositions, ...
                [1.432 1.8505; 1.432 1.7835; ...
                 1.432 1.7165; 1.432 1.6495], 'AbsTol', 1e-15);
            testCase.verifyEqual({geometry.Bars.Id}, {'BL','BR','FL','FR'});
            testCase.verifyEqual(geometry.BarDrawOrder, {'BL','BR','FL','FR'});
        end

        function completeBarFingerprintsMatchFixture(testCase)
            fixture = QuadrupedGraphicsTestSupport.fixture();
            geometry = lmzmodels.slip_quadruped.ResearchPhaseDiagramGeometry. ...
                compute(fixture.canonical.bodyX, fixture.canonical.schedule);
            testCase.verifyEqual(QuadrupedGraphicsTestSupport.fingerprint( ...
                geometry.Box.Vertices), fixture.fingerprints.phaseBox, ...
                'AbsTol', 1e-12);
            testCase.verifyEqual(QuadrupedGraphicsTestSupport.fingerprint( ...
                geometry.TextPositions), fixture.fingerprints.phaseText, ...
                'AbsTol', 1e-12);
            for index = 1:4
                code = geometry.Bars(index).Id;
                testCase.verifyEqual(QuadrupedGraphicsTestSupport.fingerprint( ...
                    geometry.Bars(index).Base.Vertices), ...
                    fixture.fingerprints.(['phase' code 'Base']), ...
                    'AbsTol', 1e-12);
                testCase.verifyEqual(QuadrupedGraphicsTestSupport.fingerprint( ...
                    geometry.Bars(index).Duration.Vertices), ...
                    fixture.fingerprints.(['phase' code 'Duration']), ...
                    'AbsTol', 1e-12);
            end
        end

        function wrappedAndEqualEventPoliciesAreExplicit(testCase)
            fixture = QuadrupedGraphicsTestSupport.fixture();
            schedule = fixture.canonical.schedule;
            schedule.tBL_TD = 0.8; schedule.tBL_LO = 0.2;
            schedule.tFL_TD = 0.3; schedule.tFL_LO = 0.3;
            geometry = lmzmodels.slip_quadruped.ResearchPhaseDiagramGeometry. ...
                compute(0, schedule);
            bl = geometry.Bars(1); fl = geometry.Bars(3);
            testCase.verifyTrue(bl.Wrapped);
            testCase.verifyEqual(bl.BaseColor, [0 0 0]);
            testCase.verifyEqual(bl.DurationColor, [1 1 1]);
            testCase.verifyFalse(fl.Wrapped);
            testCase.verifyEqual(fl.BaseColor, [1 1 1]);
            testCase.verifyEqual(fl.Duration.Vertices(:, 1), ...
                repmat(fl.Duration.Vertices(1, 1), 4, 1), 'AbsTol', 0);
        end
    end
end
