classdef TestQuadrupedResearchBodyGeometry < matlab.unittest.TestCase
    methods (Test)
        function symmetricBodyMatchesSourceRectangle(testCase)
            geometry = lmzmodels.slip_quadruped.ResearchBodyGeometry. ...
                compute([0 0 0], 0.5);
            expected = [-0.6 0.2; 0.6 0.2; 0.6 -0.2; ...
                -0.6 -0.2; -0.6 0.2];
            testCase.verifyEqual(geometry.Outline.Points, expected, ...
                'AbsTol', 1e-15);
            testCase.verifySize(geometry.PerimeterVertices, [80 2]);
            testCase.verifySize(geometry.ShadeFaces, [13 2]);
            testCase.verifyEqual(geometry.ShadeFaces(1, :), [4 78]);
            testCase.verifyEqual(geometry.ShadeFaces(end, :), [38 44]);
        end

        function asymmetricOffsetAndTranslationAreExact(testCase)
            geometry = lmzmodels.slip_quadruped.ResearchBodyGeometry. ...
                compute([0 0 0], 0.4);
            offset = sqrt(1)/15;
            testCase.verifyEqual(geometry.PerimeterVertices(1, :), ...
                [-0.5, 0.225+offset], 'AbsTol', 1e-15);
            testCase.verifyEqual(geometry.PerimeterVertices(30, :), ...
                [0.7, 0.225-offset], 'AbsTol', 1e-15);
            testCase.verifyEqual(geometry.Outline.Points(end, :), ...
                geometry.Outline.Points(1, :), 'AbsTol', 0);
        end

        function canonicalCompleteArrayFingerprintMatchesFixture(testCase)
            fixture = QuadrupedGraphicsTestSupport.fixture();
            canonical = fixture.canonical;
            geometry = lmzmodels.slip_quadruped.ResearchBodyGeometry. ...
                compute(canonical.bodyFrame, canonical.backFraction);
            expected = fixture.fingerprints;
            testCase.verifyEqual( ...
                QuadrupedGraphicsTestSupport.fingerprint( ...
                    geometry.PerimeterVertices), expected.bodyVertices, ...
                'RelTol', 2e-14, 'AbsTol', 1e-11);
            testCase.verifyEqual( ...
                QuadrupedGraphicsTestSupport.fingerprint(geometry.ShadeFaces), ...
                expected.bodyShadeFaces, 'AbsTol', 0);
            testCase.verifyEqual( ...
                QuadrupedGraphicsTestSupport.fingerprint(geometry.Outline.Points), ...
                expected.bodyOutline, 'RelTol', 2e-14, 'AbsTol', 1e-12);
            testCase.verifyEqual(geometry.Metadata.sourceCommit, ...
                fixture.source.commit);
        end
    end
end
