classdef WorkflowDescriptor
    %WORKFLOWDESCRIPTOR Validated inert registered scientific workflow.
    properties (SetAccess=private)
        SchemaVersion
        Id
        Label
        ModelId
        ProblemId
        Maturity
        ValidationStatus
        DataSourceId
        DefaultDatasetId
        DefaultPointIndex
        AxisPresetId
        VisualizationProfileId
        LayoutProfileId
        AllowedSteps
        SeedPreset
        SolveOptions
        ContinuationPreset
        HomotopyPreset
        FamilyScanPreset
        AnalysisViews
        Provenance
        ProblemConfiguration
        SourcePath
        SourceHash
        DataSource
        AxisPreset
        Workbench
    end
    properties (SetAccess=private, Transient)
        Registry=[]
    end
    methods
        function obj=WorkflowDescriptor(value,varargin)
            parser=inputParser;
            addRequired(parser,'value',@(x)isstruct(x)&&isscalar(x));
            addParameter(parser,'Registry',[]);
            addParameter(parser,'DataSource',[]);
            addParameter(parser,'AxisPreset',[]);
            addParameter(parser,'Workbench',[]);
            addParameter(parser,'SourcePath','',@ischar);
            addParameter(parser,'SourceHash','',@ischar);
            parse(parser,value,varargin{:});
            required={'schemaVersion','id','label','modelId','problemId', ...
                'maturity','validationStatus','dataSourceId', ...
                'defaultDatasetId','defaultPointIndex','axisPresetId', ...
                'visualizationProfileId','layoutProfileId','allowedSteps', ...
                'seedPreset','solveOptions','continuationPreset', ...
                'homotopyPreset','familyScanPreset','analysisViews','provenance'};
            requireFields(value,required);
            if ~strcmp(value.schemaVersion,'1.0.0')
                error('lmz:Workflow:DescriptorSchema', ...
                    'Unsupported workflow descriptor schema version.');
            end
            ids={'id','modelId','problemId','dataSourceId','axisPresetId', ...
                'visualizationProfileId','layoutProfileId'};
            for index=1:numel(ids),validateId(value.(ids{index}),ids{index});end
            if ~ischar(value.label)||isempty(strtrim(value.label))
                error('lmz:Workflow:DescriptorLabel', ...
                    'Workflow label must be nonempty text.');
            end
            if ~any(strcmp(value.maturity, ...
                    {'tutorial','compatibility','validated','experimental'}))|| ...
                    ~any(strcmp(value.validationStatus, ...
                    {'untested','tested','source-equivalent'}))
                error('lmz:Workflow:DescriptorStatus', ...
                    'Workflow maturity or validation status is invalid.');
            end
            if ~isnumeric(value.defaultPointIndex)|| ...
                    ~isscalar(value.defaultPointIndex)|| ...
                    ~isfinite(value.defaultPointIndex)|| ...
                    value.defaultPointIndex<1|| ...
                    value.defaultPointIndex~=fix(value.defaultPointIndex)
                error('lmz:Workflow:DefaultPoint', ...
                    'Workflow defaultPointIndex must be a positive integer.');
            end
            if ~isstruct(value.solveOptions)||~isscalar(value.solveOptions)|| ...
                    ~isstruct(value.provenance)||~isscalar(value.provenance)
                error('lmz:Workflow:DescriptorOptions', ...
                    'Workflow solve options and provenance must be objects.');
            end
            obj.SchemaVersion=value.schemaVersion;obj.Id=value.id; ...
                obj.Label=value.label;obj.ModelId=value.modelId; ...
                obj.ProblemId=value.problemId;obj.Maturity=value.maturity; ...
                obj.ValidationStatus=value.validationStatus; ...
                obj.DataSourceId=value.dataSourceId; ...
                obj.DefaultDatasetId=value.defaultDatasetId; ...
                obj.DefaultPointIndex=value.defaultPointIndex; ...
                obj.AxisPresetId=value.axisPresetId; ...
                obj.VisualizationProfileId=value.visualizationProfileId; ...
                obj.LayoutProfileId=value.layoutProfileId; ...
                obj.AllowedSteps=textList(value.allowedSteps,'allowedSteps'); ...
                obj.SeedPreset=lmz.workflow.SeedPreset(value.seedPreset); ...
                obj.SolveOptions=value.solveOptions; ...
                obj.ContinuationPreset=lmz.workflow.ContinuationPreset( ...
                value.continuationPreset); ...
                obj.HomotopyPreset=lmz.workflow.WorkflowPreset( ...
                value.homotopyPreset,'homotopy'); ...
                obj.FamilyScanPreset=lmz.workflow.WorkflowPreset( ...
                value.familyScanPreset,'family_scan'); ...
                obj.AnalysisViews=textList(value.analysisViews,'analysisViews'); ...
                obj.Provenance=value.provenance; ...
                obj.ProblemConfiguration=fieldOr(value, ...
                'problemConfiguration',struct());
            if ~ischar(obj.DefaultDatasetId)||isempty(obj.DefaultDatasetId)
                error('lmz:Workflow:DefaultDataset', ...
                    'Workflow defaultDatasetId must be nonempty text.');
            end
            if ~isstruct(obj.ProblemConfiguration)|| ...
                    ~isscalar(obj.ProblemConfiguration)
                error('lmz:Workflow:ProblemConfiguration', ...
                    'Workflow problemConfiguration must be one object.');
            end
            obj.Registry=parser.Results.Registry; ...
                obj.DataSource=parser.Results.DataSource; ...
                obj.AxisPreset=parser.Results.AxisPreset; ...
                obj.Workbench=parser.Results.Workbench; ...
                obj.SourcePath=parser.Results.SourcePath; ...
                obj.SourceHash=parser.Results.SourceHash;
        end

        function value=allows(obj,stepId)
            value=any(strcmp(stepId,obj.AllowedSteps));
        end

        function provider=createDataSourceProvider(obj)
            if ~isa(obj.DataSource,'lmz.workflow.DataSourceDescriptor')
                error('lmz:Workflow:DescriptorBinding', ...
                    'Workflow has no bound data-source descriptor.');
            end
            provider=obj.DataSource.createProvider();
        end

        function value=toStruct(obj)
            value=struct('schemaVersion',obj.SchemaVersion,'id',obj.Id, ...
                'label',obj.Label,'modelId',obj.ModelId, ...
                'problemId',obj.ProblemId,'maturity',obj.Maturity, ...
                'validationStatus',obj.ValidationStatus, ...
                'dataSourceId',obj.DataSourceId, ...
                'defaultDatasetId',obj.DefaultDatasetId, ...
                'defaultPointIndex',obj.DefaultPointIndex, ...
                'axisPresetId',obj.AxisPresetId, ...
                'visualizationProfileId',obj.VisualizationProfileId, ...
                'layoutProfileId',obj.LayoutProfileId, ...
                'allowedSteps',{obj.AllowedSteps}, ...
                'seedPreset',obj.SeedPreset.toStruct(), ...
                'solveOptions',obj.SolveOptions, ...
                'continuationPreset',obj.ContinuationPreset.toStruct(), ...
                'homotopyPreset',obj.HomotopyPreset.toStruct(), ...
                'familyScanPreset',obj.FamilyScanPreset.toStruct(), ...
                'analysisViews',{obj.AnalysisViews}, ...
                'provenance',obj.Provenance, ...
                'problemConfiguration',obj.ProblemConfiguration);
        end
    end
end

function requireFields(value,names)
for index=1:numel(names)
    if ~isfield(value,names{index})
        error('lmz:Workflow:MissingField', ...
            'Workflow descriptor is missing %s.',names{index});
    end
end
end
function validateId(value,name)
if ~ischar(value)||isempty(regexp(value,'^[a-z][a-z0-9_]*$','once'))
    error('lmz:Workflow:InvalidId','Workflow %s is invalid.',name);
end
end
function values=textList(value,name)
if ischar(value),values={value};elseif iscell(value)&& ...
        all(cellfun(@ischar,value)),values=value(:)';else
    error('lmz:Workflow:DescriptorList','%s must be a text list.',name);
end
if isempty(values)||numel(unique(values))~=numel(values)
    error('lmz:Workflow:DescriptorList','%s must be nonempty and unique.',name);
end
end
function value=fieldOr(source,name,fallback)
if isfield(source,name),value=source.(name);else,value=fallback;end
end
