classdef SectionTransferResult
    %SECTIONTRANSFERRESULT Rephased solution, trajectory, and durable lineage.
    properties (SetAccess=private)
        Solution
        SourceSolution
        Simulation
        Crossing
        SourceReturn
        Lineage
        PhysicalOrbitMaxError
        PhaseInvariantObservablesPreserved
        DecisionCodecRephased
    end

    methods
        function obj=SectionTransferResult(value)
            required=properties(obj);
            if ~isstruct(value)||~isscalar(value)|| ...
                    ~all(isfield(value,required))
                error('lmz:Poincare:TransferResultFields', ...
                    'Section transfer result is incomplete.');
            end
            if ~isa(value.Solution,'lmz.data.Solution')|| ...
                    ~isa(value.SourceSolution,'lmz.data.Solution')|| ...
                    ~isa(value.Simulation,'lmz.api.SimulationResult')|| ...
                    ~isa(value.Crossing,'lmz.poincare.SectionCrossing')
                error('lmz:Poincare:TransferResultTypes', ...
                    'Section transfer result contains invalid objects.');
            end
            if ~isstruct(value.Lineage)||~isscalar(value.Lineage)|| ...
                    ~isnumeric(value.PhysicalOrbitMaxError)|| ...
                    ~isscalar(value.PhysicalOrbitMaxError)|| ...
                    ~isfinite(value.PhysicalOrbitMaxError)|| ...
                    value.PhysicalOrbitMaxError<0
                error('lmz:Poincare:TransferResultMetadata', ...
                    'Section transfer result metadata are invalid.');
            end
            for index=1:numel(required),obj.(required{index})=value.(required{index});end
        end

        function value=toStruct(obj)
            sourceReturn=obj.SourceReturn;
            if isobject(sourceReturn)&&ismethod(sourceReturn,'toStruct')
                sourceReturn=sourceReturn.toStruct();
            end
            value=struct('Solution',obj.Solution.toStruct(), ...
                'SourceSolution',obj.SourceSolution.toStruct(), ...
                'Simulation',obj.Simulation.toStruct(), ...
                'Crossing',obj.Crossing.toStruct(), ...
                'SourceReturn',sourceReturn,'Lineage',obj.Lineage, ...
                'PhysicalOrbitMaxError',obj.PhysicalOrbitMaxError, ...
                'PhaseInvariantObservablesPreserved', ...
                obj.PhaseInvariantObservablesPreserved, ...
                'DecisionCodecRephased',obj.DecisionCodecRephased);
        end

        function artifact=toArtifact(obj,randomSeed)
            if nargin<2,randomSeed=0;end
            artifact=lmz.io.ArtifactStore.workflowBase( ...
                obj.Solution.ModelId,obj.Solution.ProblemId);
            artifact.artifactType='section-transfer-run';
            artifact.sectionTransferResult=obj.toStruct();
            artifact.targetSectionId=obj.Lineage.TargetSectionId;
            artifact.diagnostics=struct( ...
                'PhysicalOrbitMaxError',obj.PhysicalOrbitMaxError, ...
                'DecisionCodecRephased',obj.DecisionCodecRephased);
            artifact.lineage=obj.Lineage;
            ids={obj.Lineage.SourceSectionId,obj.Lineage.TargetSectionId};
            artifact.poincareMetadata=lmz.io.ArtifactStore.sectionMetadata( ...
                obj.Solution.ModelId,ids);
            stride=lmz.io.ArtifactStore.strideDefinitionMetadata( ...
                obj.Solution.ModelId,obj.Lineage.SourceSectionId, ...
                obj.Lineage.TargetSectionId);
            artifact.strideDefinition=stride.Record;
            artifact.strideDefinitionHash=stride.Hash;
            relative=artifact.poincareMetadata.CatalogRelativePath;
            sourceHashes=struct();
            if ~isempty(relative)
                sourceHashes.PoincareCatalog=struct( ...
                    'relativePath',relative,'sha256', ...
                    artifact.poincareMetadata.CatalogHash);
            end
            sourceHashes.StrideDefinition=stride.Hash;
            configuration=struct('TargetSectionId', ...
                obj.Lineage.TargetSectionId);
            artifact.problemMetadata.configuration=configuration;
            details=struct('Options',configuration, ...
                'SourceSeed',obj.SourceSolution.toStruct(), ...
                'RandomSeed',randomSeed,'Provenance',obj.Lineage, ...
                'TerminationReason','transferred','Warnings',{{}}, ...
                'SourceDataHashes',sourceHashes);
            artifact=lmz.io.ArtifactStore.withRunMetadata(artifact,details);
        end
    end

    methods (Static)
        function obj=fromStruct(value)
            value.Solution=lmz.data.Solution.fromStruct(value.Solution);
            value.SourceSolution=lmz.data.Solution.fromStruct( ...
                value.SourceSolution);
            value.Simulation=lmz.api.SimulationResult.fromStruct( ...
                value.Simulation);
            value.Crossing=lmz.poincare.SectionCrossing.fromStruct( ...
                value.Crossing);
            obj=lmz.data.SectionTransferResult(value);
        end

        function obj=fromArtifact(artifact)
            lmz.io.ArtifactStore.validate(artifact);
            if ~strcmp(artifact.artifactType,'section-transfer-run')
                error('lmz:Poincare:TransferArtifactType', ...
                    'Artifact is not a section-transfer run.');
            end
            obj=lmz.data.SectionTransferResult.fromStruct( ...
                artifact.sectionTransferResult);
        end
    end
end
