classdef DataToolbar < lmz.gui.branch.BranchComponentGroup
    methods
        function obj=DataToolbar(parent,callbacks)
            obj@lmz.gui.branch.BranchComponentGroup('data_toolbar');
            root=uigridlayout(parent,[2 9], ...
                'Tag','lmz-branch-data-toolbar');
            root.ColumnWidth={165,95,85,92,105,90,105,105,'1x'};
            catalog=uidropdown(root,'Tag','lmz-branch-catalog', ...
                'Tooltip','Choose a built-in scientific branch or dataset.');
            place(catalog,1,1);
            buttons={ ...
                makeButton(root,'Load selected','load-selected', ...
                    callbacks.LoadSelected), ...
                makeButton(root,'Load all','load-all',callbacks.LoadAll), ...
                makeButton(root,'Open folder…','open-folder', ...
                    callbacks.OpenFolder), ...
                makeButton(root,'Open MAT/artifact…','open-file', ...
                    callbacks.OpenFile), ...
                makeButton(root,'Reload','reload',callbacks.Reload), ...
                makeButton(root,'Remove selected','remove',callbacks.Remove), ...
                makeButton(root,'Save native…','save',callbacks.Save), ...
                makeButton(root,'Export legacy…','export-legacy', ...
                    callbacks.ExportLegacy)};
            for index=1:numel(buttons),place(buttons{index},1,index+1);end
            plotButtons={ ...
                makeButton(root,'Plot selected','plot-selected', ...
                    callbacks.PlotSelected), ...
                makeButton(root,'Plot all','plot-all',callbacks.PlotAll), ...
                makeButton(root,'Clear plot','clear-plot',callbacks.ClearPlot), ...
                makeButton(root,'Axis preset','preset',callbacks.Preset), ...
                makeButton(root,'Export plot…','export-plot', ...
                    callbacks.ExportPlot)};
            for index=1:numel(plotButtons),place(plotButtons{index},2,index);end
            obj.own(root,struct('CatalogDropDown',catalog, ...
                'Buttons',{buttons},'PlotButtons',{plotButtons}));
        end
    end
end

function button=makeButton(parent,label,tag,callback)
button=uibutton(parent,'Text',label,'Tag',['lmz-branch-' tag], ...
    'Tooltip',label,'ButtonPushedFcn',@(~,~)callback());
end
function place(control,row,column)
control.Layout.Row=row;control.Layout.Column=column;
end
