classdef DatasetPanel < lmz.gui.branch.BranchComponentGroup
    methods
        function obj=DatasetPanel(parent,callbacks)
            obj@lmz.gui.branch.BranchComponentGroup('datasets');
            root=uigridlayout(parent,[4 1], ...
                'Tag','lmz-branch-dataset-panel');
            root.RowHeight={24,'1x',28,112};
            datasetChanged=callbacks.DatasetChanged;
            visibilityChanged=callbacks.VisibilityChanged;
            uilabel(root,'Text','Datasets (active selection)', ...
                'FontWeight','bold');
            list=uilistbox(root,'Tag','lmz-branch-datasets', ...
                'Tooltip','Select the active scientific dataset.', ...
                'ValueChangedFcn',@(~,~)datasetChanged());
            visible=uicheckbox(root,'Text','Visible','Value',true, ...
                'Tag','lmz-branch-visible', ...
                'ValueChangedFcn',@(~,~)visibilityChanged());
            metadata=uitextarea(root,'Editable','off', ...
                'Value',{'No dataset'},'Tag','lmz-branch-metadata', ...
                'Tooltip','Copyable source and dataset metadata.');
            obj.own(root,struct('List',list,'Visible',visible, ...
                'Metadata',metadata));
        end
    end
end
