classdef ParameterFilterPanel < lmz.gui.branch.BranchComponentGroup
    methods
        function obj=ParameterFilterPanel(parent,callbacks)
            obj@lmz.gui.branch.BranchComponentGroup('parameter_filter');
            root=uigridlayout(parent,[1 4], ...
                'Tag','lmz-branch-parameter-filter-panel');
            root.Padding=[0 0 0 0];
            root.ColumnWidth={90,105,105,'1x'};
            filterChanged=callbacks.FilterChanged;
            varyingValueChanged=callbacks.VaryingValueChanged;
            fixedParameter=uidropdown(root,'Items',{'<none>'}, ...
                'Tag','lmz-branch-fixed-parameter', ...
                'Tooltip','Filter metadata for a fixed branch parameter.', ...
                'ValueChangedFcn',@(~,~)filterChanged());
            fixedValue=uidropdown(root,'Items',{'<all>'}, ...
                'Tag','lmz-branch-fixed-value', ...
                'Tooltip','Choose a fixed-parameter value.', ...
                'ValueChangedFcn',@(~,~)filterChanged());
            varyingParameter=uidropdown(root,'Items',{'<none>'}, ...
                'Tag','lmz-branch-varying-parameter', ...
                'Tooltip','Choose a provider-declared varying parameter.', ...
                'ValueChangedFcn',@(~,~)filterChanged());
            varyingValue=uidropdown(root,'Items',{'<all>'}, ...
                'Tag','lmz-branch-varying-value', ...
                'Tooltip','Lock the nearest point for this parameter value.', ...
                'ValueChangedFcn',@(~,~)varyingValueChanged());
            obj.own(root,struct('FixedParameter',fixedParameter, ...
                'FixedValue',fixedValue, ...
                'VaryingParameter',varyingParameter, ...
                'VaryingValue',varyingValue));
        end
    end
end
