classdef TestCoveragePolicy < matlab.unittest.TestCase
    methods (Test)
        function policyComesFromMeasuredStablePackages(testCase)
            path = fullfile(lmz.util.ProjectPaths.root(), ...
                'coverage', 'baseline_policy.json');
            testCase.assertEqual(exist(path, 'file'), 2, ...
                'Run tools/run_coverage.m and record the measured policy.');
            policy = lmz.compat.Json.read(path);
            testCase.verifyTrue(policy.measured);
            items = policy.stablePackages;
            if iscell(items)
                items = [items{:}];
            end
            testCase.verifyEqual(sort({items.name}), sort( ...
                {'lmz.api', 'lmz.data', 'lmz.io', ...
                'lmz.registry', 'lmz.services'}));
            for index = 1:numel(items)
                testCase.verifyGreaterThanOrEqual( ...
                    items(index).measuredLineRate, 0);
                testCase.verifyLessThanOrEqual( ...
                    items(index).measuredLineRate, 1);
                testCase.verifyGreaterThanOrEqual( ...
                    items(index).minimumLineRate, 0);
                testCase.verifyLessThanOrEqual(items(index).minimumLineRate, ...
                    items(index).measuredLineRate);
                testCase.verifyLessThanOrEqual( ...
                    items(index).measuredLineRate - ...
                    items(index).minimumLineRate, 0.0500001);
            end
        end
    end
end
