function report=run_clean_install_test(packagePath)
%RUN_CLEAN_INSTALL_TEST Exercise ZIP or MLTBX from an unrelated child process.
if exist(packagePath,'file')~=2,error('lmz:Release:MissingPackage','Missing package: %s',packagePath);end
[~,~,extension]=fileparts(packagePath);
if ~any(strcmpi(extension,{'.zip','.mltbx'}))
    error('lmz:Release:UnsupportedPackage','Expected a ZIP or MLTBX package.');
end
temporary=tempname;mkdir(temporary);cleanup=onCleanup(@()release_remove_tree(temporary));
scriptPath=fullfile(temporary,'lmz_clean_install.m');
marker='LMZ_CLEAN_INSTALL_OK';
if strcmpi(extension,'.zip')
    verify_release(packagePath);
    body=zipScript(packagePath,temporary,marker);
else
    body=toolboxScript(packagePath,temporary,marker);
end
writeScript(scriptPath,body);
matlabExecutable=fullfile(matlabroot,'bin','matlab');if ispc,matlabExecutable=[matlabExecutable '.exe'];end
command=sprintf('"%s" -batch "run(''%s'')"',matlabExecutable,matlabQuote(scriptPath));
[status,output]=system(command);
evidence={'registry=1','workflow=1','gui=1','artifact=1','unloaded=1'};
hasEvidence=cellfun(@(token)~isempty(strfind(output,token)),evidence); %#ok<STREMP>
if status~=0||isempty(strfind(output,marker))||~all(hasEvidence) %#ok<STREMP>
    error('lmz:Release:CleanInstallFailed','Clean install failed:\n%s',output);
end
report=struct('Passed',true,'PackageType',lower(extension(2:end)), ...
    'Marker',marker,'RegistryDiscovery',true,'Workflow',true, ...
    'GuiConstruction',true,'ArtifactRoundTrip',true,'Unloaded',true, ...
    'Output',output);
fprintf('%s type=%s\n',marker,report.PackageType);
clear cleanup
end

function body=zipScript(packagePath,temporary,marker)
extract=fullfile(temporary,'installed');
working=fullfile(temporary,'unrelated-work');
setup=sprintf([ ...
    'restoredefaultpath;mkdir(''%s'');cd(''%s'');unzip(''%s'',''%s'');' ...
    'd=dir(''%s'');d=d([d.isdir]);d=d(~ismember({d.name},{''.'',''..''}));' ...
    'assert(numel(d)==1);r=fullfile(''%s'',d(1).name);addpath(r);startup;'], ...
    matlabQuote(working),matlabQuote(working),matlabQuote(packagePath), ...
    matlabQuote(extract),matlabQuote(extract),matlabQuote(extract));
cleanup=sprintf([ ...
    'delete(app);clear app controller;delete(registry);' ...
    'clear registry model demo simulation problem decision parameters evaluation solution loaded context;' ...
    'rmpath(r);rmpath(fullfile(r,''src''));rmpath(fullfile(r,''models''));' ...
    'clear classes;rehash path;' ...
    'assert(isempty(which(''legged_model_zoo'')));' ...
    'assert(isempty(which(''lmz.util.Version'')));' ...
    'fprintf(''%s registry=1 workflow=1 gui=1 artifact=1 unloaded=1\\n'');'],marker);
body=[setup exerciseBody(working) cleanup];
end

function body=toolboxScript(packagePath,temporary,marker)
working=fullfile(temporary,'unrelated-work');
setup=sprintf([ ...
    'restoredefaultpath;mkdir(''%s'');cd(''%s'');' ...
    'addon=matlab.addons.toolbox.installToolbox(''%s'');' ...
    'c=onCleanup(@()matlab.addons.toolbox.uninstallToolbox(addon));' ...
    ],matlabQuote(working),matlabQuote(working),matlabQuote(packagePath));
cleanup=sprintf([ ...
    'delete(app);clear app controller;delete(registry);' ...
    'clear registry model demo simulation problem decision parameters evaluation solution loaded context;' ...
    'clear c addon;clear classes;rehash toolboxcache;rehash path;' ...
    'assert(isempty(which(''legged_model_zoo'')));' ...
    'assert(isempty(which(''lmz.util.Version'')));' ...
    'fprintf(''%s registry=1 workflow=1 gui=1 artifact=1 unloaded=1\\n'');'],marker);
body=[setup exerciseBody(working) cleanup];
end

function body=exerciseBody(working)
body=sprintf([ ...
    'assert(strcmp(lmz.util.Version.current(),''1.0.0-rc.1''));' ...
    'registry=lmz.registry.ModelRegistry.discover();' ...
    'assert(any(strcmp(registry.listModels(),''tutorial_hopper'')));' ...
    'model=registry.createModel(''tutorial_hopper'');' ...
    'context=lmz.api.RunContext.synchronous(23);' ...
    'demo=model.createProblem(''demo_hop'',struct());' ...
    'simulation=lmz.services.SimulationService().simulate(demo,struct(),struct(),context);' ...
    'assert(~isempty(simulation.Time));assert(numel(simulation.EventRecords)==1);' ...
    'problem=model.createProblem(''periodic_hop'',struct());' ...
    'decision=problem.getDecisionSchema().defaults();' ...
    'parameters=problem.getParameterSchema().defaults();' ...
    'evaluation=problem.evaluate(decision,parameters,context,true);' ...
    'assert(evaluation.ScaledResidualNorm<1e-9);' ...
    'solution=problem.makeSolution(decision,parameters,evaluation);' ...
    'p=fullfile(''%s'',''clean-install.lmz.mat'');' ...
    'lmz.io.ArtifactStore.save(p,solution.toArtifact());' ...
    'loaded=lmz.io.ArtifactStore.load(p);' ...
    'assert(strcmp(loaded.modelId,''tutorial_hopper''));' ...
    'assert(max(abs(loaded.decisionValues-decision))<1e-12);' ...
    'controller=lmz.gui.AppController(registry,context);' ...
    'assert(any(strcmp(controller.modelIds(),''tutorial_hopper'')));' ...
    'app=lmz.gui.LeggedModelZooApp(''Controller'',controller,''Visible'',''off'');' ...
    'assert(isgraphics(app.Figure));assert(~isempty(app.TabGroup));'], ...
    matlabQuote(working));
end

function writeScript(path,text)
fid=fopen(path,'w');if fid<0,error('lmz:Release:WriteFailed','Cannot write child script.');end
cleanup=onCleanup(@()fclose(fid));fprintf(fid,'%s\n',text);clear cleanup
end

function value=matlabQuote(value),value=strrep(value,'''','''''');end
