classdef ContactTimingSequenceEvaluator < handle
    %CONTACTTIMINGSEQUENCEEVALUATOR Propagate section returns without solves.
    properties (SetAccess=private)
        Provider
        ScheduleChart
        NumberOfStrides
        LocalDecisionCount
        FixedRowPolicy
        FixedRowTolerance
    end

    methods
        function obj=ContactTimingSequenceEvaluator(provider,chart,count, ...
                fixedRowPolicy,fixedRowTolerance)
            if nargin<4,fixedRowPolicy='validate_fixed_rows';end
            if nargin<5,fixedRowTolerance=1e-8;end
            if ~isa(provider,'lmz.schedule.ContactConstraintProvider')|| ...
                    ~isa(chart,'lmz.schedule.EventScheduleChart')
                error('lmz:MultiStride:TimingSequenceProvider', ...
                    'A contact provider and event-schedule chart are required.');
            end
            obj.Provider=provider;obj.ScheduleChart=chart;
            obj.NumberOfStrides=count;
            obj.LocalDecisionCount=chart.DecisionSchema.count();
            obj.FixedRowPolicy=lmz.schedule.TimingResidualPolicy.normalize( ...
                fixedRowPolicy);
            lmz.schedule.TimingResidualPolicy.fixedRows(chart.Template, ...
                zeros(chart.Template.count(),1),zeros(0,1),fixedRowTolerance);
            obj.FixedRowTolerance=fixedRowTolerance;
        end

        function value=evaluate(obj,u,fixedInitialState, ...
                fixedPhysicalParameters,context,includeSimulation,contract) %#ok<INUSD>
            context.check();
            if contract.NumberOfStrides~=obj.NumberOfStrides|| ...
                    numel(u)~=obj.NumberOfStrides*obj.LocalDecisionCount
                error('lmz:MultiStride:TimingSequenceDimension', ...
                    'Timing-sequence decision length does not match its stride count.');
            end
            state=fixedInitialState(:);parameters=fixedPhysicalParameters(:);
            contacts=cell(obj.NumberOfStrides,1);
            sections=cell(obj.NumberOfStrides,1);
            records=cell(obj.NumberOfStrides,1);
            fixedRowsValid=true;maximumFixedResidual=0;
            for stride=1:obj.NumberOfStrides
                context.check();
                rows=(stride-1)*obj.LocalDecisionCount+ ...
                    (1:obj.LocalDecisionCount);
                schedule=obj.ScheduleChart.decode(u(rows));
                result=obj.Provider.evaluate(state,parameters,schedule, ...
                    context,false);
                contact=result.ContactResidual(:);
                bindings=lmz.schedule.TimingResidualPolicy.bindings( ...
                    schedule,numel(contact),fieldOr(result, ...
                    'ContactRowBindings',[]));
                [active,activeSection]= ...
                    lmz.schedule.TimingResidualPolicy.activeRows( ...
                    schedule,obj.FixedRowPolicy,bindings);
                contacts{stride}=contact(active);
                if activeSection
                    sections{stride}=result.SectionResidual(:);
                else
                    sections{stride}=zeros(0,1);
                end
                [fixedRows,validFixed,maximumFixed]= ...
                    lmz.schedule.TimingResidualPolicy.fixedRows( ...
                    schedule,contact,result.SectionResidual(:), ...
                    obj.FixedRowTolerance,bindings);
                fixedRowsValid=fixedRowsValid&&validFixed;
                maximumFixedResidual=max(maximumFixedResidual,maximumFixed);
                terminal=result.TerminalState(:);
                if numel(terminal)~=numel(state)||any(~isfinite(terminal))
                    error('lmz:MultiStride:TimingSequenceTerminalState', ...
                        ['Each timing-only stride must return a finite terminal ' ...
                        'state in the fixed initial-state coordinates.']);
                end
                records{stride}=struct('StrideIndex',stride, ...
                    'InputState',state,'Schedule',schedule.toStruct(), ...
                    'ContactResidual',contact, ...
                    'ContactRowBindings',bindings, ...
                    'SectionResidual',result.SectionResidual(:), ...
                    'FixedRows',fixedRows,'FixedRowsValid',validFixed, ...
                    'TerminalState',terminal, ...
                    'ProviderDiagnostics',result.Diagnostics);
                state=terminal;
            end
            residual=[vertcat(contacts{:});vertcat(sections{:})];
            value=struct('ContactResiduals',{contacts}, ...
                'SectionResiduals',{sections},'Simulation',[], ...
                'Feasibility',struct('Valid',all(isfinite(residual))&& ...
                fixedRowsValid,'FixedRowsValid',fixedRowsValid, ...
                'MaximumFixedResidual',maximumFixedResidual, ...
                'FixedRowTolerance',obj.FixedRowTolerance, ...
                'FixedRowPolicy',obj.FixedRowPolicy), ...
                'PhysicalValidity',all(isfinite(residual))&&fixedRowsValid, ...
                'Diagnostics',struct('StrideEvaluations',{records}, ...
                'FinalState',state,'StatePropagation', ...
                'previous_terminal_state','PhysicalParametersFixed',true, ...
                'StatePeriodicityImposed',false,'HiddenTimingSolve',false, ...
                'NestedSolverCalls',0,'FixedRowPolicy',obj.FixedRowPolicy));
        end
    end
end

function value=fieldOr(source,name,fallback)
if isstruct(source)&&isfield(source,name),value=source.(name); ...
else,value=fallback;end
end
