classdef ActiveStrideParameterSelector
    %ACTIVESTRIDEPARAMETERSELECTOR Convert local rows to absolute active time.
    methods (Static)
        function value=select(parameterRows,time)
            if ~isnumeric(parameterRows)||~isreal(parameterRows)|| ...
                    size(parameterRows,2)<9||isempty(parameterRows)|| ...
                    any(~isfinite(parameterRows(:)))
                error('lmz:slip_quad_load:GraphicsParameters', ...
                    'Per-stride parameters must be a finite matrix with at least nine columns.');
            end
            if ~isnumeric(time)||~isscalar(time)||~isreal(time)||~isfinite(time)
                error('lmz:slip_quad_load:GraphicsTime', ...
                    'Frame time must be one finite real scalar.');
            end
            durations=parameterRows(:,9);
            if any(durations<=0)
                error('lmz:slip_quad_load:GraphicsDuration', ...
                    'Every per-stride duration must be positive.');
            end
            cumulativeEnds=cumsum(durations);
            strideIndex=find(time<cumulativeEnds,1,'first');
            if isempty(strideIndex),strideIndex=size(parameterRows,1);end
            offset=sum(durations(1:strideIndex-1));
            localRow=parameterRows(strideIndex,:);
            globalRow=localRow;globalRow(1:9)=globalRow(1:9)+offset;
            value=struct('StrideIndex',strideIndex,'Offset',offset, ...
                'StartTime',offset,'EndTime',cumulativeEnds(strideIndex), ...
                'LocalRow',localRow,'GlobalRow',globalRow, ...
                'CumulativeEnds',cumulativeEnds);
        end

        function value=forFrame(simulation,index)
            if ~isa(simulation,'lmz.api.SimulationResult')
                error('lmz:slip_quad_load:GraphicsSimulation', ...
                    'SimulationResult is required.');
            end
            if ~isnumeric(index)||~isscalar(index)||~isfinite(index)||index~=fix(index)|| ...
                    index<1||index>numel(simulation.Time)
                error('lmz:slip_quad_load:GraphicsFrame', ...
                    'Frame index is outside the simulation.');
            end
            parameters=simulation.Parameters;
            if ~isstruct(parameters)||~isfield(parameters,'per_stride_parameters')
                error('lmz:slip_quad_load:GraphicsParameterRows', ...
                    'Simulation parameters do not expose per_stride_parameters.');
            end
            value=lmzmodels.slip_quad_load.ActiveStrideParameterSelector.select( ...
                parameters.per_stride_parameters,simulation.Time(index));
            value.FrameIndex=index;value.FrameTime=simulation.Time(index);
        end

        function value=provenance()
            value=struct( ...
                'sourceRepository','DLARlab/2025_Gait_Transitions_in_Load_Pulling_Quadrupeds_Insights', ...
                'sourceCommit','19f3133073c988cc0c3424a647b4adbb60a90b99', ...
                'sourcePath','Section3_Gait_Transition_Replication/Section3_Gait_Transition_Replication.m', ...
                'sourceFunction','UpdateFrame', ...
                'sourceLines','299-308', ...
                'adaptation',['The source two-row switch is generalized to N rows. ', ...
                    'Its strict t < end comparison is retained, so an exact boundary ', ...
                    'selects the later stride.']);
        end
    end
end
