classdef FirstStrideLayout
    %FIRSTSTRIDELAYOUT Exact named contract for the source 44-vector.
    properties (Constant)
        Length = 44
    end
    methods (Static)
        function value = names()
            value = { ...
                'quad_dx','quad_y','quad_dy','quad_phi','quad_dphi', ...
                'alphaBL','dalphaBL','alphaFL','dalphaFL', ...
                'alphaBR','dalphaBR','alphaFR','dalphaFR', ...
                'tBL_TD','tBL_LO','tFL_TD','tFL_LO', ...
                'tBR_TD','tBR_LO','tFR_TD','tFR_LO','tAPEX', ...
                'leg_stiffness','swing_pre_BL','swing_pre_FL', ...
                'swing_pre_BR','swing_pre_FR','swing_post_BL', ...
                'swing_post_FL','swing_post_BR','swing_post_FR', ...
                'torso_inertia','leg_length','swing_neutral_angle', ...
                'back_attachment_ratio','back_front_stiffness_ratio', ...
                'load_x','load_dx','load_height','load_mass', ...
                'load_friction','tugline_rest_length', ...
                'tugline_stiffness','slope_angle'};
        end
        function value = indices()
            value = struct('QuadrupedState',1:13,'EventTiming',14:22, ...
                'QuadrupedParameters',23:36,'LoadState',37:38, ...
                'LoadParameters',39:44,'PreSwingStiffness',24:27, ...
                'PostSwingStiffness',28:31, ...
                'TransitionInvariantParameters',[23 32:36 39:44]);
        end
        function validate(vector)
            if ~isnumeric(vector) || ~isreal(vector) || ...
                    numel(vector) ~= lmzmodels.slip_quad_load.FirstStrideLayout.Length || ...
                    any(~isfinite(vector(:)))
                error('lmz:QuadLoad:FirstStrideLayout', ...
                    'The first-stride vector must contain 44 finite real values.');
            end
        end
        function value = decode(vector)
            lmzmodels.slip_quad_load.FirstStrideLayout.validate(vector);
            vector = vector(:); index = lmzmodels.slip_quad_load.FirstStrideLayout.indices();
            names = lmzmodels.slip_quad_load.FirstStrideLayout.names();
            named = cell2struct(num2cell(vector),names(:),1);
            value = struct('Vector',vector,'Named',named, ...
                'QuadrupedState',vector(index.QuadrupedState), ...
                'EventTiming',vector(index.EventTiming), ...
                'QuadrupedParameters',vector(index.QuadrupedParameters), ...
                'LoadState',vector(index.LoadState), ...
                'LoadParameters',vector(index.LoadParameters));
        end
        function vector = encode(value)
            if isnumeric(value)
                vector=value(:);
            elseif isstruct(value) && isfield(value,'Vector')
                vector=value.Vector(:);
            elseif isstruct(value) && isfield(value,'Named')
                names=lmzmodels.slip_quad_load.FirstStrideLayout.names();vector=zeros(44,1);
                for index=1:44,vector(index)=value.Named.(names{index});end
            elseif isstruct(value) && all(isfield(value, ...
                    {'QuadrupedState','EventTiming','QuadrupedParameters','LoadState','LoadParameters'}))
                vector=[value.QuadrupedState(:);value.EventTiming(:); ...
                    value.QuadrupedParameters(:);value.LoadState(:);value.LoadParameters(:)];
            else
                error('lmz:QuadLoad:FirstStrideEncode','Unsupported first-stride value.');
            end
            lmzmodels.slip_quad_load.FirstStrideLayout.validate(vector);
        end
    end
end
