classdef ObservableProvider
    methods (Static)
        function value=compute(raw)
            value=struct('stride_count',raw.StrideCount, ...
                'stride_boundaries',raw.StrideBoundaries, ...
                'tugline_force',raw.TuglineForce, ...
                'grf_magnitude',raw.GroundReactionForces(:,1:4), ...
                'horizontal_grf',raw.GroundReactionForces(:,5:8), ...
                'vertical_grf',raw.GroundReactionForces(:,9:12), ...
                'total_vertical_grf',sum(raw.GroundReactionForces(:,9:12),2), ...
                'total_horizontal_grf',sum(raw.GroundReactionForces(:,5:8),2), ...
                'load_position',raw.States(:,[15 17]), ...
                'quadruped_position',raw.States(:,[1 3]), ...
                'sample_time',raw.Time(:),'event_times',[raw.EventRecords.Time].');
            schedules=raw.Parameters(:,1:9);value.event_phases=schedules(:,1:8)./schedules(:,9);
            value.stride_durations=schedules(:,9);
            value.normalized_stride_time=zeros(size(raw.Time));
            for index=1:numel(raw.StrideBoundaries)
                b=raw.StrideBoundaries(index);selected=raw.Time>=b.StartTime&raw.Time<=b.EndTime;
                value.normalized_stride_time(selected)=(index-1)+(raw.Time(selected)-b.StartTime)/max(eps,b.EndTime-b.StartTime);
            end
        end
    end
end
