classdef QuadLoadHorizonInitializer
    %QUADLOADHORIZONINITIALIZER Build explicit nodes from source templates.
    properties (SetAccess=private)
        TemplateLibrary
    end

    methods
        function obj=QuadLoadHorizonInitializer(library)
            if nargin<1,library=lmzmodels.slip_quad_load.StrideTemplateLibrary();end
            if ~isa(library,'lmzmodels.slip_quad_load.StrideTemplateLibrary')
                error('lmz:QuadLoad:HorizonTemplateLibrary', ...
                    'QuadLoadHorizonInitializer requires a template library.');
            end
            obj.TemplateLibrary=library;
        end

        function [horizon,diagnostics]=create(obj,configuration,context)
            if nargin<2,configuration=struct();end
            if nargin<3,context=lmz.api.RunContext.synchronous(0);end
            requested=positiveInteger(fieldOr(configuration, ...
                'NumberOfStrides',3),'NumberOfStrides');
            sectionId=shootingSection(configuration);
            [xAccum,sourceLineage]=obj.initialDecision(configuration,context);
            supplied=lmzmodels.slip_quad_load.XAccumAdapter.strideCount(xAccum);
            if supplied>requested
                [xAccum,truncation]=lmzmodels.slip_quad_load. ...
                    XAccumPlanAdapter.truncate(xAccum,requested);
                sourceLineage.Truncation=truncation;supplied=requested;
            end
            plan=lmzmodels.slip_quad_load.XAccumPlanAdapter.toPlan(xAccum);
            raw=lmzmodels.slip_quad_load.MultiStrideSimulator().runRaw( ...
                xAccum,context,false);
            states=cell(requested+1,1);schedules=cell(requested,1);
            controls=cell(requested,1);physical=cell(requested,1);
            segmentLineage=cell(requested,1);history=cell(requested,1);
            for stride=1:supplied
                boundary=raw.StrideBoundaries(stride);
                states{stride}=raw.LegacyStates(boundary.RawStartIndex,:).';
                states{stride+1}=raw.LegacyStates(boundary.RawEndIndex,:).';
                schedules{stride}= ...
                    lmzmodels.slip_quad_load.QuadLoadShootingUtilities. ...
                    eventSchedule(plan.StrideSpecs(stride).EventSchedule);
                schedules{stride}=applyEventMask( ...
                    withSection(schedules{stride},sectionId),configuration);
                controls{stride}=abs(plan.StrideSpecs(stride). ...
                    ControlParameters.PostSwingStiffness(:));
                physical{stride}=plan.StrideSpecs(stride).PhysicalParameters;
                if stride==1
                    physical{stride}.InitialPreSwingStiffness=abs( ...
                        plan.StrideSpecs(stride).ControlParameters. ...
                        PreSwingStiffness(:));
                end
                segmentLineage{stride}=struct('Method','exact_source_horizon', ...
                    'Source',sourceLineage,'SourceStrideIndex',stride);
                history{stride}=struct('StrideIndex',stride, ...
                    'Method','exact_source_horizon','SelectedTemplateId', ...
                    sourceLineage.TemplateId,'ContactResidualNorm', ...
                    norm(raw.Residual(27*(stride-1)+(1:9))), ...
                    'Attempts',{{struct('Strategy', ...
                    'exact_source_horizon','Accepted',true, ...
                    'TemplateId',sourceLineage.TemplateId)}});
            end
            for stride=supplied+1:requested
                strategy=fieldOr(configuration,'InitializationStrategy', ...
                    'nearest_compatible_template');
                attempts={struct('Strategy','exact_source_horizon', ...
                    'Accepted',false,'Reason', ...
                    'source horizon does not contain requested stride')};
                useTemplateControls=logical(fieldOr(configuration, ...
                    'UseTemplateControls',false));
                if strcmp(strategy,'phase_compatible_repeat')
                    schedules{stride}=schedules{stride-1};
                    controls{stride}=controls{stride-1};
                    selection=struct('Strategy',strategy, ...
                        'RepeatedStrideIndex',stride-1,'Score',0);
                    selectedTemplateId=sourceLineage.TemplateId;
                    selectedHash=sourceLineage.SourceHash;
                    method='phase_compatible_repeat';
                    attempts{end+1}=struct('Strategy',method, ...
                        'Accepted',true,'RepeatedStrideIndex',stride-1); %#ok<AGROW>
                else
                    query=struct('InitialSectionState',states{stride}, ...
                        'EventSchedule',schedules{stride-1}, ...
                        'ControlParameters',struct('PostSwingStiffness', ...
                        controls{stride-1}),'PhysicalParameters', ...
                        physical{stride-1});
                    [template,selection]=obj.TemplateLibrary.select( ...
                        query,context);
                    schedules{stride}=lmzmodels.slip_quad_load. ...
                        QuadLoadShootingUtilities.eventSchedule( ...
                        template.EventSchedule);
                    if useTemplateControls
                        controls{stride}=abs(template.ControlParameters. ...
                            PostSwingStiffness(:));
                    else
                        controls{stride}=controls{stride-1};
                    end
                    selectedTemplateId=template.TemplateId;
                    selectedHash=template.SourceHash;
                    method='nearest_compatible_stride_template';
                    attempts{end+1}=struct('Strategy', ...
                        'nearest_compatible_template','Accepted',true, ...
                        'TemplateId',template.TemplateId, ...
                        'Score',selection.Score); %#ok<AGROW>
                end
                schedules{stride}=applyEventMask( ...
                    withSection(schedules{stride},sectionId),configuration);
                physical{stride}=physical{stride-1};
                vector=lmzmodels.slip_quad_load.QuadLoadShootingUtilities. ...
                    vector(states{stride},schedules{stride},physical{stride}, ...
                    controls{stride},controls{stride-1});
                one=lmzmodels.slip_quad_load.LegacyQuadLoadEvaluator(). ...
                    evaluateStride(vector,context,false);
                states{stride+1}=one.LegacyStates(end,:).';
                segmentLineage{stride}=struct('Method',method, ...
                    'TemplateId',selectedTemplateId, ...
                    'SourceHash',selectedHash, ...
                    'TemplateControlsApplied',useTemplateControls, ...
                    'Selection',selection);
                history{stride}=struct('StrideIndex',stride, ...
                    'Method',method, ...
                    'SelectedTemplateId',selectedTemplateId, ...
                    'ContactResidualNorm',norm(one.Residual(1:9)), ...
                    'Selection',selection,'Attempts',{attempts});
            end
            nodes=cell(requested+1,1);
            for index=1:requested+1
                nodes{index}=lmzmodels.slip_quad_load. ...
                    QuadLoadShootingUtilities.node(states{index},index, ...
                    index>1,struct('Initializer','source_template_library'), ...
                    sectionId);
            end
            energyMode=fieldOr(configuration,'EnergyMode','energy_neutral');
            energyScale=fieldOr(configuration,'EnergyScale',1);
            energyTolerance=fieldOr(configuration,'EnergyTolerance',1e-8);
            segments=cell(requested,1);contactNames= ...
                lmzmodels.slip_quad_load.ContactConstraintProvider(). ...
                eventNames();
            if strcmp(sectionId,'apex'),contactNames=[contactNames,{'APEX'}];end
            for stride=1:requested
                work=indexedValue(fieldOr(configuration,'DeclaredWork',0),stride);
                mode=indexedText(energyMode,stride);
                energy=lmzmodels.slip_quad_load.QuadLoadShootingUtilities. ...
                    energySpecification(mode,work,energyScale,energyTolerance);
                segments{stride}=lmz.shooting.ShootingSegment( ...
                    'Index',stride,'StartNode',nodes{stride}, ...
                    'StopNode',nodes{stride+1}, ...
                    'EventSchedule',schedules{stride}, ...
                    'ContactConstraints',contactNames, ...
                    'PhysicalParameters',physical{stride}, ...
                    'ControlParameters',controls{stride}, ...
                    'EnergyWorkSpecification',energy, ...
                    'SimulationOptions',struct('EnforceEventTiming',false), ...
                    'SourceLineage',segmentLineage{stride});
            end
            formulation=fieldOr(configuration,'Formulation','feasibility');
            horizon=lmz.shooting.ShootingHorizon('ModelId','slip_quad_load', ...
                'ProblemId',fieldOr(configuration,'ProblemId', ...
                'multiple_shooting_horizon'),'Nodes',nodes, ...
                'Segments',segments,'Formulation',formulation, ...
                'Target',fieldOr(configuration,'Target',struct()), ...
                'Lineage',struct('Source',sourceLineage, ...
                'InitializationHistory',{history}, ...
                'RequestedStrideCount',requested, ...
                'SuppliedStrideCount',supplied, ...
                'SectionId',sectionId));
            sourceHashes=templateSourceHashes(obj.TemplateLibrary, ...
                sourceLineage,segmentLineage);
            diagnostics=struct('RequestedStrideCount',requested, ...
                'SuppliedStrideCount',supplied, ...
                'SectionId',sectionId, ...
                'InitializationHistory',{history}, ...
                'SourceLineage',sourceLineage, ...
                'SourceDataHashes',sourceHashes, ...
                'CompleteInitialGuess',true,'PhysicalRootClaimed',false);
        end
    end

    methods (Access=private)
        function [value,lineage]=initialDecision(obj,configuration,context)
            if isfield(configuration,'InitialDecision')&& ...
                    ~isempty(configuration.InitialDecision)
                value=lmzmodels.slip_quad_load.XAccumAdapter.encode( ...
                    configuration.InitialDecision);
                lineage=struct('Method','explicit_initial_decision', ...
                    'TemplateId','','SourceHash','');return
            end
            id=fieldOr(configuration,'TemplateId','individual_1_tr_to_rl');
            template=obj.TemplateLibrary.load(id,context);value=template.XAccum;
            lineage=struct('Method','template_library','TemplateId',id, ...
                'SourceHash',template.SourceHash, ...
                'SourceCommit',template.SourceCommit);
        end
    end
end

function value=templateSourceHashes(library,sourceLineage,segmentLineage)
ids={};
if isstruct(sourceLineage)&&isfield(sourceLineage,'TemplateId')&& ...
        ~isempty(sourceLineage.TemplateId)
    ids{end+1}=sourceLineage.TemplateId;
end
for index=1:numel(segmentLineage)
    item=segmentLineage{index};id='';
    if isstruct(item)&&isfield(item,'TemplateId')
        id=item.TemplateId;
    elseif isstruct(item)&&isfield(item,'Source')&& ...
            isstruct(item.Source)&&isfield(item.Source,'TemplateId')
        id=item.Source.TemplateId;
    end
    if ~isempty(id),ids{end+1}=id;end %#ok<AGROW>
end
ids=unique(ids,'stable');value=struct();
for index=1:numel(ids)
    record=library.record(ids{index});
    relative=repositoryRelative(library.pathFor(ids{index}));
    if isempty(relative),continue,end
    if index==1
        name='QuadLoadStrideTemplate';
    else
        name=matlab.lang.makeValidName( ...
            ['QuadLoadStrideTemplate_' ids{index}]);
    end
    value.(name)=struct('relativePath',relative, ...
        'sha256',record.sha256);
end
end

function value=repositoryRelative(path)
root=lmz.util.PathGuard.canonical(lmz.util.ProjectPaths.root(),true);
absolute=lmz.util.PathGuard.canonical(path,true);value='';
if ~lmz.util.PathGuard.isWithin(root,absolute),return,end
prefix=[root filesep];
if strncmp(absolute,prefix,numel(prefix))
    value=strrep(absolute(numel(prefix)+1:end),filesep,'/');
end
end

function value=positiveInteger(source,label)
if ~isnumeric(source)||~isscalar(source)||~isfinite(source)|| ...
        source<1||source~=fix(source)
    error('lmz:QuadLoad:HorizonCount','%s must be a positive integer.',label);
end
value=source;
end

function value=indexedValue(source,index)
if isscalar(source)
    value=source;
elseif isnumeric(source)&&numel(source)>=index
    value=source(index);
else
    error('lmz:QuadLoad:HorizonWork', ...
        'DeclaredWork does not cover every requested stride.');
end
end

function value=indexedText(source,index)
if ischar(source)
    value=source;
elseif iscell(source)&&numel(source)>=index
    value=source{index};
else
    error('lmz:QuadLoad:HorizonEnergyMode', ...
        'EnergyMode does not cover every requested stride.');
end
end

function value=applyEventMask(schedule,configuration)
source=logical(fieldOr(configuration,'EventFreeMask',true));
count=schedule.count();
if isscalar(source)
    eventFree=repmat(source,count,1);returnFree=source;
elseif numel(source)==2
    eventFree=repmat(source(1),count,1);returnFree=source(2);
elseif numel(source)==count+1
    eventFree=source(1:count);returnFree=source(end);
else
    error('lmz:QuadLoad:HorizonEventMask', ...
        ['EventFreeMask must be scalar, [events return], or contain one ' ...
        'entry per event plus the return time.']);
end
value=schedule.withFixedMask(~eventFree(:),~returnFree);
end

function value=shootingSection(configuration)
hasSection=isfield(configuration,'SectionId');
hasStart=isfield(configuration,'StartSectionId');
hasStop=isfield(configuration,'StopSectionId');
if hasSection
    value=configuration.SectionId;
    if (hasStart&&~strcmp(configuration.StartSectionId,value))|| ...
            (hasStop&&~strcmp(configuration.StopSectionId,value))
        error('lmz:QuadLoad:HorizonMixedSection', ...
            ['A homogeneous multiple-shooting horizon requires SectionId, ' ...
            'StartSectionId, and StopSectionId to agree.']);
    end
elseif hasStart&&hasStop
    if ~strcmp(configuration.StartSectionId,configuration.StopSectionId)
        error('lmz:QuadLoad:HorizonMixedSection', ...
            ['Mixed start/stop sections require a true transition ' ...
            'formulation and cannot be relabeled as a homogeneous horizon.']);
    end
    value=configuration.StartSectionId;
elseif hasStart
    value=configuration.StartSectionId;
elseif hasStop
    value=configuration.StopSectionId;
else
    value='apex';
end
if ~ischar(value)||~any(strcmp(value,{'apex','stride_boundary'}))
    error('lmz:QuadLoad:HorizonSection', ...
        'SectionId must be apex or stride_boundary.');
end
end

function value=withSection(schedule,sectionId)
value=lmz.schedule.EventSchedule.fromCyclic( ...
    schedule.names(),schedule.times(),schedule.ReturnTime, ...
    'FixedMask',schedule.fixedMask(), ...
    'ReturnTimeFixed',schedule.ReturnTimeFixed, ...
    'MinimumGap',schedule.MinimumGap, ...
    'StartSectionId',sectionId,'StopSectionId',sectionId);
end

function value=fieldOr(source,name,fallback)
if isstruct(source)&&isfield(source,name),value=source.(name);else,value=fallback;end
end
