classdef QuadLoadHorizonContinuation
    %QUADLOADHORIZONCONTINUATION Explicit N-to-N+1 embedding and resume.
    methods
        function [problem,decision,diagnostics]=extend(~,previous,newCount, ...
                configuration,context)
            if nargin<4,configuration=struct();end
            if nargin<5,context=lmz.api.RunContext.synchronous(0);end
            if ~isa(previous,'lmzmodels.slip_quad_load.QuadLoadMultipleShootingProblem')
                error('lmz:QuadLoad:HorizonContinuationProblem', ...
                    'Continuation requires a quad-load shooting problem.');
            end
            oldCount=previous.Horizon.segmentCount();
            if newCount~=oldCount+1
                error('lmz:QuadLoad:HorizonEmbeddingCount', ...
                    'Horizon continuation embeds exactly N into N+1.');
            end
            configuration.NumberOfStrides=newCount;
            configuration.Formulation=previous.Horizon.Formulation;
            if ~isfield(configuration,'EnergyMode')
                configuration.EnergyMode=arrayfun(@(index) ...
                    previous.Horizon.Segments{min(index,oldCount)}. ...
                    EnergyWorkSpecification.Mode,1:newCount, ...
                    'UniformOutput',false);
            end
            if ~isfield(configuration,'FreeControlMask')
                mask=false(newCount,4);
                mask(1:oldCount,:)=previous.Codec.FreeControlMask;
                configuration.FreeControlMask=mask;
            end
            configuration.InitializationContext=context;
            problem=lmzmodels.slip_quad_load.QuadLoadMultipleShootingProblem( ...
                previous.Model,configuration);
            oldDecision=fieldOr(configuration,'PreviousDecision', ...
                previous.Codec.decisionDefaults());
            [decision,map]=embedByName(previous,oldDecision,problem);
            diagnostics=struct('FromStrideCount',oldCount, ...
                'ToStrideCount',newCount,'EmbeddingMap',map, ...
                'PreservedVariableCount',sum(map>0), ...
                'AddedVariableCount',sum(map==0), ...
                'DimensionChangedExplicitly',true, ...
                'PhysicalRootClaimed',false);
        end

        function [decision,diagnostics]=projectEnergyNeutral(~,problem, ...
                strideIndex,decision)
            if nargin<4||isempty(decision),decision=problem.Codec.decisionDefaults();end
            hyperplane=problem.energyHyperplane(strideIndex,decision);
            bindings=problem.Codec.ShootingSchema.Bindings;
            indices=find(arrayfun(@(item)strcmp(item.Kind,'control')&& ...
                item.OwnerIndex==strideIndex,bindings));
            if numel(indices)~=4
                error('lmz:QuadLoad:EnergyProjectionControls', ...
                    ['Energy-neutral projection requires all four post-swing ' ...
                    'controls of the selected stride to be free.']);
            end
            current=decision(indices);weights=hyperplane.Weights(:);
            [projected,active]=nonnegativeProjection( ...
                current,weights,hyperplane.Target);
            decision(indices)=projected;
            residual=weights.'*projected-hyperplane.Target;
            diagnostics=struct('StrideIndex',strideIndex, ...
                'OriginalControls',current,'ProjectedControls',projected, ...
                'EnergyHyperplane',hyperplane,'Residual',residual, ...
                'ActiveLowerBounds',find(active), ...
                'ProjectionNorm',norm(projected-current), ...
                'ExactWithinTolerance',abs(residual)<=1e-10);
        end

        function result=continueTo(obj,configuration,options,context)
            if nargin<2,configuration=struct();end
            if nargin<3,options=struct();end
            if nargin<4,context=lmz.api.RunContext.synchronous(0);end
            startCount=fieldOr(configuration,'StartStrideCount',2);
            targetCount=fieldOr(configuration,'TargetStrideCount',5);
            if targetCount<startCount||startCount<1|| ...
                    any([startCount targetCount]~=fix([startCount targetCount]))
                error('lmz:QuadLoad:HorizonContinuationCount', ...
                    'Continuation stride counts are invalid.');
            end
            initialConfig=configuration;
            initialConfig.NumberOfStrides=startCount;
            initialConfig=rmfieldIfPresent(initialConfig, ...
                {'StartStrideCount','TargetStrideCount'});
            suppliedDecision=[];
            if isfield(initialConfig,'InitialDecisionForContinuation')
                suppliedDecision=initialConfig.InitialDecisionForContinuation(:);
                initialConfig=rmfield(initialConfig, ...
                    'InitialDecisionForContinuation');
            end
            problem=lmzmodels.slip_quad_load.QuadLoadMultipleShootingProblem( ...
                [],initialConfig);
            decision=problem.Codec.decisionDefaults();records=cell(0,1);
            if ~isempty(suppliedDecision)
                decision=suppliedDecision;
                problem.Codec.DecisionSchema.validateVector(decision);
            end
            checkpoints=cell(0,1);completed=startCount;
            physicalCompleted=fieldOr(options, ...
                'InitialCompletedPhysicalStrideCount',0);
            if ~isnumeric(physicalCompleted)||~isscalar(physicalCompleted)|| ...
                    ~isfinite(physicalCompleted)||physicalCompleted<0|| ...
                    physicalCompleted~=fix(physicalCompleted)|| ...
                    physicalCompleted>startCount
                error('lmz:QuadLoad:HorizonPhysicalPrefix', ...
                    'The initial completed physical prefix is invalid.');
            end
            stopOnFailure=logical(fieldOr(options,'StopOnUnresolved',true));
            for count=startCount:targetCount
                if count>startCount
                    nextConfig=initialConfig;
                    nextConfig.PreviousDecision=decision;
                    [problem,decision,embedding]=obj.extend( ...
                        problem,count,nextConfig,context);
                else
                    embedding=struct('FromStrideCount',startCount, ...
                        'ToStrideCount',startCount,'EmbeddingMap', ...
                        (1:numel(decision)).','DimensionChangedExplicitly',false);
                end
                solveEach=logical(fieldOr(options,'SolveEachHorizon',false));
                solveResult=[];homotopy=struct('Completed',true, ...
                    'Lambda',1,'Attempts',{{}},'Checkpoints',{{}}, ...
                    'TerminationReason','not-required','Adaptive',false);
                if solveEach
                    solveOptions=fieldOr(options,'FeasibilityOptions',struct());
                    solveOptions.InitialDecision=decision;
                    useHomotopy=count>startCount&&logical(fieldOr( ...
                        options,'UseAdaptiveHomotopy',true));
                    if useHomotopy
                        homotopyOptions=fieldOr(solveOptions, ...
                            'SolverOptions',struct());
                        if ~isfield(homotopyOptions,'Solver')
                            homotopyOptions.Solver='lsqnonlin';
                        end
                        homotopyOptions=copyHomotopyOptions( ...
                            homotopyOptions,options);
                        homotopy=lmz.shooting.HorizonContinuation(). ...
                            traceHomotopy(problem,decision, ...
                            homotopyOptions,context);
                        if homotopy.Completed
                            decision=homotopy.Decision;
                            solveOptions.InitialDecision=decision;
                        end
                    end
                    if homotopy.Completed
                        [solveResult,report]=problem.solveFeasibility( ...
                            solveOptions,context);
                        decision=solveResult.Solution.DecisionValues;
                    else
                        report=problem.analyze(decision,context,struct( ...
                            'ComputeJacobian',false, ...
                            'TerminationReason', ...
                            homotopy.TerminationReason));
                        report.Homotopy=homotopy;
                        report.PartialHorizonPreserved=true;
                    end
                else
                    report=problem.analyze(decision,context, ...
                        struct('ComputeJacobian',false, ...
                        'TerminationReason','evaluation_only'));
                end
                records{end+1}=struct('StrideCount',count, ...
                    'Problem',problem,'Decision',decision, ...
                    'SolveResult',solveResult,'FeasibilityReport',report, ...
                    'Embedding',embedding,'Homotopy',homotopy); %#ok<AGROW>
                completed=count;
                if report.RootFound,physicalCompleted=count;end
                checkpoint=makeCheckpoint(problem,decision,count, ...
                    targetCount,physicalCompleted,report,homotopy,context);
                checkpoints{end+1}=checkpoint; %#ok<AGROW>
                callback=fieldOr(options,'CheckpointFcn',[]);
                if isa(callback,'function_handle'),callback(checkpoint);end
                context.progress(count/targetCount,sprintf( ...
                    'Quad-load horizon continuation %d/%d',count,targetCount));
                if solveEach&&stopOnFailure&&~report.RootFound,break,end
            end
            result=struct('RequestedStrideCount',targetCount, ...
                'CompletedStrideCount',completed,'Records',{records}, ...
                'CompletedPhysicalStrideCount',physicalCompleted, ...
                'StopOnUnresolved',stopOnFailure, ...
                'Checkpoints',{checkpoints},'FinalProblem',problem, ...
                'FinalDecision',decision,'FinalReport', ...
                records{end}.FeasibilityReport, ...
                'PhysicalFiveStrideRootFound',targetCount==5&& ...
                completed==5&&records{end}.FeasibilityReport.RootFound, ...
                'GlobalInfeasibilityClaimed',false);
        end

        function result=resume(obj,checkpoint,options,context)
            if nargin<3,options=struct();end
            if nargin<4,context=lmz.api.RunContext.synchronous(0);end
            required={'SchemaVersion','Kind','FrameworkVersion', ...
                'CompletedStrideCount','TargetStrideCount', ...
                'CompletedPhysicalStrideCount','Decision','DecisionHash', ...
                'DecisionNames','DecisionSchema','DecisionSchemaHash', ...
                'Configuration','ConfigurationHash','ProblemContract', ...
                'ProblemContractHash','SourceDataHashes', ...
                'SourceDataHashesHash','FeasibilityReport','Homotopy', ...
                'CheckpointHash'};
            if ~isstruct(checkpoint)||~isscalar(checkpoint)|| ...
                    ~all(isfield(checkpoint,required))|| ...
                    ~strcmp(checkpoint.SchemaVersion,'1.0.0')|| ...
                    ~strcmp(checkpoint.Kind, ...
                    'quad_load_horizon_continuation-v1')
                error('lmz:QuadLoad:HorizonContinuationCheckpoint', ...
                    'Quad-load continuation checkpoint is invalid.');
            end
            assertInertCheckpoint(checkpoint);
            validateFramework(checkpoint.FrameworkVersion);
            validateCheckpointHashes(checkpoint);
            counts=[checkpoint.CompletedStrideCount, ...
                checkpoint.TargetStrideCount, ...
                checkpoint.CompletedPhysicalStrideCount];
            if ~isnumeric(counts)||numel(counts)~=3|| ...
                    any(~isfinite(counts))||any(counts~=fix(counts))|| ...
                    counts(1)<1||counts(2)<counts(1)||counts(3)<0|| ...
                    counts(3)>counts(1)
                error('lmz:QuadLoad:HorizonContinuationCheckpoint', ...
                    'Checkpoint stride counts or physical prefix are invalid.');
            end
            configuration=checkpoint.Configuration;
            if ~isstruct(configuration)||~isscalar(configuration)|| ...
                    ~isfield(configuration,'NumberOfStrides')|| ...
                    configuration.NumberOfStrides~= ...
                    checkpoint.CompletedStrideCount
                error('lmz:QuadLoad:HorizonCheckpointConfiguration', ...
                    'Checkpoint configuration does not match its horizon.');
            end
            problem=lmzmodels.slip_quad_load.QuadLoadMultipleShootingProblem( ...
                [],configuration);
            rebuiltContract=problem.contract();
            if ~strcmp(lmz.io.ArtifactStore.dataHash(rebuiltContract), ...
                    checkpoint.ProblemContractHash)
                error('lmz:QuadLoad:HorizonCheckpointProblemContract', ...
                    'Checkpoint problem contract is incompatible.');
            end
            rebuiltNames=problem.Codec.DecisionSchema.names();
            checkpointNames=textList(checkpoint.DecisionNames);
            if ~isequal(rebuiltNames(:),checkpointNames(:))|| ...
                    ~strcmp(lmz.io.ArtifactStore.dataHash( ...
                    problem.Codec.DecisionSchema.toStruct()), ...
                    checkpoint.DecisionSchemaHash)
                error('lmz:QuadLoad:HorizonCheckpointSchema', ...
                    'Checkpoint decision names do not match the rebuilt problem.');
            end
            problem.Codec.DecisionSchema.validateVector(checkpoint.Decision);
            configuration.StartStrideCount=checkpoint.CompletedStrideCount;
            configuration.TargetStrideCount=checkpoint.TargetStrideCount;
            configuration.NumberOfStrides=checkpoint.CompletedStrideCount;
            configuration.InitialDecisionForContinuation=checkpoint.Decision;
            options.InitialCompletedPhysicalStrideCount= ...
                checkpoint.CompletedPhysicalStrideCount;
            result=obj.continueTo(configuration,options,context);
        end
    end
end

function value=makeCheckpoint(problem,decision,completed,target, ...
        physicalCompleted,report,homotopy,context)
configuration=storableConfiguration(problem.Configuration);
contract=problem.contract();schema=problem.Codec.DecisionSchema.toStruct();
sourceHashes=fieldOr(configuration,'SourceDataHashes',struct());
value=struct('SchemaVersion','1.0.0', ...
    'Kind','quad_load_horizon_continuation-v1', ...
    'FrameworkVersion',lmz.util.Version.current(), ...
    'CompletedStrideCount',completed,'TargetStrideCount',target, ...
    'CompletedPhysicalStrideCount',physicalCompleted, ...
    'Decision',decision(:),'DecisionHash', ...
    lmz.io.ArtifactStore.dataHash(decision(:)), ...
    'DecisionNames',{problem.Codec.DecisionSchema.names()}, ...
    'DecisionSchema',schema,'DecisionSchemaHash', ...
    lmz.io.ArtifactStore.dataHash(schema), ...
    'Configuration',configuration,'ConfigurationHash', ...
    lmz.io.ArtifactStore.dataHash(configuration), ...
    'ProblemContract',contract,'ProblemContractHash', ...
    lmz.io.ArtifactStore.dataHash(contract), ...
    'SourceDataHashes',sourceHashes,'SourceDataHashesHash', ...
    lmz.io.ArtifactStore.dataHash(sourceHashes), ...
    'FeasibilityReport',report,'Homotopy',homotopy, ...
    'RandomSeed',context.RandomSeed, ...
    'CreatedAt',lmz.compat.Timestamp.current());
% Hash the complete inert payload last so incidental field tampering is
% detected before any problem is reconstructed.
value.CheckpointHash=lmz.io.ArtifactStore.dataHash(value);
end

function assertInertCheckpoint(checkpoint)
try
    lmz.io.ArtifactStore.dataHash(checkpoint);
catch
    error('lmz:QuadLoad:HorizonContinuationCheckpoint', ...
        'Quad-load continuation checkpoint must contain inert plain data.');
end
end

function validateCheckpointHashes(checkpoint)
pairs={ ...
    'Decision','DecisionHash'; ...
    'DecisionSchema','DecisionSchemaHash'; ...
    'Configuration','ConfigurationHash'; ...
    'ProblemContract','ProblemContractHash'; ...
    'SourceDataHashes','SourceDataHashesHash'};
for index=1:size(pairs,1)
    expected=lmz.io.ArtifactStore.dataHash(checkpoint.(pairs{index,1}));
    actual=checkpoint.(pairs{index,2});
    if ~ischar(actual)||~strcmp(actual,expected)
        error('lmz:QuadLoad:HorizonCheckpointIntegrity', ...
            'Checkpoint %s is inconsistent.',pairs{index,2});
    end
end
if ~isfield(checkpoint.Configuration,'SourceDataHashes')|| ...
        ~isequal(checkpoint.Configuration.SourceDataHashes, ...
        checkpoint.SourceDataHashes)
    error('lmz:QuadLoad:HorizonCheckpointIntegrity', ...
        'Checkpoint source-data hashes are inconsistent.');
end
payload=rmfield(checkpoint,'CheckpointHash');
expected=lmz.io.ArtifactStore.dataHash(payload);
if ~ischar(checkpoint.CheckpointHash)|| ...
        ~strcmp(checkpoint.CheckpointHash,expected)
    error('lmz:QuadLoad:HorizonCheckpointIntegrity', ...
        'Checkpoint payload hash is invalid.');
end
end

function validateFramework(recorded)
if ~ischar(recorded)
    error('lmz:QuadLoad:HorizonCheckpointFramework', ...
        'Checkpoint framework version is invalid.');
end
try
    compatible=lmz.util.Version.isCompatible( ...
        lmz.util.Version.current(),recorded);
catch
    compatible=false;
end
if ~compatible
    error('lmz:QuadLoad:HorizonCheckpointFramework', ...
        'Checkpoint framework %s is incompatible with %s.', ...
        recorded,lmz.util.Version.current());
end
end

function value=copyHomotopyOptions(value,source)
names={'HomotopyInitialStep','HomotopyMinimumStep', ...
    'HomotopyMaximumStep','HomotopyStepGrowth', ...
    'HomotopyStepReduction','HomotopyMaximumAttempts'};
for index=1:numel(names)
    if isfield(source,names{index})
        value.(names{index})=source.(names{index});
    end
end
end

function [decision,map]=embedByName(previous,oldDecision,next)
previous.Codec.DecisionSchema.validateVector(oldDecision);
oldNames=previous.Codec.DecisionSchema.names();newNames= ...
    next.Codec.DecisionSchema.names();decision=next.Codec.decisionDefaults();
map=zeros(numel(newNames),1);
for index=1:numel(newNames)
    match=find(strcmp(newNames{index},oldNames),1);
    if ~isempty(match),decision(index)=oldDecision(match);map(index)=match;end
end
next.Codec.DecisionSchema.validateVector(decision);
end

function [value,active]=nonnegativeProjection(source,weights,target)
value=source(:);weights=weights(:);active=false(size(value));
free=true(size(value));
for iteration=1:numel(value)+1
    remainingTarget=target-weights(active).'*value(active);
    denominator=weights(free).'*weights(free);
    if denominator<=eps
        error('lmz:QuadLoad:EnergyProjectionDegenerate', ...
            'Energy-neutral control projection is degenerate.');
    end
    candidate=value;
    candidate(free)=source(free)-weights(free)*( ...
        (weights(free).'*source(free)-remainingTarget)/denominator);
    negative=free&candidate<0;
    if ~any(negative),value=candidate;return,end
    value(negative)=0;active(negative)=true;free(negative)=false;
end
error('lmz:QuadLoad:EnergyProjectionFailure', ...
    'Energy-neutral control projection did not terminate.');
end

function value=storableConfiguration(source)
value=rmfieldIfPresent(source,{'InitializationContext','PreviousDecision'});
try
    lmz.io.ArtifactStore.dataHash(value);
catch
    error('lmz:QuadLoad:HorizonCheckpointConfiguration', ...
        'Checkpoint configuration must contain inert plain data.');
end
end

function value=textList(source)
if ischar(source)
    value={source};
elseif isstring(source)
    value=cellstr(source);
elseif iscell(source)
    value=source(:).';
else
    error('lmz:QuadLoad:HorizonCheckpointSchema', ...
        'Checkpoint decision names are invalid.');
end
end

function value=rmfieldIfPresent(value,names)
for index=1:numel(names)
    if isfield(value,names{index}),value=rmfield(value,names{index});end
end
end

function value=fieldOr(source,name,fallback)
if isstruct(source)&&isfield(source,name),value=source.(name);else,value=fallback;end
end
