classdef QuadLoadSectionSimulationAdapter < ...
        lmz.shooting.SectionSimulationAdapter
    %QUADLOADSECTIONSIMULATIONADAPTER Direct section-local load propagation.
    %   Non-apex decisions are integrated from their supplied section state
    %   with a cyclically rotated contact schedule.  The source tAPEX slot is
    %   used only as the integration return time on stride-boundary and
    %   touchdown paths; its apex equation remains diagnostic there.
    properties (SetAccess=private)
        Codec
    end

    methods
        function obj=QuadLoadSectionSimulationAdapter(codec)
            if ~isa(codec, ...
                    'lmzmodels.slip_quad_load.QuadLoadSectionDecisionCodec')
                error('lmz:QuadLoad:SectionAdapterCodec', ...
                    'Load section adapter requires its section decision codec.');
            end
            obj.Codec=codec;
        end

        function value=evaluate(obj,decision,parameters,context,includeSimulation)
            if nargin<3,parameters=[];end
            if nargin<4||isempty(context)
                context=lmz.api.RunContext.synchronous(0);
            end
            if nargin<5,includeSimulation=false;end
            request=struct('DecodedDecision',obj.Codec.decode(decision), ...
                'PhysicalParameters',parameters(:),'Configuration',struct(), ...
                'Segment',[],'StartNode',[],'StopNode',[], ...
                'EventSchedule',[],'ControlParameters',[]);
            value=obj.simulateSegment(request,context,includeSimulation);
        end

        function value=simulateSegment(obj,request,context,includeSimulation)
            if nargin<4,includeSimulation=false;end
            if nargin<3||isempty(context)
                context=lmz.api.RunContext.synchronous(0);
            end
            context.check();decoded=localDecoded(obj.Codec,request);
            plan=lmzmodels.slip_quad_load.XAccumPlanAdapter.toPlan( ...
                decoded.BaseStrideVector);
            specification=plan.StrideSpecs(1);
            controls=specification.ControlParameters;
            schedule=lmz.schedule.EventSchedule.fromCyclic( ...
                obj.Codec.EventNames,decoded.EventTimes,decoded.ReturnTime, ...
                'MinimumGap',0,'StartSectionId',obj.Codec.StartSection.Id, ...
                'StopSectionId',obj.Codec.StopSection.Id);
            [~,origin]=lmzmodels.slip_quad_load. ...
                QuadLoadShootingUtilities.localState(decoded.InitialState);
            vector=lmzmodels.slip_quad_load.QuadLoadShootingUtilities. ...
                vector(decoded.InitialState,schedule, ...
                specification.PhysicalParameters, ...
                controls.PostSwingStiffness,controls.PreSwingStiffness);
            raw=lmzmodels.slip_quad_load.MultiStrideSimulator().runRaw( ...
                vector,context,false);
            raw=worldGauge(raw,origin);
            [terminal,crossing,records,endpointDiagnostics]= ...
                terminalFor(raw,obj.Codec.StopSection,decoded.ReturnTime, ...
                decoded.EndpointContactIndex,decoded.BaseStrideVector);
            raw.EventRecords=records;
            raw.States(end,:)=terminal(:).';
            raw.LegacyStates(end,:)=terminal(:).';
            coordinates=obj.Codec.TerminalStateCoordinates.extract(terminal);
            if strcmp(obj.Codec.StopSection.Descriptor.EventId,'APEX')
                sectionResidual=raw.Residual(9);
            else
                sectionResidual=zeros(0,1);
            end
            simulation=[];simulationValid=true;simulationError='';
            if includeSimulation
                try
                    simulation=makeSimulation(raw,vector,obj.Codec, ...
                        endpointDiagnostics);
                catch exception
                    simulationValid=false;simulationError=exception.identifier;
                end
            end
            finite=all(isfinite([raw.Residual(:);terminal(:); ...
                coordinates(:);sectionResidual(:)]));
            directNonApex=~strcmp(obj.Codec.StartSection.Id,'apex')|| ...
                ~strcmp(obj.Codec.StopSection.Id,'apex');
            diagnostics=struct('ModelId','slip_quad_load', ...
                'Formulation','direct-section-local-single-shooting-v1', ...
                'DirectSectionIntegration',true, ...
                'DirectNonApexIntegration',directNonApex, ...
                'FullApexTrajectoryLookupDuringEvaluation',false, ...
                'ApexOracleUsed',~directNonApex, ...
                'SourceApexPhaseGaugePreserved',false, ...
                'StartSectionId',obj.Codec.StartSection.Id, ...
                'StopSectionId',obj.Codec.StopSection.Id, ...
                'StartStateSide',obj.Codec.StartSection.StateSide, ...
                'StopStateSide',obj.Codec.StopSection.StateSide, ...
                'SourceFixedCoordinateNames', ...
                {obj.Codec.SourceFixedCoordinateNames}, ...
                'SourceFixedInitialCoordinates',fixedCoordinates( ...
                decoded.InitialState,obj.Codec), ...
                'SourceFixedTerminalCoordinates',fixedCoordinates( ...
                terminal,obj.Codec), ...
                'LegacyEndpointVariableRole',endpointRole(obj.Codec), ...
                'SegmentSimulationCount',1,'HiddenTimingSolve',false, ...
                'SimulationConstructionValid',simulationValid, ...
                'SimulationConstructionError',simulationError, ...
                'RawApexResidualDiagnostic',raw.Residual(9), ...
                'Endpoint',endpointDiagnostics, ...
                'SourceLineage',decoded.SourceLineage, ...
                'RawResidual',raw.Residual);
            value=struct('TerminalState',terminal, ...
                'TerminalCoordinates',coordinates, ...
                'ContactResiduals',raw.Residual(1:8), ...
                'SectionResidual',sectionResidual(:), ...
                'EnergyResidual',zeros(0,1),'Crossing',crossing, ...
                'Simulation',simulation,'PhysicalValidity', ...
                finite&&all(raw.States(:,3)>0)&&crossing.Accepted&& ...
                simulationValid,'Diagnostics',diagnostics);
            value=obj.validateResult(value);
        end
    end
end

function value=fixedCoordinates(state,codec)
schema=codec.StateCoordinates.PhysicalSchema;
value=zeros(numel(codec.SourceFixedCoordinateNames),1);
for index=1:numel(value)
    value(index)=state(schema.indexOf( ...
        codec.SourceFixedCoordinateNames{index}));
end
end

function value=localDecoded(codec,request)
if ~isstruct(request)||~isscalar(request)|| ...
        ~isfield(request,'DecodedDecision')
    error('lmz:QuadLoad:SectionRequest', ...
        'Load section request requires DecodedDecision.');
end
value=request.DecodedDecision;
if isnumeric(value),value=codec.decode(value);end
required={'InitialState','EventTimes','ReturnTime','BaseStrideVector', ...
    'EndpointContactIndex','SourceLineage'};
if ~isstruct(value)||~all(isfield(value,required))
    error('lmz:QuadLoad:SectionDecodedDecision', ...
        'Decoded load section decision is incomplete.');
end
end

function raw=worldGauge(raw,origin)
raw.States(:,[1 15])=raw.States(:,[1 15])+origin;
raw.LegacyStates(:,[1 15])=raw.LegacyStates(:,[1 15])+origin;
raw.EventStates(:,[1 15])=raw.EventStates(:,[1 15])+origin;
for index=1:numel(raw.EventRecords)
    fields={'State','PreState','PostState'};
    for fieldIndex=1:numel(fields)
        name=fields{fieldIndex};
        raw.EventRecords(index).(name)([1 15])= ...
            raw.EventRecords(index).(name)([1 15])+origin;
    end
end
end

function [terminal,crossing,records,diagnostics]=terminalFor( ...
        raw,section,returnTime,endpointContactIndex,baseVector)
records=raw.EventRecords;eventId=section.Descriptor.EventId;
if strcmp(eventId,'STRIDE_BOUNDARY')
    record=struct('Name','STRIDE_BOUNDARY','Time',returnTime, ...
        'StrideIndex',1,'State',raw.States(end,:), ...
        'PreState',raw.States(end,:),'PostState',raw.States(end,:), ...
        'DirectionalDerivative',NaN,'Direction',0,'Metadata', ...
        struct('EndpointRole','integration_boundary'));
    history=orderedHistory(records,returnTime,'');
    crossing=section.crossingFromRecord(record,'Occurrence',1, ...
        'EventHistory',history);
    terminal=crossing.State(:);records(end+1,1)=stripExtra(record);
    extraction='integration_endpoint';actualEventTime=returnTime;
elseif endpointContactIndex>0
    matches=find(strcmp({records.Name},eventId));
    if numel(matches)~=1
        error('lmz:QuadLoad:SectionStopEvent', ...
            'The requested load touchdown was not simulated exactly once.');
    end
    index=matches(1);record=records(index);
    actualEventTime=record.Time;record.Time=returnTime;
    record.DirectionalDerivative=guardDerivative( ...
        record.PreState(:),eventId,baseVector);
    record.Direction=sign(record.DirectionalDerivative);
    history=orderedHistory(records,actualEventTime,eventId);
    crossing=section.crossingFromRecord(record,'Occurrence',1, ...
        'EventHistory',history);
    terminal=crossing.State(:);records(index)=stripExtra(record);
    extraction='final_touchdown_event';
else
    matches=find(strcmp({records.Name},eventId));
    if numel(matches)~=1
        error('lmz:QuadLoad:SectionStopEvent', ...
            'The requested load endpoint event was not simulated exactly once.');
    end
    index=matches(1);record=records(index);actualEventTime=record.Time;
    record.Time=returnTime;record.DirectionalDerivative=NaN;
    record.Direction=section.CrossingDirection;
    history=orderedHistory(records,actualEventTime,eventId);
    crossing=section.crossingFromRecord(record,'Occurrence',1, ...
        'EventHistory',history);
    terminal=crossing.State(:);records(index)=stripExtra(record);
    extraction='integration_endpoint_named_event';
end
diagnostics=struct('EventId',eventId,'Extraction',extraction, ...
    'RequestedReturnTime',returnTime,'IntegratedEventTime',actualEventTime, ...
    'EndpointTimeDifference',returnTime-actualEventTime, ...
    'TerminalWasInteriorLookup',false, ...
    'EndpointContactIndex',endpointContactIndex, ...
    'CrossingAccepted',crossing.Accepted, ...
    'CrossingRejectionReason',crossing.RejectionReason);
end

function value=stripExtra(record)
% Legacy EventRecords use a fixed six-field layout.  Keep that public
% layout after using richer local fields to construct the crossing.
value=struct('Name',record.Name,'Time',record.Time, ...
    'StrideIndex',record.StrideIndex,'State',record.State, ...
    'PreState',record.PreState,'PostState',record.PostState);
end

function value=orderedHistory(records,endpointTime,endpointId)
times=[records.Time].';names={records.Name}.';
keep=times>0&times<endpointTime;
if ~isempty(endpointId),keep=keep&~strcmp(names,endpointId);end
[~,order]=sort(times(keep));selected=names(keep);
value=reshape(selected(order),1,[]);
end

function value=guardDerivative(state,eventId,baseVector)
decoded=lmzmodels.slip_quad_load.FirstStrideLayout.decode(baseVector);
length=abs(decoded.QuadrupedParameters(11));
back=min(.9,max(.1,abs(decoded.QuadrupedParameters(13))));
dy=state(4);phi=state(5);dphi=state(6);
switch eventId
    case 'BL_TD'
        alpha=state(7);dalpha=state(8);
        value=dy-back*cos(phi)*dphi+ ...
            length*sin(phi+alpha)*(dphi+dalpha);
    otherwise
        value=NaN;
end
end

function value=makeSimulation(raw,vector,codec,endpointDiagnostics)
decoded=lmzmodels.slip_quad_load.XAccumAdapter.decode(vector);
parameters=struct('stride_count',1, ...
    'per_stride_parameters',raw.Parameters, ...
    'quadruped',decoded.FirstStride.QuadrupedParameters, ...
    'load',decoded.FirstStride.LoadParameters);
diagnostics=struct('Evaluator','section-local-quad-load-v1', ...
    'DirectSectionIntegration',true,'StartSectionId', ...
    codec.StartSection.Id,'StopSectionId',codec.StopSection.Id, ...
    'Endpoint',endpointDiagnostics,'HiddenTimingSolve',false, ...
    'RawResidual',raw.Residual);
provenance=struct('sourceRepository', ...
    ['https://github.com/DLARlab/' ...
    '2025_Gait_Transitions_in_Load_Pulling_Quadrupeds_Insights.git'], ...
    'sourceCommit','19f3133073c988cc0c3424a647b4adbb60a90b99', ...
    'sourceFile','Stored_Functions/Dynamics/Quad_Load_ZeroFun_Transition_v2.m');
observables=lmzmodels.slip_quad_load.ObservableProvider.compute(raw);
interim=lmz.api.SimulationResult(raw.Time, ...
    lmzmodels.slip_quad_load.PhysicalStateSchema.create(),raw.States, ...
    raw.Modes,observables,parameters,diagnostics,provenance, ...
    'EventRecords',raw.EventRecords, ...
    'GroundReactionForces',raw.GroundReactionForces);
value=lmz.api.SimulationResult(interim.Time,interim.StateSchema, ...
    interim.States,interim.Modes,interim.Observables,interim.Parameters, ...
    interim.Diagnostics,interim.Provenance, ...
    'EventRecords',interim.EventRecords, ...
    'GroundReactionForces',interim.GroundReactionForces, ...
    'Kinematics',lmzmodels.slip_quad_load.KinematicsProvider.compute(interim));
end

function value=endpointRole(codec)
if strcmp(codec.StopSection.Descriptor.EventId,'APEX')
    value='apex_section_and_return_time';
else
    value='return_time_only';
end
end
