classdef QuadLoadMultipleShootingEvaluator < lmz.shooting.SectionSimulationAdapter
    %QUADLOADMULTIPLESHOOTINGEVALUATOR Direct one-pass load segments.
    methods
        function value=simulateSegment(~,request,context,includeSimulation)
            if nargin<4,includeSimulation=false;end
            required={'Segment','StartNode','StopNode','EventSchedule', ...
                'ControlParameters','PhysicalParameters','DecodedDecision', ...
                'Configuration'};
            if ~isstruct(request)||~all(isfield(request,required))
                error('lmz:QuadLoad:ShootingRequest', ...
                    'Quad-load shooting request is incomplete.');
            end
            segment=request.Segment;index=segment.Index;
            state=request.StartNode.FullState(:);
            post=effectiveControls(request.ControlParameters);
            if index==1
                physical=request.PhysicalParameters.Segment;
                pre=fieldOr(physical,'InitialPreSwingStiffness',post);
                pre=effectiveControls(pre);
            else
                pre=effectiveControls( ...
                    request.DecodedDecision.Controls{index-1});
                physical=request.PhysicalParameters.Segment;
            end
            vector=lmzmodels.slip_quad_load.QuadLoadShootingUtilities. ...
                vector(state,request.EventSchedule,physical,post,pre);
            raw=lmzmodels.slip_quad_load.LegacyQuadLoadEvaluator(). ...
                evaluateStride(vector,context,false);
            [terminal,translation]= ...
                lmzmodels.slip_quad_load.QuadLoadShootingUtilities. ...
                localState(raw.LegacyStates(end,:).');
            sectionSchema=request.StopNode.StateSchema;
            coordinates=sectionSchema.extract(terminal);
            contact=raw.Residual(1:8);
            strideBoundary=strcmp(request.StopNode.SectionId, ...
                'stride_boundary');
            if strideBoundary
                sectionResidual=zeros(0,1);
            else
                sectionResidual=raw.Residual(9);
            end
            [energyResidual,energyDiagnostics]=energyResidualFor( ...
                request,state,pre,post);
            if strideBoundary
                crossing=strideBoundaryCrossing(raw,terminal);
            else
                crossing=lmz.schedule.ContactConstraintProvider. ...
                    sectionCrossing(raw,'APEX',4,'post');
            end
            simulation=[];simulationValid=true;simulationError='';
            if includeSimulation
                try
                    simulation=lmzmodels.slip_quad_load. ...
                        MultiStrideSimulator().run(vector,context, ...
                        struct('EnforceEventTiming',false));
                catch exception
                    % A least-squares search may terminate at a finite
                    % residual whose trajectory is outside the public
                    % SimulationResult contract.  Preserve that qualified
                    % feasibility result, but never synthesize a simulation.
                    simulationValid=false;
                    simulationError=exception.identifier;
                end
            end
            schedule=request.EventSchedule;scheduleTimes=schedule.times();
            eventOrder=schedule.ReturnTime>scheduleTimes(end)&& ...
                all(diff([0;scheduleTimes;schedule.ReturnTime])> ...
                schedule.MinimumGap);
            finite=all(isfinite(raw.LegacyStates(:)))&& ...
                all(isfinite(raw.Residual));
            value=struct('TerminalState',terminal, ...
                'TerminalCoordinates',coordinates, ...
                'ContactResiduals',contact(:), ...
                'SectionResidual',sectionResidual(:), ...
                'EnergyResidual',energyResidual(:), ...
                'Crossing',crossing,'Simulation',simulation, ...
                'PhysicalValidity',finite&&all(raw.LegacyStates(:,3)>0)&& ...
                simulationValid&&energyDiagnostics.Accepted, ...
                'Diagnostics',struct('ModelId','slip_quad_load', ...
                'SegmentIndex',index,'EventOrderValid',eventOrder, ...
                'EnergyValid',logical(energyDiagnostics.Accepted), ...
                'StartSectionId',request.StartNode.SectionId, ...
                'StopSectionId',request.StopNode.SectionId, ...
                'ApexConditionActive',~strideBoundary, ...
                'SegmentSimulationCount',1,'HiddenTimingSolve',false, ...
                'SimulationConstructionValid',simulationValid, ...
                'SimulationConstructionError',simulationError, ...
                'WorldTranslation',translation,'FullXAccum',vector, ...
                'MinimumBodyHeight',min(raw.LegacyStates(:,3)), ...
                'ContactResidualNorm',norm(contact), ...
                'SectionResidualNorm',norm(sectionResidual), ...
                'Energy',energyDiagnostics, ...
                'RawResidual',raw.Residual));
        end
    end
end

function value=strideBoundaryCrossing(raw,terminal)
state=raw.LegacyStates(end,:).';
value=struct('SectionId','stride_boundary','SectionValue',0, ...
    'DirectionalDerivative',NaN,'CrossingDirection',0, ...
    'Grazing',false,'EventId','STRIDE_BOUNDARY', ...
    'ModeBefore','','ModeAfter','','Time',raw.Time(end), ...
    'PreState',state,'PostState',state,'State',terminal(:), ...
    'StateSide','post','Occurrence',1,'Accepted',true, ...
    'RejectionReason','');
end

function [residual,diagnostics]=energyResidualFor(request,state,pre,post)
index=request.Segment.Index;spec=request.Segment.EnergyWorkSpecification;
if index==1
    residual=zeros(0,1);
    diagnostics=struct('Mode',spec.Mode,'Applied',false, ...
        'Reason','no_preceding_parameter_transition','EnergyDelta',0, ...
        'DeclaredWork',0,'ConstraintResidual',0,'Accepted',true);return
end
previous=effectiveControls(request.DecodedDecision.Controls{index-1});
physical=request.PhysicalParameters.Segment;
before=struct('PhysicalParameters',physical,'ControlParameters', ...
    struct('PreSwingStiffness',previous,'PostSwingStiffness',previous));
after=struct('PhysicalParameters',physical,'ControlParameters', ...
    struct('PreSwingStiffness',pre,'PostSwingStiffness',post));
policy=lmzmodels.slip_quad_load.QuadLoadEnergyPolicy('Id','allow_non_neutral');
[delta,details]=policy.parameterTransitionEnergy(state,before,after);
work=spec.DeclaredWork;
switch spec.Mode
    case 'energy_neutral'
        mismatch=delta;residual=mismatch;
    case 'prescribed_work'
        mismatch=delta-work;residual=mismatch;
    case 'bounded_work'
        bound=abs(work);mismatch=max(0,abs(delta)-bound);
        residual=mismatch;
    case 'diagnostic_only'
        mismatch=delta-work;residual=mismatch;
    otherwise
        error('lmz:QuadLoad:ShootingEnergyMode', ...
            'Unknown energy/work mode %s.',spec.Mode);
end
tolerance=fieldOr(spec,'AcceptanceTolerance',1e-8);
diagnostics=struct('Mode',spec.Mode,'Applied',true, ...
    'EnergyDelta',delta,'DeclaredWork',work, ...
    'ConstraintResidual',mismatch,'Tolerance',tolerance, ...
    'Accepted',strcmp(spec.Mode,'diagnostic_only')||abs(mismatch)<=tolerance, ...
    'EnergyHyperplaneWeights',.5*state([7 9 11 13]).^2, ...
    'BeforePostSwing',previous,'AfterPostSwing',post, ...
    'Details',details);
end

function value=effectiveControls(source)
if isstruct(source)&&isfield(source,'PostSwingStiffness')
    source=source.PostSwingStiffness;
end
if ~isnumeric(source)||numel(source)~=4||any(~isfinite(source(:)))
    error('lmz:QuadLoad:ShootingControls', ...
        'Post-swing control data must contain four finite values.');
end
value=abs(source(:));
end

function value=fieldOr(source,name,fallback)
if isstruct(source)&&isfield(source,name),value=source.(name);else,value=fallback;end
end
