classdef QuadLoadFeasibilityEvidence
    %QUADLOADFEASIBILITYEVIDENCE Read and replay the Round 10 searches.
    properties (SetAccess=private)
        Path
        Data
    end

    methods
        function obj=QuadLoadFeasibilityEvidence(path)
            if nargin<1
                path=fullfile(lmz.util.ProjectPaths.examples(),'data', ...
                    'slip_quad_load','Scientific','MultipleShooting', ...
                    'round10_feasibility_evidence.json');
            end
            obj.Path=lmz.util.PathGuard.canonical(path,true);
            obj.Data=lmz.io.SafeJson.read(obj.Path,'Root',fileparts(obj.Path), ...
                'MaximumItems',50000);
            validateData(obj.Data);
        end

        function value=cases(obj)
            value=obj.Data.cases;
            if isstruct(value),value=num2cell(value);end
        end

        function value=caseRecord(obj,id)
            records=obj.cases();ids=cellfun(@(item)item.id,records, ...
                'UniformOutput',false);index=find(strcmp(ids,id),1);
            if isempty(index)
                error('lmz:QuadLoad:UnknownFeasibilityCase', ...
                    'Unknown quad-load feasibility case %s.',id);
            end
            value=records{index};
        end

        function value=attempts(obj,id)
            record=obj.caseRecord(id);value=record.attempts;
            if isstruct(value),value=num2cell(value);end
            value=value(:);
        end

        function value=configuration(obj,record)
            value=struct('NumberOfStrides',record.numberOfStrides, ...
                'EnergyMode',{textList(record.energyModes)}, ...
                'FreeControlMask',logicalMatrix(record.freeControlMask), ...
                'Formulation',record.formulation, ...
                'ExpectedLocalDimension',max(0, ...
                record.unknownCount-record.residualCount), ...
                'ResidualTolerance',1e-7,'RequireAcceptedCrossing',true);
            if isfield(record,'unboundedControls')&&record.unboundedControls
                value.UnboundedControls=true;
            end
            if isfield(record,'sectionId')
                value.SectionId=record.sectionId;
            end
            if isfield(record,'eventFreeMask')
                value.EventFreeMask=logical(record.eventFreeMask(:).');
            end
            if isfield(record,'initialXAccum')
                value.InitialDecision=record.initialXAccum(:);
            end
            if isfield(record,'declaredWork')
                value.DeclaredWork=record.declaredWork(:);
            end
            if isfield(record,'energyScale')
                value.EnergyScale=record.energyScale;
            end
            if isfield(record,'energyTolerance')
                value.EnergyTolerance=record.energyTolerance;
            end
            library=lmzmodels.slip_quad_load.StrideTemplateLibrary();
            template=library.record(obj.Data.sourceTemplateId);
            templatePath=library.pathFor(template.id);
            if ~strcmpi(template.sha256,obj.Data.sourceTemplateSha256)|| ...
                    ~strcmpi(lmz.util.FileHash.sha256(templatePath), ...
                    obj.Data.sourceTemplateSha256)
                error('lmz:QuadLoad:FeasibilityTemplateHash', ...
                    ['Feasibility evidence and its source template have ' ...
                    'inconsistent SHA-256 values.']);
            end
            value.FeasibilityEvidenceCaseId=record.id;
            value.SourceDataHashes=struct( ...
                'QuadLoadFeasibilityEvidence',sourceRecord(obj.Path, ...
                lmz.util.FileHash.sha256(obj.Path)), ...
                'QuadLoadStrideTemplate',sourceRecord(templatePath, ...
                template.sha256));
        end

        function [problem,decision]=problemFor(obj,id)
            record=obj.caseRecord(id);
            problem=lmzmodels.slip_quad_load. ...
                QuadLoadMultipleShootingProblem([],obj.configuration(record));
            decision=record.decision(:);
            problem.getDecisionSchema().validateVector(decision);
        end

        function value=replay(obj,id,context,includeSimulation)
            if nargin<3||isempty(context)
                context=lmz.api.RunContext.synchronous(obj.Data.randomSeed);
            end
            if nargin<4,includeSimulation=false;end
            record=obj.caseRecord(id);[problem,decision]=obj.problemFor(id);
            residual=problem.evaluateShooting( ...
                decision,[],context,includeSimulation);
            scaled=residual.scaled();
            solverExit=record.solver.exitFlag;
            classification=classify(residual.Feasibility.Valid, ...
                residual.Feasibility.PhysicalValidity,solverExit, ...
                numel(scaled),numel(decision));
            blockNames={residual.Blocks.Name};
            blockNames=blockNames(:);
            blockScaledNorms=arrayfun(@(item)norm(item.scaled()), ...
                residual.Blocks);
            blockScaledNorms=blockScaledNorms(:);
            storedBlockNames={};storedBlockScaledNorms=[];
            blockNamesMatch=true;blockNormsMatch=true;
            if isfield(record,'blockNames')
                storedBlockNames=textList(record.blockNames);
                storedBlockScaledNorms=record.blockScaledNorms(:);
                blockNamesMatch=isequal(blockNames(:), ...
                    storedBlockNames(:));
                blockNormsMatch=numel(blockScaledNorms)== ...
                    numel(storedBlockScaledNorms)&&max(abs( ...
                    blockScaledNorms-storedBlockScaledNorms))<=1e-12;
            end
            value=struct('CaseId',id,'Problem',problem, ...
                'Decision',decision,'Residual',residual, ...
                'ScaledResidualNorm',norm(scaled), ...
                'MaximumScaledResidual',max(abs(scaled)), ...
                'PhysicalValidity',residual.Feasibility.PhysicalValidity, ...
                'CrossingsAccepted',residual.Feasibility.CrossingsAccepted, ...
                'EventOrderValid',residual.Feasibility.EventOrderValid, ...
                'RootFound',strcmp(classification,'root_found'), ...
                'LeastSquaresFeasible',strcmp(classification, ...
                'least_squares_feasible'), ...
                'SolverExitFlag',solverExit, ...
                'SolverTerminationAcceptable',solverExit>0, ...
                'Classification',classification, ...
                'StoredClassification',record.classification, ...
                'StoredClassificationMatch',strcmp( ...
                classification,record.classification), ...
                'BlockNames',{blockNames}, ...
                'BlockScaledNorms',blockScaledNorms, ...
                'StoredBlockNames',{storedBlockNames}, ...
                'StoredBlockScaledNorms',storedBlockScaledNorms, ...
                'StoredBlockNamesMatch',blockNamesMatch, ...
                'StoredBlockNormsMatch',blockNormsMatch, ...
                'StoredScaledResidualNorm',record.scaledResidualNorm, ...
                'StoredMaximumScaledResidual',record.maximumScaledResidual, ...
                'StoredRootFound',logical(record.rootFound));
        end

        function value=horizonStatus(obj)
            value=obj.Data.horizonContinuation;
        end
    end
end

function value=sourceRecord(path,digest)
root=lmz.util.PathGuard.canonical(lmz.util.ProjectPaths.root(),true);
absolute=lmz.util.PathGuard.canonical(path,true);
lmz.util.PathGuard.assertWithin(root,absolute);
prefix=[root filesep];
if ~strncmp(absolute,prefix,numel(prefix))
    error('lmz:QuadLoad:FeasibilitySourcePath', ...
        'Feasibility sources must be repository-contained files.');
end
relative=strrep(absolute(numel(prefix)+1:end),filesep,'/');
value=struct('relativePath',relative,'sha256',lower(digest));
end

function validateData(value)
required={'schemaVersion','modelId','randomSeed','sourceTemplateId', ...
    'sourceTemplateSha256','sourceCommit','claimPolicy','cases', ...
    'horizonContinuation'};
if ~isstruct(value)||~isscalar(value)||~all(isfield(value,required))|| ...
        ~strcmp(value.schemaVersion,'1.0.0')|| ...
        ~strcmp(value.modelId,'slip_quad_load')
    error('lmz:QuadLoad:FeasibilityEvidence', ...
        'Quad-load feasibility evidence header is invalid.');
end
records=value.cases;if isstruct(records),records=num2cell(records);end
fields={'id','formulation','numberOfStrides','energyModes', ...
    'freeControlMask','unknownCount','residualCount','scaledResidualNorm', ...
    'maximumScaledResidual','physicalValidity','rootFound','classification', ...
    'decision','attempts','solver','jacobianRankEstimate','nullity', ...
    'conditionEstimate','firstOrderOptimality','activeLowerBounds', ...
    'activeUpperBounds','rankDiagnosticMethod','singularValues', ...
    'blockNames','blockScaledNorms'};
ids=cellfun(@(item)item.id,records,'UniformOutput',false);
if isempty(records)||numel(unique(ids))~=numel(ids)
    error('lmz:QuadLoad:FeasibilityEvidence', ...
        'Feasibility evidence case IDs are invalid.');
end
for index=1:numel(records)
    item=records{index};
    if ~all(isfield(item,fields))|| ...
            numel(item.decision)~=item.unknownCount|| ...
            (~item.rootFound&&isfield(item,'simulationPublished')&& ...
            item.simulationPublished)|| ...
            any(~isfinite([item.decision(:);item.scaledResidualNorm; ...
            item.maximumScaledResidual]))
        error('lmz:QuadLoad:FeasibilityEvidence', ...
            'Feasibility evidence case %d is invalid.',index);
    end
    if ~isstruct(item.solver)||~isscalar(item.solver)|| ...
            ~isfield(item.solver,'exitFlag')|| ...
            ~isnumeric(item.solver.exitFlag)|| ...
            ~isscalar(item.solver.exitFlag)||~isfinite(item.solver.exitFlag)
        error('lmz:QuadLoad:FeasibilityEvidence', ...
            'Feasibility evidence case %d has invalid solver metadata.',index);
    end
    expected=classify(logical(item.rootFound), ...
        logical(item.physicalValidity),item.solver.exitFlag, ...
        item.residualCount,item.unknownCount);
    if ~strcmp(item.classification,expected)
        error('lmz:QuadLoad:FeasibilityClassification', ...
            'Feasibility evidence case %d has inconsistent classification.', ...
            index);
    end
    validateAttempts(item,index);
    validateRankDiagnostics(item,index);
    validateControlChange(item,index);
    hasNames=isfield(item,'blockNames');
    hasNorms=isfield(item,'blockScaledNorms');
    if hasNames~=hasNorms|| ...
            (hasNames&&numel(textList(item.blockNames))~= ...
            numel(item.blockScaledNorms))
        error('lmz:QuadLoad:FeasibilityBlocks', ...
            'Feasibility evidence case %d has invalid block metadata.',index);
    end
end
status=value.horizonContinuation;
if status.fiveStrideRootFound|| ...
        status.physicalFiveStrideSimulationPublished|| ...
        status.syntheticCarryForwardUsed||status.globalInfeasibilityClaimed
    error('lmz:QuadLoad:FeasibilityEvidenceClaims', ...
        'Stored unresolved horizon claims are internally inconsistent.');
end
end

function validateAttempts(record,caseIndex)
attempts=record.attempts;
if isstruct(attempts),attempts=num2cell(attempts);end
required={'index','seedDerivation','initializerLineage','randomSeed', ...
    'solver','exitFlag','terminationReason','scaledResidualNorm'};
if isempty(attempts)
    error('lmz:QuadLoad:FeasibilityAttempts', ...
        'Feasibility evidence case %d has no attempt records.',caseIndex);
end
for index=1:numel(attempts)
    item=attempts{index};
    if ~isstruct(item)||~isscalar(item)||~all(isfield(item,required))
        error('lmz:QuadLoad:FeasibilityAttempts', ...
            'Attempt %d in feasibility case %d is incomplete.', ...
            index,caseIndex);
    end
    validSeed=(isnumeric(item.randomSeed)&&isscalar(item.randomSeed)&& ...
        isfinite(item.randomSeed))||isUnknown(item.randomSeed);
    validExit=(isnumeric(item.exitFlag)&&isscalar(item.exitFlag)&& ...
        isfinite(item.exitFlag))||isUnknown(item.exitFlag);
    if item.index~=index||~ischar(item.seedDerivation)|| ...
            ~ischar(item.initializerLineage)||~validSeed||~validExit|| ...
            ~ischar(item.terminationReason)|| ...
            ~isnumeric(item.scaledResidualNorm)|| ...
            ~isscalar(item.scaledResidualNorm)|| ...
            ~isfinite(item.scaledResidualNorm)|| ...
            ~isstruct(item.solver)||~isscalar(item.solver)|| ...
            ~all(isfield(item.solver,{'name','algorithm'}))
        error('lmz:QuadLoad:FeasibilityAttempts', ...
            'Attempt %d in feasibility case %d is invalid.', ...
            index,caseIndex);
    end
    if isfield(record,'formalAttemptsComplete')&& ...
            logical(record.formalAttemptsComplete)&& ...
            (isUnknown(item.seedDerivation)|| ...
            isUnknown(item.initializerLineage)||isUnknown(item.randomSeed)|| ...
            isUnknown(item.exitFlag)||isUnknown(item.terminationReason)|| ...
            isUnknown(item.solver.name)||isUnknown(item.solver.algorithm))
        error('lmz:QuadLoad:FeasibilityAttemptProvenance', ...
            ['Formal attempt %d in feasibility case %d contains ' ...
            'unretained provenance.'],index,caseIndex);
    end
    if isfield(item,'finalDecision')&& ...
            (numel(item.finalDecision)~=record.unknownCount|| ...
            any(~isfinite(item.finalDecision(:))))
        error('lmz:QuadLoad:FeasibilityAttempts', ...
            'Attempt %d in feasibility case %d has an invalid final decision.', ...
            index,caseIndex);
    end
end
if isfield(record,'multistartScaledResidualNorms')
    stored=record.multistartScaledResidualNorms(:);
    replayed=cellfun(@(item)item.scaledResidualNorm,attempts(:));
    if ~isequal(stored,replayed)
        error('lmz:QuadLoad:FeasibilityAttempts', ...
            ['Attempt norms in feasibility case %d do not match the ' ...
            'recorded multistart norms.'],caseIndex);
    end
end
if isfield(record,'historicalExploratoryAttempts')
    validateHistoricalAttempts(record,caseIndex);
end
if isfield(record,'candidateFamilySummaries')
    validateCandidateSummaries(record,caseIndex);
end
if isfield(record,'deterministicSearchSeed')&& ...
        (numel(record.deterministicSearchSeed)~=record.unknownCount|| ...
        any(~isfinite(record.deterministicSearchSeed(:))))
    error('lmz:QuadLoad:FeasibilityAttempts', ...
        'Feasibility case %d has an invalid deterministic search seed.', ...
        caseIndex);
end
end

function value=isUnknown(source)
value=ischar(source)&&strcmp(source,'unknown_not_retained');
end

function validateHistoricalAttempts(record,caseIndex)
items=record.historicalExploratoryAttempts;
if isstruct(items),items=num2cell(items);end
if isempty(items)||~isfield(record,'historicalMultistartScaledResidualNorms')
    error('lmz:QuadLoad:FeasibilityHistoricalAttempts', ...
        'Feasibility case %d has incomplete historical attempts.',caseIndex);
end
for index=1:numel(items)
    item=items{index};
    if ~isstruct(item)||~isscalar(item)||~isfield(item,'gating')|| ...
            logical(item.gating)||~isfield(item,'provenanceStatus')|| ...
            ~strcmp(item.provenanceStatus,'incomplete')|| ...
            ~isfield(item,'scaledResidualNorm')|| ...
            ~isnumeric(item.scaledResidualNorm)|| ...
            ~isscalar(item.scaledResidualNorm)|| ...
            ~isfinite(item.scaledResidualNorm)
        error('lmz:QuadLoad:FeasibilityHistoricalAttempts', ...
            'Historical attempt %d in case %d is invalid.',index,caseIndex);
    end
end
norms=cellfun(@(item)item.scaledResidualNorm,items(:));
if ~isequal(norms,record.historicalMultistartScaledResidualNorms(:))
    error('lmz:QuadLoad:FeasibilityHistoricalAttempts', ...
        'Historical attempt norms in case %d are inconsistent.',caseIndex);
end
end

function validateCandidateSummaries(record,caseIndex)
items=record.candidateFamilySummaries;
if isstruct(items),items=num2cell(items);end
if isempty(items)||~isfield(record,'candidateFamilyScaledResidualNorms')|| ...
        ~isfield(record,'candidateFamilySummariesGating')|| ...
        logical(record.candidateFamilySummariesGating)
    error('lmz:QuadLoad:FeasibilityCandidateSummaries', ...
        'Feasibility case %d has incomplete candidate summaries.',caseIndex);
end
for index=1:numel(items)
    item=items{index};
    if ~isstruct(item)||~isscalar(item)|| ...
            ~isfield(item,'scaledResidualNorm')|| ...
            ~isnumeric(item.scaledResidualNorm)|| ...
            ~isscalar(item.scaledResidualNorm)|| ...
            ~isfinite(item.scaledResidualNorm)
        error('lmz:QuadLoad:FeasibilityCandidateSummaries', ...
            'Candidate summary %d in case %d is invalid.',index,caseIndex);
    end
end
norms=cellfun(@(item)item.scaledResidualNorm,items(:));
if ~isequal(norms,record.candidateFamilyScaledResidualNorms(:))
    error('lmz:QuadLoad:FeasibilityCandidateSummaries', ...
        'Candidate summary norms in case %d are inconsistent.',caseIndex);
end
end

function validateRankDiagnostics(item,caseIndex)
singular=item.singularValues(:);limit=min(item.residualCount,item.unknownCount);
conditionValid=(isnumeric(item.conditionEstimate)&& ...
    isscalar(item.conditionEstimate)&&~isnan(item.conditionEstimate)&& ...
    item.conditionEstimate>=0)|| ...
    (ischar(item.conditionEstimate)&&strcmp(item.conditionEstimate,'Inf'));
if ~isnumeric(item.jacobianRankEstimate)|| ...
        ~isscalar(item.jacobianRankEstimate)|| ...
        item.jacobianRankEstimate~=fix(item.jacobianRankEstimate)|| ...
        item.jacobianRankEstimate<0||item.jacobianRankEstimate>limit|| ...
        item.nullity~=item.unknownCount-item.jacobianRankEstimate|| ...
        ~conditionValid||~isnumeric(item.firstOrderOptimality)|| ...
        ~isscalar(item.firstOrderOptimality)|| ...
        ~isfinite(item.firstOrderOptimality)||item.firstOrderOptimality<0|| ...
        numel(singular)~=limit||any(~isfinite(singular))||any(singular<0)|| ...
        ~ischar(item.rankDiagnosticMethod)|| ...
        ~(iscell(item.activeLowerBounds)||isempty(item.activeLowerBounds))|| ...
        ~(iscell(item.activeUpperBounds)||isempty(item.activeUpperBounds))
    error('lmz:QuadLoad:FeasibilityRankDiagnostics', ...
        'Feasibility case %d has invalid rank diagnostics.',caseIndex);
end
end

function validateControlChange(item,caseIndex)
hasChanged=isfield(item,'changedControls');
hasReport=isfield(item,'controlChangeReport');
if ~hasChanged&&~hasReport,return,end
if ~hasChanged||~hasReport
    error('lmz:QuadLoad:FeasibilityControlChange', ...
        'Feasibility case %d has incomplete control-change evidence.', ...
        caseIndex);
end
report=item.controlChangeReport;
required={'decisionNames','baselineControls','finalControls', ...
    'deltaFromBaseline','lowerBounds','upperBounds','boundPolicy'};
if ~isstruct(report)||~isscalar(report)||~all(isfield(report,required))
    error('lmz:QuadLoad:FeasibilityControlChange', ...
        'Feasibility case %d has invalid control-change evidence.',caseIndex);
end
names=textList(report.decisionNames);count=numel(names);
baseline=report.baselineControls(:);final=report.finalControls(:);
delta=report.deltaFromBaseline(:);changed=item.changedControls(:);
[lower,lowerOk]=controlBounds(report.lowerBounds,count,'-Inf');
[upper,upperOk]=controlBounds(report.upperBounds,count,'Inf');
if count==0||numel(baseline)~=count||numel(final)~=count|| ...
        numel(delta)~=count||numel(changed)~=count|| ...
        any(~isfinite([baseline;final;delta;changed]))|| ...
        max(abs(final-changed))>1e-12|| ...
        max(abs((final-baseline)-delta))>1e-12|| ...
        ~lowerOk||~upperOk||any(final<lower)||any(final>upper)|| ...
        ~ischar(report.boundPolicy)||isempty(report.boundPolicy)
    error('lmz:QuadLoad:FeasibilityControlChange', ...
        'Feasibility case %d has inconsistent control-change evidence.', ...
        caseIndex);
end
if isfield(report,'deterministicSeedControls')&& ...
        (numel(report.deterministicSeedControls)~=count|| ...
        any(~isfinite(report.deterministicSeedControls(:))))
    error('lmz:QuadLoad:FeasibilityControlChange', ...
        'Feasibility case %d has invalid deterministic seed controls.', ...
        caseIndex);
end
end

function [value,valid]=controlBounds(source,count,infinityToken)
if isnumeric(source)
    value=source(:);valid=numel(value)==count&&all(~isnan(value));return
end
try
    items=textList(source);
catch
    value=[];valid=false;return
end
valid=numel(items)==count&&all(strcmp(items,infinityToken));
if strcmp(infinityToken,'-Inf')
    value=-Inf(count,1);
else
    value=Inf(count,1);
end
end

function value=classify(residualAndPhysicalValid,physicalValidity, ...
        solverExit,residualCount,unknownCount)
if ~physicalValidity
    value='physical_validation_failure';
elseif ~isnumeric(solverExit)||~isscalar(solverExit)|| ...
        ~isfinite(solverExit)||solverExit<=0
    value='numerical_failure';
elseif residualAndPhysicalValid&&residualCount==unknownCount
    value='root_found';
elseif residualAndPhysicalValid
    value='least_squares_feasible';
else
    value='best_known_residual';
end
end

function value=textList(source)
if ischar(source)
    value={source};
elseif isstring(source)
    value=cellstr(source);
elseif iscell(source)
    value=source(:).';
else
    error('lmz:QuadLoad:FeasibilityEvidence', ...
        'Stored energy modes are invalid.');
end
end

function value=logicalMatrix(source)
if iscell(source)
    rows=cellfun(@(x)logical(x(:).'),source,'UniformOutput',false);
    value=vertcat(rows{:});
else
    value=logical(source);
end
end
