classdef SectionReturnTimingProblem < lmz.api.NonlinearEquationProblem
    %SECTIONRETURNTIMINGPROBLEM Event/return timing with fixed state/physics.
    properties (SetAccess=private)
        Provider
        InputSchedule
        ScheduleChart
        FixedInitialState
        FixedPhysicalParameters
        FixedRowPolicy
        FixedRowTolerance
    end

    methods
        function obj=SectionReturnTimingProblem(model,id,provider, ...
                initialState,physicalParameters,schedule,configuration)
            if nargin<7, configuration=struct(); end
            if ~isa(provider,'lmz.schedule.ContactConstraintProvider')
                error('lmz:Timing:ProviderType', ...
                    'Timing problems require a ContactConstraintProvider.');
            end
            if ~isnumeric(initialState)||~isreal(initialState)|| ...
                    any(~isfinite(initialState(:)))
                error('lmz:Timing:InitialState', ...
                    'Fixed initial state must be finite real numeric data.');
            end
            if ~isnumeric(physicalParameters)||~isreal(physicalParameters)|| ...
                    any(~isfinite(physicalParameters(:)))
                error('lmz:Timing:PhysicalParameters', ...
                    'Fixed physical parameters must be finite real numeric data.');
            end
            chart=lmz.schedule.EventScheduleChart(schedule);
            emptyParameters=lmz.schema.VariableSchema( ...
                lmz.schema.VariableSpec.empty(0,1),'1.0.0');
            obj@lmz.api.NonlinearEquationProblem(model,id, ...
                'nonlinear_equation',chart.DecisionSchema,emptyParameters,[],configuration);
            obj.Version='1.0.0';
            obj.Provider=provider;
            obj.InputSchedule=schedule;
            obj.ScheduleChart=chart;
            obj.FixedInitialState=initialState(:);
            obj.FixedPhysicalParameters=physicalParameters(:);
            obj.FixedRowPolicy=lmz.schedule.TimingResidualPolicy.normalize( ...
                fieldOr(configuration,'FixedRowPolicy', ...
                'validate_fixed_rows'));
            obj.FixedRowTolerance=fieldOr(configuration, ...
                'FixedRowTolerance',1e-8);
            lmz.schedule.TimingResidualPolicy.fixedRows(schedule, ...
                zeros(schedule.count(),1),zeros(0,1), ...
                obj.FixedRowTolerance);
            obj.evaluate(chart.DecisionSchema.defaults(),[], ...
                lmz.api.RunContext.synchronous(0),false);
        end

        function evaluation=evaluate(obj,u,p,context,includeSimulation) %#ok<INUSD>
            if nargin<5, includeSimulation=false; end
            context.check();
            obj.DecisionSchema.validateVector(u);
            schedule=obj.ScheduleChart.decode(u);
            value=obj.evaluateTiming(schedule,context,includeSimulation);
            contact=value.ContactResidual(:);
            bindings=lmz.schedule.TimingResidualPolicy.bindings( ...
                schedule,numel(contact),fieldOr(value, ...
                'ContactRowBindings',[]));
            [activeContact,activeSection,fixedContact]= ...
                lmz.schedule.TimingResidualPolicy.activeRows( ...
                schedule,obj.FixedRowPolicy,bindings);
            blocks=lmz.data.ResidualBlock.empty(0,1);
            if any(activeContact)
                blocks(end+1,1)=lmz.data.ResidualBlock( ...
                    'contact_constraints',contact(activeContact), ...
                    ones(sum(activeContact),1));
            end
            if activeSection&&~isempty(value.SectionResidual)
                blocks(end+1,1)=lmz.data.ResidualBlock('section_return', ...
                    value.SectionResidual(:), ...
                    ones(numel(value.SectionResidual),1));
            end
            if includeSimulation, simulation=value.Simulation; else, simulation=[]; end
            [fixedRows,fixedRowsValid,maximumFixedResidual]= ...
                lmz.schedule.TimingResidualPolicy.fixedRows(schedule, ...
                contact,value.SectionResidual(:),obj.FixedRowTolerance, ...
                bindings);
            finiteData=all(isfinite([value.ContactResidual(:); ...
                value.SectionResidual(:);value.TerminalState(:)]));
            crossingAccepted=acceptedCrossing(value.SectionCrossing);
            energyValid=providerEnergyValid(value);
            feasibility=struct('Valid',finiteData&&fixedRowsValid&& ...
                crossingAccepted&&energyValid,'EventOrderValid',true, ...
                'FixedRowsValid',fixedRowsValid, ...
                'SectionCrossingAccepted',crossingAccepted, ...
                'FiniteData',finiteData,'EnergyValid',energyValid, ...
                'MaximumFixedResidual',maximumFixedResidual, ...
                'FixedRowTolerance',obj.FixedRowTolerance, ...
                'FixedRowPolicy',obj.FixedRowPolicy);
            diagnostics=struct('Formulation','timing-only-section-return-v1', ...
                'HiddenPeriodicityResidual',false,'FixedInitialState', ...
                obj.FixedInitialState,'FixedPhysicalParameters', ...
                obj.FixedPhysicalParameters,'SolvedSchedule',schedule.toStruct(), ...
                'TerminalState',value.TerminalState, ...
                'SectionCrossing',obj.serializable(value.SectionCrossing), ...
                'ActiveContactMask',activeContact, ...
                'ActiveSectionRow',activeSection, ...
                'ContactRowBindings',bindings, ...
                'FixedEventResiduals',contact(fixedContact), ...
                'FixedReturnSectionResidual',conditionalValue( ...
                schedule.ReturnTimeFixed,value.SectionResidual(:)), ...
                'FixedRows',fixedRows,'FixedRowsValid',fixedRowsValid, ...
                'FixedRowPolicy',obj.FixedRowPolicy, ...
                'FixedRowTolerance',obj.FixedRowTolerance, ...
                'ProviderDiagnostics',value.Diagnostics);
            evaluation=lmz.data.ProblemEvaluation(blocks, ...
                'Simulation',simulation,'Feasibility',feasibility, ...
                'PhysicalValidity',feasibility.Valid,'Diagnostics',diagnostics);
        end

        function value=evaluateTiming(obj,schedule,context,includeSimulation)
            if nargin<4, includeSimulation=true; end
            value=obj.Provider.evaluate(obj.FixedInitialState, ...
                obj.FixedPhysicalParameters,schedule,context,includeSimulation);
            required={'ContactResidual','SectionResidual','TerminalState', ...
                'SectionCrossing','Simulation','Diagnostics'};
            for index=1:numel(required)
                if ~isfield(value,required{index})
                    error('lmz:Timing:ProviderContract', ...
                        'Contact provider omitted %s.',required{index});
                end
            end
        end

        function schedule=scheduleFromDecision(obj,u)
            schedule=obj.ScheduleChart.decode(u);
        end

        function u=decisionFromSchedule(obj,schedule)
            u=obj.ScheduleChart.encode(schedule);
        end

        function value=expectedLocalDimension(~),value=0;end
    end

    methods (Static, Access=private)
        function value=serializable(item)
            if isobject(item)&&ismethod(item,'toStruct')
                value=item.toStruct();
            else
                value=item;
            end
        end
    end
end

function value=conditionalValue(condition,source)
if condition,value=source;else,value=zeros(0,1);end
end

function value=acceptedCrossing(crossing)
value=false;
if isobject(crossing)&&isprop(crossing,'Accepted')
    value=logical(crossing.Accepted);
    if isprop(crossing,'Grazing'),value=value&&~crossing.Grazing;end
elseif isstruct(crossing)&&isscalar(crossing)
    if isfield(crossing,'Accepted'),value=logical(crossing.Accepted);end
    if isfield(crossing,'Grazing'),value=value&&~logical(crossing.Grazing);end
end
end

function value=providerEnergyValid(source)
value=true;
if isfield(source,'EnergyValid'),value=logical(source.EnergyValid);return,end
if isfield(source,'Diagnostics')&&isstruct(source.Diagnostics)&& ...
        isfield(source.Diagnostics,'EnergyValid')
    value=logical(source.Diagnostics.EnergyValid);
end
value=isscalar(value)&&value;
end

function value=fieldOr(source,name,fallback)
if isstruct(source)&&isfield(source,name),value=source.(name); ...
else,value=fallback;end
end
