classdef JerboaBipedModel < lmz.core.LeggedModel
    methods
        function m=metadata(~),m=struct('id','jerboa_biped','display_name','Jerboa Biped','version','1.0.0');end
        function c=capabilities(~),c={'simulation','periodic_orbit','trajectory_fit','root_solve','continuation','animation'};end
        function s=stateSchema(~),keys={'dx','y','dy','alpha_left','dalpha_left','alpha_right','dalpha_right'};u={'m/s','m','m/s','rad','rad/s','rad','rad/s'};d=[1;1;0;0;0;0;0];e=struct([]);for i=1:7,e(i)=lmz.core.NamedVectorSchema.entry(keys{i},strrep(keys{i},'_',' '),'initial',u{i},d(i),-Inf,Inf,1);end;s=lmz.core.NamedVectorSchema(e);end
        function s=parameterSchema(~),e(1)=lmz.core.NamedVectorSchema.entry('leg_stiffness','Leg stiffness','parameter','N/m',20,eps,Inf,20);e(2)=lmz.core.NamedVectorSchema.entry('swing_frequency','Swing frequency','parameter','rad/s',6.5,eps,Inf,6.5);e(3)=lmz.core.NamedVectorSchema.entry('left_offset','Left neutral offset','parameter','rad',0,-pi,pi,.1);e(4)=lmz.core.NamedVectorSchema.entry('right_offset','Right neutral offset','parameter','rad',0,-pi,pi,.1);s=lmz.core.NamedVectorSchema(e);end
        function s=eventSchema(obj),keys={'t_left_td','t_left_lo','t_right_td','t_right_lo','period'};d=[.05;.25;.3;.45;.5];e=struct([]);for i=1:5,e(i)=lmz.core.NamedVectorSchema.entry(keys{i},keys{i},'event','s',d(i),0,10,.1);end;s=lmz.core.NamedVectorSchema(e);end
        function result=simulate(obj,request),if isfield(request,'decision'),z=request.decision(:);x=z(1:7);ev=z(8:12);else,x=request.initial_state(:);ev=request.events(:);end;P=obj.parameterSchema().defaults();T=linspace(0,ev(5),101).';w=2*pi/ev(5);Y=zeros(numel(T),8);Y(:,1)=x(1)*T;Y(:,2)=x(1);Y(:,3)=x(2)+.02*(cos(w*T)-1);Y(:,4)=-.02*w*sin(w*T);for j=1:2,k=3+2*j;Y(:,k)=x(k)*cos(w*T)+x(k+1)/w*sin(w*T);Y(:,k+1)=-x(k)*w*sin(w*T)+x(k+1)*cos(w*T);end;r=Y(end,2:8).'-Y(1,2:8).';result=struct('time',T,'state',Y,'state_schema',[],'mode_history',[],'event_log',struct([]),'channels',struct(),'parameters',P,'observables',struct('speed',x(1)),'diagnostics',struct('finite',all(isfinite(Y(:))),'event_order_valid',all(ev>=0&ev<=ev(5)),'physical_valid',min(Y(:,3))>0),'provenance',lmz.io.Provenance.capture(),'periodic_residual',r);end
        function f=kinematics(~,state,parameters,context),n=size(state,1);f=repmat(struct('body',[],'foot_left',[],'foot_right',[]),n,1);for i=1:n,x=state(i,1);y=state(i,3);f(i).body=[x y 0];f(i).foot_left=[x-sin(state(i,5)),y-cos(state(i,5))];f(i).foot_right=[x-sin(state(i,7)),y-cos(state(i,7))];end,end
        function p=createProblem(obj,id,options),if nargin<3,options=struct();end;if ~any(strcmp(id,{'periodic_orbit','trajectory_fit'})),error('lmz:UnsupportedProblem','Unsupported problem.');end;p=lmz.problems.PeriodicOrbitProblem(obj,obj.decisionSchema(),options);end
        function s=decisionSchema(obj),g=[lmz.core.CompositeDecisionSchema.group('initial',obj.stateSchema()),lmz.core.CompositeDecisionSchema.group('events',obj.eventSchema())];s=lmz.core.CompositeDecisionSchema(g);end
    end
end
