classdef ContactConstraintProvider < lmz.schedule.ContactConstraintProvider
    %CONTACTCONSTRAINTPROVIDER Exact quadruped contact/apex timing rows.
    methods
        function value=eventNames(~)
            value={'BL_TD','BL_LO','FL_TD','FL_LO', ...
                'BR_TD','BR_LO','FR_TD','FR_LO'};
        end

        function value=evaluate(obj,initialState,physicalParameters, ...
                schedule,context,includeSimulation)
            if nargin<6,includeSimulation=true;end
            state=initialState(:);
            if numel(state)==14,state=state(2:14);end
            if numel(state)~=13
                error('lmz:Timing:QuadrupedInitialState', ...
                    'Quadruped timing requires 13 local or 14 physical states.');
            end
            parameters=physicalParameters(:);
            lmzmodels.slip_quadruped.ParameterSchema.create().validateVector(parameters);
            eventTimes=schedule.namedTimes(obj.eventNames());
            decision=[state;eventTimes;schedule.ReturnTime];
            raw=lmzmodels.slip_quadruped.LegacyQuadrupedEvaluator().evaluate( ...
                decision,parameters,context);
            simulation=[];
            if includeSimulation
                observables=lmzmodels.slip_quadruped.ObservableProvider.compute( ...
                    raw.Time,raw.States,decision,raw.GroundReactionForces);
                interim=lmz.api.SimulationResult(raw.Time, ...
                    lmzmodels.slip_quadruped.PhysicalStateSchema.create(), ...
                    raw.States,raw.Modes,observables, ...
                    lmzmodels.slip_quadruped.ParameterSchema.create().unpack(parameters), ...
                    struct('Evaluator','timing-only-quadruped-v1', ...
                    'HiddenEventTimeSolve',false, ...
                    'DuplicateSamplesRemoved',raw.DuplicateSamplesRemoved), ...
                    struct('source','scientific-roadmap-timing'), ...
                    'EventRecords',raw.EventRecords, ...
                    'GroundReactionForces',raw.GroundReactionForces);
                simulation=lmz.api.SimulationResult(interim.Time,interim.StateSchema, ...
                    interim.States,interim.Modes,interim.Observables,interim.Parameters, ...
                    interim.Diagnostics,interim.Provenance, ...
                    'EventRecords',interim.EventRecords, ...
                    'GroundReactionForces',interim.GroundReactionForces, ...
                    'Kinematics',lmzmodels.slip_quadruped.KinematicsProvider.compute(interim));
            end
            crossing=lmz.schedule.ContactConstraintProvider.sectionCrossing( ...
                raw,'APEX',4,'post');
            value=struct('ContactResidual',raw.Residual(1:8), ...
                'SectionResidual',raw.Residual(9), ...
                'TerminalState',raw.States(end,:).', ...
                'SectionCrossing',crossing,'Simulation',simulation, ...
                'Diagnostics',struct('ModelId','slip_quadruped', ...
                'ResidualRows',1:9,'PeriodicityRowsIncluded',false, ...
                'ScheduleNames',{[obj.eventNames(),{'APEX'}]}));
        end
    end

    methods (Static)
        function problem=createProblem(model,configuration)
            if nargin<2,configuration=struct();end
            decision=lmzmodels.slip_quadruped.PeriodicDecisionSchema.create().defaults();
            parameters=lmzmodels.slip_quadruped.ParameterSchema.create().defaults();
            initial=decision(1:13);
            if isfield(configuration,'InitialState'),initial=configuration.InitialState(:);end
            if isfield(configuration,'PhysicalParameters'),parameters=configuration.PhysicalParameters(:);end
            provider=lmzmodels.slip_quadruped.ContactConstraintProvider();
            schedule=lmz.schedule.ContactConstraintProvider.scheduleFromConfiguration( ...
                provider.eventNames(),decision(14:21),decision(22),configuration);
            lmz.schedule.ContactConstraintProvider. ...
                assertSupportedApexSchedule(schedule,'slip_quadruped');
            problem=lmz.schedule.SectionReturnTimingProblem(model, ...
                'section_return_timing',provider,initial,parameters,schedule,configuration);
        end
    end
end
