classdef ObservableProvider
    %OBSERVABLEPROVIDER Named scientific quantities derived from one stride.
    methods (Static)
        function value = compute(time, states, decision, grf)
            period = decision(22);
            events = mod(decision(14:21),period);
            durations = mod(decision([15 17 19 21])-decision([14 16 18 20]),period);
            sortedEvents = sort(events);
            gaps = diff([sortedEvents;sortedEvents(1)+period]);
            strideLength = states(end,1)-states(1,1);
            value = struct('forward_speed',strideLength/period, ...
                'stride_period',period,'stride_length',strideLength, ...
                'duty_factors',durations(:).'/period, ...
                'event_phases',events(:).'/period, ...
                'minimum_event_gap',min(gaps), ...
                'vertical_grf',grf(:,9:12), ...
                'horizontal_grf',grf(:,5:8), ...
                'grf_magnitude',grf(:,1:4), ...
                'total_vertical_grf',sum(grf(:,9:12),2), ...
                'total_horizontal_grf',sum(grf(:,5:8),2), ...
                'sample_time',time(:));
            gait = lmzmodels.slip_quadruped.GaitClassifier.classify(decision);
            value.gait_name = gait.Name;
            value.gait_abbreviation = gait.Abbreviation;
        end
    end
end
