classdef PeriodicApexProblem < lmz.api.NonlinearEquationProblem
    %PERIODICAPEXPROBLEM Scientific 22-by-22 RoadMap residual problem.
    properties (SetAccess=private)
        Evaluator
        EventProjector
        Feasibility
        Continuation
    end
    methods
        function obj = PeriodicApexProblem(model,configuration)
            decision = lmzmodels.slip_quadruped.PeriodicDecisionSchema.create();
            parameters = lmzmodels.slip_quadruped.ParameterSchema.create();
            obj@lmz.api.NonlinearEquationProblem(model,'periodic_apex', ...
                'nonlinear_equation',decision,parameters,parameters.defaults(),configuration);
            obj.Version = '2.0.0';
            obj.Evaluator = lmzmodels.slip_quadruped.LegacyQuadrupedEvaluator();
            obj.EventProjector = lmzmodels.slip_quadruped.EventScheduleProjector();
            obj.Feasibility = lmzmodels.slip_quadruped.FeasibilityPolicy();
            obj.Continuation = lmzmodels.slip_quadruped.ContinuationPolicy();
        end

        function evaluation = evaluate(obj,u,p,context,includeSimulation)
            context.check();
            obj.DecisionSchema.validateVector(u);
            obj.ParameterSchema.validateVector(p);
            raw = obj.Evaluator.evaluate(u,p,context);
            blocks = [ ...
                lmz.data.ResidualBlock('contact_geometry',raw.Residual(1:8),ones(8,1)); ...
                lmz.data.ResidualBlock('apex_section',raw.Residual(9),1); ...
                lmz.data.ResidualBlock('periodicity',raw.Residual(10:22),ones(13,1))];
            feasibility = obj.Feasibility.assess(u,p,raw.Residual);
            physicalValidity = feasibility.Valid && all(raw.States(:,3) > 0);
            simulation = [];
            observables = lmzmodels.slip_quadruped.ObservableProvider.compute( ...
                raw.Time,raw.States,u,raw.GroundReactionForces);
            if includeSimulation
                parameterStruct = obj.ParameterSchema.unpack(p);
                simulation = lmz.api.SimulationResult(raw.Time, ...
                    lmzmodels.slip_quadruped.PhysicalStateSchema.create(), ...
                    raw.States,raw.Modes,observables,parameterStruct, ...
                    struct('Evaluator','migrated-Quadrupedal_ZeroFun_v2', ...
                    'DuplicateSamplesRemoved',raw.DuplicateSamplesRemoved, ...
                    'HiddenEventTimeSolve',false), ...
                    struct('sourceRepository','DLARlab/SLIP_Model_Zoo', ...
                    'sourceCommit','2c106101383ecee1b2a9d695efe09fbd72d5718a'), ...
                    'EventRecords',raw.EventRecords, ...
                    'GroundReactionForces',raw.GroundReactionForces);
                simulation = obj.attachKinematics(simulation);
            end
            diagnostics = struct('Formulation','scientific-roadmap-v2', ...
                'LegacyEquivalent',true,'HiddenEventTimeSolve',false, ...
                'DuplicateSamplesRemoved',raw.DuplicateSamplesRemoved, ...
                'GaitName',observables.gait_name, ...
                'GaitAbbreviation',observables.gait_abbreviation);
            evaluation = lmz.data.ProblemEvaluation(blocks, ...
                'Simulation',simulation,'Feasibility',feasibility, ...
                'PhysicalValidity',physicalValidity,'Diagnostics',diagnostics);
        end

        function names = listObservables(~)
            names = {'forward_speed','stride_period','stride_length', ...
                'duty_factors','event_phases','minimum_event_gap', ...
                'gait_name','gait_abbreviation','vertical_grf','horizontal_grf'};
        end

        function [value,diagnostics] = projectSeed(obj,u,p,options,context)
            if nargin<4,options=struct();end
            if nargin<5,context=lmz.api.RunContext.synchronous(0);end
            seed=obj.makeSolution(u,p,[]);[candidate,diagnostics]=obj.EventProjector.project(seed,options,context);value=candidate.DecisionValues;
            diagnostics.ChangedVariables={'tBL_TD','tBL_LO','tFL_TD','tFL_LO', ...
                'tBR_TD','tBR_LO','tFR_TD','tFR_LO'};
            diagnostics.Version='explicit-event-projector-v1';
        end

        function solution = makeSolution(obj,u,p,evaluation)
            if nargin < 3 || isempty(p), p = obj.DefaultParameters; end
            if nargin < 4 || isempty(evaluation)
                blocks = lmz.data.ResidualBlock.empty(0,1);
                diagnostics = struct(); feasibility = struct('Valid',true);
                observables = struct(); classification = struct();
            else
                blocks = evaluation.ResidualBlocks;
                diagnostics = evaluation.Diagnostics;
                feasibility = evaluation.Feasibility;
                if ~isempty(evaluation.Simulation)
                    observables = evaluation.Simulation.Observables;
                else
                    observables = struct('gait_name',diagnostics.GaitName, ...
                        'gait_abbreviation',diagnostics.GaitAbbreviation);
                end
                classification = lmzmodels.slip_quadruped.GaitClassifier.classify(u);
            end
            descriptor = obj.getDescriptor();
            value = struct('Id',lmz.util.Ids.new('solution'), ...
                'ModelId',descriptor.modelId,'ModelVersion',descriptor.modelVersion, ...
                'ProblemId',obj.Id,'ProblemVersion',obj.Version, ...
                'DecisionSchema',obj.DecisionSchema,'ParameterSchema',obj.ParameterSchema, ...
                'DecisionValues',u(:),'ParameterValues',p(:), ...
                'Observables',observables,'ResidualBlocks',blocks, ...
                'Diagnostics',diagnostics,'Classification',classification, ...
                'Feasibility',feasibility,'Lineage',struct(), ...
                'Provenance',struct('source','scientific-roadmap-runtime', ...
                'sourceCommit','2c106101383ecee1b2a9d695efe09fbd72d5718a'), ...
                'CreatedAt',datestr(now,30));
            solution = lmz.data.Solution(value);
        end
    end

    methods (Access=private)
        function result = attachKinematics(~,result)
            kinematics = lmzmodels.slip_quadruped.KinematicsProvider.compute(result);
            result = lmz.api.SimulationResult(result.Time,result.StateSchema, ...
                result.States,result.Modes,result.Observables,result.Parameters, ...
                result.Diagnostics,result.Provenance, ...
                'EventRecords',result.EventRecords, ...
                'GroundReactionForces',result.GroundReactionForces, ...
                'Kinematics',kinematics);
        end
    end
end
