classdef QuadrupedSectionTransitionDecisionCodec < ...
        lmz.shooting.SectionTransitionDecisionCodec
    %QUADRUPEDSECTIONTRANSITIONDECISIONCODEC Mixed RoadMap section chart.
    methods
        function obj=QuadrupedSectionTransitionDecisionCodec( ...
                startSection,stopSection,eventTimes,returnTime,seedState, ...
                sourceDecision,varargin)
            if nargin<6,sourceDecision=[];end
            names={'BL_TD','BL_LO','FL_TD','FL_LO', ...
                'BR_TD','BR_LO','FR_TD','FR_LO'};
            obj@lmz.shooting.SectionTransitionDecisionCodec( ...
                'slip_quadruped', ...
                lmzmodels.slip_quadruped.PhysicalStateSchema.create(), ...
                startSection,stopSection,names,eventTimes,returnTime, ...
                seedState,'SourceDecision',sourceDecision,varargin{:});
        end
    end
end
