classdef QuadrupedSectionDecisionCodec < ...
        lmz.shooting.CyclicSectionDecisionCodec
    %QUADRUPEDSECTIONDECISIONCODEC Target-section RoadMap state/schedule chart.
    methods
        function obj=QuadrupedSectionDecisionCodec(startSection,stopSection, ...
                localEventTimes,returnTime,seedState,sourceDecision)
            if nargin<6,sourceDecision=[];end
            names={'BL_TD','BL_LO','FL_TD','FL_LO', ...
                'BR_TD','BR_LO','FR_TD','FR_LO'};
            obj@lmz.shooting.CyclicSectionDecisionCodec( ...
                'slip_quadruped', ...
                lmzmodels.slip_quadruped.PhysicalStateSchema.create(), ...
                startSection,stopSection,names,localEventTimes, ...
                returnTime,seedState,'SourceDecision',sourceDecision);
        end
    end
end
