classdef QuadrupedScenePlugin < lmz.viz.PlotPlugin
    %QUADRUPEDSCENEPLUGIN Generic scene adapter for the tutorial path.
    properties (SetAccess = private)
        ScenePath
    end
    methods
        function obj = QuadrupedScenePlugin(scenePath)
            obj.ScenePath = scenePath;
        end
        function value = sceneSpec(obj)
            value = lmz.viz.SceneSpec.fromJson( ...
                obj.ScenePath, fileparts(obj.ScenePath));
        end
        function value = kinematicsFrame(~, simulation, index)
            names = simulation.StateSchema.names();
            if any(strcmp(names, 'foot_bl_x'))
                center = [simulation.state('x') simulation.state('y')];
                pitch = simulation.state('body_pitch');
                feetX = [simulation.state('foot_bl_x') ...
                    simulation.state('foot_fl_x') ...
                    simulation.state('foot_br_x') ...
                    simulation.state('foot_fr_x')];
                feetY = [simulation.state('foot_bl_y') ...
                    simulation.state('foot_fl_y') ...
                    simulation.state('foot_br_y') ...
                    simulation.state('foot_fr_y')];
            else
                allFrames = lmzmodels.slip_quadruped.KinematicsProvider.compute( ...
                    simulation);
                center = allFrames.CenterOfMass;
                pitch = simulation.state('phi');
                feetX = allFrames.FootX;
                feetY = allFrames.FootY;
            end
            frames = struct('world', [0 0 0], ...
                'body', [center(index, :) pitch(index)], ...
                'foot_bl', [feetX(index, 1) feetY(index, 1) 0], ...
                'foot_fl', [feetX(index, 2) feetY(index, 2) 0], ...
                'foot_br', [feetX(index, 3) feetY(index, 3) 0], ...
                'foot_fr', [feetX(index, 4) feetY(index, 4) 0]);
            value = lmz.viz.KinematicsFrame( ...
                simulation.Time(index), index, frames);
        end
        function value = plotDescriptors(~)
            value = struct('id', {'trajectory','vertical_grf', ...
                'horizontal_grf','oscillator'}, ...
                'label', {'Torso and legs','Vertical GRF', ...
                'Horizontal GRF','Footfall phases'});
        end
        function handles = plot(~, axesHandle, descriptorId, simulation, ~)
            switch descriptorId
                case 'trajectory'
                    handles = lmzmodels.slip_quadruped.QuadrupedPlotProvider. ...
                        plotTorso(axesHandle, simulation);
                case {'vertical_grf','horizontal_grf'}
                    handles = lmzmodels.slip_quadruped.QuadrupedPlotProvider. ...
                        plotGRF(axesHandle, simulation);
                case 'oscillator'
                    handles = lmzmodels.slip_quadruped.QuadrupedPlotProvider. ...
                        plotOscillator(axesHandle, simulation);
                otherwise
                    error('lmz:Scene:QuadrupedPlot', ...
                        'Unknown quadruped plot descriptor %s.', descriptorId);
            end
        end
    end
end
