classdef ResearchBodyGeometry
    %RESEARCHBODYGEOMETRY Pure source-derived quadruped body geometry.
    %   The formulas are adapted from ComputeBodyGraphics.m at the pinned
    %   SLIP_Model_Zoo source commit. No graphics handles are created here.
    properties (Constant)
        SourceCommit = '2c106101383ecee1b2a9d695efe09fbd72d5718a'
        SourcePath = ['SLIP_Quadruped/2_Graphic_ToolBox/' ...
            'SLIP_Quadrupedal_Graphics/GraphicFunctions/' ...
            'ComputeBodyGraphics.m']
    end

    methods (Static)
        function value = compute(bodyFrame, backFraction)
            if ~isnumeric(bodyFrame) || ~isreal(bodyFrame) || ...
                    numel(bodyFrame) ~= 3 || any(~isfinite(bodyFrame(:)))
                error('lmz:slip_quadruped:BodyFrame', ...
                    'Body frame must be finite [x y pitch].');
            end
            bodyFrame = reshape(bodyFrame, 1, []);
            if ~isnumeric(backFraction) || ~isscalar(backFraction) || ...
                    ~isreal(backFraction) || ~isfinite(backFraction)
                error('lmz:slip_quadruped:BackFraction', ...
                    'Back attachment fraction must be finite.');
            end

            lengthValue = 1.2;
            heightValue = 0.4;
            lengthSamples = 30;
            heightSamples = 10;
            offset = 0;
            if backFraction == 0.5
                local = [ ...
                    repmat([-lengthValue/2, heightValue/2], lengthSamples, 1) + ...
                        [linspace(0, lengthValue, lengthSamples).', ...
                         zeros(lengthSamples, 1)]; ...
                    repmat([lengthValue/2, heightValue/2], heightSamples, 1) - ...
                        [zeros(heightSamples, 1), ...
                         linspace(0, heightValue, heightSamples).']; ...
                    repmat([lengthValue/2, -heightValue/2], lengthSamples, 1) - ...
                        [linspace(0, lengthValue, lengthSamples).', ...
                         zeros(lengthSamples, 1)]; ...
                    repmat([-lengthValue/2, -heightValue/2], heightSamples, 1) + ...
                        [zeros(heightSamples, 1), ...
                         linspace(0, heightValue, heightSamples).']];
            else
                heightValue = 0.45;
                offset = sign(0.5-backFraction) * ...
                    sqrt(abs((0.5-backFraction)*10))/15;
                local = [ ...
                    repmat([-lengthValue/2, heightValue/2+offset], ...
                        lengthSamples, 1) + ...
                        [linspace(0, lengthValue, lengthSamples).', ...
                         linspace(0, -2*offset, lengthSamples).']; ...
                    repmat([lengthValue/2, heightValue/2-offset], ...
                        heightSamples, 1) - ...
                        [zeros(heightSamples, 1), ...
                         linspace(0, heightValue-2*offset, heightSamples).']; ...
                    repmat([lengthValue/2, -heightValue/2+offset], ...
                        lengthSamples, 1) - ...
                        [linspace(0, lengthValue, lengthSamples).', ...
                         linspace(0, 2*offset, lengthSamples).']; ...
                    repmat([-lengthValue/2, -heightValue/2-offset], ...
                        heightSamples, 1) + ...
                        [zeros(heightSamples, 1), ...
                         linspace(0, heightValue+2*offset, heightSamples).']];
                local(:, 1) = local(:, 1) + (0.5-backFraction);
            end

            vertices = transform(local, bodyFrame(3), bodyFrame(1:2));
            shadeFaces = [ ...
                [4:3:lengthSamples, lengthSamples+2:2:lengthSamples+8]; ...
                [2*heightSamples+2*lengthSamples-2:-2: ...
                    heightSamples+2*lengthSamples+2, ...
                 heightSamples+2*lengthSamples-2:-3: ...
                    heightSamples+lengthSamples+2]].';
            outlineIndex = [1, 1+lengthSamples, ...
                1+lengthSamples+heightSamples, ...
                1+2*lengthSamples+heightSamples, 1];
            outline = vertices(outlineIndex, :);
            metadata = lmzmodels.slip_quadruped.ResearchBodyGeometry.provenance();
            metadata.constants = struct('nominalLength', 1.2, ...
                'symmetricHeight', 0.4, 'asymmetricHeight', 0.45, ...
                'lengthSamples', 30, 'heightSamples', 10, ...
                'asymmetricOffset', offset);

            background = lmz.viz.PatchGeometry('body_background', ...
                outline(1:4, :), 1:4, metadata);
            shading = lmz.viz.PatchGeometry('body_shading', ...
                vertices, shadeFaces, metadata);
            border = lmz.viz.PolylineGeometry('body_outline', ...
                outline, metadata);
            value = struct('Background', background, 'Shading', shading, ...
                'Outline', border, 'PerimeterVertices', vertices, ...
                'ShadeFaces', shadeFaces, 'OutlineIndex', outlineIndex, ...
                'Layers', lmz.viz.LayeredGeometry('research_body', ...
                    {background, shading, border}, metadata), ...
                'Metadata', metadata);
        end

        function value = fromSimulation(simulation, index)
            assertSimulation(simulation, index);
            x = simulation.state('x');
            y = simulation.state('y');
            phi = simulation.state('phi');
            frame = [x(index), y(index), phi(index)];
            value = lmzmodels.slip_quadruped.ResearchBodyGeometry.compute( ...
                frame, parameter(simulation, 'l_b'));
        end

        function value = provenance()
            value = struct('sourceRepository', 'DLARlab/SLIP_Model_Zoo', ...
                'sourceCommit', ...
                lmzmodels.slip_quadruped.ResearchBodyGeometry.SourceCommit, ...
                'sourcePath', ...
                lmzmodels.slip_quadruped.ResearchBodyGeometry.SourcePath, ...
                'sourceLines', '3-32', ...
                'adaptation', ['Pure namespaced numeric geometry; source ' ...
                    'theme-dependent outline color is made explicit by style.'], ...
                'redistributionStatus', 'unresolved_source_derived');
        end
    end
end

function points = transform(points, angle, center)
rotation = [cos(angle), -sin(angle); sin(angle), cos(angle)];
points = points * rotation.' + reshape(center, 1, 2);
end

function assertSimulation(simulation, index)
if ~isa(simulation, 'lmz.api.SimulationResult') || ...
        ~isnumeric(index) || ~isreal(index) || ~isscalar(index) || ...
        ~isfinite(index) || index ~= fix(index) || ...
        index < 1 || index > numel(simulation.Time)
    error('lmz:slip_quadruped:GeometryFrame', ...
        'A SimulationResult and valid frame index are required.');
end
end

function value = parameter(simulation, name)
if ~isstruct(simulation.Parameters) || ~isfield(simulation.Parameters, name) || ...
        ~isnumeric(simulation.Parameters.(name)) || ...
        ~isreal(simulation.Parameters.(name)) || ...
        ~isscalar(simulation.Parameters.(name)) || ...
        ~isfinite(simulation.Parameters.(name))
    error('lmz:slip_quadruped:GeometryParameter', ...
        'Simulation parameter %s is required.', name);
end
value = simulation.Parameters.(name);
end
