classdef ResearchPhaseDiagramGeometry
    %RESEARCHPHASEDIAGRAMGEOMETRY Source phase box, labels, and bars.
    properties (Constant)
        SourceCommit = '2c106101383ecee1b2a9d695efe09fbd72d5718a'
        SourcePath = ['SLIP_Quadruped/2_Graphic_ToolBox/' ...
            'SLIP_Quadrupedal_Graphics/GraphicFunctions/' ...
            'ComputePhaseDiagram.m']
    end

    methods (Static)
        function value = compute(bodyX, schedule)
            if ~isnumeric(bodyX) || ~isreal(bodyX) || ...
                    ~isscalar(bodyX) || ~isfinite(bodyX)
                error('lmz:slip_quadruped:PhaseBodyX', ...
                    'Finite body horizontal position is required.');
            end
            schedule = validateSchedule(schedule);
            boxCenterX = bodyX + 0.93;
            boxCenterY = 1.2 + 0.55;
            boxHalfLength = 0.45;
            boxHalfWidth = 0.16;
            textLength = 0.08;
            boxVertices = [ ...
                boxCenterX-boxHalfLength-textLength, boxCenterY-boxHalfWidth; ...
                boxCenterX+boxHalfLength+0.5*textLength, boxCenterY-boxHalfWidth; ...
                boxCenterX+boxHalfLength+0.5*textLength, boxCenterY+boxHalfWidth; ...
                boxCenterX-boxHalfLength-textLength, boxCenterY+boxHalfWidth];
            origin = boxCenterX-boxHalfLength+1.2*textLength;
            wholeLength = (boxHalfLength-0.05)*2;
            width = 0.037;
            yShift = 0.030;
            textPositions = [ ...
                boxCenterX-boxHalfLength-0.6*textLength, ...
                    boxCenterY+1.5*yShift+1.5*width; ...
                boxCenterX-boxHalfLength-0.6*textLength, ...
                    boxCenterY+0.5*yShift+0.5*width; ...
                boxCenterX-boxHalfLength-0.6*textLength, ...
                    boxCenterY-0.5*yShift-0.5*width; ...
                boxCenterX-boxHalfLength-0.6*textLength, ...
                    boxCenterY-1.5*yShift-1.5*width];

            metadata = lmzmodels.slip_quadruped. ...
                ResearchPhaseDiagramGeometry.provenance();
            metadata.constants = struct('boxOffsetX', 0.93, ...
                'boxCenterY', 1.75, 'boxHalfLength', 0.45, ...
                'boxHalfWidth', 0.16, 'textLength', 0.08, ...
                'barOriginOffsetX', 0.576, 'barLength', 0.8, ...
                'barWidth', width, 'barYShift', yShift);
            box = lmz.viz.PatchGeometry('phase_box', boxVertices, 1:4, metadata);
            definitions = { ...
                'BL','LH','tBL_TD','tBL_LO', ...
                    [boxCenterY+width+1.5*yShift, ...
                     boxCenterY+2*width+1.5*yShift]; ...
                'BR','RH','tBR_TD','tBR_LO', ...
                    [boxCenterY-width-1.5*yShift, ...
                     boxCenterY-2*width-1.5*yShift]; ...
                'FL','LF','tFL_TD','tFL_LO', ...
                    [boxCenterY+0.5*yShift, ...
                     boxCenterY+width+0.5*yShift]; ...
                'FR','RF','tFR_TD','tFR_LO', ...
                    [boxCenterY-0.5*yShift, ...
                     boxCenterY-width-0.5*yShift]};
            bars = repmat(struct('Id','','Label','','Base',[], ...
                'Duration',[],'BaseColor',[],'DurationColor',[], ...
                'Wrapped',false,'Touchdown',0,'Liftoff',0), 1, 4);
            layers = {box};
            for index = 1:4
                touchdown = schedule.(definitions{index, 3});
                liftoff = schedule.(definitions{index, 4});
                yRange = definitions{index, 5};
                [baseVertices, durationVertices, baseColor, ...
                    durationColor, wrapped] = barGeometry(origin, wholeLength, ...
                    yRange, touchdown, liftoff, schedule.tAPEX);
                base = lmz.viz.PatchGeometry( ...
                    ['phase_' lower(definitions{index, 1}) '_base'], ...
                    baseVertices, 1:4, metadata);
                duration = lmz.viz.PatchGeometry( ...
                    ['phase_' lower(definitions{index, 1}) '_duration'], ...
                    durationVertices, 1:4, metadata);
                bars(index) = struct('Id', definitions{index, 1}, ...
                    'Label', definitions{index, 2}, 'Base', base, ...
                    'Duration', duration, 'BaseColor', baseColor, ...
                    'DurationColor', durationColor, 'Wrapped', wrapped, ...
                    'Touchdown', touchdown, 'Liftoff', liftoff);
                layers{end+1} = base; %#ok<AGROW>
                layers{end+1} = duration; %#ok<AGROW>
            end
            value = struct('Box', box, 'TextLabels', ...
                {{'LH','LF','RF','RH'}}, 'TextPositions', textPositions, ...
                'Bars', bars, 'BarDrawOrder', {{'BL','BR','FL','FR'}}, ...
                'Layers', lmz.viz.LayeredGeometry('research_phase', ...
                    layers, metadata), 'Metadata', metadata);
        end

        function value = fromSimulation(simulation, index)
            if ~isa(simulation, 'lmz.api.SimulationResult') || ...
                    ~isnumeric(index) || ~isreal(index) || ...
                    ~isscalar(index) || ~isfinite(index) || ...
                    index < 1 || index > numel(simulation.Time) || ...
                    index ~= fix(index)
                error('lmz:slip_quadruped:GeometryFrame', ...
                    'A SimulationResult and valid frame index are required.');
            end
            x = simulation.state('x');
            schedule = lmzmodels.slip_quadruped.ResearchLegGeometry. ...
                eventSchedule(simulation);
            value = lmzmodels.slip_quadruped.ResearchPhaseDiagramGeometry. ...
                compute(x(index), schedule);
        end

        function value = provenance()
            value = struct('sourceRepository', 'DLARlab/SLIP_Model_Zoo', ...
                'sourceCommit', ...
                lmzmodels.slip_quadruped.ResearchPhaseDiagramGeometry.SourceCommit, ...
                'sourcePath', ...
                lmzmodels.slip_quadruped.ResearchPhaseDiagramGeometry.SourcePath, ...
                'sourceLines', '3-132', ...
                'adaptation', ['Named event schedule and explicit black/white ' ...
                    'colors; geometry and source BL/BR/FL/FR draw order retained.'], ...
                'qualification', ['Equal touchdown/liftoff is treated as an ' ...
                    'empty stance bar; the source left this case undefined.'], ...
                'redistributionStatus', 'unresolved_source_derived');
        end
    end
end

function [baseVertices, durationVertices, baseColor, durationColor, wrapped] = ...
        barGeometry(origin, lengthValue, yRange, touchdown, liftoff, period)
baseVertices = rectangle(origin, origin+lengthValue, yRange);
if touchdown < liftoff
    first = touchdown; second = liftoff;
    baseColor = [1 1 1]; durationColor = [0 0 0]; wrapped = false;
elseif touchdown > liftoff
    first = liftoff; second = touchdown;
    baseColor = [0 0 0]; durationColor = [1 1 1]; wrapped = true;
else
    first = touchdown; second = liftoff;
    baseColor = [1 1 1]; durationColor = [0 0 0]; wrapped = false;
end
durationVertices = rectangle(origin+first/period*lengthValue, ...
    origin+second/period*lengthValue, yRange);
end

function vertices = rectangle(first, second, yRange)
vertices = [first yRange(1); second yRange(1); ...
    second yRange(2); first yRange(2)];
end

function schedule = validateSchedule(schedule)
required = {'tBL_TD','tBL_LO','tFL_TD','tFL_LO', ...
    'tBR_TD','tBR_LO','tFR_TD','tFR_LO','tAPEX'};
if ~isstruct(schedule) || ~isscalar(schedule)
    error('lmz:slip_quadruped:PhaseSchedule', ...
        'Named phase schedule must be one struct.');
end
for index = 1:numel(required)
    name = required{index};
    if ~isfield(schedule, name) || ~isnumeric(schedule.(name)) || ...
            ~isreal(schedule.(name)) || ~isscalar(schedule.(name)) || ...
            ~isfinite(schedule.(name))
        error('lmz:slip_quadruped:PhaseSchedule', ...
            'Named event %s is required.', name);
    end
end
if schedule.tAPEX <= 0
    error('lmz:slip_quadruped:PhasePeriod', ...
        'Phase period must be positive.');
end
end
