classdef ResearchStyle
    %RESEARCHSTYLE Deterministic style for source-derived quadruped graphics.
    methods (Static)
        function value = defaults()
            value = struct();
            value.body = struct('backgroundColor', [1 1 1], ...
                'shadeColor', [0.8 0.8 0.8], 'edgeColor', [0 0 0], ...
                'shadeWidth', 3, 'outlineWidth', 4);
            value.leg = struct('springColor', [245 131 58]/256, ...
                'springWidth', 5, 'upperBackgroundColor', [1 1 1], ...
                'shadeColor', [0.8 0.8 0.8], 'shadeWidth', 3, ...
                'outlineColor', [0 0 0], 'outlineWidth', 3, ...
                'lowerColor', [1 1 1], 'lowerEdgeColor', [0 0 0], ...
                'lowerWidth', 3);
            value.com = struct('outerColor', [1 1 1], ...
                'edgeColor', [0 0 0], 'outerWidth', 5, ...
                'innerWidth', 3, 'radius', 0.15);
            value.ground = struct('fieldColor', [1 1 1], ...
                'edgeColor', [0 0 0], 'hatchColor', [0 0 0], ...
                'lineWidth', 0.5);
            value.phase = struct('boxColor', [1 1 1], ...
                'edgeColor', [0 0 0], 'lineWidth', 1.5, ...
                'textColor', [0 0 0], 'fontSize', 10, ...
                'titleFontSize', 15);
            value.force = struct('color', [0.75 0.1 0.1], ...
                'lineWidth', 1.2, 'scale', 0.025);
        end

        function value = resolve(profile)
            value = lmzmodels.slip_quadruped.ResearchStyle.defaults();
            if nargin < 1 || isempty(profile), return, end
            if ~isa(profile, 'lmz.viz.VisualizationProfile')
                error('lmz:slip_quadruped:ResearchStyleProfile', ...
                    'VisualizationProfile is required.');
            end
            value = merge(value, profile.Style);
        end
    end
end

function result = merge(base, override)
result = base;
if isempty(override), return, end
names = fieldnames(override);
for index = 1:numel(names)
    name = names{index};
    if isfield(result, name) && isstruct(result.(name)) && ...
            isstruct(override.(name)) && isscalar(result.(name)) && ...
            isscalar(override.(name))
        result.(name) = merge(result.(name), override.(name));
    else
        result.(name) = override.(name);
    end
end
end
