classdef ResearchCOMGeometry
    %RESEARCHCOMGEOMETRY Pure source-derived center-of-mass symbol.
    properties (Constant)
        SourceCommit = '2c106101383ecee1b2a9d695efe09fbd72d5718a'
        SourcePath = ['SLIP_Quadruped/2_Graphic_ToolBox/' ...
            'SLIP_Quadrupedal_Graphics/GraphicFunctions/' ...
            'SLIP_Animation_Quad.m']
    end

    methods (Static)
        function value = compute(bodyFrame, radius)
            if nargin < 2, radius = 0.15; end
            if ~isnumeric(bodyFrame) || ~isreal(bodyFrame) || ...
                    numel(bodyFrame) ~= 3 || ...
                    any(~isfinite(bodyFrame(:))) || ...
                    ~isnumeric(radius) || ~isscalar(radius) || ...
                    ~isreal(radius) || ~isfinite(radius) || radius <= 0
                error('lmz:slip_quadruped:COMGeometryInput', ...
                    'Finite body frame and positive COM radius are required.');
            end
            bodyFrame = reshape(bodyFrame, 1, []);
            outerAngle = linspace(0, 2*pi, 40);
            outerLocal = [sin(outerAngle).' * radius * 0.5, ...
                cos(outerAngle).' * radius * 0.5];
            outerVertices = transform(outerLocal, bodyFrame(3), bodyFrame(1:2));

            quarterAngle = linspace(0, pi/2, 10);
            base = [0, sin(quarterAngle)*radius*0.75, 0; ...
                    0, cos(quarterAngle)*radius*0.75, 0].';
            signs = [1 1; 1 -1; -1 -1; -1 1];
            innerVertices = zeros(48, 2);
            innerFaces = zeros(4, 12);
            for quarter = 1:4
                rows = (quarter-1)*12 + (1:12);
                local = base .* signs(quarter, :);
                innerVertices(rows, :) = transform( ...
                    local, bodyFrame(3), bodyFrame(1:2));
                innerFaces(quarter, :) = rows;
            end
            faceColors = repmat([1; 0; 1; 0], 1, 3);
            metadata = lmzmodels.slip_quadruped.ResearchCOMGeometry.provenance();
            metadata.constants = struct('sourceRadius', radius, ...
                'outerScale', 0.5, 'innerScale', 0.75, ...
                'outerSamples', 40, 'quarterArcSamples', 10);
            outer = lmz.viz.PatchGeometry('com_outer', outerVertices, ...
                1:40, metadata);
            inner = lmz.viz.PatchGeometry('com_inner', innerVertices, ...
                innerFaces, metadata);
            value = struct('Outer', outer, 'Inner', inner, ...
                'InnerFaceColors', faceColors, 'Radius', radius, ...
                'Layers', lmz.viz.LayeredGeometry('research_com', ...
                    {outer, inner}, metadata), 'Metadata', metadata);
        end

        function value = fromSimulation(simulation, index, radius)
            if nargin < 3, radius = 0.15; end
            if ~isa(simulation, 'lmz.api.SimulationResult') || ...
                    ~isnumeric(index) || ~isreal(index) || ...
                    ~isscalar(index) || ~isfinite(index) || ...
                    index < 1 || index > numel(simulation.Time) || ...
                    index ~= fix(index)
                error('lmz:slip_quadruped:GeometryFrame', ...
                    'A SimulationResult and valid frame index are required.');
            end
            x = simulation.state('x'); y = simulation.state('y');
            pitch = simulation.state('phi');
            value = lmzmodels.slip_quadruped.ResearchCOMGeometry.compute( ...
                [x(index), y(index), pitch(index)], radius);
        end

        function value = provenance()
            value = struct('sourceRepository', 'DLARlab/SLIP_Model_Zoo', ...
                'sourceCommit', ...
                lmzmodels.slip_quadruped.ResearchCOMGeometry.SourceCommit, ...
                'sourcePath', ...
                lmzmodels.slip_quadruped.ResearchCOMGeometry.SourcePath, ...
                'sourceLines', '219-252,390-417', ...
                'adaptation', ['Four source XData/YData columns are represented ' ...
                    'as four indexed faces with alternating explicit colors.'], ...
                'redistributionStatus', 'unresolved_source_derived');
        end
    end
end

function points = transform(points, angle, center)
rotation = [cos(angle), -sin(angle); sin(angle), cos(angle)];
points = points * rotation.' + reshape(center, 1, 2);
end
