classdef ResearchGroundGeometry
    %RESEARCHGROUNDGEOMETRY Pure source ground field and dense hatch mesh.
    properties (Constant)
        SourceCommit = '2c106101383ecee1b2a9d695efe09fbd72d5718a'
        SourcePath = ['SLIP_Quadruped/2_Graphic_ToolBox/' ...
            'SLIP_Quadrupedal_Graphics/GraphicFunctions/' ...
            'SLIP_Animation_Quad.m']
    end

    methods (Static)
        function value = compute()
            height = 0.01;
            count = 5000;
            spacing = 0.05;
            width = 0.01;
            extension = 0.1;
            locations = -50 + linspace(0, spacing*count, count).';
            vertices = [ ...
                -50, 0; ...
                [zeros(count, 1), repmat(-height, count, 1)] + ...
                    [locations, zeros(count, 1)]; ...
                repmat([-extension, -extension-height], count, 1) + ...
                    [locations, zeros(count, 1)]; ...
                repmat([-extension+width, -extension-height], count, 1) + ...
                    [locations, zeros(count, 1)]; ...
                repmat([width, -height], count, 1) + ...
                    [locations, zeros(count, 1)]; ...
                -50+spacing*count+width, 0];
            faces = [1, 2, 4*count+1, 4*count+2; ...
                repmat([0, count, 2*count, 3*count], count, 1) + ...
                    repmat((1:count).', 1, 4) + 1];
            fieldVertices = [-15 0; 100 0; 100 -20; -15 -20];
            metadata = lmzmodels.slip_quadruped.ResearchGroundGeometry.provenance();
            metadata.constants = struct('topHeight', height, ...
                'stripeCount', count, 'spacing', spacing, ...
                'stripeWidth', width, 'stripeExtension', extension, ...
                'fieldXLimits', [-15 100], 'fieldYLimits', [-20 0], ...
                'hatchXLimits', [-50.1 200.01]);
            field = lmz.viz.PatchGeometry('ground_field', ...
                fieldVertices, 1:4, metadata);
            hatch = lmz.viz.PatchGeometry('ground_hatch', ...
                vertices, faces, metadata);
            value = struct('Field', field, 'Hatch', hatch, ...
                'Summary', struct('vertexCount', size(vertices, 1), ...
                    'faceCount', size(faces, 1), 'stripeCount', count, ...
                    'topFace', faces(1, :), ...
                    'xExtent', [min(vertices(:, 1)), max(vertices(:, 1))], ...
                    'yExtent', [min(vertices(:, 2)), max(vertices(:, 2))]), ...
                'Layers', lmz.viz.LayeredGeometry('research_ground', ...
                    {field, hatch}, metadata), 'Metadata', metadata);
        end

        function value = provenance()
            value = struct('sourceRepository', 'DLARlab/SLIP_Model_Zoo', ...
                'sourceCommit', ...
                lmzmodels.slip_quadruped.ResearchGroundGeometry.SourceCommit, ...
                'sourcePath', ...
                lmzmodels.slip_quadruped.ResearchGroundGeometry.SourcePath, ...
                'sourceLines', '254-281', ...
                'adaptation', ['Source uses two patches; MATLAB default dark ' ...
                    'edge/face is made explicit black by renderer style.'], ...
                'qualification', ['Source comment says -2.5 to 6.5, while ' ...
                    'executed numeric geometry spans the recorded larger extents.'], ...
                'redistributionStatus', 'unresolved_source_derived');
        end
    end
end
