classdef TestGovernanceFiles < matlab.unittest.TestCase
    methods (Test)
        function requiredFilesAndCitationScopesExist(testCase)
            root = lmz.util.ProjectPaths.root();
            required = {'CONTRIBUTING.md', 'SECURITY.md', ...
                'CODE_OF_CONDUCT.md', 'CITATION.cff', 'SUPPORT.md'};
            for index = 1:numel(required)
                testCase.verifyEqual(exist(fullfile(root, required{index}), ...
                    'file'), 2, sprintf('%s is missing.', required{index}));
            end
            citation = fileread(fullfile(root, 'CITATION.cff'));
            tokens = {'cff-version: 1.2.0', 'title: Legged Model Zoo', ...
                'version: 1.0.0-rc.1', ...
                'Breaking Symmetries Leads to Diverse Quadrupedal Gaits', ...
                '10.1109/LRA.2024.3384908', ...
                'A template model explains jerboa gait transitions', ...
                '10.7302/ewaa-qm16', ...
                'Gait Transitions in Load-Pulling Quadrupeds', ...
                '10.48550/arXiv.2507.14727', ...
                'this citation file is not a license grant'};
            for index = 1:numel(tokens)
                testCase.verifyNotEmpty(strfind(citation, tokens{index}), ... %#ok<STREMP>
                    sprintf('CITATION.cff is missing %s.', tokens{index}));
            end
            testCase.verifyEqual(exist(fullfile(root, 'LICENSE'), 'file'), 0, ...
                ['A root LICENSE must remain absent until an authorized ' ...
                'owner decision supplies its exact text.']);
        end
    end
end
