classdef TestMultipleShootingDocumentationContract < matlab.unittest.TestCase
    methods (Test)
        function readmeLinksDetailedRoundTenUsage(testCase)
            root=lmz.util.ProjectPaths.root();
            readme=fileread(fullfile(root,'README.md'));
            tokens={'Rank-aware timing and multiple shooting', ...
                'Use multiple shooting in the GUI', ...
                'docs/multiple-shooting.md', ...
                'docs/horizon-feasibility.md', ...
                'docs/scientific-section-shooting.md', ...
                'docs/quad-load-horizon-continuation.md', ...
                'demo_rectangular_contact_timing.m', ...
                'demo_timing_family_continuation.m', ...
                'demo_multiple_shooting_tutorial.m', ...
                'demo_heterogeneous_stride_plan.m'};
            for index=1:numel(tokens)
                testCase.verifyNotEmpty(strfind(readme,tokens{index}), ... %#ok<STREMP>
                    sprintf('README misses %s.',tokens{index}));
            end
        end

        function readmeDocumentsCompleteGuiArtifactAndResumeWorkflow(testCase)
            root=lmz.util.ProjectPaths.root();
            readme=fileread(fullfile(root,'README.md'));
            tokens={'Section combination', ...
                '14 interface coordinates', ...
                'stride-boundary section has 15', ...
                'individual_1_identical_tr_to_rl', ...
                'phase_compatible_repeat', ...
                'Simulate solved', ...
                'simulate=false', ...
                'shooting.toArtifact()', ...
                'lmz.services.reproduceRun(artifactPath)', ...
                'HorizonContinuationService().resumeHomotopy', ...
                'physical_validation_failure', ...
                'positive solver exit flag alone'};
            for index=1:numel(tokens)
                testCase.verifyNotEmpty(strfind(readme,tokens{index}), ... %#ok<STREMP>
                    sprintf('README GUI usage misses %s.',tokens{index}));
            end
        end

        function loadReadmeDocumentsNativeShootingControls(testCase)
            root=lmz.util.ProjectPaths.root();
            content=fileread(fullfile(root,'models','+lmzmodels', ...
                '+slip_quad_load','README.md'));
            tokens={'multiple_shooting_horizon','14-coordinate interface mask', ...
                'stride-boundary-to-stride-boundary uses 15', ...
                'Apex-to-stride-boundary belongs to **Contact timings only**', ...
                'individual_1_tr_to_rl','phase_compatible_repeat', ...
                'simulate=false','README.md#use-multiple-shooting-in-the-gui'};
            for index=1:numel(tokens)
                testCase.verifyNotEmpty(strfind(content,tokens{index}), ... %#ok<STREMP>
                    sprintf('Load README usage misses %s.',tokens{index}));
            end
        end

        function migrationReportsDetailedUsageAndClosedLocalGate(testCase)
            root=lmz.util.ProjectPaths.root();
            content=fileread(fullfile(root,'MIGRATION_STATUS.md'));
            tokens={'Detailed README and guides', ...
                'beginner-oriented, copyable GUI workflow', ...
                '14-versus-15-coordinate load masks', ...
                'TestMultipleShootingDocumentationContract', ...
                'ROUND10_LOCAL_AUTOMATION_PASSED','544/544', ...
                '4 models and 30 problems'};
            for index=1:numel(tokens)
                testCase.verifyNotEmpty(strfind(content,tokens{index}), ... %#ok<STREMP>
                    sprintf('Migration status misses %s.',tokens{index}));
            end
        end

        function guidesSeparateNumericalAndPhysicalClaims(testCase)
            root=lmz.util.ProjectPaths.root();
            combined=[fileread(fullfile(root,'docs','multiple-shooting.md')) ...
                fileread(fullfile(root,'docs','horizon-feasibility.md'))];
            tokens={'root_found','least_squares_feasible', ...
                'best_known_residual','local_infeasibility_evidence', ...
                'numerical_failure','physical_validation_failure', ...
                'does not prove global nonexistence'};
            for index=1:numel(tokens)
                testCase.verifyNotEmpty(strfind(combined,tokens{index}), ... %#ok<STREMP>
                    sprintf('Guides miss %s.',tokens{index}));
            end
        end

        function documentedPublicExamplesExist(testCase)
            root=lmz.util.ProjectPaths.root();
            names={'demo_rectangular_contact_timing.m', ...
                'demo_timing_family_continuation.m', ...
                'demo_multiple_shooting_tutorial.m', ...
                'demo_heterogeneous_stride_plan.m'};
            for index=1:numel(names)
                testCase.verifyEqual(exist(fullfile(root,'examples', ...
                    names{index}),'file'),2,names{index});
            end
        end

        function continuationAuthoringAndGuiGuidesCrossLink(testCase)
            root=lmz.util.ProjectPaths.root();docsRoot=fullfile(root,'docs');
            contracts={ ...
                'periodic-orbit-and-continuation-tutorial.md', ...
                    {'TimingContinuationService', ...
                    'HorizonContinuationService','multiple-shooting.md'}; ...
                'getting-started-build-a-model.md', ...
                    {'SectionSimulationAdapter','ShootingDecisionSchema', ...
                    'tutorial_hopper/multiple_shooting'}; ...
                'model-author-guide.md', ...
                    {'MultipleShootingProblem','simulateSegment', ...
                    'API_STABILITY.md'}; ...
                'gui-design.md', ...
                    {'Multiple shooting','Horizon feasibility', ...
                    'MultipleShootingService','physical_validation_failure'}};
            for row=1:size(contracts,1)
                content=fileread(fullfile(docsRoot,contracts{row,1}));
                tokens=contracts{row,2};
                for index=1:numel(tokens)
                    testCase.verifyNotEmpty(strfind(content,tokens{index}), ... %#ok<STREMP>
                        sprintf('%s misses %s.',contracts{row,1}, ...
                        tokens{index}));
                end
            end
        end

    end
end
