classdef TestQuadLoadHorizonDocumentationContract < matlab.unittest.TestCase
    methods (Test)
        function guideStatesApisEvidenceAndQualifiedOutcome(testCase)
            root=lmz.util.ProjectPaths.root();
            path=fullfile(root,'docs','quad-load-horizon-continuation.md');
            testCase.verifyEqual(exist(path,'file'),2);
            text=fileread(path);
            tokens={'StrideTemplateLibrary','QuadLoadShootingCodec', ...
                'QuadLoadMultipleShootingProblem', ...
                'QuadLoadHorizonContinuation', ...
                'QuadLoadSectionSimulationAdapter', ...
                'round10_feasibility_evidence.json', ...
                '0.7136044533002278','0.7217887917287552', ...
                '2.8172762892858283','does not prove global', ...
                'n5_stride_boundary_bounded_work_best_known', ...
                '0.3086908931991573', ...
                'smallest tested control-cardinality', ...
                'structural warm-start ladder', ...
                'historicalExploratoryAttempts', ...
                'candidateFamilySummaries','numerical_failure', ...
                'schema bounds','[0, 100]','Energy.Accepted', ...
                '96-entry','structural','tempname(tempdir)'};
            for index=1:numel(tokens)
                testCase.verifyNotEmpty(strfind(text,tokens{index}), ... %#ok<STREMP>
                    sprintf('Guide misses %s.',tokens{index}));
            end
        end

        function fiveQualifiedExamplesExistAndUseTemporaryOutputs(testCase)
            folder=fullfile(lmz.util.ProjectPaths.root(),'examples');
            names={'demo_quad_load_template_library.m', ...
                'demo_quad_load_three_stride_feasibility.m', ...
                'demo_quad_load_five_stride_horizon.m', ...
                'demo_quad_load_horizon_continuation.m', ...
                'demo_quad_load_n2_periodic_solve.m'};
            for index=1:numel(names)
                path=fullfile(folder,names{index});
                testCase.verifyEqual(exist(path,'file'),2,names{index});
                text=fileread(path);
                testCase.verifyNotEmpty(strfind(text,'output=struct'));
                testCase.verifyNotEmpty(strfind(text,'OutputDirectory'));
                testCase.verifyNotEmpty(strfind(text,'tempname'));
                testCase.verifyEmpty(strfind(text,'/Users/'));
            end
        end

        function modelReadmeDocumentsRound10UsageAndQualifications(testCase)
            path=fullfile(lmz.util.ProjectPaths.root(),'models', ...
                '+lmzmodels','+slip_quad_load','README.md');
            text=fileread(path);
            tokens={'multiple_shooting_horizon', ...
                'QuadLoadFeasibilityEvidence', ...
                'CompletedPhysicalStrideCount', ...
                'Direct load section timing', ...
                'SourceFixedCoordinateNames', ...
                'segment_2_post_swing_1','47-variable', ...
                'do not prove global nonexistence', ...
                '0.7136044533002278', ...
                'physical_validation_failure', ...
                'n5_stride_boundary_bounded_work_best_known', ...
                '0.3086908931991573','numerical_failure', ...
                '119/119','rank 112/nullity 7', ...
                'absolute bound of 100','publishes no simulation', ...
                'demo_quad_load_template_library.m', ...
                'demo_quad_load_three_stride_feasibility.m', ...
                'demo_quad_load_five_stride_horizon.m', ...
                'demo_quad_load_horizon_continuation.m', ...
                'demo_quad_load_n2_periodic_solve.m'};
            for index=1:numel(tokens)
                testCase.verifyNotEmpty(strfind(text,tokens{index}), ... %#ok<STREMP>
                    sprintf('Model README misses %s.',tokens{index}));
            end
        end

        function fixedDimensionStiffnessFamilyIsRecordedAndQualified(testCase)
            root=lmz.util.ProjectPaths.root();
            guide=fileread(fullfile(root,'docs', ...
                'quad-load-horizon-continuation.md'));
            example=fileread(fullfile(root,'examples', ...
                'demo_quad_load_horizon_continuation.m'));
            guideTokens={'Fixed-dimension N=2 stiffness continuation', ...
                'segment_2_post_swing_1','ExpectedLocalDimension', ...
                'ContinuationService','46-to-47','47-variable', ...
                '25.88062464009689','EnergyMode=''diagnostic_only''', ...
                'not the unresolved N=2 periodic'};
            exampleTokens={'ContinuationParameter', ...
                'ProblemConfiguration','ParameterValues', ...
                'DecisionSchemaHash','FixedDimensionArtifactPath', ...
                'ExpectedLocalDimension','SourceEvidence', ...
                'segment_2_post_swing_1'};
            for index=1:numel(guideTokens)
                testCase.verifyNotEmpty(strfind(guide, ... %#ok<STREMP>
                    guideTokens{index}),sprintf('Guide misses %s.', ...
                    guideTokens{index}));
            end
            for index=1:numel(exampleTokens)
                testCase.verifyNotEmpty(strfind(example, ... %#ok<STREMP>
                    exampleTokens{index}),sprintf('Example misses %s.', ...
                    exampleTokens{index}));
            end
        end
    end
end
