classdef TestRound11DocumentationContracts < matlab.unittest.TestCase
    methods (Test)
        function requiredGuidesDescribeRegisteredWorkflow(testCase)
            root=lmz.util.ProjectPaths.root();
            records={ ...
                'docs/registered-workflows.md', ...
                {'WorkflowRegistry','WorkflowRunner', ...
                'DataSourceProvider','schema `1.0.0`', ...
                'discoverWithPlugins'}; ...
                'docs/scientific-workbench-layout.md', ...
                {'scientific_workbench','classic_tabs','3.35:1.85', ...
                'SolveIterationSnapshot','900 x 650'}; ...
                'docs/gui-layout-profiles.md', ...
                {'scientific_workbench','classic_tabs','PreferencesStore', ...
                'workbench.lmz.json'}; ...
                'docs/quadruped-reference-workflow.md', ...
                {'roadmap_root_continuation','PK_20_2','267', ...
                '45835bb5024b1dc9b875c7b8f7b205769f537a4ff4144c763058537f44dbf401', ...
                'DirectionMode','demo_registered_slip_quadruped_workflow.m'}; ...
                'docs/quadruped-workflow-parity.md', ...
                {'Source data loading','Hover preview','Root refinement', ...
                'Descending and ascending branch search','Human visual'}; ...
                'docs/quadruped-gui-layout-map.md', ...
                {'Data Info','BranchCanvas','StatusDock','SidebarHost', ...
                'human visual approval'}};
            for recordIndex=1:size(records,1)
                path=fullfile(root,records{recordIndex,1});
                testCase.verifyEqual(exist(path,'file'),2, ...
                    sprintf('Missing Round 11 guide: %s', ...
                    records{recordIndex,1}));
                content=fileread(path);
                required=records{recordIndex,2};
                for tokenIndex=1:numel(required)
                    testCase.verifyNotEmpty(strfind(content, ... %#ok<STREMP>
                        required{tokenIndex}),sprintf( ...
                        '%s misses %s.',records{recordIndex,1}, ...
                        required{tokenIndex}));
                end
            end
        end

        function readmeCoversUsageAndExtensionRoute(testCase)
            root=lmz.util.ProjectPaths.root();
            readme=fileread(fullfile(root,'README.md'));
            required={'## Registered workflows and layout profiles', ...
                'roadmap_root_continuation','scientific_workbench', ...
                'classic_tabs','DirectionMode', ...
                'SolveIterationSnapshot','DataSourceProvider', ...
                'minimal_simulation','scientific_periodic_branch', ...
                'docs/registered-workflows.md', ...
                'docs/quadruped-workflow-parity.md', ...
                'docs/quadruped-gui-layout-map.md'};
            for index=1:numel(required)
                testCase.verifyNotEmpty(strfind(readme,required{index}), ... %#ok<STREMP>
                    sprintf('README misses %s.',required{index}));
            end
            testCase.verifyNotEmpty(strfind(readme, ... %#ok<STREMP>
                '''DirectionMode'', ''both'''), ...
                'README misses the copyable both-direction option.');
        end

        function newGuideLinksResolveLocally(testCase)
            docsRoot=fullfile(lmz.util.ProjectPaths.root(),'docs');
            names={'registered-workflows.md', ...
                'scientific-workbench-layout.md','gui-layout-profiles.md', ...
                'quadruped-reference-workflow.md', ...
                'quadruped-workflow-parity.md', ...
                'quadruped-gui-layout-map.md'};
            for index=1:numel(names)
                content=fileread(fullfile(docsRoot,names{index}));
                links=regexp(content, ...
                    '\]\(([^\)#]+\.md)(?:#[^\)]*)?\)','tokens');
                for linkIndex=1:numel(links)
                    target=fullfile(docsRoot,links{linkIndex}{1});
                    testCase.verifyEqual(exist(target,'file'),2, ...
                        sprintf('%s links missing %s.',names{index}, ...
                        links{linkIndex}{1}));
                end
            end
        end

        function rc3KeepsPersistentSchemasAtOneZero(testCase)
            root=lmz.util.ProjectPaths.root();
            testCase.verifyEqual(strtrim(fileread(fullfile(root, ...
                'VERSION'))),'1.0.0-rc.3');
            frameworkPaths={'README.md','CITATION.cff', ...
                'docs/API_STABILITY.md','docs/RELEASE_NOTES_1_0.md'};
            for index=1:numel(frameworkPaths)
                content=fileread(fullfile(root,frameworkPaths{index}));
                testCase.verifyNotEmpty(strfind(content, ... %#ok<STREMP>
                    '1.0.0-rc.3'),sprintf('%s misses rc.3.', ...
                    frameworkPaths{index}));
            end
            schemaPaths={'docs/API_STABILITY.md', ...
                'docs/configuration-reference.md', ...
                'docs/registered-workflows.md', ...
                'docs/RELEASE_NOTES_1_0.md'};
            for index=1:numel(schemaPaths)
                content=fileread(fullfile(root,schemaPaths{index}));
                testCase.verifyNotEmpty(strfind(content, ... %#ok<STREMP>
                    '1.0.0'),sprintf('%s misses schema 1.0.0.', ...
                    schemaPaths{index}));
            end
        end

        function authoringAndBenchmarkGuidesAreConcrete(testCase)
            root=lmz.util.ProjectPaths.root();
            authoring=[fileread(fullfile(root,'README.md')) ...
                fileread(fullfile(root,'docs','model-author-guide.md')) ...
                fileread(fullfile(root,'docs', ...
                'getting-started-build-a-model.md')) ...
                fileread(fullfile(root,'tools','model_template','README.md'))];
            requiredAuthoring={'minimal_simulation', ...
                'scientific_periodic_branch','data_sources.lmz.json', ...
                'workbench.lmz.json','BranchCatalogProvider.m', ...
                'LegacyAdapterProvider.m', ...
                'TestGeneratedScientificWorkflow.m'};
            for index=1:numel(requiredAuthoring)
                testCase.verifyNotEmpty(strfind(authoring, ... %#ok<STREMP>
                    requiredAuthoring{index}),sprintf( ...
                    'Authoring guides miss %s.',requiredAuthoring{index}));
            end

            benchmark=fileread(fullfile(root,'benchmarks','README.md'));
            requiredBenchmarks={'run_round11_workbench_benchmarks', ...
                '''Repetitions'', 3','workbench_construction', ...
                'model_workflow_switch', ...
                'roadmap_all_branches_registered_load', ...
                'branch_axis_change_with_overlays_20', ...
                'branch_hover_updates_100','sidebar_tab_switching_50', ...
                'solve_progress_updates_100', ...
                'accepted_continuation_overlay_updates_20', ...
                'minimum_size_resize_scroll_refresh_20', ...
                'classic_workbench_layout_switch_10'};
            for index=1:numel(requiredBenchmarks)
                testCase.verifyNotEmpty(strfind(benchmark, ... %#ok<STREMP>
                    requiredBenchmarks{index}),sprintf( ...
                    'Benchmark guide misses %s.', ...
                    requiredBenchmarks{index}));
            end
        end

        function statusSeparatesWorktreeFromExternalGates(testCase)
            root=lmz.util.ProjectPaths.root();
            paths={'README.md','CHANGELOG.md','MIGRATION_STATUS.md', ...
                'docs/TEST_STATUS.md', ...
                'docs/RELEASE_CANDIDATE_STATUS.md'};
            combined='';
            for index=1:numel(paths)
                combined=[combined fileread(fullfile(root,paths{index}))]; ...
                    %#ok<AGROW>
            end
            required={ ...
                '5c6a6c100f752ea6ed1fd20114f84800f9b52070', ...
                'latest public committed HEAD', ...
                'current uncommitted Round 11 worktree','remote CI', ...
                'human desktop','R2019b runtime', ...
                'redistribution authority'};
            lowerCombined=lower(combined);
            for index=1:numel(required)
                testCase.verifyNotEmpty(strfind(lowerCombined, ... %#ok<STREMP>
                    lower(required{index})),sprintf( ...
                    'Round 11 status misses %s.',required{index}));
            end
        end
    end
end
