classdef TestReadmeScientificModelContract < matlab.unittest.TestCase
    methods (Test)
        function tutorialsSchemasMaturityAndExamplesAreCurrent(testCase)
            root=lmz.util.ProjectPaths.root();text=fileread(fullfile(root,'README.md'));
            required={ ...
                '## SLIP Quadruped RoadMap Tutorial', ...
                '## SLIP Biped GaitMap Tutorial', ...
                '## SLIP Quadruped-with-Load Fitting Tutorial', ...
                'W1`, `R1`, `HP1`, `SK1`, `SK2`, and `AR1`', ...
                '2,967 total points','nine named residual blocks', ...
                '44 + 13*(N-1)','18 physical states', ...
                'stride-duration mismatch','guarded R-squared', ...
                '<!-- LMZ:PROBLEM_TABLE:BEGIN -->', ...
                '`slip_biped/periodic_apex` | nonlinear_equation | validated | source-equivalent', ...
                '`slip_quad_load/multi_stride_fit` | optimization | validated | source-equivalent', ...
                '`slip_quadruped/demo_stride` | simulation | tutorial | tested', ...
                'docs/REDISTRIBUTION_STATUS.md'};
            for index=1:numel(required)
                testCase.verifyNotEmpty(strfind(text,required{index}), ... %#ok<STREMP>
                    sprintf('README is missing scientific contract text: %s',required{index}));
            end
            examples={ ...
                'demo_slip_biped_gaitmap_workflow.m','demo_slip_biped_solve.m', ...
                'demo_slip_biped_continuation.m','demo_slip_biped_trajectory_fit.m', ...
                'demo_slip_quad_load_single_stride.m','demo_slip_quad_load_multi_stride.m', ...
                'demo_slip_quad_load_fit.m','demo_all_scientific_models.m', ...
                'demo_full_desktop_workflow.m', ...
                'demo_slip_quadruped_roadmap_workflow.m'};
            for index=1:numel(examples)
                testCase.verifyEqual(exist(fullfile(root,'examples',examples{index}),'file'),2, ...
                    sprintf('Documented scientific example is missing: %s',examples{index}));
            end
            roadmapExample=fileread(fullfile(root,'examples', ...
                'demo_slip_quadruped_roadmap_workflow.m'));
            roadmapContracts={ ...
                'roadmapOutputDirectory=fullfile(tempdir', ...
                'output=struct(', ...
                '''ArtifactPath'',roadmapArtifactPath', ...
                '''SuccessMarker'',''LMZ_ROADMAP_WORKFLOW_OK'''};
            for index=1:numel(roadmapContracts)
                testCase.verifyNotEmpty(strfind(roadmapExample, ...
                    roadmapContracts{index}), ... %#ok<STREMP>
                    sprintf('RoadMap example contract is missing: %s', ...
                    roadmapContracts{index}));
            end
            testCase.verifyEmpty(strfind(roadmapExample, ...
                'roadmapOutputDirectory=pwd')); %#ok<STREMP>
            exampleRunner=fileread(fullfile(root,'tools', ...
                'run_public_examples.m'));
            testCase.verifyNotEmpty(strfind(exampleRunner, ...
                'removeExampleOutput(exampleOutputDirectory019f)')); %#ok<STREMP>
            tables=generate_readme_tables(false);
            rows=[tables.ModelRows;tables.ProblemRows];
            for index=1:numel(rows)
                testCase.verifyNotEmpty(strfind(text,rows{index})); %#ok<STREMP>
            end
        end
    end
end
