classdef TestModelAuthorTutorialExamples < matlab.unittest.TestCase
    %TESTMODELAUTHORTUTORIALEXAMPLES Execute the documented Round 9 chain.
    methods (Test)
        function descendingReturnAndSupportedTimingExecute(testCase)
            registry=lmz.registry.ModelRegistry.discover();
            model=registry.createModel('tutorial_hopper');
            catalog=registry.getPoincareSectionRegistry('tutorial_hopper');
            descending=catalog.section('height_descending');
            context=lmz.api.RunContext.synchronous(2026);

            apexProblem=model.createProblem('periodic_hop',struct());
            decision=apexProblem.getDecisionSchema().defaults();
            parameters=apexProblem.getParameterSchema().defaults();
            evaluation=apexProblem.evaluate( ...
                decision,parameters,context,true);
            source=apexProblem.makeSolution( ...
                decision,parameters,evaluation);
            returned=lmz.services.PoincareReturnService().simulate( ...
                model,source,struct('StartSectionId','apex', ...
                'StopSectionId','height_descending'),context);

            testCase.verifyEqual(returned.StopCrossing.SectionId, ...
                'height_descending');
            testCase.verifyGreaterThan(returned.StopCrossing.Time, ...
                descending.MinimumReturnTime);
            testCase.verifyLessThan( ...
                returned.StopCrossing.DirectionalDerivative,0);
            testCase.verifyFalse(returned.StopCrossing.Grazing);
            testCase.verifyTrue(returned.StopCrossing.Accepted);
            testCase.verifyEqual(descending.value( ...
                returned.StopCrossing.Time,returned.StopCrossing.State, ...
                parameters,returned.StopCrossing.ModeBefore),0, ...
                'AbsTol',2e-12);

            descendingTimingProblem=model.createProblem( ...
                'section_return_timing',struct( ...
                'StartSectionId','height_descending', ...
                'StopSectionId','height_descending'));
            descendingTiming=lmz.services.ContactTimingService().solve( ...
                descendingTimingProblem, ...
                descendingTimingProblem.InputSchedule, ...
                struct('MultistartCount',1),context);
            testCase.verifyEqual( ...
                descendingTiming.SectionCrossing.SectionId, ...
                'height_descending');
            testCase.verifyTrue(descendingTiming.SectionCrossing.Accepted);
            testCase.verifyLessThan(norm([ ...
                descendingTiming.ContactResiduals; ...
                descendingTiming.SectionResidual]),1e-9);
            testCase.verifyEqual(descendingTiming.FixedInitialState(3), ...
                0.1,'AbsTol',10*eps);
            testCase.verifyLessThan( ...
                descendingTiming.FixedInitialState(4),0);

            timingProblem=model.createProblem( ...
                'section_return_timing',struct());
            fixedState=timingProblem.FixedInitialState;
            fixedParameters=timingProblem.FixedPhysicalParameters;
            timing=lmz.services.ContactTimingService().solve( ...
                timingProblem,timingProblem.InputSchedule, ...
                struct('MultistartCount',1),context);
            testCase.verifyEqual(timing.FixedInitialState,fixedState);
            testCase.verifyEqual( ...
                timing.FixedPhysicalParameters,fixedParameters);
            testCase.verifyTrue( ...
                timing.SolverDiagnostics.NoPeriodicityResidual);
            testCase.verifyEqual(timing.SectionCrossing.SectionId,'apex');
            testCase.verifyLessThan(norm([timing.ContactResiduals; ...
                timing.SectionResidual]),1e-10);
        end

        function periodicContinuationComparesApexAndDescendingBranches(testCase)
            registry=lmz.registry.ModelRegistry.discover();
            model=registry.createModel('tutorial_hopper');
            context=lmz.api.RunContext.synchronous(2027);
            apexProblem=model.createProblem('periodic_hop',struct());
            decision=apexProblem.getDecisionSchema().defaults();
            parameters=apexProblem.getParameterSchema().defaults();
            seedEvaluation=apexProblem.evaluate( ...
                decision,parameters,context,false);
            seed=apexProblem.makeSolution( ...
                decision,parameters,seedEvaluation);
            apexSolved=lmz.services.SolveService().solve( ...
                apexProblem,seed,struct('Display','off', ...
                'MaxIterations',100,'MaxFunctionEvaluations',500),context);
            testCase.verifyGreaterThan(apexSolved.ExitFlag,0);
            testCase.verifyLessThan( ...
                apexSolved.Evaluation.ScaledResidualNorm,1e-9);

            transferred=lmz.services.SectionTransferService().transfer( ...
                model,apexSolved.Solution,'height_descending',context);
            configuration=struct( ...
                'StartSectionId','height_descending', ...
                'StopSectionId','height_descending');
            descendingProblem=model.createProblem( ...
                'periodic_orbit',configuration);
            descendingEvaluation=descendingProblem.evaluate( ...
                transferred.Solution.DecisionValues, ...
                transferred.Solution.ParameterValues,context,true);
            descendingSeed=descendingProblem.makeSolution( ...
                transferred.Solution.DecisionValues, ...
                transferred.Solution.ParameterValues, ...
                descendingEvaluation);
            descendingSolved=lmz.services.SolveService().solve( ...
                descendingProblem,descendingSeed,struct('Display','off', ...
                'MaxIterations',100,'MaxFunctionEvaluations',500),context);
            testCase.verifyGreaterThan(descendingSolved.ExitFlag,0);
            testCase.verifyLessThan( ...
                descendingSolved.Evaluation.ScaledResidualNorm,1e-8);

            % The documented analytic family uses periodic_hop as its
            % continuation chart.  Each accepted point is then evaluated
            % under the configured descending-section problem below.
            pair=lmz.services.SeedService().makeSecondSeed( ...
                apexProblem,apexSolved.Solution,0.01, ...
                struct(),context);
            testCase.verifyGreaterThan(pair.AchievedRadius,0);
            continuation=lmz.services.ContinuationService().run( ...
                apexProblem,pair,struct('MaximumPoints',4, ...
                'BothDirections',false,'InitialStep',pair.AchievedRadius, ...
                'MinimumStep',1e-5,'MaximumStep',pair.AchievedRadius, ...
                'CorrectorTolerance',1e-9),context);
            apexBranch=continuation.Branch;
            testCase.verifyGreaterThanOrEqual( ...
                apexBranch.pointCount(),2);

            count=apexBranch.pointCount();
            descendingSolutions=descendingSolved.Solution;
            apexInvariants=zeros(4,count);
            descendingInvariants=zeros(4,count);
            for index=1:count
                point=apexBranch.point(index);
                apexEvaluation=apexProblem.evaluate( ...
                    point.DecisionValues,point.ParameterValues,context,true);
                targetEvaluation=descendingProblem.evaluate( ...
                    point.DecisionValues,point.ParameterValues,context,true);
                targetSolution=descendingProblem.makeSolution( ...
                    point.DecisionValues,point.ParameterValues, ...
                    targetEvaluation);
                if index==1
                    descendingSolutions=targetSolution;
                else
                    descendingSolutions(index)=targetSolution;
                end

                testCase.verifyLessThan( ...
                    apexEvaluation.ScaledResidualNorm,1e-8);
                testCase.verifyLessThan( ...
                    targetEvaluation.ScaledResidualNorm,1e-8);
                testCase.verifyFalse( ...
                    targetEvaluation.Diagnostics.HiddenTimingSolve);
                testCase.verifyEqual( ...
                    targetEvaluation.Simulation.States(1,3),0.1, ...
                    'AbsTol',2e-12);
                testCase.verifyLessThanOrEqual( ...
                    targetEvaluation.Diagnostics.ReturnDiagnostics. ...
                    PhysicalOrbitMaxError,1e-10);

                apexInvariants(:,index)=orbitInvariants( ...
                    apexEvaluation.Simulation,point);
                descendingInvariants(:,index)=orbitInvariants( ...
                    targetEvaluation.Simulation,point);
            end
            descendingBranch=lmz.data.SolutionBranch.fromSolutions( ...
                descendingSolutions);
            testCase.verifyEqual(descendingBranch.pointCount(),count);
            testCase.verifyEqual(descendingBranch.DecisionValues, ...
                apexBranch.DecisionValues);
            testCase.verifyEqual(descendingInvariants,apexInvariants, ...
                'AbsTol',2e-10);
        end
    end
end

function value=orbitInvariants(simulation,solution)
value=[simulation.Time(end); ...
    simulation.States(end,1)-simulation.States(1,1); ...
    solution.decision('horizontal_speed'); ...
    solution.decision('stride_length')];
end
