classdef TestCommittedHeadStatusContract < matlab.unittest.TestCase
    methods (Test)
        function releaseStatusRecordsCommittedRoundHistory(testCase)
            root=lmz.util.ProjectPaths.root();
            status=fileread(fullfile(root,'docs', ...
                'RELEASE_CANDIDATE_STATUS.md'));
            required={'c2616735354a354fa432bac549f81861f8ddd9a5', ...
                'c0d87860b59cfbdffe96e165cd01c68e2de7d948', ...
                '5c6a6c100f752ea6ed1fd20114f84800f9b52070', ...
                'Round 8 closing HEAD','Round 9 closing HEAD', ...
                'Round 10 closing HEAD','latest public committed HEAD'};
            for index=1:numel(required)
                testCase.verifyNotEmpty(strfind(status,required{index}), ... %#ok<STREMP>
                    sprintf('Release status misses %s.',required{index}));
            end
            stale={['the requested implementation remains an uncommitted ' ...
                'worktree change'], ...
                'uncommitted Round 10 worktree', ...
                'Round 10 locally closed worktree status', ...
                'Round 10 worktree base/current committed HEAD', ...
                'Treat the uncommitted Round 10'};
            for index=1:numel(stale)
                testCase.verifyEmpty(strfind(status,stale{index}), ... %#ok<STREMP>
                    sprintf('Release status retains stale text: %s.',stale{index}));
            end
        end

        function roundTenCommittedGateIsClosedAndExternallyQualified(testCase)
            root=lmz.util.ProjectPaths.root();
            paths={'docs/RELEASE_CANDIDATE_STATUS.md', ...
                'docs/TEST_STATUS.md','MIGRATION_STATUS.md','CHANGELOG.md', ...
                'README.md','docs/RELEASE_NOTES_1_0.md'};
            for index=1:numel(paths)
                content=fileread(fullfile(root,paths{index}));
                testCase.verifyNotEmpty(strfind(content,'Round 10'), ... %#ok<STREMP>
                    sprintf('%s misses Round 10.',paths{index}));
                testCase.verifyNotEmpty(strfind(content, ... %#ok<STREMP>
                    'ROUND10_LOCAL_AUTOMATION_PASSED'), ...
                    sprintf('%s misses the local-close marker.',paths{index}));
            end
            status=fileread(fullfile(root,'docs', ...
                'RELEASE_CANDIDATE_STATUS.md'));
            qualifiers={'latest public committed HEAD','locally executed', ...
                'remote CI','human desktop','R2019b runtime', ...
                'redistribution authority'};
            lowerStatus=lower(status);
            for index=1:numel(qualifiers)
                testCase.verifyNotEmpty(strfind(lowerStatus, ... %#ok<STREMP>
                    lower(qualifiers{index})),qualifiers{index});
            end
            combined='';
            for index=1:numel(paths)
                combined=[combined fileread(fullfile(root,paths{index}))]; %#ok<AGROW>
            end
            required={'544/544','19,973/25,363','932','917', ...
                'not an authorized public release'};
            for index=1:numel(required)
                testCase.verifyNotEmpty(strfind(combined,required{index}), ... %#ok<STREMP>
                    sprintf('Round 10 close misses %s.',required{index}));
            end
            stale={'Round 10 closing evidence is **PENDING**', ...
                'aggregate release gates are still **PENDING**', ...
                'Round 10 closing automation PENDING', ...
                'Round 10 aggregates above remain **PENDING**', ...
                'uncommitted Round 10 worktree', ...
                'Round 10 locally closed worktree status', ...
                ['Round 10 implementation and documentation are current ' ...
                'worktree changes'], ...
                'Round 10 worktree base/current committed HEAD', ...
                'current uncommitted worktree', ...
                'The committed HEAD remains the Round 9 closing', ...
                'Latest committed closing baseline: 2026-07-20 Round 9'};
            for index=1:numel(stale)
                testCase.verifyEmpty(strfind(combined,stale{index}), ... %#ok<STREMP>
                    sprintf('Stale Round 10 status remains: %s.',stale{index}));
            end

            committedStatusPaths={'docs/RELEASE_CANDIDATE_STATUS.md', ...
                'docs/TEST_STATUS.md','MIGRATION_STATUS.md','CHANGELOG.md', ...
                'README.md'};
            roundTenHead='5c6a6c100f752ea6ed1fd20114f84800f9b52070';
            for index=1:numel(committedStatusPaths)
                content=fileread(fullfile(root,committedStatusPaths{index}));
                testCase.verifyNotEmpty(strfind(content,roundTenHead), ... %#ok<STREMP>
                    sprintf('%s misses committed Round 10 HEAD.', ...
                    committedStatusPaths{index}));
            end
        end
    end
end
