classdef TestRound10DocumentationContracts < matlab.unittest.TestCase
    methods (Test)
        function shootingAndFeasibilityGuidesUseQualifiedLanguage(testCase)
            root=lmz.util.ProjectPaths.root();docsRoot=fullfile(root,'docs');
            contracts={ ...
                'multiple-shooting.md',{'MultipleShootingService', ...
                    'interface_k_defect','RankAwareNonlinearSolver', ...
                    'least_squares_feasible','n-rank(J)=1'}; ...
                'horizon-feasibility.md',{'root_found', ...
                    'best_known_residual','local_infeasibility_evidence', ...
                    'numerical_failure','physical_validation_failure', ...
                    'GlobalInfeasibilityProven=false'}; ...
                'contact-timing-solve.md',{'validate_fixed_rows', ...
                    'include_fixed_rows_in_least_squares', ...
                    'diagnostic_only','TimingContinuationService', ...
                    'lmz:Timing:GaugeRequired'}; ...
                'multi-stride-planning.md',{'ShootingHorizon', ...
                    'HeterogeneousStridePlan','allow_non_neutral'}; ...
                'service-api.md',{'FeasibilityAnalysisService', ...
                    'HorizonContinuationService','MultipleShootingService'}};
            for row=1:size(contracts,1)
                path=fullfile(docsRoot,contracts{row,1});
                testCase.verifyEqual(exist(path,'file'),2,contracts{row,1});
                text=fileread(path);tokens=contracts{row,2};
                for index=1:numel(tokens)
                    testCase.verifyNotEmpty(strfind(text,tokens{index}), ... %#ok<STREMP>
                        sprintf('%s misses %s.',contracts{row,1},tokens{index}));
                end
            end
            feasibility=fileread(fullfile(docsRoot,'horizon-feasibility.md'));
            testCase.verifyNotEmpty(strfind(feasibility, ... %#ok<STREMP>
                'does not prove'));
        end

        function newGuideLinksResolveLocally(testCase)
            docsRoot=fullfile(lmz.util.ProjectPaths.root(),'docs');
            names={'multiple-shooting.md','horizon-feasibility.md'};
            for index=1:numel(names)
                text=fileread(fullfile(docsRoot,names{index}));
                links=regexp(text,'\]\(([^\)#]+\.md)(?:#[^\)]*)?\)', ...
                    'tokens');
                for linkIndex=1:numel(links)
                    target=fullfile(docsRoot,links{linkIndex}{1});
                    testCase.verifyEqual(exist(target,'file'),2, ...
                        sprintf('%s links missing %s.', ...
                        names{index},links{linkIndex}{1}));
                end
            end
        end

        function publicExamplesExposeExactContracts(testCase)
            root=lmz.util.ProjectPaths.root();folder=fullfile(root,'examples');
            required={ ...
                'demo_rectangular_contact_timing.m', ...
                    'LMZ_RECTANGULAR_CONTACT_TIMING_OK'; ...
                'demo_timing_family_continuation.m', ...
                    'LMZ_TIMING_FAMILY_CONTINUATION_OK'; ...
                'demo_quadruped_touchdown_periodic_orbit.m', ...
                    'LMZ_QUADRUPED_TOUCHDOWN_PERIODIC_ORBIT_OK'; ...
                'demo_biped_touchdown_timing.m', ...
                    'LMZ_BIPED_TOUCHDOWN_TIMING_OK'; ...
                'demo_scientific_state_plane_shooting.m', ...
                    'LMZ_SCIENTIFIC_STATE_PLANE_SHOOTING_OK'; ...
                'demo_multiple_shooting_tutorial.m', ...
                    'LMZ_MULTIPLE_SHOOTING_TUTORIAL_OK'; ...
                'demo_heterogeneous_stride_plan.m', ...
                    'LMZ_HETEROGENEOUS_STRIDE_PLAN_OK'};
            for row=1:size(required,1)
                path=fullfile(folder,required{row,1});
                testCase.verifyEqual(exist(path,'file'),2,required{row,1});
                text=fileread(path);
                tokens={'output=struct','OutputDirectory', ...
                    required{row,2},'tempname'};
                for index=1:numel(tokens)
                    testCase.verifyNotEmpty(strfind(text,tokens{index}), ... %#ok<STREMP>
                        sprintf('%s misses %s.',required{row,1},tokens{index}));
                end
                testCase.verifyEmpty(strfind(text,'lmztest.'), ... %#ok<STREMP>
                    sprintf('%s depends on a test fixture.',required{row,1}));
                testCase.verifyEmpty(strfind(text,'/Users/'), ... %#ok<STREMP>
                    sprintf('%s contains a host-specific path.',required{row,1}));
            end
            provider=fullfile(folder,'+lmzexamples', ...
                'AffineTimingFamilyProvider.m');
            testCase.verifyEqual(exist(provider,'file'),2);
            timing=fileread(fullfile(folder, ...
                'demo_timing_family_continuation.m'));
            testCase.verifyNotEmpty(strfind(timing,'reproduceRun'));
            testCase.verifyNotEmpty(strfind( ... %#ok<STREMP>
                timing,'ReproductionSucceeded'));
        end

        function roundTenExamplesUseOnlyDeclaredModelFacades(testCase)
            root=lmz.util.ProjectPaths.root();folder=fullfile(root,'examples');
            names={'demo_rectangular_contact_timing.m', ...
                'demo_timing_family_continuation.m', ...
                'demo_quadruped_touchdown_periodic_orbit.m', ...
                'demo_biped_touchdown_timing.m', ...
                'demo_scientific_state_plane_shooting.m', ...
                'demo_multiple_shooting_tutorial.m', ...
                'demo_heterogeneous_stride_plan.m', ...
                'demo_quad_load_template_library.m', ...
                'demo_quad_load_three_stride_feasibility.m', ...
                'demo_quad_load_five_stride_horizon.m', ...
                'demo_quad_load_horizon_continuation.m', ...
                'demo_quad_load_n2_periodic_solve.m'};
            allowed={'StrideTemplateLibrary','QuadLoadFeasibilityEvidence', ...
                'QuadLoadMultipleShootingProblem', ...
                'QuadLoadHorizonContinuation'};
            for index=1:numel(names)
                content=fileread(fullfile(folder,names{index}));
                matches=regexp(content, ...
                    'lmzmodels\.slip_quad_load\.([A-Za-z0-9_]+)', ...
                    'tokens');
                for matchIndex=1:numel(matches)
                    testCase.verifyTrue(any(strcmp(matches{matchIndex}{1}, ...
                        allowed)),sprintf('%s uses undeclared facade %s.', ...
                        names{index},matches{matchIndex}{1}));
                end
            end
        end
    end
end
