classdef TestModelTemplateGenerator < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addGeneratorToPath(testCase)
            toolsRoot = fullfile(lmz.util.ProjectPaths.root(), 'tools');
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(toolsRoot));
        end
    end

    methods (Test)
        function generatesInactiveExecutableExternalProject(testCase)
            outputRoot = tempname; mkdir(outputRoot);
            cleanup = onCleanup(@() removeTree(outputRoot));
            report = new_model('example_hopper', outputRoot);
            testCase.verifyFalse(report.ActivatedProductionCatalog);
            testCase.verifyEqual(report.AuthoringRoute, ...
                'minimal_simulation');
            required = { ...
                fullfile('models','+lmzmodels','+example_hopper','Model.m'), ...
                fullfile('catalog','example_hopper','manifest.json'), ...
                fullfile('catalog','example_hopper','graphics.lmz.json'), ...
                fullfile('catalog','example_hopper','graphics','clean_generic_style.json'), ...
                fullfile('tests','generated','example_hopper','TestGeneratedModel.m'), ...
                fullfile('examples','demo_example_hopper.m'), 'plugin.json'};
            for index = 1:numel(required)
                testCase.verifyEqual(exist(fullfile(outputRoot, required{index}), 'file'), 2);
            end
            testCase.verifyEqual(exist(fullfile(outputRoot, 'catalog', ...
                'example_hopper', 'data_sources.lmz.json'), 'file'), 0);
            manifest = lmz.compat.Json.read(fullfile(outputRoot, ...
                'catalog', 'example_hopper', 'manifest.json'));
            testCase.verifyFalse(isfield(manifest, 'dataSources'));
            testCase.verifyFalse(isfield(manifest, 'workbench'));
            testCase.verifyFalse(isfield(manifest, 'workflows'));
            defaultRegistry = lmz.registry.ModelRegistry.discover();
            defaultCleanup = onCleanup(@() delete(defaultRegistry));
            testCase.verifyFalse(any(strcmp(defaultRegistry.listModels(), 'example_hopper')));
            clear defaultCleanup
            registry = lmz.registry.ModelRegistry.discoverWithPlugins( ...
                outputRoot, 'IncludeBuiltIns', false);
            registryCleanup = onCleanup(@() delete(registry));
            workflows = ...
                lmz.workflow.WorkflowRegistry.fromModelRegistry(registry);
            testCase.verifyEmpty(workflows.listDataSources('example_hopper'));
            testCase.verifyEmpty(workflows.list('example_hopper'));
            workbench = workflows.getWorkbench('example_hopper');
            testCase.verifyEqual(workbench.Id, 'generic');
            model = registry.createModel('example_hopper');
            graphics = registry.getGraphicsConfig('example_hopper');
            testCase.verifyEqual(graphics.defaultForMaturity('experimental'), ...
                'clean_generic');
            problem = model.createProblem('periodic_orbit', struct());
            result = problem.evaluate(problem.getDecisionSchema().defaults(), ...
                problem.getParameterSchema().defaults(), ...
                lmz.api.RunContext.synchronous(4), true);
            testCase.verifyLessThan(result.ScaledResidualNorm, 1e-12);
            testCase.verifyClass(result.Simulation, 'lmz.api.SimulationResult');
            testCase.verifyError(@() new_model('example_hopper', outputRoot), ...
                'lmz:Template:Collision');
            clear result problem model graphics workbench workflows
            clear registryCleanup cleanup
        end

        function generatesRegisteredScientificPeriodicBranch(testCase)
            outputRoot = tempname; mkdir(outputRoot);
            cleanup = onCleanup(@() removeTree(outputRoot));
            report = new_model('registered_hopper', outputRoot, ...
                'AuthoringRoute', 'scientific_periodic_branch');
            testCase.verifyEqual(report.AuthoringRoute, ...
                'scientific_periodic_branch');
            package = fullfile('models', '+lmzmodels', ...
                '+registered_hopper');
            catalog = fullfile('catalog', 'registered_hopper');
            required = { ...
                fullfile(package, 'BranchCatalogProvider.m'), ...
                fullfile(package, 'LegacyAdapterProvider.m'), ...
                fullfile(catalog, 'data_sources.lmz.json'), ...
                fullfile(catalog, 'workbench.lmz.json'), ...
                fullfile(catalog, 'workflows', ...
                'periodic_branch_workflow.json'), ...
                fullfile('tests', 'generated', 'registered_hopper', ...
                'TestGeneratedScientificWorkflow.m'), ...
                fullfile('examples', ...
                'demo_registered_hopper_registered_workflow.m')};
            for index = 1:numel(required)
                testCase.verifyEqual(exist(fullfile( ...
                    outputRoot, required{index}), 'file'), 2);
            end
            manifest = lmz.compat.Json.read(fullfile( ...
                outputRoot, catalog, 'manifest.json'));
            testCase.verifyEqual(manifest.dataSources, ...
                'data_sources.lmz.json');
            testCase.verifyEqual(manifest.workbench, ...
                'workbench.lmz.json');
            testCase.verifyEqual(manifest.workflows, ...
                {'workflows/periodic_branch_workflow.json'});

            registry = lmz.registry.ModelRegistry.discoverWithPlugins( ...
                outputRoot, 'IncludeBuiltIns', false);
            registryCleanup = onCleanup(@() delete(registry));
            workflows = ...
                lmz.workflow.WorkflowRegistry.fromModelRegistry(registry);
            testCase.verifyEqual(workflows.list('registered_hopper'), ...
                {'periodic_branch_workflow'});
            descriptor = workflows.get( ...
                'registered_hopper', 'periodic_branch_workflow');
            testCase.verifyEqual(numel(descriptor.SourceHash), 64);
            testCase.verifyEqual(numel(descriptor.DataSource.SourceHash), 64);
            testCase.verifyEqual(numel(descriptor.Workbench.SourceHash), 64);
            provider = descriptor.createDataSourceProvider();
            testCase.verifyClass(provider, ...
                'lmzmodels.registered_hopper.BranchCatalogProvider');
            dataset = provider.load(descriptor.DataSource, ...
                descriptor.DefaultDatasetId, registry);
            testCase.verifyEqual(dataset.Branch.ModelId, ...
                'registered_hopper');
            testCase.verifyEqual(dataset.Branch.pointCount(), 3);

            session = lmz.workflow.WorkflowRunner().initialize( ...
                descriptor, lmz.api.RunContext.synchronous(41));
            testCase.verifyLessThan( ...
                session.InitialEvaluation.ScaledResidualNorm, 1e-12);
            solved = session.solve(struct());
            testCase.verifyGreaterThan(solved.ExitFlag, 0);
            testCase.verifyLessThan( ...
                solved.Evaluation.ScaledResidualNorm, 1e-12);
            pair = session.makeAdjacentSeedPair(+1, struct());
            continuation = session.continueBranch(struct( ...
                'MaximumPoints',4,'DirectionMode','both', ...
                'InitialStep',pair.AchievedRadius, ...
                'MaximumStep',pair.AchievedRadius));
            testCase.verifyEqual(continuation.Branch.pointCount(), 4);

            adapter = provider.legacyAdapter( ...
                descriptor.DataSource, registry);
            testCase.verifyClass(adapter, ...
                'lmzmodels.registered_hopper.LegacyAdapterProvider');
            path = [tempname '.mat'];
            fileCleanup = onCleanup(@() deleteIfPresent(path));
            adapter.exportBranch(path, dataset.Branch);
            testCase.verifyTrue(adapter.canLoad(path));
            restored = adapter.importBranch(path, session.Problem);
            testCase.verifyEqual(restored.DecisionValues, ...
                dataset.Branch.DecisionValues, 'AbsTol', 0);

            workflowPath = fullfile(outputRoot, catalog, 'workflows', ...
                'periodic_branch_workflow.json');
            workflowValue = lmz.compat.Json.read(workflowPath);
            workflowValue.label = 'Changed after registry discovery';
            writeText(workflowPath, ...
                lmz.compat.Json.encode(workflowValue));
            testCase.verifyError(@() ...
                lmz.workflow.WorkflowRegistry.fromModelRegistry(registry), ...
                'lmz:Workflow:DescriptorChanged');
            clear fileCleanup registryCleanup cleanup
        end

        function rejectsUnsafeIdsAndImplicitProductionActivation(testCase)
            outputRoot = tempname; mkdir(outputRoot);
            cleanup = onCleanup(@() removeTree(outputRoot));
            testCase.verifyError(@() new_model('../escape', outputRoot), ...
                'lmz:Template:ModelId');
            testCase.verifyError(@() new_model('slip_biped', outputRoot), ...
                'lmz:Template:ReservedModelId');
            testCase.verifyError(@() new_model('implicit_activation', ...
                lmz.util.ProjectPaths.root()), ...
                'lmz:Template:ProductionActivation');
            testCase.verifyError(@() new_model('unsafe_route', ...
                outputRoot, 'AuthoringRoute', 'executable_json'), ...
                'lmz:Template:AuthoringRoute');
            clear cleanup
        end
    end
end

function removeTree(value)
if exist(value, 'dir') == 7, rmdir(value, 's'); end
end

function deleteIfPresent(path)
if exist(path, 'file') == 2, delete(path); end
end

function writeText(path, value)
file = fopen(path, 'w');
if file < 0, error('lmz:Test:Write', 'Could not write %s.', path); end
cleanup = onCleanup(@() fclose(file));
fprintf(file, '%s', value);
clear cleanup
end
