%DEMO_N_STRIDE_PERIODIC_ORBIT Evaluate explicit two-stride final closure.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;
directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('round9OutputDirectory','var')||isempty(round9OutputDirectory)
    round9OutputDirectory=tempname(tempdir);
end
if exist(round9OutputDirectory,'dir')~=7
    [created,message]=mkdir(round9OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

registry=lmz.registry.ModelRegistry.discover();
model=registry.createModel('slip_quad_load');
configuration=struct('NumberOfStrides',2, ...
    'StartSectionId','apex','StopSectionId','apex', ...
    'TimingMode','explicit_variables');
problem=model.createProblem('n_stride_periodic',configuration);
decision=problem.getDecisionSchema().defaults();
parameters=problem.getParameterSchema().defaults();
context=lmz.api.RunContext.synchronous(910);
evaluation=problem.evaluate(decision,parameters,context,true);

if ~isfinite(evaluation.ScaledResidualNorm)|| ...
        ~evaluation.Diagnostics.FinalReturnClosureOnly|| ...
        evaluation.Diagnostics.IntermediatePeriodicityImposed|| ...
        evaluation.Diagnostics.HiddenTimingSolve|| ...
        ~evaluation.Diagnostics.EventTimingVariablesExplicit|| ...
        numel(evaluation.ResidualBlocks)~=3
    error('lmz:Example:NStridePeriodic', ...
        'The explicit final-return-only N-stride periodic contract failed.');
end
candidate=problem.makeSolution(decision,parameters,evaluation);
artifactPath=fullfile(round9OutputDirectory, ...
    'n_stride_periodic_candidate.lmz.mat');
lmz.io.ArtifactStore.save(artifactPath,candidate.toArtifact());
output=struct('NumberOfStrides',2,'PeriodicProblem',problem, ...
    'Evaluation',evaluation,'Candidate',candidate, ...
    'IntermediatePeriodicityImposed',false, ...
    'FinalReturnClosureOnly',true,'HiddenTimingSolve',false, ...
    'EventTimingVariablesExplicit',true,'EvaluationOnly',true, ...
    'SolveConvergenceClaimed',false, ...
    'ArtifactPath',artifactPath,'OutputDirectory',round9OutputDirectory, ...
    'SuccessMarker','LMZ_N_STRIDE_PERIODIC_ORBIT_OK');
fprintf('%s strides=%d residual=%.3g final_only=1 evaluation_only=1\n', ...
    output.SuccessMarker,output.NumberOfStrides, ...
    evaluation.ScaledResidualNorm);
clear directoryCleanup
