%DEMO_QUAD_LOAD_FIVE_STRIDE_HORIZON Report structural N=5 without a root claim.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;
directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('round10OutputDirectory','var')||isempty(round10OutputDirectory)
    round10OutputDirectory=tempname(tempdir);
end
if exist(round10OutputDirectory,'dir')~=7
    [created,message]=mkdir(round10OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

evidence=lmzmodels.slip_quad_load.QuadLoadFeasibilityEvidence();
status=evidence.horizonStatus();
record=evidence.caseRecord( ...
    'n5_stride_boundary_bounded_work_best_known');
replay=evidence.replay(record.id,lmz.api.RunContext.synchronous(0),false);
attempts=evidence.attempts(record.id);
problem=lmzmodels.slip_quad_load.QuadLoadMultipleShootingProblem([], ...
    struct('NumberOfStrides',5,'EnergyMode','diagnostic_only'));
if problem.Horizon.segmentCount()~=5||problem.Codec.unknownCount()~=115|| ...
        status.fiveStrideRootFound|| ...
        status.physicalFiveStrideSimulationPublished|| ...
        status.syntheticCarryForwardUsed||replay.RootFound|| ...
        ~replay.PhysicalValidity|| ...
        ~strcmp(replay.Classification,'numerical_failure')|| ...
        numel(attempts)~=1||numel(record.candidateFamilySummaries)~=4|| ...
        record.candidateFamilySummariesGating
    error('lmz:Example:QuadLoadFiveStrideQualification', ...
        'The structural five-stride result was misclassified as physical.');
end
output=struct('StructuralProblem',problem, ...
    'RelaxedEvidenceReplay',replay, ...
    'FormalAttempt',{attempts}, ...
    'CandidateFamilySummaries',{record.candidateFamilySummaries}, ...
    'ExactSearchSeed',record.deterministicSearchSeed, ...
    'ControlChangeReport',record.controlChangeReport, ...
    'JacobianRank',record.jacobianRankEstimate, ...
    'JacobianNullity',record.nullity, ...
    'BestRecordedScaledResidualNorm',record.scaledResidualNorm, ...
    'ResidualClassification',record.classification, ...
    'StructuralStrideCount',problem.Horizon.segmentCount(), ...
    'StructuralUnknownCount',problem.Codec.unknownCount(), ...
    'CompletedPhysicalStrideCount',status.completedPhysicalStrideCount, ...
    'FiveStrideRootFound',false,'PhysicalSimulation',[], ...
    'SyntheticCarryForwardUsed',false, ...
    'Qualification',status.qualification, ...
    'OutputDirectory',round10OutputDirectory, ...
    'SuccessMarker','LMZ_QUAD_LOAD_FIVE_STRIDE_HORIZON_QUALIFIED_OK');
fprintf('%s structural=%d physical=%d root=%d\n',output.SuccessMarker, ...
    output.StructuralStrideCount,output.CompletedPhysicalStrideCount, ...
    output.FiveStrideRootFound);
clear directoryCleanup
