%DEMO_BIPED_CONTACT_TIMING Solve scientific biped contact times.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;
directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('round9OutputDirectory','var')||isempty(round9OutputDirectory)
    round9OutputDirectory=tempname(tempdir);
end
if exist(round9OutputDirectory,'dir')~=7
    [created,message]=mkdir(round9OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

registry=lmz.registry.ModelRegistry.discover();
model=registry.createModel('slip_biped');
problem=model.createProblem('section_return_timing',struct());
fixedState=problem.FixedInitialState;
fixedParameters=problem.FixedPhysicalParameters;
context=lmz.api.RunContext.synchronous(907);
timingResult=lmz.services.ContactTimingService().solve( ...
    problem,problem.InputSchedule,struct('MultistartCount',1, ...
    'Display','off','MaxIterations',100, ...
    'MaxFunctionEvaluations',500),context);
residualNorm=norm([timingResult.ContactResiduals; ...
    timingResult.SectionResidual]);
if ~isequaln(timingResult.FixedInitialState,fixedState)|| ...
        ~isequaln(timingResult.FixedPhysicalParameters,fixedParameters)|| ...
        ~timingResult.SolverDiagnostics.NoPeriodicityResidual|| ...
        residualNorm>1e-9
    error('lmz:Example:BipedContactTiming', ...
        'Biped timing-only contract failed.');
end
artifactPath=fullfile(round9OutputDirectory,'biped_contact_timing.lmz.mat');
lmz.io.ArtifactStore.save(artifactPath,timingResult.toArtifact());
output=struct('TimingResult',timingResult,'ResidualNorm',residualNorm, ...
    'InitialStateBitwiseUnchanged',true, ...
    'PhysicalParametersBitwiseUnchanged',true, ...
    'ArtifactPath',artifactPath,'OutputDirectory',round9OutputDirectory, ...
    'SuccessMarker','LMZ_BIPED_CONTACT_TIMING_OK');
fprintf('%s residual=%.3g fixed_state=1 fixed_parameters=1\n', ...
    output.SuccessMarker,residualNorm);
clear directoryCleanup
