%DEMO_QUAD_LOAD_N2_PERIODIC_SOLVE Replay the executed periodic search evidence.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;
directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('round10OutputDirectory','var')||isempty(round10OutputDirectory)
    round10OutputDirectory=tempname(tempdir);
end
if exist(round10OutputDirectory,'dir')~=7
    [created,message]=mkdir(round10OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

context=lmz.api.RunContext.synchronous(1005);
evidence=lmzmodels.slip_quad_load.QuadLoadFeasibilityEvidence();
record=evidence.caseRecord('n2_periodic_best_known');
replay=evidence.replay(record.id,context,false);
if replay.RootFound||~replay.PhysicalValidity|| ...
        record.globalInfeasibilityClaimed||record.simulationPublished|| ...
        ~strcmp(replay.Classification,'numerical_failure')|| ...
        replay.SolverTerminationAcceptable|| ...
        ~strcmp(record.solver.terminationReason, ...
        'iteration_or_evaluation_limit')
    error('lmz:Example:QuadLoadN2PeriodicQualification', ...
        'The N=2 periodic search evidence was misclassified.');
end
output=struct('EvidenceReplay',replay,'Rank', ...
    record.jacobianRankEstimate,'SingularValues',record.singularValues, ...
    'ClosureNorm',record.finalClosureNorm,'PeriodicRootFound',false, ...
    'ResidualClassification',record.classification, ...
    'PhysicalCandidate',true,'PhysicalSimulationPublished',false, ...
    'GlobalInfeasibilityClaimed',false, ...
    'OutputDirectory',round10OutputDirectory, ...
    'SuccessMarker','LMZ_QUAD_LOAD_N2_PERIODIC_QUALIFIED_OK');
fprintf('%s residual=%.6g closure=%.6g root=%d\n',output.SuccessMarker, ...
    replay.ScaledResidualNorm,output.ClosureNorm,output.PeriodicRootFound);
clear directoryCleanup
