%DEMO_QUADRUPED_TOUCHDOWN_PERIODIC_ORBIT Solve a section-local return.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;
directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('round10OutputDirectory','var')||isempty(round10OutputDirectory)
    round10OutputDirectory=tempname(tempdir);
end
if exist(round10OutputDirectory,'dir')~=7
    [created,message]=mkdir(round10OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

registry=lmz.registry.ModelRegistry.discover();
model=registry.createModel('slip_quadruped');
configuration=struct('StartSectionId','back_left_touchdown', ...
    'StopSectionId','back_left_touchdown', ...
    'SymmetryId','planar_translation');
problem=model.createProblem('periodic_orbit',configuration);
decision=problem.getDecisionSchema().defaults();
parameters=problem.getParameterSchema().defaults();
seed=problem.makeSolution(decision,parameters,[]);
context=lmz.api.RunContext.synchronous(1200);
solveResult=lmz.services.SolveService().solve(problem,seed,struct( ...
    'AcceptExistingTolerance',1e-8,'FunctionTolerance',1e-10, ...
    'StepTolerance',1e-10,'MaximumIterations',100),context);
evaluation=solveResult.Evaluation;
if solveResult.ExitFlag<=0||evaluation.ScaledResidualNorm>1e-8|| ...
        ~evaluation.PhysicalValidity|| ...
        ~evaluation.Diagnostics.StopCrossing.accepted
    error('lmz:Example:QuadrupedTouchdownPeriodicOrbit', ...
        ['The touchdown return did not meet the root-found and physical ' ...
        'validation criteria.']);
end
artifactPath=fullfile(round10OutputDirectory, ...
    'quadruped_touchdown_periodic_orbit.lmz.mat');
lmz.io.ArtifactStore.save(artifactPath,solveResult.toArtifact());
output=struct('ModelId','slip_quadruped', ...
    'ProblemId','periodic_orbit', ...
    'StartSectionId','back_left_touchdown', ...
    'StopSectionId','back_left_touchdown', ...
    'DecisionCount',numel(solveResult.Solution.DecisionValues), ...
    'SolveResult',solveResult, ...
    'ResidualNorm',evaluation.ScaledResidualNorm, ...
    'PhysicalValidity',evaluation.PhysicalValidity, ...
    'DirectSectionIntegration', ...
    evaluation.Diagnostics.DirectSectionIntegration, ...
    'SourceApexPhaseGaugePreserved', ...
    evaluation.Diagnostics.SourceApexPhaseGaugePreserved, ...
    'Qualification','root_found', ...
    'GlobalInfeasibilityProven',false, ...
    'ArtifactPath',artifactPath, ...
    'OutputDirectory',round10OutputDirectory, ...
    'SuccessMarker','LMZ_QUADRUPED_TOUCHDOWN_PERIODIC_ORBIT_OK');
fprintf('%s qualification=%s variables=%d residual=%.3g\n', ...
    output.SuccessMarker,output.Qualification,output.DecisionCount, ...
    output.ResidualNorm);
clear directoryCleanup
