%DEMO_RECTANGULAR_CONTACT_TIMING Solve two timing rows with one unknown.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;
directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('round9OutputDirectory','var')||isempty(round9OutputDirectory)
    round9OutputDirectory=tempname(tempdir);
end
if exist(round9OutputDirectory,'dir')~=7
    [created,message]=mkdir(round9OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

registry=lmz.registry.ModelRegistry.discover();
model=registry.createModel('tutorial_hopper');
configuration=struct('FixedEventMask',true,'FreeReturnTime',true, ...
    'FixedRowPolicy','include_fixed_rows_in_least_squares', ...
    'FixedRowTolerance',1e-9,'StartSectionId','apex', ...
    'StopSectionId','apex');
problem=model.createProblem('section_return_timing',configuration);
context=lmz.api.RunContext.synchronous(1016);
timingResult=lmz.services.ContactTimingService().solve( ...
    problem,problem.InputSchedule,struct('Solver','lsqnonlin', ...
    'Display','off','ResidualTolerance',1e-9),context);
rank=timingResult.SolverDiagnostics.RankDiagnostics;
if ~timingResult.SolverDiagnostics.Success||rank.M~=2||rank.N~=1|| ...
        rank.Rank~=1||~strcmp(rank.SolverSelected,'lsqnonlin')|| ...
        timingResult.SolverDiagnostics.ResidualNorm>1e-9|| ...
        ~timingResult.SolverDiagnostics.Feasibility.FixedRowsValid
    error('lmz:Example:RectangularContactTiming', ...
        'The overdetermined timing solve did not meet its physical contract.');
end
artifactPath=fullfile(round9OutputDirectory, ...
    'rectangular_contact_timing.lmz.mat');
lmz.io.ArtifactStore.save(artifactPath,timingResult.toArtifact());
output=struct('TimingResult',timingResult,'ResidualRows',rank.M, ...
    'DecisionVariables',rank.N,'JacobianRank',rank.Rank, ...
    'Nullity',rank.Nullity,'SolverSelected',rank.SolverSelected, ...
    'Classification','least_squares_feasible', ...
    'ArtifactPath',artifactPath,'OutputDirectory',round9OutputDirectory, ...
    'SuccessMarker','LMZ_RECTANGULAR_CONTACT_TIMING_OK');
fprintf('%s m=%d n=%d rank=%d residual=%.3g\n',output.SuccessMarker, ...
    output.ResidualRows,output.DecisionVariables,output.JacobianRank, ...
    timingResult.SolverDiagnostics.ResidualNorm);
clear directoryCleanup
