%DEMO_TIMING_FAMILY_CONTINUATION Trace an explicit one-dimensional family.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
examplesRoot=fullfile(projectRoot,'examples');
originalDirectory=pwd;originalSearchPath=path;
directoryCleanup=onCleanup(@()cd(originalDirectory));
pathCleanup=onCleanup(@()path(originalSearchPath));
cd(projectRoot);startup;addpath(examplesRoot);cd(originalDirectory);
if ~exist('round9OutputDirectory','var')||isempty(round9OutputDirectory)
    round9OutputDirectory=tempname(tempdir);
end
if exist(round9OutputDirectory,'dir')~=7
    [created,message]=mkdir(round9OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

model=lmz.registry.ModelRegistry.discover().createModel('tutorial_hopper');
schedule=lmz.schedule.EventSchedule.fromCyclic({'impact'},0.4,1.0, ...
    'FixedMask',false,'ReturnTimeFixed',false,'MinimumGap',1e-8, ...
    'StartSectionId','apex','StopSectionId','apex');
provider=lmzexamples.AffineTimingFamilyProvider();
base=lmz.schedule.SectionReturnTimingProblem(model, ...
    'section_return_timing',provider,[0;1;1;0],9.81,schedule, ...
    struct('FixedRowPolicy','validate_fixed_rows'));
family=lmz.schedule.TimingFamilyProblem(base, ...
    lmz.schedule.TimingGauge.empty(0,1), ...
    struct('ExpectedLocalDimension',1));
seed=family.getDecisionSchema().defaults();
context=lmz.api.RunContext.synchronous(1018);
initialRank=lmz.solvers.RankAwareNonlinearSolver().analyze( ...
    family,seed,[],struct(),context);
options=struct('SecondSeedRadius',0.01,'ResidualTolerance',1e-9, ...
    'ContinuationOptions',struct('MaximumPoints',5, ...
    'BothDirections',false,'InitialStep',0.01,'MinimumStep',1e-5, ...
    'MaximumStep',0.02,'CorrectorTolerance',1e-10));
continuation=lmz.services.TimingContinuationService().run( ...
    family,seed,options,context);
pointCount=continuation.Branch.pointCount();
returnTimes=zeros(pointCount,1);maximumResidual=0;
for index=1:pointCount
    point=continuation.Branch.point(index);
    evaluation=family.evaluate(point.DecisionValues,[],context,false);
    maximumResidual=max(maximumResidual,evaluation.ScaledResidualNorm);
    returnTimes(index)=family.scheduleFromDecision( ...
        point.DecisionValues).ReturnTime;
end
if initialRank.M~=1||initialRank.N~=2||initialRank.Rank~=1|| ...
        initialRank.Nullity~=1||pointCount~=5||maximumResidual>1e-9|| ...
        max(returnTimes)-min(returnTimes)<=1e-4
    error('lmz:Example:TimingFamilyContinuation', ...
        'The timing-family continuation contract was not satisfied.');
end
artifactPath=fullfile(round9OutputDirectory, ...
    'timing_family_continuation.lmz.mat');
lmz.io.ArtifactStore.save(artifactPath,continuation.toArtifact());
[reproduced,reproductionReport]=lmz.services.reproduceRun( ...
    artifactPath,struct('Context', ...
    lmz.api.RunContext.synchronous(context.RandomSeed)));
reproducedCount=reproduced.Branch.pointCount();
reproducedReturnTimes=zeros(reproducedCount,1);reproducedResidual=0;
for index=1:reproducedCount
    point=reproduced.Branch.point(index);
    evaluation=family.evaluate(point.DecisionValues,[],context,false);
    reproducedResidual=max(reproducedResidual, ...
        evaluation.ScaledResidualNorm);
    reproducedReturnTimes(index)=family.scheduleFromDecision( ...
        point.DecisionValues).ReturnTime;
end
returnSpan=max(returnTimes)-min(returnTimes);
reproducedSpan=max(reproducedReturnTimes)-min(reproducedReturnTimes);
reproductionSucceeded=reproducedCount==pointCount&& ...
    reproducedResidual<=1e-9&& ...
    abs(reproducedSpan-returnSpan)<=1e-10&& ...
    strcmp(reproductionReport.ArtifactType,'continuation-run');
if ~reproductionSucceeded
    error('lmz:Example:TimingFamilyReproduction', ...
        'The timing-family continuation artifact did not reproduce.');
end
output=struct('Continuation',continuation,'InitialRank',initialRank, ...
    'PointCount',pointCount,'ReturnTimes',returnTimes, ...
    'MaximumResidual',maximumResidual,'ExpectedLocalDimension',1, ...
    'ReproducedContinuation',reproduced, ...
    'ReproductionReport',reproductionReport, ...
    'ReproducedPointCount',reproducedCount, ...
    'ReproducedReturnTimes',reproducedReturnTimes, ...
    'ReproducedMaximumResidual',reproducedResidual, ...
    'ReproductionSucceeded',reproductionSucceeded, ...
    'ArtifactPath',artifactPath,'OutputDirectory',round9OutputDirectory, ...
    'SuccessMarker','LMZ_TIMING_FAMILY_CONTINUATION_OK');
fprintf(['%s points=%d nullity=%d return_span=%.3g residual=%.3g ' ...
    'reproduced=1\n'], ...
    output.SuccessMarker,pointCount,initialRank.Nullity, ...
    returnSpan,maximumResidual);
clear pathCleanup directoryCleanup
