%DEMO_HETEROGENEOUS_STRIDE_PLAN Simulate two nonidentical hopper strides.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;
directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('round9OutputDirectory','var')||isempty(round9OutputDirectory)
    round9OutputDirectory=tempname(tempdir);
end
if exist(round9OutputDirectory,'dir')~=7
    [created,message]=mkdir(round9OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

gravity=9.81;impulses=[10;12];initialState=[0;1;1;0];
height=initialState(3);schedules=cell(2,1);apexHeights=zeros(3,1);
apexHeights(1)=height;specs=lmz.multistride.StrideSpec.empty(0,1);
for stride=1:2
    impactTime=sqrt(2*height/gravity);
    postImpactVelocity=impulses(stride)-gravity*impactTime;
    if postImpactVelocity<=0
        error('lmz:Example:HeterogeneousStridePlan', ...
            'The declared impulse cannot produce an apex return.');
    end
    returnTime=impactTime+postImpactVelocity/gravity;
    height=postImpactVelocity^2/(2*gravity);
    apexHeights(stride+1)=height;
    schedules{stride}=struct('Names',{{'impact','apex'}}, ...
        'Times',[impactTime;returnTime],'ReturnTime',returnTime, ...
        'OccurrenceOrder',{{'impact','apex'}}, ...
        'Chart','explicit_heterogeneous','MinimumGap',1e-9);
    specs(stride,1)=lmz.multistride.StrideSpec('Index',stride, ...
        'StartSectionId','apex','StopSectionId','apex', ...
        'StartStateSide','post','StopStateSide','post', ...
        'EventSchedule',schedules{stride}, ...
        'PhysicalParameters',struct('gravity',gravity), ...
        'ControlParameters',struct('impulse',impulses(stride)), ...
        'InitialStateSource','previous_terminal_state', ...
        'CompletionStatus','completed','Lineage',struct( ...
        'Source','demo_heterogeneous_stride_plan'));
end
energyPolicy=lmz.multistride.EnergyConsistencyPolicy( ...
    'Id','allow_non_neutral');
plan=lmz.multistride.StridePlan('ModelId','tutorial_hopper', ...
    'ProblemId','n_stride_simulation','RequestedStrideCount',2, ...
    'InitialState',initialState,'DefaultPhysicalParameters',gravity, ...
    'StrideSpecs',specs,'CompletionPolicy','error_if_missing', ...
    'EnergyPolicy',energyPolicy,'FailurePolicy','error', ...
    'Provenance',struct('Source','public-heterogeneous-tutorial-v1'));
request=lmz.multistride.MultiStrideRequest('NumberOfStrides',2, ...
    'StridePlan',plan,'EnergyNeutralOnly',false, ...
    'EnergyPolicy',energyPolicy,'FailurePolicy','error');
model=lmz.registry.ModelRegistry.discover().createModel('tutorial_hopper');
context=lmz.api.RunContext.synchronous(1019);
result=lmz.services.MultiStrideSimulationService().simulate( ...
    model,request,context);
boundaries=result.Diagnostics.StrideBoundaries;
boundaryApexError=zeros(2,1);
for stride=1:2
    terminal=result.Simulation.States(boundaries(stride).EndIndex,:);
    boundaryApexError(stride)=max(abs([terminal(3)-apexHeights(stride+1), ...
        terminal(4)]));
end
durations=cellfun(@(item)item.ReturnTime,schedules);
if ~strcmp(result.CompletionStatus,'complete')|| ...
        result.CompletedStrideCount~=2|| ...
        ~result.Diagnostics.HeterogeneousStridePlan|| ...
        ~result.Diagnostics.StrictlyIncreasingTime|| ...
        numel(unique(round(durations*1e12)))~=2|| ...
        numel(unique(round(impulses*1e12)))~=2|| ...
        max(boundaryApexError)>1e-7
    error('lmz:Example:HeterogeneousStridePlan', ...
        'The explicit heterogeneous stride plan did not execute correctly.');
end
artifactPath=fullfile(round9OutputDirectory, ...
    'heterogeneous_stride_plan.lmz.mat');
lmz.io.ArtifactStore.save(artifactPath,result.toArtifact( ...
    request,context.RandomSeed));
output=struct('MultiStrideResult',result,'StridePlan',plan, ...
    'ReturnTimes',durations,'ImpulseSequence',impulses, ...
    'ApexHeights',apexHeights,'BoundaryApexError',boundaryApexError, ...
    'PhysicalApexReturnsValidated',true, ...
    'ArtifactPath',artifactPath,'OutputDirectory',round9OutputDirectory, ...
    'SuccessMarker','LMZ_HETEROGENEOUS_STRIDE_PLAN_OK');
fprintf('%s strides=%d durations=[%.3g %.3g] impulses=[%.3g %.3g]\n', ...
    output.SuccessMarker,result.CompletedStrideCount,durations(1), ...
    durations(2),impulses(1),impulses(2));
clear directoryCleanup
