%DEMO_MULTIPLE_SHOOTING_TUTORIAL Solve two- and five-segment hopper horizons.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;
directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('round9OutputDirectory','var')||isempty(round9OutputDirectory)
    round9OutputDirectory=tempname(tempdir);
end
if exist(round9OutputDirectory,'dir')~=7
    [created,message]=mkdir(round9OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

model=lmz.registry.ModelRegistry.discover().createModel('tutorial_hopper');
problem=model.createProblem('multiple_shooting',struct( ...
    'HorizonLength',2,'Formulation','periodic', ...
    'ResidualTolerance',1e-8));
seed=problem.ShootingSchema.defaults();
context=lmz.api.RunContext.synchronous(1017);
shootingResult=lmz.services.MultipleShootingService().solve( ...
    problem,seed,struct('Solver','auto','Display','off', ...
    'ResidualTolerance',1e-8),context);
report=shootingResult.FeasibilityReport;
diagnostics=shootingResult.SolveResult.Evaluation.Diagnostics;
fiveProblem=model.createProblem('multiple_shooting',struct( ...
    'HorizonLength',5,'Formulation','periodic', ...
    'ResidualTolerance',1e-8));
fiveResult=lmz.services.MultipleShootingService().solve( ...
    fiveProblem,fiveProblem.ShootingSchema.defaults(), ...
    struct('Solver','auto','Display','off', ...
    'ResidualTolerance',1e-8),context);
fiveReport=fiveResult.FeasibilityReport;
if ~report.Success||~strcmp(report.Classification,'root_found')|| ...
        shootingResult.Horizon.segmentCount()~=2|| ...
        diagnostics.SegmentEvaluationCount~=2|| ...
        ~diagnostics.SingleEvaluationCache|| ...
        max(diagnostics.InterfaceDefectNorms)>1e-8|| ...
        report.MaximumScaledResidual>1e-8|| ...
        ~fiveReport.Success|| ...
        ~strcmp(fiveReport.Classification,'root_found')|| ...
        fiveResult.Horizon.segmentCount()~=5|| ...
        fiveReport.MaximumScaledResidual>1e-8
    error('lmz:Example:MultipleShootingTutorial', ...
        'The analytic multiple-shooting solve did not satisfy its contract.');
end
artifactPath=fullfile(round9OutputDirectory, ...
    'multiple_shooting_tutorial.lmz.mat');
lmz.io.ArtifactStore.save(artifactPath,shootingResult.toArtifact());
output=struct('ShootingResult',shootingResult, ...
    'FeasibilityReport',report,'SegmentCount',2, ...
    'FiveSegmentResult',fiveResult, ...
    'FiveSegmentFeasibilityReport',fiveReport, ...
    'ValidatedSegmentCounts',[2 5], ...
    'InterfaceDefectNorms',diagnostics.InterfaceDefectNorms, ...
    'Classification',report.Classification, ...
    'ArtifactPath',artifactPath,'OutputDirectory',round9OutputDirectory, ...
    'SuccessMarker','LMZ_MULTIPLE_SHOOTING_TUTORIAL_OK');
fprintf(['%s segments=%d,%d classification=%s ' ...
    'residual_n2=%.3g residual_n5=%.3g\n'], ...
    output.SuccessMarker,output.ValidatedSegmentCounts(1), ...
    output.ValidatedSegmentCounts(2), ...
    output.Classification,report.MaximumScaledResidual, ...
    fiveReport.MaximumScaledResidual);
clear directoryCleanup
