%DEMO_QUAD_LOAD_THREE_STRIDE_FEASIBILITY Replay qualified Case A and B evidence.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;
directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('round10OutputDirectory','var')||isempty(round10OutputDirectory)
    round10OutputDirectory=tempname(tempdir);
end
if exist(round10OutputDirectory,'dir')~=7
    [created,message]=mkdir(round10OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

context=lmz.api.RunContext.synchronous(1002);
evidence=lmzmodels.slip_quad_load.QuadLoadFeasibilityEvidence();
fixed=evidence.replay('case_a_fixed_controls_best_known',context,false);
energy=evidence.replay( ...
    'case_b_energy_neutral_controls_best_known',context,false);
fixedRecord=evidence.caseRecord(fixed.CaseId);
energyRecord=evidence.caseRecord(energy.CaseId);
fixedAttempts=evidence.attempts(fixed.CaseId);
energyAttempts=evidence.attempts(energy.CaseId);
fixedHistorical=num2cell(fixedRecord.historicalExploratoryAttempts);
energyHistorical=num2cell(energyRecord.historicalExploratoryAttempts);
if fixed.RootFound||energy.RootFound||fixed.PhysicalValidity|| ...
        energy.PhysicalValidity||fixedRecord.globalInfeasibilityClaimed|| ...
        energyRecord.globalInfeasibilityClaimed
    error('lmz:Example:QuadLoadThreeStrideQualification', ...
        'The unresolved three-stride searches were misclassified.');
end
fixedAttemptNorms=cellfun(@(item)item.scaledResidualNorm,fixedAttempts);
energyAttemptNorms=cellfun(@(item)item.scaledResidualNorm,energyAttempts);
if ~isequal(fixedAttemptNorms,fixedRecord. ...
        multistartScaledResidualNorms(:))|| ...
        ~isequal(energyAttemptNorms,energyRecord. ...
        multistartScaledResidualNorms(:))
    error('lmz:Example:QuadLoadAttemptEvidence', ...
        'Per-attempt records do not match the retained multistart norms.');
end
formalComplete=fixedRecord.formalAttemptsComplete&& ...
    energyRecord.formalAttemptsComplete&& ...
    all(cellfun(@(item)~strcmp(item.seedDerivation, ...
    'unknown_not_retained'),fixedAttempts))&& ...
    all(cellfun(@(item)~strcmp(item.seedDerivation, ...
    'unknown_not_retained'),energyAttempts));
historicalNonGating=all(cellfun(@(item)~item.gating, ...
    fixedHistorical(:)))&&all(cellfun(@(item)~item.gating, ...
    energyHistorical(:)));
if ~formalComplete||~historicalNonGating
    error('lmz:Example:QuadLoadAttemptProvenance', ...
        'Formal and historical attempt provenance is inconsistent.');
end
output=struct('FixedControlReplay',fixed, ...
    'EnergyNeutralControlReplay',energy, ...
    'FixedControlAttempts',{fixedAttempts}, ...
    'EnergyNeutralControlAttempts',{energyAttempts}, ...
    'HistoricalFixedControlAttempts',{fixedHistorical}, ...
    'HistoricalEnergyNeutralAttempts',{energyHistorical}, ...
    'FormalAttemptMetadataComplete',formalComplete, ...
    'HistoricalAttemptsAreNonGating',historicalNonGating, ...
    'EnergyNeutralControlChangeReport',energyRecord.controlChangeReport, ...
    'FixedControlRank',fixedRecord.jacobianRankEstimate, ...
    'EnergyNeutralRank',energyRecord.jacobianRankEstimate, ...
    'ThreeStrideRootFound',false,'GlobalInfeasibilityClaimed',false, ...
    'PhysicalSimulationPublished',false, ...
    'OutputDirectory',round10OutputDirectory, ...
    'SuccessMarker','LMZ_QUAD_LOAD_THREE_STRIDE_FEASIBILITY_OK');
fprintf('%s fixed=%.6g energy=%.6g root=%d\n',output.SuccessMarker, ...
    fixed.ScaledResidualNorm,energy.ScaledResidualNorm, ...
    output.ThreeStrideRootFound);
clear directoryCleanup
