%DEMO_BIPED_TOUCHDOWN_TIMING Solve a direct touchdown timing return.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;
directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('round10OutputDirectory','var')||isempty(round10OutputDirectory)
    round10OutputDirectory=tempname(tempdir);
end
if exist(round10OutputDirectory,'dir')~=7
    [created,message]=mkdir(round10OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

model=lmz.registry.ModelRegistry.discover().createModel('slip_biped');
configuration=struct('StartSectionId','left_touchdown', ...
    'StopSectionId','left_touchdown','SymmetryId','planar_translation');
problem=model.createProblem('section_return_timing',configuration);
context=lmz.api.RunContext.synchronous(1201);
timingResult=lmz.services.ContactTimingService().solve(problem, ...
    problem.InputSchedule,struct('Solver','fsolve','Display','off', ...
    'ResidualTolerance',1e-9,'FunctionTolerance',1e-10, ...
    'StepTolerance',1e-10),context);
diagnostics=timingResult.SolverDiagnostics;
rank=diagnostics.RankDiagnostics;
if ~diagnostics.Success||norm(timingResult.ContactResiduals)>1e-9|| ...
        ~diagnostics.Feasibility.Valid||rank.Nullity~=0
    error('lmz:Example:BipedTouchdownTiming', ...
        ['The touchdown timing solve did not satisfy the root, rank, and ' ...
        'physical validation criteria.']);
end
artifactPath=fullfile(round10OutputDirectory, ...
    'biped_touchdown_timing.lmz.mat');
lmz.io.ArtifactStore.save(artifactPath,timingResult.toArtifact());
output=struct('ModelId','slip_biped', ...
    'ProblemId','section_return_timing', ...
    'StartSectionId','left_touchdown', ...
    'StopSectionId','left_touchdown', ...
    'TimingResult',timingResult, ...
    'ResidualRows',rank.M,'DecisionVariables',rank.N, ...
    'JacobianRank',rank.Rank,'Nullity',rank.Nullity, ...
    'Qualification','root_found', ...
    'UniquenessQualification', ...
    diagnostics.SuccessCriteria.RankQualification, ...
    'GlobalInfeasibilityProven',false, ...
    'ArtifactPath',artifactPath, ...
    'OutputDirectory',round10OutputDirectory, ...
    'SuccessMarker','LMZ_BIPED_TOUCHDOWN_TIMING_OK');
fprintf(['%s qualification=%s m=%d n=%d rank=%d ' ...
    'residual=%.3g\n'],output.SuccessMarker,output.Qualification, ...
    output.ResidualRows,output.DecisionVariables,output.JacobianRank, ...
    diagnostics.ResidualNorm);
clear directoryCleanup
