%DEMO_SLIP_QUAD_LOAD_FIT Short generic fit from the stored scientific seed.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
registry=lmz.registry.ModelRegistry.discover();
model=registry.createModel('slip_quad_load');
problem=model.createProblem('multi_stride_fit',struct('InitialPerturbation',0));
sourceSeed=problem.sourceSeed();parameters=problem.getParameterSchema().defaults();
seed=problem.makeSolution(sourceSeed,parameters,[]);
context=lmz.api.RunContext.synchronous(83);
[initialObjective,initialTerms,initialDiagnostics]=problem.evaluateObjective( ...
    sourceSeed,parameters,context);
options=struct('Algorithm','sqp','MaxIterations',1, ...
    'MaxFunctionEvaluations',30,'OptimalityTolerance',1e-5, ...
    'StepTolerance',1e-5);
optimizationResult=lmz.services.OptimizationService().run( ...
    problem,seed,options,context);
optimizedSimulation=lmz.services.SolutionService().simulate( ...
    problem,optimizationResult.Solution,context);
if ~exist('slipQuadLoadOutputDirectory','var')|| ...
        isempty(slipQuadLoadOutputDirectory)
    slipQuadLoadOutputDirectory=fullfile(tempdir,'legged_model_zoo_examples');
end
if exist(slipQuadLoadOutputDirectory,'dir')~=7,mkdir(slipQuadLoadOutputDirectory);end
artifactPath=fullfile(slipQuadLoadOutputDirectory,'slip_quad_load_fit.lmz.mat');
lmz.io.ArtifactStore.save(artifactPath,optimizationResult.toArtifact());
objectiveDecrease=initialObjective-optimizationResult.Objective;
if objectiveDecrease<=0
    error('lmz:Example:QuadLoadFit', ...
        'The short load-pulling fit did not decrease the objective.');
end
output=struct('SourceSeed',seed,'InitialObjective',initialObjective, ...
    'InitialTerms',initialTerms,'InitialDiagnostics',initialDiagnostics, ...
    'OptimizationResult',optimizationResult, ...
    'OptimizedSimulation',optimizedSimulation,'ArtifactPath',artifactPath, ...
    'ObjectiveDecrease',objectiveDecrease, ...
    'SuccessMarker','LMZ_QUAD_LOAD_FIT_OK');
fprintf('%s initial=%.12g final=%.12g decrease=%.12g artifact=%s\n', ...
    output.SuccessMarker,initialObjective,optimizationResult.Objective, ...
    objectiveDecrease,artifactPath);
clear directoryCleanup
