%DEMO_QUAD_LOAD_HORIZON_CONTINUATION Exercise explicit N-to-N+1 embeddings.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;
directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('round10OutputDirectory','var')||isempty(round10OutputDirectory)
    round10OutputDirectory=tempname(tempdir);
end
if exist(round10OutputDirectory,'dir')~=7
    [created,message]=mkdir(round10OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

context=lmz.api.RunContext.synchronous(1004);
evidence=lmzmodels.slip_quad_load.QuadLoadFeasibilityEvidence();
[n2Problem,n2Decision]=evidence.problemFor( ...
    'n2_transition_feasibility_root');
configuration=struct('StartStrideCount',2,'TargetStrideCount',5, ...
    'EnergyMode','diagnostic_only', ...
    'InitialDecisionForContinuation',n2Decision);
continuation=lmzmodels.slip_quad_load.QuadLoadHorizonContinuation();
structural=continuation.continueTo(configuration, ...
    struct('SolveEachHorizon',false),context);
status=evidence.horizonStatus();
preserved=arrayfun(@(index)structural.Records{index}.Embedding. ...
    PreservedVariableCount,2:numel(structural.Records));

sourceCaseId='n2_transition_feasibility_root';
sourceRecord=evidence.caseRecord(sourceCaseId);
familyConfiguration=evidence.configuration(sourceRecord);
freeControlMask=false(2,4);freeControlMask(2,1)=true;
familyConfiguration.FreeControlMask=freeControlMask;
familyConfiguration.ExpectedLocalDimension=1;
familyProblem=lmzmodels.slip_quad_load. ...
    QuadLoadMultipleShootingProblem([],familyConfiguration);
[familySeed,familyEmbedding]=lmz.shooting.HorizonContinuation(). ...
    embedDecision(n2Problem.ShootingSchema,n2Decision, ...
    familyProblem.ShootingSchema);
familyEvaluation=familyProblem.evaluate(familySeed,[],context,false);
familySolution=familyProblem.makeSolution( ...
    familySeed,[],familyEvaluation);
seedRadius=1e-4;
familyPair=lmz.services.SeedService().makeSecondSeed( ...
    familyProblem,familySolution,seedRadius, ...
    struct('ExpectedLocalDimension',1),context);
familyOptions=struct('MaximumPoints',3,'BothDirections',false, ...
    'InitialStep',familyPair.AchievedRadius,'MinimumStep',1e-6, ...
    'MaximumStep',familyPair.AchievedRadius, ...
    'CorrectorTolerance',1e-9,'RequireFeasible',true);
family=lmz.services.ContinuationService().run( ...
    familyProblem,familyPair,familyOptions,context);
selectedQuantity='segment_2_post_swing_1';
decisionNames=familyProblem.getDecisionSchema().names();
selectedIndex=find(strcmp(decisionNames,selectedQuantity),1);
chartRecord=struct('Class','lmz.schema.VariableChart', ...
    'DecisionDimension',familyProblem.getDecisionSchema().count(), ...
    'DecisionNames',{decisionNames}, ...
    'DecisionSchemaHash',lmz.io.ArtifactStore.dataHash( ...
    familyProblem.getDecisionSchema().toStruct()));
familyHistory=cell(family.Branch.pointCount(),1);
controlValues=zeros(1,family.Branch.pointCount());
maximumResiduals=zeros(1,family.Branch.pointCount());
for index=1:family.Branch.pointCount()
    point=family.Branch.point(index);feasibility=point.Feasibility;
    controlValues(index)=point.DecisionValues(selectedIndex);
    maximumResiduals(index)=feasibility.MaximumScaledResidual;
    familyHistory{index}=struct('PointIndex',index, ...
        'ContinuationParameter',struct('Name',selectedQuantity, ...
        'Role','control_stiffness','DecisionIndex',selectedIndex, ...
        'Value',controlValues(index)), ...
        'ProblemConfiguration',familyConfiguration, ...
        'ParameterValues',point.ParameterValues, ...
        'DecisionDimension',numel(point.DecisionValues), ...
        'Chart',chartRecord,'MaximumScaledResidual', ...
        maximumResiduals(index),'PhysicalChecks',struct( ...
        'Valid',feasibility.Valid, ...
        'PhysicalValidity',feasibility.PhysicalValidity, ...
        'CrossingsAccepted',feasibility.CrossingsAccepted, ...
        'EventOrderValid',feasibility.EventOrderValid));
end
familyProvenance=family.Provenance;
familyProvenance.Workflow= ...
    'quad-load-fixed-dimension-stiffness-continuation';
familyProvenance.SourceCaseId=sourceCaseId;
familyProvenance.ProblemConfiguration=familyConfiguration;
familyProvenance.ContinuationParameter=selectedQuantity;
familyProvenance.InitialEmbedding=familyEmbedding;
familyProvenance.FixedDecisionDimension=chartRecord.DecisionDimension;
familyProvenance.Chart=chartRecord;
familyProvenance.EnergyMode='diagnostic_only';
familyProvenance.History=familyHistory;
sourceEvidence=struct('relativePath',[ ...
    'examples/data/slip_quad_load/Scientific/MultipleShooting/' ...
    'round10_feasibility_evidence.json'], ...
    'sha256',lmz.util.FileHash.sha256(evidence.Path));
familyProvenance.SourceEvidence=sourceEvidence;
familyProvenance.SourceCommit=evidence.Data.sourceCommit;
familyProvenance.SourceTemplateSha256=evidence.Data.sourceTemplateSha256;
family=lmz.data.ContinuationResult(family.Branch,family.Snapshots, ...
    family.TerminationReason,family.Options,family.Diagnostics, ...
    family.SourcePair,family.RandomSeed,familyProvenance);
familyArtifactPath=fullfile(round10OutputDirectory, ...
    'quad_load_n2_fixed_dimension_stiffness.lmz.mat');
familyArtifact=family.toArtifact();
familyArtifact.sourceDataHashes.QuadLoadFeasibilityEvidence=sourceEvidence;
lmz.io.ArtifactStore.save(familyArtifactPath,familyArtifact);

if structural.CompletedStrideCount~=5|| ...
        ~isequal(preserved,[46 69 92])|| ...
        status.completedPhysicalStrideCount~=2||status.fiveStrideRootFound|| ...
        ~isequal(familyEmbedding.AddedNames,{selectedQuantity})|| ...
        familyEmbedding.OldDimension~=46||familyEmbedding.NewDimension~=47|| ...
        familyPair.Diagnostics.LocalDimension~=1|| ...
        familyPair.Diagnostics.JacobianRank~=46|| ...
        family.Branch.pointCount()~=3|| ...
        any(cellfun(@(item)item.DecisionDimension,familyHistory)~=47)|| ...
        any(maximumResiduals>1e-8)|| ...
        any(~cellfun(@(item)item.PhysicalChecks.Valid,familyHistory))|| ...
        max(controlValues)-min(controlValues)<=1e-5|| ...
        ~strcmp(family.TerminationReason,'maximum_points')
    error('lmz:Example:QuadLoadHorizonContinuation', ...
        'The structural embedding or physical qualification is invalid.');
end
output=struct('StructuralContinuation',structural, ...
    'EmbeddingPreservedCounts',preserved, ...
    'RequestedSequence',status.requestedSequence, ...
    'CompletedPhysicalStrideCount',status.completedPhysicalStrideCount, ...
    'PhysicalFiveStrideRootFound',false, ...
    'GlobalInfeasibilityClaimed',false, ...
    'FixedDimensionStiffnessFamily',family, ...
    'FixedDimensionHistory',{familyHistory}, ...
    'FixedDimensionEmbedding',familyEmbedding, ...
    'FixedDimensionChart',chartRecord, ...
    'FixedDimensionConfiguration',familyConfiguration, ...
    'SelectedContinuationQuantity',selectedQuantity, ...
    'StiffnessValues',controlValues, ...
    'StiffnessMaximumResiduals',maximumResiduals, ...
    'FixedDimensionArtifactPath',familyArtifactPath, ...
    'OutputDirectory',round10OutputDirectory, ...
    'SuccessMarker','LMZ_QUAD_LOAD_HORIZON_CONTINUATION_QUALIFIED_OK');
fprintf(['%s structural=%d physical=%d root=%d fixed_points=%d ' ...
    'fixed_dimension=%d fixed_residual=%.3g\n'],output.SuccessMarker, ...
    structural.CompletedStrideCount,output.CompletedPhysicalStrideCount, ...
    output.PhysicalFiveStrideRootFound,family.Branch.pointCount(), ...
    chartRecord.DecisionDimension,max(maximumResiduals));
clear directoryCleanup
