%DEMO_FULL_DESKTOP_WORKFLOW Exercise all scientific GUI/service workflows.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('desktopOutputDirectory','var')||isempty(desktopOutputDirectory)
    desktopOutputDirectory=fullfile(tempdir,'legged_model_zoo_examples', ...
        'full_desktop_workflow');
end
if exist(desktopOutputDirectory,'dir')~=7,mkdir(desktopOutputDirectory);end
if ~exist('keepDesktopAppOpen','var')||isempty(keepDesktopAppOpen)
    keepDesktopAppOpen=false;
end

app=lmz.gui.LeggedModelZooApp();
appCleanup=onCleanup(@()deleteIfValid(app));
controller=app.Controller;

controller.selectModel('slip_quadruped');
quadrupedSimulation=controller.simulateWorkingSolution();
quadrupedSolve=controller.solveWorkingSolution(struct());
quadrupedPair=controller.makeAdjacentSeedPair(1,struct());
quadrupedContinuation=controller.runContinuation(struct( ...
    'MaximumPoints',3,'BothDirections',false, ...
    'InitialStep',quadrupedPair.AchievedRadius, ...
    'MaximumStep',quadrupedPair.AchievedRadius));

controller.selectModel('slip_biped');
bipedSimulation=controller.simulateWorkingSolution();
bipedSolve=controller.solveWorkingSolution(struct());
bipedPair=controller.makeAdjacentSeedPair(1,struct());
bipedContinuation=controller.runContinuation(struct( ...
    'MaximumPoints',3,'BothDirections',false, ...
    'InitialStep',bipedPair.AchievedRadius, ...
    'MaximumStep',bipedPair.AchievedRadius));

controller.selectModel('slip_quad_load');
loadSimulation=controller.simulateWorkingSolution();
optimizationOptions=struct('Algorithm','sqp','Display','off', ...
    'MaxIterations',1,'MaxFunctionEvaluations',30, ...
    'OptimalityTolerance',1e-5,'StepTolerance',1e-5);
loadOptimization=controller.runOptimization(optimizationOptions);

artifactPaths=struct( ...
    'QuadrupedBranch',fullfile(desktopOutputDirectory, ...
        'quadruped_branch.lmz.mat'), ...
    'BipedSolution',fullfile(desktopOutputDirectory, ...
        'biped_solution.lmz.mat'), ...
    'BipedContinuation',fullfile(desktopOutputDirectory, ...
        'biped_continuation.lmz.mat'), ...
    'LoadOptimization',fullfile(desktopOutputDirectory, ...
        'load_optimization.lmz.mat'));
lmz.io.ArtifactStore.save(artifactPaths.QuadrupedBranch, ...
    quadrupedContinuation.Branch.toArtifact());
lmz.io.ArtifactStore.save(artifactPaths.BipedSolution, ...
    bipedSolve.Solution.toArtifact());
lmz.io.ArtifactStore.save(artifactPaths.BipedContinuation, ...
    bipedContinuation.toArtifact());
lmz.io.ArtifactStore.save(artifactPaths.LoadOptimization, ...
    loadOptimization.toArtifact());

artifactNames=fieldnames(artifactPaths);
artifactTypes=cell(size(artifactNames));
for artifactIndex=1:numel(artifactNames)
    restored=lmz.io.ArtifactStore.load( ...
        artifactPaths.(artifactNames{artifactIndex}));
    artifactTypes{artifactIndex}=restored.artifactType;
end

output=struct( ...
    'Quadruped',struct('Simulation',quadrupedSimulation, ...
        'SolveResult',quadrupedSolve, ...
        'ContinuationResult',quadrupedContinuation), ...
    'Biped',struct('Simulation',bipedSimulation, ...
        'SolveResult',bipedSolve, ...
        'ContinuationResult',bipedContinuation), ...
    'Load',struct('Simulation',loadSimulation, ...
        'OptimizationResult',loadOptimization), ...
    'ArtifactPaths',artifactPaths,'ArtifactTypes',{artifactTypes}, ...
    'GuiConstructed',~isempty(app.Figure)&&isvalid(app.Figure), ...
    'SuccessMarker','LMZ_FULL_DESKTOP_WORKFLOW_OK');
fprintf('%s artifacts=%d output=%s\n',output.SuccessMarker, ...
    numel(artifactTypes),desktopOutputDirectory);
if keepDesktopAppOpen
    output.App=app;
    clear appCleanup
else
    delete(app);
    clear appCleanup
end
clear directoryCleanup

function deleteIfValid(app)
if ~isempty(app)&&isvalid(app),delete(app);end
end
