%DEMO_ALL_SCIENTIFIC_MODELS Simulate one repository-contained scientific point per model.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);

registry=lmz.registry.ModelRegistry.discover();
branchService=lmz.services.BranchService();
context=lmz.api.RunContext.synchronous(90);

bipedModel=registry.createModel('slip_biped');
bipedProblem=bipedModel.createProblem('periodic_apex',struct());
bipedBranch=branchService.loadBuiltInBranch(registry,'slip_biped');
bipedCatalog=lmzmodels.slip_biped.GaitMapCatalog.default();
bipedIndex=bipedCatalog.recommendedSeedIndex(bipedCatalog.defaultBranchPath());
bipedSolution=bipedBranch.point(bipedIndex);
bipedEvaluation=lmz.services.EvaluationService().evaluate( ...
    bipedProblem,bipedSolution,true,context);

loadModel=registry.createModel('slip_quad_load');
loadProblem=loadModel.createProblem('multi_stride_fit', ...
    struct('InitialPerturbation',0));
loadBranch=branchService.loadBuiltInBranch(registry,'slip_quad_load');
loadSolution=loadBranch.point(1);
loadSimulation=lmz.services.SolutionService().simulate( ...
    loadProblem,loadSolution,context);
[loadObjective,loadTerms,loadDiagnostics]=loadProblem.evaluateObjective( ...
    loadSolution.DecisionValues,loadSolution.ParameterValues,context);

quadrupedModel=registry.createModel('slip_quadruped');
quadrupedProblem=quadrupedModel.createProblem('periodic_apex',struct());
quadrupedBranch=branchService.loadBuiltInBranch(registry,'slip_quadruped');
quadrupedCatalog=lmzmodels.slip_quadruped.RoadMapCatalog.default();
quadrupedIndex=quadrupedCatalog.recommendedSeedIndex( ...
    quadrupedCatalog.defaultBranchPath());
quadrupedSolution=quadrupedBranch.point(quadrupedIndex);
quadrupedEvaluation=lmz.services.EvaluationService().evaluate( ...
    quadrupedProblem,quadrupedSolution,true,context);

output=struct( ...
    'ModelIds',{registry.listModels()}, ...
    'Biped',struct('Branch',bipedBranch,'SeedIndex',bipedIndex, ...
        'Solution',bipedSolution,'Evaluation',bipedEvaluation, ...
        'Simulation',bipedEvaluation.Simulation), ...
    'Load',struct('Branch',loadBranch,'Solution',loadSolution, ...
        'Simulation',loadSimulation,'Objective',loadObjective, ...
        'Terms',loadTerms,'Diagnostics',loadDiagnostics), ...
    'Quadruped',struct('Branch',quadrupedBranch, ...
        'SeedIndex',quadrupedIndex,'Solution',quadrupedSolution, ...
        'Evaluation',quadrupedEvaluation, ...
        'Simulation',quadrupedEvaluation.Simulation), ...
    'SuccessMarker','LMZ_ALL_SCIENTIFIC_MODELS_OK');
fprintf('%s biped=%d load=%d quadruped=%d\n',output.SuccessMarker, ...
    output.Biped.Branch.pointCount(),output.Load.Branch.pointCount(), ...
    output.Quadruped.Branch.pointCount());
clear directoryCleanup
