%DEMO_QUAD_LOAD_EXTEND_TO_FIVE_STRIDES Expose synthetic and corrected outcomes.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;
directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('round9OutputDirectory','var')||isempty(round9OutputDirectory)
    round9OutputDirectory=tempname(tempdir);
end
if exist(round9OutputDirectory,'dir')~=7
    [created,message]=mkdir(round9OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

registry=lmz.registry.ModelRegistry.discover();
model=registry.createModel('slip_quad_load');
catalog=lmzmodels.slip_quad_load.ScientificDatasetCatalog.default();
dataset=catalog.load(catalog.Manifest.defaultMultiStride);
carryRequest=lmz.multistride.MultiStrideRequest( ...
    'NumberOfStrides',5,'InitialDecision',dataset.XAccum, ...
    'CompletionPolicy','carry_forward', ...
    'EnergyNeutralOnly',true,'FailurePolicy','error', ...
    'StartSectionId','apex','StopSectionId','apex');
context=lmz.api.RunContext.synchronous(908);
builder=lmzmodels.slip_quad_load.QuadLoadStridePlanBuilder();
syntheticCompletion=builder.build(carryRequest,context);
expectedLength=44+13*(5-1);
syntheticXAccum=lmzmodels.slip_quad_load.XAccumPlanAdapter.encode( ...
    syntheticCompletion.Plan);
roundTripXAccum=lmzmodels.slip_quad_load.XAccumPlanAdapter.encode( ...
    lmzmodels.slip_quad_load.XAccumPlanAdapter.toPlan(syntheticXAccum));
if syntheticCompletion.CompletedStrideCount~=5|| ...
        numel(syntheticXAccum)~=expectedLength|| ...
        ~isequaln(syntheticXAccum,roundTripXAccum)
    error('lmz:Example:QuadLoadFiveStrides', ...
        'The synthetic five-stride plan or exact codec contract failed.');
end

predictorRequest=lmz.multistride.MultiStrideRequest( ...
    'NumberOfStrides',5,'InitialDecision',dataset.XAccum, ...
    'CompletionPolicy','predictor_corrector', ...
    'EnergyNeutralOnly',true,'FailurePolicy','return_partial', ...
    'StartSectionId','apex','StopSectionId','apex');
correctedAttempt=lmz.services.MultiStrideSimulationService().simulate( ...
    model,predictorRequest,context);
if correctedAttempt.CompletedStrideCount~=2||~correctedAttempt.Partial|| ...
        ~strcmp(correctedAttempt.CompletionStatus,'failed')|| ...
        ~isempty(correctedAttempt.Simulation)|| ...
        ~strcmp(correctedAttempt.Failure.Identifier, ...
        'lmz:MultiStride:TimingSeedOutsideTrustRegion')|| ...
        correctedAttempt.Failure.StrideIndex~=3
    error('lmz:Example:QuadLoadFiveStrides', ...
        'The predictor-corrector did not retain its honest partial failure.');
end
syntheticArtifactPath=fullfile(round9OutputDirectory, ...
    'quad_load_five_stride_synthetic_plan.lmz.mat');
failureArtifactPath=fullfile(round9OutputDirectory, ...
    'quad_load_five_stride_correction_attempt.lmz.mat');
lmz.io.ArtifactStore.save(syntheticArtifactPath, ...
    syntheticCompletion.toArtifact(carryRequest,context.RandomSeed));
lmz.io.ArtifactStore.save(failureArtifactPath, ...
    correctedAttempt.toArtifact(predictorRequest,context.RandomSeed));
output=struct('SyntheticPlanResult',syntheticCompletion, ...
    'SyntheticPlanStrideCount',syntheticCompletion.CompletedStrideCount, ...
    'SyntheticXAccum',syntheticXAccum, ...
    'SyntheticXAccumLength',numel(syntheticXAccum), ...
    'SyntheticSchedulePolicy','carry_forward', ...
    'CorrectedAttempt',correctedAttempt, ...
    'CorrectedCompletedStrideCount',correctedAttempt.CompletedStrideCount, ...
    'CorrectionFailure',correctedAttempt.Failure, ...
    'TimingFeasibilityClaimed',false, ...
    'SyntheticArtifactPath',syntheticArtifactPath, ...
    'FailureArtifactPath',failureArtifactPath, ...
    'OutputDirectory',round9OutputDirectory, ...
    'SuccessMarker','LMZ_QUAD_LOAD_FIVE_STRIDES_OK');
fprintf('%s synthetic_strides=%d x_accum=%d corrected_strides=%d failure=%s\n', ...
    output.SuccessMarker,output.SyntheticPlanStrideCount, ...
    output.SyntheticXAccumLength,output.CorrectedCompletedStrideCount, ...
    output.CorrectionFailure.Identifier);
clear directoryCleanup
