%DEMO_BUILD_MODEL_END_TO_END Generate, test, solve, and continue a plugin.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;
directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('round9OutputDirectory','var')||isempty(round9OutputDirectory)
    round9OutputDirectory=tempname(tempdir);
end
if exist(round9OutputDirectory,'dir')~=7
    [created,message]=mkdir(round9OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

toolsPath=fullfile(projectRoot,'tools');
addpath(toolsPath);
toolsCleanup=onCleanup(@()rmpath(toolsPath));
pluginRoot=tempname(round9OutputDirectory);
mkdir(pluginRoot);
generatorReport=new_model('round9_generated_hopper',pluginRoot);
generatedResults=runtests(fullfile(pluginRoot,'tests','generated'), ...
    'IncludeSubfolders',true);
if any([generatedResults.Failed])||any([generatedResults.Incomplete])
    error('lmz:Example:GeneratedTests','Generated model tests failed.');
end

pluginRegistry=lmz.registry.ModelRegistry.discoverWithPlugins( ...
    pluginRoot,'IncludeBuiltIns',false);
registryCleanup=onCleanup(@()delete(pluginRegistry));
model=pluginRegistry.createModel('round9_generated_hopper');
context=lmz.api.RunContext.synchronous(911);
simulationProblem=model.createProblem('demo_stride',struct());
simulation=lmz.services.SimulationService().simulate( ...
    simulationProblem,[],struct(),context);
periodicProblem=model.createProblem('periodic_orbit',struct());
decision=periodicProblem.getDecisionSchema().defaults();
parameters=periodicProblem.getParameterSchema().defaults();
seed=periodicProblem.makeSolution(decision,parameters, ...
    periodicProblem.evaluate(decision,parameters,context,false));
solved=lmz.services.SolveService().solve( ...
    periodicProblem,seed,struct('Display','off'),context);
secondDecision=solved.Solution.DecisionValues;
secondDecision(1)=secondDecision(1)+0.02;
secondEvaluation=periodicProblem.evaluate( ...
    secondDecision,parameters,context,false);
secondSolution=periodicProblem.makeSolution( ...
    secondDecision,parameters,secondEvaluation);
metric=lmz.schema.DiagonalMetric(periodicProblem.scale( ...
    solved.Solution.DecisionValues));
radius=metric.norm(periodicProblem.difference( ...
    secondDecision,solved.Solution.DecisionValues));
pair=lmz.data.SolutionPair(solved.Solution,secondSolution,radius,radius, ...
    struct('source','generated-analytic-family'));
continued=lmz.services.ContinuationService().run( ...
    periodicProblem,pair,struct('MaximumPoints',4, ...
    'BothDirections',false,'InitialStep',pair.AchievedRadius, ...
    'MaximumStep',pair.AchievedRadius),context);
if solved.Evaluation.ScaledResidualNorm>1e-12|| ...
        continued.Branch.pointCount()<2||~all(diff(simulation.Time)>0)
    error('lmz:Example:BuildModelEndToEnd', ...
        'Generated simulation, solve, or continuation failed.');
end
artifactPath=fullfile(round9OutputDirectory, ...
    'generated_model_continuation.lmz.mat');
lmz.io.ArtifactStore.save(artifactPath,continued.toArtifact());
output=struct('GeneratorReport',generatorReport, ...
    'GeneratedTestCount',numel(generatedResults), ...
    'Simulation',simulation,'SolveResult',solved, ...
    'ContinuationResult',continued, ...
    'ArtifactPath',artifactPath,'OutputDirectory',round9OutputDirectory, ...
    'SuccessMarker','LMZ_BUILD_MODEL_END_TO_END_OK');
fprintf('%s tests=%d residual=%.3g points=%d\n',output.SuccessMarker, ...
    output.GeneratedTestCount,solved.Evaluation.ScaledResidualNorm, ...
    continued.Branch.pointCount());
clear registryCleanup toolsCleanup directoryCleanup
