%DEMO_TUTORIAL_HOPPER_PERIODIC_CONTINUATION Solve and continue a hop family.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;
directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('round9OutputDirectory','var')||isempty(round9OutputDirectory)
    round9OutputDirectory=tempname(tempdir);
end
if exist(round9OutputDirectory,'dir')~=7
    [created,message]=mkdir(round9OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

registry=lmz.registry.ModelRegistry.discover();
model=registry.createModel('tutorial_hopper');
problem=model.createProblem('periodic_hop',struct());
decision=problem.getDecisionSchema().defaults();
parameters=problem.getParameterSchema().defaults();
context=lmz.api.RunContext.synchronous(904);
seed=problem.makeSolution(decision,parameters, ...
    problem.evaluate(decision,parameters,context,false));
solved=lmz.services.SolveService().solve(problem,seed, ...
    struct('Display','off','MaxIterations',100, ...
    'MaxFunctionEvaluations',500),context);
pair=lmz.services.SeedService().makeSecondSeed( ...
    problem,solved.Solution,0.02,struct(),context);
continued=lmz.services.ContinuationService().run(problem,pair, ...
    struct('MaximumPoints',5,'BothDirections',false, ...
    'InitialStep',pair.AchievedRadius, ...
    'MaximumStep',pair.AchievedRadius),context);
if solved.Evaluation.ScaledResidualNorm>1e-9|| ...
        pair.AchievedRadius<=0||continued.Branch.pointCount()<2
    error('lmz:Example:TutorialContinuation', ...
        'Periodic solve, second seed, or continuation failed.');
end
artifactPath=fullfile(round9OutputDirectory, ...
    'tutorial_hopper_continuation.lmz.mat');
lmz.io.ArtifactStore.save(artifactPath,continued.toArtifact());
output=struct('SolveResult',solved,'SeedPair',pair, ...
    'ContinuationResult',continued, ...
    'PointCount',continued.Branch.pointCount(), ...
    'ArtifactPath',artifactPath,'OutputDirectory',round9OutputDirectory, ...
    'SuccessMarker','LMZ_TUTORIAL_PERIODIC_CONTINUATION_OK');
fprintf('%s residual=%.3g points=%d\n',output.SuccessMarker, ...
    solved.Evaluation.ScaledResidualNorm,output.PointCount);
clear directoryCleanup
