%DEMO_TUTORIAL_HOPPER_FIVE_STRIDES Simulate five analytic hopper returns.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;
directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('round9OutputDirectory','var')||isempty(round9OutputDirectory)
    round9OutputDirectory=tempname(tempdir);
end
if exist(round9OutputDirectory,'dir')~=7
    [created,message]=mkdir(round9OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

registry=lmz.registry.ModelRegistry.discover();
model=registry.createModel('tutorial_hopper');
request=lmz.multistride.MultiStrideRequest( ...
    'NumberOfStrides',5,'CompletionPolicy','carry_forward', ...
    'EnergyNeutralOnly',true,'FailurePolicy','error', ...
    'StartSectionId','apex','StopSectionId','apex');
context=lmz.api.RunContext.synchronous(905);
result=lmz.services.MultiStrideSimulationService().simulate( ...
    model,request,context);
if result.CompletedStrideCount~=5|| ...
        ~strcmp(result.CompletionStatus,'complete')|| ...
        ~all(diff(result.Simulation.Time)>0)
    error('lmz:Example:TutorialFiveStrides', ...
        'The tutorial five-stride simulation did not complete.');
end
artifactPath=fullfile(round9OutputDirectory, ...
    'tutorial_hopper_five_stride_plan.lmz.mat');
lmz.io.ArtifactStore.save(artifactPath,result.Plan.toArtifact());
output=struct('MultiStrideResult',result,'StrideCount',5, ...
    'SampleCount',numel(result.Simulation.Time), ...
    'ArtifactPath',artifactPath,'OutputDirectory',round9OutputDirectory, ...
    'SuccessMarker','LMZ_TUTORIAL_FIVE_STRIDES_OK');
fprintf('%s strides=%d samples=%d\n',output.SuccessMarker, ...
    output.StrideCount,output.SampleCount);
clear directoryCleanup
