%DEMO_SCIENTIFIC_STATE_PLANE_SHOOTING Solve descending-plane returns.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;
directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('round10OutputDirectory','var')||isempty(round10OutputDirectory)
    round10OutputDirectory=tempname(tempdir);
end
if exist(round10OutputDirectory,'dir')~=7
    [created,message]=mkdir(round10OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

registry=lmz.registry.ModelRegistry.discover();
specifications={ ...
    'slip_quadruped','descending_y_0_9'; ...
    'slip_biped','descending_y_0_95'};
cases=repmat(struct('ModelId','','SectionId','','SolveResult',[], ...
    'ResidualNorm',Inf,'DirectionalDerivative',NaN, ...
    'Qualification','','ArtifactPath',''),size(specifications,1),1);
context=lmz.api.RunContext.synchronous(1202);
for index=1:size(specifications,1)
    model=registry.createModel(specifications{index,1});
    configuration=struct('StartSectionId',specifications{index,2}, ...
        'StopSectionId',specifications{index,2}, ...
        'SymmetryId','planar_translation');
    problem=model.createProblem('periodic_orbit',configuration);
    seed=problem.makeSolution(problem.getDecisionSchema().defaults(), ...
        problem.getParameterSchema().defaults(),[]);
    solved=lmz.services.SolveService().solve(problem,seed,struct( ...
        'AcceptExistingTolerance',1e-10, ...
        'FunctionTolerance',1e-10,'StepTolerance',1e-10, ...
        'MaximumIterations',100),context);
    crossing=solved.Evaluation.Diagnostics.StopCrossing;
    if solved.ExitFlag<=0||solved.Evaluation.ScaledResidualNorm>1e-9|| ...
            ~solved.Evaluation.PhysicalValidity||~crossing.accepted|| ...
            crossing.grazing||crossing.directionalDerivative>=0
        error('lmz:Example:ScientificStatePlaneShooting', ...
            ['A descending-plane solve did not meet the root-found, ' ...
            'transversality, and physical validation criteria.']);
    end
    artifactPath=fullfile(round10OutputDirectory, ...
        [specifications{index,1} '_state_plane_shooting.lmz.mat']);
    lmz.io.ArtifactStore.save(artifactPath,solved.toArtifact());
    cases(index)=struct('ModelId',specifications{index,1}, ...
        'SectionId',specifications{index,2},'SolveResult',solved, ...
        'ResidualNorm',solved.Evaluation.ScaledResidualNorm, ...
        'DirectionalDerivative',crossing.directionalDerivative, ...
        'Qualification','root_found','ArtifactPath',artifactPath);
end
output=struct('Cases',cases, ...
    'Qualifications',{reshape({cases.Qualification},[],1)}, ...
    'DirectSectionIntegration',true, ...
    'GlobalInfeasibilityProven',false, ...
    'OutputDirectory',round10OutputDirectory, ...
    'SuccessMarker','LMZ_SCIENTIFIC_STATE_PLANE_SHOOTING_OK');
fprintf('%s qualifications=%s,%s residuals=[%.3g %.3g]\n', ...
    output.SuccessMarker,cases(1).Qualification,cases(2).Qualification, ...
    cases(1).ResidualNorm,cases(2).ResidualNorm);
clear directoryCleanup
