%DEMO_QUAD_LOAD_N_STRIDE_FIT Fit the repository-contained N-stride dataset.
projectRoot=fileparts(fileparts(mfilename('fullpath')));
originalDirectory=pwd;
directoryCleanup=onCleanup(@()cd(originalDirectory));
cd(projectRoot);startup;cd(originalDirectory);
if ~exist('round9OutputDirectory','var')||isempty(round9OutputDirectory)
    round9OutputDirectory=tempname(tempdir);
end
if exist(round9OutputDirectory,'dir')~=7
    [created,message]=mkdir(round9OutputDirectory);
    if ~created,error('lmz:Example:OutputDirectory','%s',message);end
end

registry=lmz.registry.ModelRegistry.discover();
model=registry.createModel('slip_quad_load');
catalog=lmzmodels.slip_quad_load.ScientificDatasetCatalog.default();
problem=model.createProblem('n_stride_fit',struct( ...
    'DatasetPath',catalog.defaultMultiPath(), ...
    'InitialPerturbation',0.03));
parameters=problem.getParameterSchema().defaults();
decision=problem.getDecisionSchema().defaults();
context=lmz.api.RunContext.synchronous(909);
[initialObjective,initialTerms,initialDiagnostics]= ...
    problem.evaluateObjective(decision,parameters,context);
[inequalities,equalities]=problem.nonlinearConstraints( ...
    decision,parameters,context);
seed=problem.makeSolution(decision,parameters,[]);
fitResult=lmz.services.OptimizationService().run(problem,seed,struct( ...
    'Algorithm','sqp','Display','off','MaxIterations',1, ...
    'MaxFunctionEvaluations',30,'OptimalityTolerance',1e-5, ...
    'StepTolerance',1e-5),context);
strideCount=initialDiagnostics.StrideCount;
if strideCount~=2||initialDiagnostics.HiddenTimingSolve|| ...
        initialDiagnostics.SourceEquivalent|| ...
        ~initialDiagnostics.ContactConstraintsExplicit|| ...
        ~isempty(inequalities)||numel(equalities)~=18|| ...
        ~isfinite(fitResult.Objective)|| ...
        fitResult.Objective>=initialObjective|| ...
        ~strcmp(initialDiagnostics.TimingSeedProvenance.Source, ...
        'repository_captured_fixed_timing_seed')
    error('lmz:Example:QuadLoadNStrideFit', ...
        'The fixed-schedule N-stride fit contract failed.');
end

extendedDecision=[problem.SourceDecision; ...
    problem.SourceDecision(end-12:end)];
extendedProblem=model.createProblem('n_stride_fit',struct( ...
    'DatasetPath',catalog.defaultMultiPath(), ...
    'InitialDecision',extendedDecision,'NumberOfStrides',3, ...
    'ReferenceExtensionPolicy','repeat_final_reference', ...
    'InitialPerturbation',0));
extendedParameters=extendedProblem.getParameterSchema().defaults();
[~,extendedEqualities]=extendedProblem.nonlinearConstraints( ...
    extendedProblem.getDecisionSchema().defaults(),extendedParameters,context);
if extendedProblem.getDecisionSchema().count()~=70|| ...
        numel(extendedEqualities)~=27
    error('lmz:Example:QuadLoadNStrideFit', ...
        'The explicit three-stride schema/constraint layout is incorrect.');
end
artifactPath=fullfile(round9OutputDirectory, ...
    'quad_load_n_stride_fit.lmz.mat');
lmz.io.ArtifactStore.save(artifactPath,fitResult.toArtifact());
output=struct('NumberOfStrides',strideCount, ...
    'InitialObjective',initialObjective,'InitialTerms',initialTerms, ...
    'FitResult',fitResult,'ObjectiveDecrease', ...
    initialObjective-fitResult.Objective, ...
    'ExplicitConstraintCount',numel(equalities), ...
    'InitialConstraintNorm',norm(equalities), ...
    'HiddenTimingSolve',initialDiagnostics.HiddenTimingSolve, ...
    'SourceEquivalent',initialDiagnostics.SourceEquivalent, ...
    'TimingSeedProvenance',initialDiagnostics.TimingSeedProvenance, ...
    'ExtendedSchemaDecisionCount',70, ...
    'ExtendedConstraintCount',numel(extendedEqualities), ...
    'ExtendedConstraintNorm',norm(extendedEqualities), ...
    'ExtendedReferencePolicy','repeat_final_reference', ...
    'ExtendedTimingFeasibilityClaimed',false, ...
    'Scope',['two-stride fixed captured timing seed is optimized; the ' ...
    'three-stride extension demonstrates schema/constraints only'], ...
    'ArtifactPath',artifactPath,'OutputDirectory',round9OutputDirectory, ...
    'SuccessMarker','LMZ_QUAD_LOAD_N_STRIDE_FIT_OK');
fprintf('%s strides=%d decrease=%.12g\n',output.SuccessMarker, ...
    output.NumberOfStrides,output.ObjectiveDecrease);
clear directoryCleanup
