classdef BipedSectionDecisionCodec < lmz.shooting.CyclicSectionDecisionCodec
    %BIPEDSECTIONDECISIONCODEC Target-section jerboa state/schedule chart.
    methods
        function obj=BipedSectionDecisionCodec(startSection,stopSection, ...
                localEventTimes,returnTime,seedState,sourceDecision)
            if nargin<6,sourceDecision=[];end
            names={'L_TD','L_LO','R_TD','R_LO'};
            obj@lmz.shooting.CyclicSectionDecisionCodec( ...
                'slip_biped', ...
                lmzmodels.slip_biped.PhysicalStateSchema.create(), ...
                startSection,stopSection,names,localEventTimes, ...
                returnTime,seedState,'SourceDecision',sourceDecision);
        end
    end
end
