classdef BipedSectionTransitionDecisionCodec < ...
        lmz.shooting.SectionTransitionDecisionCodec
    %BIPEDSECTIONTRANSITIONDECISIONCODEC Mixed jerboa section chart.
    methods
        function obj=BipedSectionTransitionDecisionCodec( ...
                startSection,stopSection,eventTimes,returnTime,seedState, ...
                sourceDecision,varargin)
            if nargin<6,sourceDecision=[];end
            names={'L_TD','L_LO','R_TD','R_LO'};
            obj@lmz.shooting.SectionTransitionDecisionCodec( ...
                'slip_biped', ...
                lmzmodels.slip_biped.PhysicalStateSchema.create(), ...
                startSection,stopSection,names,eventTimes,returnTime, ...
                seedState,'SourceDecision',sourceDecision,varargin{:});
        end
    end
end
