classdef ContactConstraintProvider < lmz.schedule.ContactConstraintProvider
    %CONTACTCONSTRAINTPROVIDER Exact biped contact/apex timing rows.
    properties (SetAccess=private)
        FixedConfiguration
    end
    methods
        function obj=ContactConstraintProvider(configuration)
            if nargin<1,configuration=struct();end
            obj.FixedConfiguration=struct('k_leg',fieldOr(configuration,'k_leg',20), ...
                'omega_swing',fieldOr(configuration,'omega_swing',6.5));
        end
        function value=eventNames(~),value={'L_TD','L_LO','R_TD','R_LO'};end
        function value=evaluate(obj,initialState,physicalParameters, ...
                schedule,context,includeSimulation)
            if nargin<6,includeSimulation=true;end
            state=initialState(:);if numel(state)==8,state=state(2:8);end
            if numel(state)~=7,error('lmz:Timing:BipedInitialState', ...
                    'Biped timing requires 7 local or 8 physical states.');end
            offsets=physicalParameters(:);
            lmzmodels.slip_biped.OffsetParameterSchema.create().validateVector(offsets);
            decision=[state;schedule.namedTimes(obj.eventNames());schedule.ReturnTime];
            raw=lmzmodels.slip_biped.LegacyBipedEvaluator().evaluate( ...
                decision,offsets,context,obj.FixedConfiguration);
            simulation=[];
            if includeSimulation
                observables=lmzmodels.slip_biped.ObservableProvider.compute( ...
                    raw.Time,raw.States,decision,raw,'');
                parameterStruct=lmzmodels.slip_biped.OffsetParameterSchema.create().unpack(offsets);
                parameterStruct.k_leg=obj.FixedConfiguration.k_leg;
                parameterStruct.omega_swing=obj.FixedConfiguration.omega_swing;
                interim=lmz.api.SimulationResult(raw.Time, ...
                    lmzmodels.slip_biped.PhysicalStateSchema.create(),raw.States, ...
                    raw.Modes,observables,parameterStruct, ...
                    struct('Evaluator','timing-only-biped-v1', ...
                    'HiddenEventTimeSolve',false,'Energy',raw.Energy), ...
                    struct('source','scientific-biped-timing'), ...
                    'EventRecords',raw.EventRecords, ...
                    'GroundReactionForces',raw.GroundReactionForces);
                simulation=lmz.api.SimulationResult(interim.Time,interim.StateSchema, ...
                    interim.States,interim.Modes,interim.Observables,interim.Parameters, ...
                    interim.Diagnostics,interim.Provenance, ...
                    'EventRecords',interim.EventRecords, ...
                    'GroundReactionForces',interim.GroundReactionForces, ...
                    'Kinematics',lmzmodels.slip_biped.KinematicsProvider.compute(interim));
            end
            crossing=lmz.schedule.ContactConstraintProvider.sectionCrossing( ...
                raw,'APEX',4,'post');
            value=struct('ContactResidual',raw.Residual(8:11), ...
                'SectionResidual',raw.Residual(15), ...
                'TerminalState',raw.States(end,:).', ...
                'SectionCrossing',crossing,'Simulation',simulation, ...
                'Diagnostics',struct('ModelId','slip_biped', ...
                'ResidualRows',[8:11 15],'PeriodicityRowsIncluded',false, ...
                'FixedConfiguration',obj.FixedConfiguration));
        end
    end
    methods (Static)
        function problem=createProblem(model,configuration)
            if nargin<2,configuration=struct();end
            decision=lmzmodels.slip_biped.PeriodicDecisionSchema.create().defaults();
            parameters=lmzmodels.slip_biped.OffsetParameterSchema.create().defaults();
            initial=decision(1:7);
            if isfield(configuration,'InitialState'),initial=configuration.InitialState(:);end
            if isfield(configuration,'PhysicalParameters'),parameters=configuration.PhysicalParameters(:);end
            provider=lmzmodels.slip_biped.ContactConstraintProvider(configuration);
            schedule=lmz.schedule.ContactConstraintProvider.scheduleFromConfiguration( ...
                provider.eventNames(),decision(8:11),decision(12),configuration);
            lmz.schedule.ContactConstraintProvider. ...
                assertSupportedApexSchedule(schedule,'slip_biped');
            problem=lmz.schedule.SectionReturnTimingProblem(model, ...
                'section_return_timing',provider,initial,parameters,schedule,configuration);
        end
    end
end

function value=fieldOr(source,name,fallback)
if isfield(source,name),value=source.(name);else,value=fallback;end
end
