classdef OffsetParameterSchema
    %OFFSETPARAMETERSCHEMA Results14 rows 13-14 as named parameters.
    methods (Static)
        function schema = create()
            schema = lmz.schema.VariableSchema([ ...
                lmz.schema.VariableSpec('offset_left', ...
                    'Label','Left swing equilibrium angle','Group','parameter', ...
                    'Unit','rad','DefaultValue',0,'Scale',0.2, ...
                    'Role','control','EnergyEffect','unknown'); ...
                lmz.schema.VariableSpec('offset_right', ...
                    'Label','Right swing equilibrium angle','Group','parameter', ...
                    'Unit','rad','DefaultValue',0,'Scale',0.2, ...
                    'Role','control','EnergyEffect','unknown')],'1.0.0');
        end
    end
end
