classdef PeriodicApexProblem < lmz.api.NonlinearEquationProblem
    %PERIODICAPEXPROBLEM Source-equivalent 15-by-12 jerboa problem.
    properties (SetAccess=private)
        Evaluator
        Feasibility
        Continuation
        FixedConfiguration
    end
    methods
        function obj=PeriodicApexProblem(model,configuration)
            if nargin<2,configuration=struct();end
            decision=lmzmodels.slip_biped.PeriodicDecisionSchema.create();
            parameters=lmzmodels.slip_biped.OffsetParameterSchema.create();
            obj@lmz.api.NonlinearEquationProblem(model,'periodic_apex', ...
                'nonlinear_equation',decision,parameters,parameters.defaults(),configuration);
            obj.Version='2.0.0';obj.Evaluator=lmzmodels.slip_biped.LegacyBipedEvaluator();
            obj.Feasibility=lmzmodels.slip_biped.FeasibilityPolicy();
            obj.Continuation=lmzmodels.slip_biped.ContinuationPolicy();
            obj.FixedConfiguration=struct('k_leg',20,'omega_swing',6.5);
        end
        function evaluation=evaluate(obj,u,p,context,includeSimulation)
            if nargin<5,includeSimulation=false;end
            context.check();obj.DecisionSchema.validateVector(u);obj.ParameterSchema.validateVector(p);
            raw=obj.Evaluator.evaluate(u,p,context,obj.FixedConfiguration);
            blocks=[ ...
                lmz.data.ResidualBlock('periodicity',raw.Residual(1:7),ones(7,1)); ...
                lmz.data.ResidualBlock('left_touchdown_ground',raw.Residual(8),1); ...
                lmz.data.ResidualBlock('right_touchdown_ground',raw.Residual(9),1); ...
                lmz.data.ResidualBlock('left_liftoff_ground',raw.Residual(10),1); ...
                lmz.data.ResidualBlock('right_liftoff_ground',raw.Residual(11),1); ...
                lmz.data.ResidualBlock('legacy_reserved_zero',raw.Residual(12),1); ...
                lmz.data.ResidualBlock('symmetry_left_touchdown_right_liftoff',raw.Residual(13),1); ...
                lmz.data.ResidualBlock('symmetry_right_touchdown_left_liftoff',raw.Residual(14),1); ...
                lmz.data.ResidualBlock('apex_vertical_velocity',raw.Residual(15),1)];
            feasibility=obj.Feasibility.assess(u,p,raw.Residual,raw.States);
            classification=lmzmodels.slip_biped.GaitClassifier.classify(u);
            observables=lmzmodels.slip_biped.ObservableProvider.compute(raw.Time,raw.States,u,raw,'');
            simulation=[];
            if includeSimulation
                parameterStruct=obj.ParameterSchema.unpack(p);
                parameterStruct.k_leg=obj.FixedConfiguration.k_leg;
                parameterStruct.omega_swing=obj.FixedConfiguration.omega_swing;
                diagnostics=struct('Evaluator','migrated-ZeroFunc_BipedApex_offset', ...
                    'DuplicateSamplesRemoved',raw.DuplicateSamplesRemoved, ...
                    'HiddenEventTimeSolve',false,'RawSampleCount',numel(raw.LegacyTime), ...
                    'Energy',raw.Energy);
                simulation=lmz.api.SimulationResult(raw.Time, ...
                    lmzmodels.slip_biped.PhysicalStateSchema.create(),raw.States, ...
                    raw.Modes,observables,parameterStruct,diagnostics, ...
                    struct('sourceRepository','DLARlab/2022_A_Template_Model_Explains_Jerboa_Gait_Transitions', ...
                    'sourceCommit','4595146c5881a5313bc8fe92de85099193ef9be9'), ...
                    'EventRecords',raw.EventRecords, ...
                    'GroundReactionForces',raw.GroundReactionForces);
                kinematics=lmzmodels.slip_biped.KinematicsProvider.compute(simulation);
                simulation=lmz.api.SimulationResult(simulation.Time,simulation.StateSchema, ...
                    simulation.States,simulation.Modes,simulation.Observables, ...
                    simulation.Parameters,simulation.Diagnostics,simulation.Provenance, ...
                    'EventRecords',simulation.EventRecords, ...
                    'GroundReactionForces',simulation.GroundReactionForces, ...
                    'Kinematics',kinematics);
            end
            diagnostics=struct('Formulation','source-equivalent-biped-v2', ...
                'LegacyEquivalent',true,'HiddenEventTimeSolve',false, ...
                'FixedConfiguration',obj.FixedConfiguration, ...
                'DuplicateSamplesRemoved',raw.DuplicateSamplesRemoved, ...
                'Energy',raw.Energy,'Classification',classification, ...
                'GaitName',classification.Name,'GaitAbbreviation',classification.Abbreviation);
            evaluation=lmz.data.ProblemEvaluation(blocks,'Simulation',simulation, ...
                'Feasibility',feasibility,'PhysicalValidity',feasibility.Valid, ...
                'Diagnostics',diagnostics);
        end
        function names=listObservables(~)
            names={'forward_speed','apex_forward_velocity','stride_period', ...
                'stride_length','duty_factors','event_phases','minimum_event_gap', ...
                'gait_code','gait_name','gait_abbreviation','total_energy', ...
                'vertical_grf','horizontal_grf','grf_magnitude'};
        end
        function solution=makeSolution(obj,u,p,evaluation)
            if nargin<3||isempty(p),p=obj.DefaultParameters;end
            if nargin<4||isempty(evaluation)
                blocks=lmz.data.ResidualBlock.empty(0,1);diagnostics=struct();
                feasibility=struct('Valid',true);observables=struct();
            else
                blocks=evaluation.ResidualBlocks;diagnostics=evaluation.Diagnostics;
                feasibility=evaluation.Feasibility;
                if isempty(evaluation.Simulation),observables=struct( ...
                        'gait_name',diagnostics.GaitName, ...
                        'gait_abbreviation',diagnostics.GaitAbbreviation); ...
                else,observables=evaluation.Simulation.Observables;end
            end
            classification=lmzmodels.slip_biped.GaitClassifier.classify(u);
            descriptor=obj.getDescriptor();
            value=struct('Id',lmz.util.Ids.new('solution'),'ModelId',descriptor.modelId, ...
                'ModelVersion',descriptor.modelVersion,'ProblemId',obj.Id, ...
                'ProblemVersion',obj.Version,'DecisionSchema',obj.DecisionSchema, ...
                'ParameterSchema',obj.ParameterSchema,'DecisionValues',u(:), ...
                'ParameterValues',p(:),'Observables',observables, ...
                'ResidualBlocks',blocks,'Diagnostics',diagnostics, ...
                'Classification',classification,'Feasibility',feasibility, ...
                'Lineage',struct(),'Provenance',struct( ...
                'source','scientific-biped-runtime', ...
                'sourceCommit','4595146c5881a5313bc8fe92de85099193ef9be9'), ...
                'CreatedAt',datestr(now,30));
            solution=lmz.data.Solution(value);
        end
    end
end
