classdef ResearchGroundGeometry
    %RESEARCHGROUNDGEOMETRY Source white mask and dense hatched ground.
    methods (Static)
        function geometry=compute()
            mask=lmzmodels.slip_biped.ResearchGroundGeometry.mask();
            hatch=lmzmodels.slip_biped.ResearchGroundGeometry.hatch();
            metadata=lmzmodels.slip_biped.ResearchGroundGeometry.provenance();
            metadata.layerOrder={'mask','hatch'};
            geometry=lmz.viz.LayeredGeometry('bipedGround',{mask,hatch},metadata);
        end

        function geometry=mask()
            vertices=[-20 0;100 0;100 -40;-20 -40];
            metadata=lmzmodels.slip_biped.ResearchGroundGeometry.provenance();
            metadata.styleKey='ground.mask';
            geometry=lmz.viz.PatchGeometry('groundMask',vertices,1:4,metadata);
        end

        function geometry=hatch()
            h=0.01;n=5000;s=0.05;w=0.01;extension=0.1;
            positions=-50+linspace(0,s*n,n).';
            vertices=[-50,0; ...
                positions,repmat(-h,n,1); ...
                positions-extension,repmat(-extension-h,n,1); ...
                positions-extension+w,repmat(-extension-h,n,1); ...
                positions+w,repmat(-h,n,1); ...
                -50+s*n+w,0];
            faces=zeros(n+1,4);
            faces(1,:)=[1,2,4*n+1,4*n+2];
            offsets=(1:n).';
            faces(2:end,:)=[offsets+1,n+offsets+1, ...
                2*n+offsets+1,3*n+offsets+1];
            metadata=lmzmodels.slip_biped.ResearchGroundGeometry.provenance();
            metadata.styleKey='ground.hatch';metadata.height=h;
            metadata.stripeCount=n;metadata.spacing=s;metadata.stripeWidth=w;
            metadata.stripeExtension=extension;
            geometry=lmz.viz.PatchGeometry('groundHatch',vertices,faces,metadata);
        end

        function value=summary()
            value=struct('maskVertexCount',4,'maskFaceCount',1, ...
                'hatchVertexCount',20002,'hatchFaceCount',5001, ...
                'xLimits',[-50.1 200.01],'yLimits',[-0.11 0], ...
                'topHeight',0.01, ...
                'stripeCount',5000,'spacing',0.05, ...
                'stripeWidth',0.01,'stripeExtension',0.1);
        end

        function value=provenance()
            value=struct( ...
                'sourceRepository','DLARlab/2022_A_Template_Model_Explains_Jerboa_Gait_Transitions', ...
                'sourceCommit','4595146c5881a5313bc8fe92de85099193ef9be9', ...
                'sourcePath','Stored_Functions/Graphics/SLIP_Model_Graphics_PointFeet_BipedalDemo.m', ...
                'sourceFunction','constructor_ground', ...
                'sourceLines','89-112', ...
                'adaptation',['Geometry is exact. The source did not explicitly set ground ', ...
                    'colors; the research style freezes its documented black intent instead ', ...
                    'of the MATLAB-release-dependent patch default.']);
        end
    end
end
