function fixture=capture_quad_load_graphics_baselines(sourceRoot,outputPath)
%CAPTURE_QUAD_LOAD_GRAPHICS_BASELINES Capture pinned load and rope geometry.
root=lmz.util.ProjectPaths.root();
if nargin<1||isempty(sourceRoot)
    sourceRoot=fullfile(fileparts(root), ...
        '2025_Gait_Transitions_in_Load_Pulling_Quadrupeds_Insights');
end
if nargin<2||isempty(outputPath)
    outputPath=fullfile(root,'tests','fixtures','graphics', ...
        'slip_quad_load','source_capture.json');
end
commit='19f3133073c988cc0c3424a647b4adbb60a90b99';verifySource(sourceRoot,commit);
graphicsRoot=fullfile(sourceRoot,'Stored_Functions','Graphics');
addpath(graphicsRoot);pathCleanup=onCleanup(@()rmpath(graphicsRoot));
state=zeros(18,1);state([1 3 5 7 9 11 13 15 17])= ...
    [1 1.2 .1 .2 -.15 .25 -.1 -.4 .8];
parameters=zeros(2,17);parameters(:,13)=1;parameters(:,15)=.4;
parameters(1,1:9)=[.1 .4 .2 .5 .6 .9 .7 .95 1];
parameters(2,1:9)=[.15 .45 .25 .55 .65 .92 .72 .97 1.1];
[loadX,loadY]=ComputeLoadGraphics(state);
fixture=struct('schemaVersion','1.0.0', ...
    'sourceRepository','2025_Gait_Transitions_in_Load_Pulling_Quadrupeds_Insights', ...
    'sourceCommit',commit,'state',state,'parameters',parameters, ...
    'load',struct('x',loadX,'y',loadY,'vertices',[loadX(:) loadY(:)]), ...
    'rope',struct('x',[state(1);state(1);state(15);state(15)], ...
    'y',[state(3);state(3);state(17);state(17)]), ...
    'strideEnds',cumsum(parameters(:,9)), ...
    'boundarySelection',struct('time',parameters(1,9),'selectedRow',2, ...
    'offset',parameters(1,9)), ...
    'camera',struct('xLimits',state(1)+[-3 1.5], ...
    'yLimits',[-.1 2],'plotBoxAspectRatio',[2 1 1]), ...
    'style',struct('faceColor',[0 0 0],'faceAlpha',.3, ...
    'edgeColor',[0 0 0],'lineWidth',2));
writeFixture(outputPath,fixture);clear pathCleanup
fprintf('LMZ_QUAD_LOAD_GRAPHICS_BASELINE_OK path=%s\n',outputPath);
end

function verifySource(root,expected)
[status,head]=system(sprintf('git -C "%s" rev-parse HEAD',root));
if status~=0||~strcmp(strtrim(head),expected),error('lmz:GraphicsCapture:Commit', ...
        'Load source commit mismatch.');end
[status,worktree]=system(sprintf('git -C "%s" status --porcelain',root));
if status~=0||~isempty(strtrim(worktree)),error('lmz:GraphicsCapture:DirtySource', ...
        'Load source must be clean.');end
end
function writeFixture(path,value)
folder=fileparts(path);if exist(folder,'dir')~=7,mkdir(folder);end
temporary=lmz.compat.Files.temporary(folder,'.json');cleanup=onCleanup(@()deleteFile(temporary));
file=fopen(temporary,'w');if file<0,error('lmz:GraphicsCapture:Write','Cannot write fixture.');end
fileCleanup=onCleanup(@()fclose(file));fprintf(file,'%s',lmz.compat.Json.encode(value,true));
clear fileCleanup;lmz.compat.Files.atomicMove(temporary,path);clear cleanup
end
function deleteFile(path),if exist(path,'file')==2,delete(path);end,end
