function baselinePath=capture_slip_biped_source_baselines(sourceRoot)
%CAPTURE_SLIP_BIPED_SOURCE_BASELINES Run only against immutable upstream.
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
addpath(fullfile(root,'src'));
if nargin<1
    sourceRoot=fullfile(fileparts(root), ...
        '2022_A_Template_Model_Explains_Jerboa_Gait_Transitions');
end
sourceCommit='4595146c5881a5313bc8fe92de85099193ef9be9';
storedFunctions=fullfile(sourceRoot,'Stored_Functions');
if exist(storedFunctions,'dir')~=7
    error('lmz:Baseline:MissingSource','Immutable biped source checkout is missing.');
end
[status,head]=system(sprintf('git -C "%s" rev-parse HEAD',sourceRoot));
if status~=0||~strcmp(strtrim(head),sourceCommit)
    error('lmz:Baseline:SourceCommit','Biped source checkout is not at the recorded commit.');
end
[status,origin]=system(sprintf('git -C "%s" remote get-url origin',sourceRoot));
if status~=0||~strcmp(strtrim(origin), ...
        'https://github.com/DLARlab/2022_A_Template_Model_Explains_Jerboa_Gait_Transitions.git')
    error('lmz:Baseline:SourceOrigin','Biped source checkout has an unexpected origin.');
end
[status,sourceStatus]=system(sprintf('git -C "%s" status --porcelain',sourceRoot));
if status~=0||~isempty(strtrim(sourceStatus))
    error('lmz:Baseline:SourceDirty','Biped source checkout must be clean before capture.');
end
addpath(storedFunctions,'-begin');cleanup=onCleanup(@()rmpath(storedFunctions));
names={'W1','R1','HP1','SK1','SK2','AR1'};columns=[30 30 50 30 30 50];
gaitLabels={'walking','running','hopping','skipping','skipping','asymmetric running'};
sourceHashes={'52a6243833851ab9e498b0eb60e5489ab78747a3f9ff05c9be02d5c66e61d6dc', ...
    'd8f891a0a6da9d3a99a6e202aac1d725a53e47714aed3cf998bdd14b05b2cfd0', ...
    '9003caa634b68401b1b0b91b4fef50515d41088a3685cd52db84cd0dfc3adf3e', ...
    '8898f7d209cefc8f80b700701d5a9331201cedaf2ed205af001272b934712c55', ...
    'bb17a9799ec8f407295b40a0d799f64ad793a1a90faedbc571e875b26a617eb7', ...
    'a39312da6db1f7119b7ccd941b6d4c7ac8e7251fb7700431a58b6ec5544df5fa'};
entries=repmat(struct('SourceFile','','SourceSHA256','','ColumnIndex',0,'GaitLabel','', ...
    'Decision',zeros(12,1),'Offsets',zeros(2,1),'Residual',zeros(15,1), ...
    'ResidualNorm',0,'Time',[],'States',[],'Parameters',[], ...
    'EventStates',[],'Energy',0,'GaitCode',0),1,numel(names));
for index=1:numel(names)
    sourceFile=[names{index} '.mat'];
    path=fullfile(sourceRoot,'Section2_solution_examples',sourceFile);
    if ~strcmpi(lmz.util.FileHash.sha256(path),sourceHashes{index})
        error('lmz:Baseline:SourceHash','Source hash changed for %s.',sourceFile);
    end
    loaded=load(path,'results');decision=loaded.results(1:12,columns(index));
    offsets=loaded.results(13:14,columns(index));
    [residual,time,states,parameters,eventStates,energy]= ...
        ZeroFunc_BipedApex_offset(decision,offsets);
    entries(index)=struct('SourceFile',sourceFile,'SourceSHA256',sourceHashes{index}, ...
        'ColumnIndex',columns(index), ...
        'GaitLabel',gaitLabels{index},'Decision',decision,'Offsets',offsets, ...
        'Residual',residual,'ResidualNorm',norm(residual),'Time',time, ...
        'States',states,'Parameters',parameters,'EventStates',eventStates, ...
        'Energy',energy,'GaitCode',Gaitidentify(decision));
end

options=optimset('Algorithm','levenberg-marquardt','Display','off', ...
    'MaxFunEvals',500,'MaxIter',100,'TolFun',1e-13,'TolX',1e-12);
[solvedDecision,~,solveExitFlag,solveOutput]=fsolve( ...
    @(candidate)ZeroFunc_BipedApex_offset(candidate,entries(1).Offsets), ...
    entries(1).Decision,options);
[solvedResidual,solvedTime,solvedStates,solvedParameters, ...
    solvedEventStates,solvedEnergy]=ZeroFunc_BipedApex_offset( ...
    solvedDecision,entries(1).Offsets);
sourceSolve=struct('SourceFile','W1.mat','ColumnIndex',30, ...
    'InitialDecision',entries(1).Decision,'Offsets',entries(1).Offsets, ...
    'Decision',solvedDecision,'Residual',solvedResidual, ...
    'Time',solvedTime,'States',solvedStates,'Parameters',solvedParameters, ...
    'EventStates',solvedEventStates,'Energy',solvedEnergy, ...
    'ExitFlag',solveExitFlag,'Output',solveOutput);

experimentPath=fullfile(sourceRoot,'Section3_optimization','exp_1802_j30.mat');
seedPath=fullfile(sourceRoot,'Section3_optimization','sim_1802_j30.mat');
if ~strcmpi(lmz.util.FileHash.sha256(experimentPath), ...
        '4b16bfc041cc386e9768d035716a0dedb1ff38b7fb7efe70fbf749ce3c5596cc') || ...
        ~strcmpi(lmz.util.FileHash.sha256(seedPath), ...
        '303aeca45c7717d5745f1c0e436442d2b083edb9162ecbfc69277b1abfe35e23')
    error('lmz:Baseline:FitSourceHash','Biped trajectory-fit source hash changed.');
end
experiment=load(experimentPath);seed=load(seedPath,'X');X=seed.X(:);
[fitResidual,fitTime,fitStates,fitParameters,fitEventStates,fitEnergy]= ...
    ZeroFunc_BipedApex_offset_optimization(X);
[fitX,fitY,fitAlphaL,fitAlphaR]=ZFBA_resample2(fitTime,fitStates,experiment.To);
norms=struct('position',norm(fitX'-experiment.ob_data(:,1)), ...
    'height',norm(fitY'-experiment.ob_data(:,3)), ...
    'leftAngle',norm(fitAlphaL'-experiment.ob_data(:,5)), ...
    'rightAngle',norm(fitAlphaR'-experiment.ob_data(:,7)), ...
    'residual',norm(fitResidual), ...
    'eventTiming',norm([experiment.footsequence experiment.To(end)]-X(8:12)));
terms=struct('position',5*norms.position,'height',50*norms.height, ...
    'leftAngle',20*norms.leftAngle,'rightAngle',20*norms.rightAngle, ...
    'residual',100*norms.residual,'eventTiming',100*norms.eventTiming);
constrainedTerms=struct('position',5*norms.position,'height',50*norms.height, ...
    'leftAngle',10*norms.leftAngle,'rightAngle',10*norms.rightAngle, ...
    'residual',0,'eventTiming',0);
trajectoryFit=struct('Dataset','exp_1802_j30.mat','SeedFile','sim_1802_j30.mat', ...
    'DatasetSHA256','4b16bfc041cc386e9768d035716a0dedb1ff38b7fb7efe70fbf749ce3c5596cc', ...
    'SeedSHA256','303aeca45c7717d5745f1c0e436442d2b083edb9162ecbfc69277b1abfe35e23', ...
    'Decision',X,'Residual',fitResidual,'ConstraintResidual',fitResidual, ...
    'Objective',sum(cell2mat(struct2cell(terms))),'ObjectiveTerms',terms, ...
    'ConstrainedObjective',sum(cell2mat(struct2cell(constrainedTerms))), ...
    'ConstrainedObjectiveTerms',constrainedTerms, ...
    'UnweightedNorms',norms,'Time',fitTime,'States',fitStates, ...
    'Parameters',fitParameters,'EventStates',fitEventStates,'Energy',fitEnergy, ...
    'Resampled',struct('time',experiment.To(:),'x',fitX(:),'y',fitY(:), ...
    'alphaL',fitAlphaL(:),'alphaR',fitAlphaR(:)));

baseline=struct('SchemaVersion','1.0.0','SourceRepository', ...
    'https://github.com/DLARlab/2022_A_Template_Model_Explains_Jerboa_Gait_Transitions.git', ...
    'SourceCommit',sourceCommit,'CapturedWith',version,'Entries',entries, ...
    'SourceSolve',sourceSolve,'TrajectoryFit',trajectoryFit, ...
    'Tolerances',struct('ResidualAbsolute',5e-11,'TimeAbsolute',5e-12, ...
    'StateAbsolute',5e-10,'StateRelative',5e-10,'EventAbsolute',5e-10, ...
    'ObjectiveAbsolute',1e-9,'ResampledAbsolute',5e-10));
baselinePath=fullfile(root,'tests','fixtures','baselines','slip_biped', ...
    'source_equivalence.mat');
save(baselinePath,'baseline','-v7');clear cleanup
end
