function baselinePath = capture_slip_quadruped_source_baselines(sourceRoot)
%CAPTURE_SLIP_QUADRUPED_SOURCE_BASELINES Run only against immutable upstream.
root=fileparts(fileparts(fileparts(mfilename('fullpath'))));
if nargin<1,sourceRoot=fullfile(fileparts(root),'SLIP_Model_Zoo');end
sourceCommit='2c106101383ecee1b2a9d695efe09fbd72d5718a';
dynamics=fullfile(sourceRoot,'SLIP_Quadruped','1_Dynamic_Frameworks','v2');
management=fullfile(sourceRoot,'SLIP_Quadruped','4_Solution_Management');
if exist(dynamics,'dir')~=7||exist(management,'dir')~=7,error('lmz:Baseline:MissingSource','Immutable source checkout is missing.');end
addpath(dynamics,'-begin');addpath(management,'-begin');cleanup=onCleanup(@()removeSourcePaths(dynamics,management));
dataPath=fullfile(root,'examples','data','slip_quadruped','RoadMap','PK_20_2.mat');
loaded=load(dataPath,'results');columns=[1 267 446];entries=repmat(struct( ...
    'ColumnIndex',0,'Decision',zeros(22,1),'Parameters',zeros(7,1), ...
    'Residual',zeros(22,1),'Time',[],'States',[],'LegacyParameters',[], ...
    'GroundReactionForces',[],'EventStates',[],'GaitName','','GaitAbbreviation',''),1,numel(columns));
for index=1:numel(columns)
    column=columns(index);decision=loaded.results(1:22,column);parameters=loaded.results(23:29,column);
    [residual,time,states,p,grf,eventStates]=Quadrupedal_ZeroFun_v2( ...
        decision(1:13),decision(14:22),parameters,{},'skipSolve');
    [gait,abbr]=Gait_Identification(decision);
    entries(index)=struct('ColumnIndex',column,'Decision',decision,'Parameters',parameters, ...
        'Residual',residual,'Time',time,'States',states,'LegacyParameters',p, ...
        'GroundReactionForces',grf,'EventStates',eventStates, ...
        'GaitName',char(gait),'GaitAbbreviation',char(abbr));
end
baseline=struct('SchemaVersion','1.0.0','SourceRepository', ...
    'https://github.com/DLARlab/SLIP_Model_Zoo.git','SourceCommit',sourceCommit, ...
    'SourceFile','PK_20_2.mat','SourceSHA256', ...
    '45835bb5024b1dc9b875c7b8f7b205769f537a4ff4144c763058537f44dbf401', ...
    'CapturedWith',version,'Columns',columns,'Entries',entries, ...
    'Tolerances',struct('ResidualAbsolute',1e-11,'TimeAbsolute',1e-13, ...
    'StateAbsolute',1e-10,'StateRelative',1e-9,'GRFAbsolute',1e-9,'GRFRelative',1e-8));
baselinePath=fullfile(root,'tests','fixtures','slip_quadruped_roadmap_baseline.mat');
save(baselinePath,'baseline');clear cleanup
end

function removeSourcePaths(dynamics,management),rmpath(dynamics);rmpath(management);end
