classdef HorizonContinuation
    %HORIZONCONTINUATION Explicit N-to-N+1 embedding and checkpoint records.
    methods
        function [embedded,record]=embedDecision(~,oldSchema,oldDecision,newSchema)
            if isa(oldSchema,'lmz.shooting.ShootingDecisionSchema')
                oldSchema=oldSchema.VariableSchema;
            end
            if isa(newSchema,'lmz.shooting.ShootingDecisionSchema')
                newSchema=newSchema.VariableSchema;
            end
            if ~isa(oldSchema,'lmz.schema.VariableSchema')|| ...
                    ~isa(newSchema,'lmz.schema.VariableSchema')
                error('lmz:Shooting:HorizonEmbeddingSchema', ...
                    'Horizon embedding requires variable schemas.');
            end
            oldSchema.validateVector(oldDecision);
            embedded=newSchema.defaults();oldNames=oldSchema.names();
            newNames=newSchema.names();mapped={};
            for index=1:numel(oldNames)
                target=find(strcmp(oldNames{index},newNames),1);
                if ~isempty(target)
                    embedded(target)=oldDecision(index);
                    mapped{end+1,1}=oldNames{index}; %#ok<AGROW>
                end
            end
            newSchema.validateVector(embedded);
            record=struct('Kind','name_bound_horizon_embedding-v1', ...
                'OldDimension',oldSchema.count(), ...
                'NewDimension',newSchema.count(),'MappedNames',{mapped}, ...
                'AddedNames',{setdiff(newNames,oldNames,'stable')}, ...
                'RemovedNames',{setdiff(oldNames,newNames,'stable')});
        end

        function checkpoint=checkpoint(~,problem,decision,history,status)
            if ~isa(problem,'lmz.shooting.MultipleShootingProblem')
                error('lmz:Shooting:HorizonCheckpointProblem', ...
                    'Checkpoint requires a MultipleShootingProblem.');
            end
            problem.getDecisionSchema().validateVector(decision);
            contract=problem.contract();
            lmz.io.ArtifactStore.dataHash(history);
            lmz.io.ArtifactStore.dataHash(status);
            checkpoint=struct('SchemaVersion','1.0.0', ...
                'FrameworkVersion',lmz.util.Version.current(), ...
                'SegmentCount',problem.Horizon.segmentCount(), ...
                'Decision',decision(:),'ProblemContract',contract, ...
                'ProblemContractHash', ...
                lmz.io.ArtifactStore.dataHash(contract), ...
                'History',{history},'Status',status, ...
                'CreatedAt',lmz.compat.Timestamp.current());
        end

        function [decision,history]=resume(~,checkpoint,problem)
            required={'SchemaVersion','FrameworkVersion','SegmentCount', ...
                'Decision','ProblemContract','ProblemContractHash', ...
                'History','Status'};
            if ~isstruct(checkpoint)||~isscalar(checkpoint)|| ...
                    ~all(isfield(checkpoint,required))|| ...
                    ~strcmp(checkpoint.SchemaVersion,'1.0.0')|| ...
                    ~isa(problem,'lmz.shooting.MultipleShootingProblem')
                error('lmz:Shooting:HorizonCheckpoint', ...
                    'Horizon continuation checkpoint is invalid.');
            end
            try
                lmz.io.ArtifactStore.dataHash(checkpoint);
            catch
                error('lmz:Shooting:HorizonCheckpoint', ...
                    'Horizon continuation checkpoint must be inert plain data.');
            end
            if checkpoint.SegmentCount~=problem.Horizon.segmentCount()
                error('lmz:Shooting:HorizonCheckpointDimension', ...
                    'Checkpoint segment dimension does not match the problem.');
            end
            validateFramework(checkpoint.FrameworkVersion, ...
                'lmz:Shooting:HorizonCheckpointFramework');
            validateProblemContract(checkpoint,problem, ...
                'lmz:Shooting:HorizonCheckpointProblemContract');
            problem.getDecisionSchema().validateVector(checkpoint.Decision);
            decision=checkpoint.Decision(:);history=checkpoint.History;
        end

        function result=traceHomotopy(~,problem,anchor,options,context)
            %TRACEHOMOTOPY Adaptively introduce the full horizon residual.
            if nargin<4||isempty(options),options=struct();end
            if nargin<5||isempty(context)
                context=lmz.api.RunContext.synchronous(0);
            end
            if ~isa(problem,'lmz.shooting.MultipleShootingProblem')
                error('lmz:Shooting:HorizonHomotopyProblem', ...
                    'Adaptive horizon homotopy requires a shooting problem.');
            end
            problem.getDecisionSchema().validateVector(anchor);
            parameters=problem.getParameterSchema().defaults();
            initial=problem.evaluate(anchor,parameters,context,false);
            m=numel(initial.ScaledResidual);n=numel(anchor);
            if m<n
                error('lmz:Shooting:HomotopyGaugeRequired', ...
                    ['Adaptive point homotopy requires explicit gauges when ' ...
                    'the full horizon has fewer rows than unknowns.']);
            end
            step=positiveOption(options,'HomotopyInitialStep',0.25);
            minimum=positiveOption(options,'HomotopyMinimumStep',0.01);
            maximum=positiveOption(options,'HomotopyMaximumStep',0.5);
            growth=positiveOption(options,'HomotopyStepGrowth',1.5);
            reduction=positiveOption(options,'HomotopyStepReduction',0.5);
            if minimum>maximum||step<minimum||step>maximum||growth<=1|| ...
                    reduction>=1
                error('lmz:Shooting:HomotopyStepPolicy', ...
                    'Adaptive homotopy step policy is inconsistent.');
            end
            maxAttempts=positiveInteger(options,'HomotopyMaximumAttempts',50);
            tolerance=positiveOption(options,'ResidualTolerance',1e-7);
            solverOptions=removeFields(options,{ ...
                'HomotopyInitialStep','HomotopyMinimumStep', ...
                'HomotopyMaximumStep','HomotopyStepGrowth', ...
                'HomotopyStepReduction','HomotopyMaximumAttempts', ...
                'ResumeCheckpoint'});
            resumeCheckpoint=fieldOr(options,'ResumeCheckpoint',[]);
            if isempty(resumeCheckpoint)
                lambda=0;decision=anchor(:);attempts=cell(0,1);
                residualNorm=0;
                checkpoints={homotopyCheckpoint(problem,anchor,lambda, ...
                    decision,step,attempts,'anchor',residualNorm)};
            else
                [lambda,decision,step,attempts,residualNorm]= ...
                    resumeHomotopyCheckpoint( ...
                    resumeCheckpoint,problem,anchor);
                if step<minimum||step>maximum
                    error('lmz:Shooting:HomotopyStepPolicy', ...
                        ['Checkpoint next step lies outside the configured ' ...
                        'homotopy step interval.']);
                end
                checkpoints={resumeCheckpoint};
            end
            termination='lambda_one_reached';
            while numel(attempts)<maxAttempts
                if lambda>=1,break,end
                attempt=numel(attempts)+1;
                target=min(1,lambda+step);
                wrapped=lmz.shooting.HorizonHomotopyProblem( ...
                    problem,anchor,target,m);
                accepted=false;exceptionRecord=struct();rank=struct();
                exitFlag=NaN;maximumResidual=Inf;candidate=decision;
                try
                    [solved,rank]=lmz.solvers. ...
                        RankAwareNonlinearSolver().solve(wrapped,decision, ...
                        parameters,solverOptions,context);
                    candidate=solved.Solution.DecisionValues;
                    evaluated=wrapped.evaluate(candidate,parameters, ...
                        context,false);
                    maximumResidual=maxOrZero(abs( ...
                        evaluated.ScaledResidual));
                    exitFlag=solved.ExitFlag;
                    accepted=exitFlag>0&&isfinite(maximumResidual)&& ...
                        maximumResidual<=tolerance;
                catch exception
                    exceptionRecord=struct('Identifier', ...
                        exception.identifier,'Message',exception.message);
                end
                record=struct('Attempt',attempt,'FromLambda',lambda, ...
                    'TargetLambda',target,'Step',step, ...
                    'Accepted',accepted,'ExitFlag',exitFlag, ...
                    'MaximumScaledResidual',maximumResidual, ...
                    'Rank',fieldOr(rank,'Rank',NaN), ...
                    'Nullity',fieldOr(rank,'Nullity',NaN), ...
                    'ConditionEstimate',fieldOr(rank, ...
                    'ConditionEstimate',Inf), ...
                    'TerminationReason',fieldOr(rank, ...
                    'TerminationReason','solver_exception'), ...
                    'Exception',exceptionRecord);
                attempts{end+1,1}=record; %#ok<AGROW>
                if accepted
                    lambda=target;decision=candidate;
                    residualNorm=maximumResidual;
                    step=min(maximum,step*growth);
                    checkpoints{end+1,1}=homotopyCheckpoint( ...
                        problem,anchor,lambda,decision,step,attempts, ...
                        'accepted',residualNorm); %#ok<AGROW>
                else
                    step=step*reduction;
                    checkpoints{end}=homotopyCheckpoint( ...
                        problem,anchor,lambda,decision,step,attempts, ...
                        checkpointStatus(lambda),residualNorm);
                    if step<minimum
                        termination='minimum_step_reached';
                        break
                    end
                end
                context.progress(lambda,sprintf( ...
                    'Horizon homotopy lambda %.6g',lambda));
            end
            completed=lambda>=1;
            if ~completed&&strcmp(termination,'lambda_one_reached')
                termination='maximum_attempts_reached';
            end
            result=struct('Completed',completed,'Lambda',lambda, ...
                'Decision',decision,'Attempts',{attempts}, ...
                'Checkpoints',{checkpoints},'TerminationReason',termination, ...
                'Adaptive',true,'ResidualDimension',m, ...
                'DecisionDimension',n);
        end
    end
end

function checkpoint=homotopyCheckpoint(problem,anchor,lambda,decision, ...
        nextStep,attempts,status,residualNorm)
contract=problem.contract();
checkpoint=struct('SchemaVersion','1.0.0', ...
    'Kind','horizon-homotopy-checkpoint-v1', ...
    'FrameworkVersion',lmz.util.Version.current(), ...
    'ProblemContract',contract,'ProblemContractHash', ...
    lmz.io.ArtifactStore.dataHash(contract), ...
    'AnchorHash',lmz.io.ArtifactStore.dataHash(anchor(:)), ...
    'Lambda',lambda,'Decision',decision(:),'NextStep',nextStep, ...
    'AttemptCount',numel(attempts),'Attempts',{attempts}, ...
    'Status',status,'ResidualNorm',residualNorm, ...
    'CreatedAt',lmz.compat.Timestamp.current());
end

function [lambda,decision,nextStep,attempts,residualNorm]= ...
        resumeHomotopyCheckpoint(checkpoint,problem,anchor)
required={'SchemaVersion','Kind','FrameworkVersion','ProblemContract', ...
    'ProblemContractHash','AnchorHash','Lambda','Decision','NextStep', ...
    'AttemptCount','Attempts','Status','ResidualNorm'};
if ~isstruct(checkpoint)||~isscalar(checkpoint)|| ...
        ~all(isfield(checkpoint,required))|| ...
        ~strcmp(checkpoint.SchemaVersion,'1.0.0')|| ...
        ~strcmp(checkpoint.Kind,'horizon-homotopy-checkpoint-v1')
    error('lmz:Shooting:HorizonHomotopyCheckpoint', ...
        'Adaptive horizon-homotopy checkpoint is invalid.');
end
try
    lmz.io.ArtifactStore.dataHash(checkpoint);
catch
    error('lmz:Shooting:HorizonHomotopyCheckpoint', ...
        'Adaptive checkpoint must contain inert plain data only.');
end
validateFramework(checkpoint.FrameworkVersion, ...
    'lmz:Shooting:HorizonHomotopyCheckpointFramework');
validateProblemContract(checkpoint,problem, ...
    'lmz:Shooting:HorizonHomotopyCheckpointProblemContract');
expectedAnchor=lmz.io.ArtifactStore.dataHash(anchor(:));
if ~ischar(checkpoint.AnchorHash)|| ...
        ~strcmp(checkpoint.AnchorHash,expectedAnchor)
    error('lmz:Shooting:HorizonHomotopyCheckpointAnchor', ...
        'Adaptive checkpoint belongs to a different homotopy anchor.');
end
lambda=checkpoint.Lambda;decision=checkpoint.Decision(:);
nextStep=checkpoint.NextStep;attempts=checkpoint.Attempts;
residualNorm=checkpoint.ResidualNorm;
if ~isnumeric(lambda)||~isscalar(lambda)||~isfinite(lambda)|| ...
        lambda<0||lambda>1||~isnumeric(nextStep)|| ...
        ~isscalar(nextStep)||~isfinite(nextStep)||nextStep<=0|| ...
        ~iscell(attempts)||checkpoint.AttemptCount~=numel(attempts)|| ...
        ~isnumeric(residualNorm)||~isscalar(residualNorm)|| ...
        ~isfinite(residualNorm)||residualNorm<0
    error('lmz:Shooting:HorizonHomotopyCheckpoint', ...
        'Adaptive horizon-homotopy checkpoint state is invalid.');
end
problem.getDecisionSchema().validateVector(decision);
end

function validateFramework(recorded,errorId)
if ~ischar(recorded)
    error(errorId,'Checkpoint framework version is invalid.');
end
try
    compatible=lmz.util.Version.isCompatible( ...
        lmz.util.Version.current(),recorded);
catch
    compatible=false;
end
if ~compatible
    error(errorId, ...
        'Checkpoint framework %s is incompatible with %s.', ...
        recorded,lmz.util.Version.current());
end
end

function validateProblemContract(checkpoint,problem,errorId)
recordedHash=lmz.io.ArtifactStore.dataHash(checkpoint.ProblemContract);
if isfield(checkpoint,'ProblemContractHash')&& ...
        (~ischar(checkpoint.ProblemContractHash)|| ...
        ~strcmp(checkpoint.ProblemContractHash,recordedHash))
    error(errorId,'Checkpoint problem-contract hash is invalid.');
end
currentHash=lmz.io.ArtifactStore.dataHash(problem.contract());
if ~strcmp(recordedHash,currentHash)
    error(errorId, ...
        'Checkpoint belongs to a different shooting problem contract.');
end
end

function value=checkpointStatus(lambda)
if lambda==0,value='anchor';else,value='accepted';end
end

function value=positiveOption(options,name,fallback)
value=fieldOr(options,name,fallback);
if ~isnumeric(value)||~isscalar(value)||~isfinite(value)||value<=0
    error('lmz:Shooting:HomotopyOption', ...
        '%s must be finite and positive.',name);
end
end

function value=positiveInteger(options,name,fallback)
value=positiveOption(options,name,fallback);
if value~=fix(value)
    error('lmz:Shooting:HomotopyOption','%s must be an integer.',name);
end
end

function value=removeFields(value,names)
for index=1:numel(names)
    if isfield(value,names{index}),value=rmfield(value,names{index});end
end
end

function value=fieldOr(source,name,fallback)
if isstruct(source)&&isfield(source,name),value=source.(name); ...
else,value=fallback;end
end

function value=maxOrZero(source)
if isempty(source),value=0;else,value=max(source);end
end
