classdef InterfaceDefect
    %INTERFACEDEFECT Named mismatch between propagated and node coordinates.
    properties (SetAccess=private)
        InterfaceIndex
        CoordinateNames
        Values
        Scale
    end
    methods
        function obj=InterfaceDefect(index,terminal,target,names,scale)
            if nargin<5||isempty(scale),scale=ones(numel(terminal),1);end
            if nargin<4||isempty(names)
                names=arrayfun(@(item)sprintf('coordinate_%d',item), ...
                    (1:numel(terminal)).','UniformOutput',false);
            end
            if ~isnumeric(index)||~isscalar(index)||index<1||index~=fix(index)|| ...
                    ~isnumeric(terminal)||~isnumeric(target)|| ...
                    numel(terminal)~=numel(target)|| ...
                    any(~isfinite([terminal(:);target(:)]))|| ...
                    ~iscell(names)||numel(names)~=numel(terminal)|| ...
                    ~isnumeric(scale)||numel(scale)~=numel(terminal)|| ...
                    any(~isfinite(scale(:)))||any(scale(:)<=0)
                error('lmz:Shooting:InterfaceDefect', ...
                    'Interface-defect inputs are invalid.');
            end
            obj.InterfaceIndex=index;obj.CoordinateNames=reshape(names,[],1);
            obj.Values=terminal(:)-target(:);obj.Scale=scale(:);
        end
        function value=norm(obj),value=norm(obj.Values./obj.Scale);end
        function value=toResidualBlock(obj)
            value=lmz.data.ResidualBlock( ...
                sprintf('interface_%d_defect',obj.InterfaceIndex), ...
                obj.Values,obj.Scale);
        end
        function value=toStruct(obj)
            value=struct('InterfaceIndex',obj.InterfaceIndex, ...
                'CoordinateNames',{obj.CoordinateNames}, ...
                'Values',obj.Values,'Scale',obj.Scale, ...
                'ScaledNorm',obj.norm());
        end
    end
end
