classdef ScientificSectionTransitionFactory
    %SCIENTIFICSECTIONTRANSITIONFACTORY Direct mixed-section shooting route.
    %   Source-periodic data initialize a chart once.  Every problem
    %   evaluation thereafter starts from the decision-owned start state and
    %   integrates the model equations directly to the requested stop chart.
    methods (Static)
        function problem=create(model,configuration)
            if nargin<2,configuration=struct();end
            if ~isa(model,'lmz.api.LeggedModel')|| ...
                    ~isstruct(configuration)||~isscalar(configuration)
                error('lmz:Shooting:ScientificTransitionInput', ...
                    'A scientific model and scalar configuration are required.');
            end
            profile=localProfile(model.getManifest().id);
            registry=lmz.registry.ModelRegistry.discover();
            catalog=registry.getPoincareSectionRegistry(profile.ModelId);
            startId=fieldOr(configuration,'StartSectionId', ...
                profile.DefaultStartSectionId);
            stopId=fieldOr(configuration,'StopSectionId', ...
                profile.DefaultStopSectionId);
            if strcmp(startId,stopId)
                error('lmz:Shooting:TransitionDistinctSections', ...
                    ['section_transition requires distinct endpoint IDs. ' ...
                    'Use periodic_orbit or multiple_shooting for closure.']);
            end
            physical=model.getPhysicalStateSchema();
            startSection=localConfiguredSection(catalog.section(startId), ...
                configuration,'Start',physical);
            stopSection=localConfiguredSection(catalog.section(stopId), ...
                configuration,'Stop',physical);
            localValidateSection(startSection);localValidateSection(stopSection);
            if isfield(configuration,'TransitionSeed')
                seed=localValidateStoredSeed(configuration.TransitionSeed, ...
                    profile,physical);
            else
                seed=localSeed(model,catalog,startSection,stopSection, ...
                    configuration,profile);
            end
            codec=localCodec(profile,startSection,stopSection,seed);
            adapter=localAdapter(profile,codec,configuration);
            if isfield(configuration,'Horizon')
                horizon=configuration.Horizon;
                if isstruct(horizon)
                    horizon=lmz.shooting.ShootingHorizon.fromStruct(horizon);
                end
                if ~isa(horizon,'lmz.shooting.ShootingHorizon')|| ...
                        ~strcmp(horizon.ModelId,profile.ModelId)|| ...
                        ~strcmp(horizon.Formulation,'transition')
                    error('lmz:Shooting:ScientificTransitionHorizon', ...
                        'Stored transition horizon is incompatible.');
                end
            else
                [horizon,seed]=localHorizon(catalog,codec,adapter, ...
                    seed,configuration,profile);
            end
            if isfield(configuration,'ShootingDecisionSchema')
                shootingSchema=configuration.ShootingDecisionSchema;
                if isstruct(shootingSchema)
                    shootingSchema=lmz.shooting.ShootingDecisionSchema. ...
                        fromStruct(shootingSchema);
                end
            else
                shootingSchema=lmz.shooting.ShootingDecisionSchema. ...
                    fromHorizon(horizon);
            end
            stored=configuration;
            removable={'Horizon','ShootingDecisionSchema'};
            for index=1:numel(removable)
                if isfield(stored,removable{index})
                    stored=rmfield(stored,removable{index});
                end
            end
            stored.ProblemId='section_transition';
            stored.Formulation='transition';
            stored.StartSectionId=startSection.Id;
            stored.StopSectionId=stopSection.Id;
            stored.TargetSectionCoordinates= ...
                horizon.Target.SectionCoordinates(:);
            stored.TransitionSeed=seed;
            stored.DirectSectionIntegration=true;
            stored.PeriodicClosure=false;
            stored.MixedSectionTransition=true;
            stored.ExpectedLocalDimension=0;
            parameters=model.getParameterSchema();
            problem=lmz.shooting.TransitionMultipleShootingProblem( ...
                model,shootingSchema,parameters,seed.ParameterValues(:), ...
                horizon,adapter,stored);
        end
    end
end

function seed=localSeed(model,catalog,startSection,stopSection, ...
        configuration,profile)
context=lmz.api.RunContext.synchronous(0);
sourceConfiguration=struct();
if strcmp(profile.ModelId,'slip_biped')
    sourceConfiguration.FixedConfiguration=fieldOr(configuration, ...
        'FixedConfiguration',profile.FixedConfiguration);
end
source=model.createProblem('periodic_apex',sourceConfiguration);
decision=fieldOr(configuration,'SourceDecisionValues', ...
    source.getDecisionSchema().defaults());
parameters=fieldOr(configuration,'SourceParameterValues', ...
    source.getParameterSchema().defaults());
source.getDecisionSchema().validateVector(decision);
source.getParameterSchema().validateVector(parameters);
evaluation=source.evaluate(decision,parameters,context,true);
symmetry=catalog.symmetryFor(startSection.Id);
[simulation,startCrossing]=lmz.services.SectionTransferService. ...
    rephaseSimulationToSection(evaluation.Simulation,startSection,symmetry);
stopCrossing=localLocateCrossing(stopSection,simulation);
names=profile.EventNames;
[eventTimes,interior,active]=localBoundarySchedule( ...
    simulation,stopCrossing.Time,names,startSection,stopSection,profile);
seed=struct('SchemaVersion','1.0.0','ModelId',profile.ModelId, ...
    'StartSectionId',startSection.Id,'StopSectionId',stopSection.Id, ...
    'InitialState',simulation.States(1,:).', ...
    'TerminalState',stopCrossing.State(:), ...
    'EventNames',{names(:)},'EventTimes',eventTimes(:), ...
    'ReturnTime',stopCrossing.Time, ...
    'InteriorEventNames',{interior(:)}, ...
    'ActiveContactNames',{active(:)}, ...
    'SourceDecisionValues',decision(:), ...
    'ParameterValues',parameters(:), ...
    'StartCrossing',startCrossing.toStruct(), ...
    'StopCrossing',stopCrossing.toStruct(), ...
    'InitializationOnlySourceOrbit',true, ...
    'ResidualEvaluationUsesSourceOrbit',false);
end

function [horizon,seed]=localHorizon(catalog,codec,adapter,seed, ...
        configuration,profile)
schedule=codec.templateSchedule();
free=localEventMask(configuration,schedule.count());
schedule=schedule.withFixedMask(~free(1:end-1),~free(end));
startMask=localStateMask(configuration,'StartStateFreeMask', ...
    codec.StateCoordinates.count(),true);
stopMask=localStateMask(configuration,'TargetStateFreeMask', ...
    codec.StopStateCoordinates.count(),true);
symmetry=catalog.symmetryFor(codec.StopSection.Id);
startNode=lmz.shooting.ShootingNode( ...
    'SectionId',codec.StartSection.Id, ...
    'SectionHash',codec.StartSection.Descriptor.fingerprint(), ...
    'StateSide',codec.StartSection.StateSide, ...
    'StateSchema',codec.StateCoordinates,'FullState',seed.InitialState, ...
    'WorldTranslation',seed.InitialState(1), ...
    'FreeCoordinateMask',startMask, ...
    'Symmetry',struct('Id',symmetry.Id), ...
    'Lineage',struct('Source','mixed-section-transition-seed', ...
    'InitializationOnlySourceOrbit',true));
temporary=codec.decodeSegment(seed.InitialState,schedule);
propagated=adapter.simulateSegment(struct('DecodedDecision',temporary, ...
    'PhysicalParameters',seed.ParameterValues,'Configuration',struct(), ...
    'Segment',[],'StartNode',startNode,'StopNode',[], ...
    'EventSchedule',schedule,'ControlParameters',[]), ...
    lmz.api.RunContext.synchronous(0),false);
if localStatePlane(codec.StopSection)&& ...
        (~propagated.Crossing.Accepted||norm(propagated.SectionResidual)>1e-9)
    [schedule,propagated]=localRefinePlaneReturn( ...
        adapter,codec,startNode,schedule,seed.ParameterValues);
end
if ~propagated.Crossing.Accepted||propagated.Crossing.Grazing
    error('lmz:Shooting:ScientificTransitionSeedCrossing', ...
        ['The direct mixed-section seed does not terminate at an accepted ' ...
        'transverse stop crossing (%s, direction %d, derivative %.16g).'], ...
        propagated.Crossing.RejectionReason, ...
        propagated.Crossing.CrossingDirection, ...
        propagated.Crossing.DirectionalDerivative);
end
target=fieldOr(configuration,'TargetSectionCoordinates', ...
    propagated.TerminalCoordinates(:));
if ~isnumeric(target)||numel(target)~=codec.StopStateCoordinates.count()|| ...
        any(~isfinite(target(:)))
    error('lmz:Shooting:ScientificTransitionTarget', ...
        'TargetSectionCoordinates do not match the stop-section chart.');
end
stopState=codec.StopStateCoordinates.embed( ...
    propagated.TerminalState,target(:));
stopNode=lmz.shooting.ShootingNode( ...
    'SectionId',codec.StopSection.Id, ...
    'SectionHash',codec.StopSection.Descriptor.fingerprint(), ...
    'StateSide',codec.StopSection.StateSide, ...
    'StateSchema',codec.StopStateCoordinates,'FullState',stopState, ...
    'WorldTranslation',propagated.TerminalState(1), ...
    'FreeCoordinateMask',stopMask,'Symmetry',struct('Id',symmetry.Id), ...
    'Lineage',struct('Source','explicit-transition-target', ...
    'PeriodicClosure',false));
energy=struct('Mode','diagnostic_only','DeclaredWork',0,'Tolerance',1e-9);
segment=lmz.shooting.ShootingSegment('Index',1, ...
    'StartNode',startNode,'StopNode',stopNode,'EventSchedule',schedule, ...
    'ContactConstraints',codec.ActiveContactNames, ...
    'PhysicalParameters',struct('ProblemValues',seed.ParameterValues(:)), ...
    'ControlParameters',struct(),'EnergyWorkSpecification',energy, ...
    'SimulationOptions',struct('Termination','accepted_stop_section'), ...
    'SourceLineage',struct('Source','direct-mixed-section-integration', ...
    'ApexOracleUsedDuringResidualEvaluation',false));
targetRecord=struct('SectionId',codec.StopSection.Id, ...
    'SectionHash',codec.StopSection.Descriptor.fingerprint(), ...
    'SectionCoordinates',target(:),'FullState',stopState(:), ...
    'StateSide',codec.StopSection.StateSide, ...
    'ResidualName','final_transition_target', ...
    'PeriodicClosure',false);
horizon=lmz.shooting.ShootingHorizon('ModelId',profile.ModelId, ...
    'ProblemId','section_transition','Nodes',{startNode;stopNode}, ...
    'Segments',{segment},'Formulation','transition','Target',targetRecord, ...
    'Lineage',struct('Source','scientific-section-transition-v1', ...
    'StartSectionId',codec.StartSection.Id, ...
    'StopSectionId',codec.StopSection.Id, ...
    'DirectSectionIntegration',true,'PeriodicClosure',false));
seed.ReturnTime=schedule.ReturnTime;
seed.EventTimes=codec.decodeSegment(seed.InitialState,schedule).EventTimes;
seed.TerminalState=propagated.TerminalState(:);
seed.DirectStopCrossing=propagated.Crossing.toStruct();
seed.DirectSectionResidualNorm=norm(propagated.SectionResidual);
seed.DirectContactResidualNorm=norm(propagated.ContactResiduals);
end

function [schedule,propagated]=localRefinePlaneReturn( ...
        adapter,codec,startNode,schedule,parameters)
times=schedule.times();base=schedule.ReturnTime;
lower=max([base*(1-1e-3),maxOrZero(times)+1e-9, ...
    codec.StopSection.MinimumReturnTime]);
upper=base*(1+1e-3);
fun=@(time)localPlaneValue(adapter,codec,startNode, ...
    schedule.withTimes(times,time),parameters);
f0=fun(lower);f1=fun(upper);
attempt=0;
while sign(f0)==sign(f1)&&attempt<8
    attempt=attempt+1;
    width=(2^attempt)*1e-3*max(1,base);
    lower=max([base-width,maxOrZero(times)+1e-9, ...
        codec.StopSection.MinimumReturnTime]);
    upper=base+width;f0=fun(lower);f1=fun(upper);
end
if sign(f0)==sign(f1)
    error('lmz:Shooting:ScientificTransitionPlaneBracket', ...
        'Unable to bracket the direct stop-plane crossing.');
end
root=fzero(fun,[lower upper]);
schedule=schedule.withTimes(times,root);
decoded=codec.decodeSegment(startNode.FullState,schedule);
propagated=adapter.simulateSegment(struct('DecodedDecision',decoded, ...
    'PhysicalParameters',parameters,'Configuration',struct(), ...
    'Segment',[],'StartNode',startNode,'StopNode',[], ...
    'EventSchedule',schedule,'ControlParameters',[]), ...
    lmz.api.RunContext.synchronous(0),false);
end

function value=localPlaneValue(adapter,codec,startNode,schedule,parameters)
decoded=codec.decodeSegment(startNode.FullState,schedule);
result=adapter.simulateSegment(struct('DecodedDecision',decoded, ...
    'PhysicalParameters',parameters,'Configuration',struct(), ...
    'Segment',[],'StartNode',startNode,'StopNode',[], ...
    'EventSchedule',schedule,'ControlParameters',[]), ...
    lmz.api.RunContext.synchronous(0),false);
value=result.SectionResidual(1);
end

function crossing=localLocateCrossing(section,simulation)
primary=localPrimary(section);
if isa(primary,'lmz.poincare.NamedEventSection')
    records=simulation.EventRecords;
    [~,order]=sortrows([[records.Time].',(1:numel(records)).'],[1 2]);
    records=records(order);history={};occurrence=0;crossing=[];
    for index=1:numel(records)
        record=records(index);
        if record.Time<=section.MinimumReturnTime
            history{end+1}=record.Name; %#ok<AGROW>
            continue
        end
        if section.matches(record)
            occurrence=occurrence+1;
            candidate=section.crossingFromRecord(record, ...
                'Occurrence',occurrence,'EventHistory',history);
            if candidate.Accepted,crossing=candidate;break,end
        end
        history{end+1}=record.Name; %#ok<AGROW>
    end
    if isempty(crossing)&&any(arrayfun(@(item) ...
            section.matches(item)&& ...
            item.Time<=section.MinimumReturnTime,records))
        state=simulation.States(end,:);
        endpoint=struct('Name',primary.Descriptor.EventId, ...
            'Time',simulation.Time(end),'State',state, ...
            'PreState',state,'PostState',state, ...
            'DirectionalDerivative',NaN,'Direction',section.CrossingDirection);
        candidate=section.crossingFromRecord(endpoint, ...
            'Occurrence',1,'EventHistory',{records.Name});
        if candidate.Accepted,crossing=candidate;end
    end
else
    crossing=[];occurrence=0;
    for index=1:numel(simulation.Time)-1
        if simulation.Time(index+1)<=section.MinimumReturnTime,continue,end
        history=localEventsBefore( ...
            simulation.EventRecords,simulation.Time(index));
        [detected,candidate]=section.detectCrossing( ...
            simulation.Time(index),simulation.States(index,:).', ...
            simulation.Time(index+1),simulation.States(index+1,:).', ...
            'Occurrence',occurrence+1,'EventHistory',history);
        if detected
            occurrence=occurrence+1;
            if candidate.Accepted,crossing=candidate;break,end
        end
    end
end
if isempty(crossing)
    error('lmz:Shooting:ScientificTransitionCrossingNotFound', ...
        'No accepted initialization crossing was found for %s.',section.Id);
end
end

function [eventTimes,interior,active]=localBoundarySchedule( ...
        simulation,returnTime,names,startSection,stopSection,profile)
names=reshape(names,[],1);
tolerance=1e-9*max(1,simulation.Time(end));
recordTimes=nan(numel(names),1);
for index=1:numel(names)
    matches=find(strcmp(names{index},{simulation.EventRecords.Name}));
    if ~isempty(matches)
        candidates=[simulation.EventRecords(matches).Time].';
        candidates=candidates(candidates>=-tolerance);
        if ~isempty(candidates),recordTimes(index)=min(candidates);end
    end
end
startEvent=localEventId(startSection);stopEvent=localEventId(stopSection);
known=false(numel(names),1);eventTimes=zeros(numel(names),1);
for index=1:numel(names)
    if strcmp(names{index},startEvent)
        eventTimes(index)=0;known(index)=true;
    elseif strcmp(names{index},stopEvent)
        eventTimes(index)=returnTime;known(index)=true;
    elseif isfinite(recordTimes(index))&& ...
            recordTimes(index)>tolerance&& ...
            recordTimes(index)<returnTime-tolerance
        eventTimes(index)=recordTimes(index);known(index)=true;
    end
end
contacts=localInitialContacts(simulation,profile);
for pairIndex=1:size(profile.EventPairs,1)
    td=profile.EventPairs(pairIndex,1);lo=profile.EventPairs(pairIndex,2);
    if known(td)&&~known(lo)
        eventTimes(lo)=returnTime;
    elseif ~known(td)&&known(lo)
        eventTimes(td)=0;
    elseif ~known(td)&&~known(lo)
        if contacts(pairIndex)
            eventTimes(td)=0;eventTimes(lo)=returnTime;
        else
            eventTimes(td)=returnTime;eventTimes(lo)=returnTime;
        end
    end
end
interior=names(known&eventTimes>tolerance& ...
    eventTimes<returnTime-tolerance);
active=interior;
if any(strcmp(startEvent,names)),active{end+1,1}=startEvent;end
if any(strcmp(stopEvent,names)),active{end+1,1}=stopEvent;end
active=unique(active,'stable');
end

function value=localInitialContacts(simulation,profile)
value=false(size(profile.EventPairs,1),1);modes=simulation.Modes;
for index=1:numel(profile.ModeNames)
    name=profile.ModeNames{index};
    if isstruct(modes)&&isfield(modes,name)
        item=modes.(name);value(index)=logical(item(1));
    end
end
end

function value=localEventsBefore(records,time)
value={};
for index=1:numel(records)
    if records(index).Time<time,value{end+1}=records(index).Name;end %#ok<AGROW>
end
end

function codec=localCodec(profile,startSection,stopSection,seed)
codecArgs={startSection,stopSection,seed.EventTimes,seed.ReturnTime, ...
    seed.InitialState,seed.SourceDecisionValues, ...
    'InteriorEventNames',seed.InteriorEventNames, ...
    'ActiveContactNames',seed.ActiveContactNames};
switch profile.ModelId
    case 'slip_quadruped'
        codec=lmzmodels.slip_quadruped. ...
            QuadrupedSectionTransitionDecisionCodec(codecArgs{:});
    case 'slip_biped'
        codec=lmzmodels.slip_biped. ...
            BipedSectionTransitionDecisionCodec(codecArgs{:});
end
end

function adapter=localAdapter(profile,codec,configuration)
if strcmp(profile.ModelId,'slip_quadruped')
    adapter=lmzmodels.slip_quadruped. ...
        QuadrupedSectionSimulationAdapter(codec);
else
    fixed=fieldOr(configuration,'FixedConfiguration', ...
        profile.FixedConfiguration);
    adapter=lmzmodels.slip_biped.BipedSectionSimulationAdapter( ...
        codec,'FixedConfiguration',fixed);
end
end

function section=localConfiguredSection(section,configuration,prefix,schema)
value=section.toStruct();
fields={'StateSide','CrossingDirection','MinimumReturnTime', ...
    'RequiredEventSequence','ReturnOccurrence'};
targets={'stateSide','crossingDirection','minimumReturnTime', ...
    'requiredEventSequence','returnOccurrence'};
for index=1:numel(fields)
    name=[prefix fields{index}];
    if isfield(configuration,name)
        value.(targets{index})=configuration.(name);
    elseif strcmp(prefix,'Stop')&&isfield(configuration,fields{index})
        value.(targets{index})=configuration.(fields{index});
    end
end
descriptor=lmz.poincare.PoincareSectionDescriptor(value);
if strcmp(descriptor.Kind,'named_event')
    section=lmz.poincare.NamedEventSection(descriptor);
elseif strcmp(descriptor.Kind,'state_plane')
    section=lmz.poincare.StateFunctionSection(descriptor,schema);
elseif isa(section,'lmz.poincare.CompositeSection')
    section=lmz.poincare.CompositeSection( ...
        descriptor,section.Primary,section.Conditions);
end
end

function localValidateSection(section)
primary=localPrimary(section);
if ~isa(primary,'lmz.poincare.NamedEventSection')&& ...
        ~isa(primary,'lmz.poincare.StateFunctionSection')
    error('lmz:Shooting:ScientificTransitionSectionKind', ...
        'Transition endpoints require named-event or state-plane primaries.');
end
end

function value=localStateMask(configuration,name,count,fallback)
source=fieldOr(configuration,name,fallback);
if ~(islogical(source)||(isnumeric(source)&&isreal(source)&& ...
        all(ismember(source(:),[0 1]))))
    error('lmz:Shooting:ScientificTransitionStateMask', ...
        '%s must be a logical mask.',name);
end
source=logical(source(:));
if isscalar(source),value=repmat(source,count,1); ...
elseif numel(source)==count,value=source;else
    error('lmz:Shooting:ScientificTransitionStateMask', ...
        '%s does not match the section-coordinate count.',name);
end
end

function value=localEventMask(configuration,count)
source=fieldOr(configuration,'EventFreeMask',false(count+1,1));
if ~(islogical(source)||(isnumeric(source)&&isreal(source)&& ...
        all(ismember(source(:),[0 1]))))
    error('lmz:Shooting:ScientificTransitionEventMask', ...
        'EventFreeMask must be logical.');
end
source=logical(source(:));
if isscalar(source),value=repmat(source,count+1,1); ...
elseif numel(source)==2,value=[repmat(source(1),count,1);source(2)]; ...
elseif numel(source)==count+1,value=source;else
    error('lmz:Shooting:ScientificTransitionEventMask', ...
        'EventFreeMask does not match the transition schedule.');
end
end

function seed=localValidateStoredSeed(seed,profile,physical)
required={'ModelId','StartSectionId','StopSectionId','InitialState', ...
    'TerminalState','EventNames','EventTimes','ReturnTime', ...
    'InteriorEventNames','ActiveContactNames','SourceDecisionValues', ...
    'ParameterValues'};
if ~isstruct(seed)||~isscalar(seed)||~all(isfield(seed,required))|| ...
        ~strcmp(seed.ModelId,profile.ModelId)|| ...
        ~isequal(reshape(seed.EventNames,[],1),reshape(profile.EventNames,[],1))
    error('lmz:Shooting:ScientificTransitionStoredSeed', ...
        'Stored transition seed metadata are incompatible.');
end
physical.validateVector(seed.InitialState);
physical.validateVector(seed.TerminalState);
seed.EventTimes=seed.EventTimes(:);seed.ParameterValues=seed.ParameterValues(:);
seed.SourceDecisionValues=seed.SourceDecisionValues(:);
end

function value=localStatePlane(section)
value=isa(localPrimary(section),'lmz.poincare.StateFunctionSection');
end

function value=localEventId(section)
primary=localPrimary(section);value='';
if isa(primary,'lmz.poincare.NamedEventSection')
    value=primary.Descriptor.EventId;
end
end

function value=localPrimary(section)
if isa(section,'lmz.poincare.CompositeSection'),value=section.Primary; ...
else,value=section;end
end

function value=localProfile(modelId)
switch modelId
    case 'slip_quadruped'
        value=struct('ModelId',modelId, ...
            'DefaultStartSectionId','back_left_touchdown', ...
            'DefaultStopSectionId','descending_y_0_9', ...
            'EventNames',{{'BL_TD','BL_LO','FL_TD','FL_LO', ...
            'BR_TD','BR_LO','FR_TD','FR_LO'}}, ...
            'EventPairs',[1 2;3 4;5 6;7 8], ...
            'ModeNames',{{'back_left','front_left', ...
            'back_right','front_right'}},'FixedConfiguration',struct());
    case 'slip_biped'
        value=struct('ModelId',modelId, ...
            'DefaultStartSectionId','left_touchdown', ...
            'DefaultStopSectionId','descending_y_0_95', ...
            'EventNames',{{'L_TD','L_LO','R_TD','R_LO'}}, ...
            'EventPairs',[1 2;3 4],'ModeNames',{{'left','right'}}, ...
            'FixedConfiguration',struct('k_leg',20,'omega_swing',6.5));
    otherwise
        error('lmz:Shooting:ScientificTransitionModel', ...
            'Scientific section transitions are unavailable for %s.',modelId);
end
end

function value=maxOrZero(source)
if isempty(source),value=0;else,value=max(source);end
end

function value=fieldOr(source,name,fallback)
if isstruct(source)&&isfield(source,name),value=source.(name); ...
else,value=fallback;end
end
