classdef ShootingResult
    %SHOOTINGRESULT Multiple-shooting solve, feasibility, and lineage record.
    properties (SetAccess=private)
        SolveResult
        Horizon
        FeasibilityReport
        SegmentResults
        InitializerHistory
        ContinuationHistory
        Checkpoints
        Diagnostics
    end
    methods
        function obj=ShootingResult(solveResult,horizon,report,varargin)
            if ~isa(solveResult,'lmz.data.SolveResult')|| ...
                    ~isa(horizon,'lmz.shooting.ShootingHorizon')|| ...
                    ~isa(report,'lmz.shooting.FeasibilityReport')
                error('lmz:Shooting:ResultContract', ...
                    'ShootingResult inputs are invalid.');
            end
            parser=inputParser;
            addParameter(parser,'SegmentResults',{},@iscell);
            addParameter(parser,'InitializerHistory',{},@iscell);
            addParameter(parser,'ContinuationHistory',{},@iscell);
            addParameter(parser,'Checkpoints',{},@iscell);
            addParameter(parser,'Diagnostics',struct(),@isstruct);
            parse(parser,varargin{:});value=parser.Results;
            obj.SolveResult=solveResult;obj.Horizon=horizon;
            obj.FeasibilityReport=report;
            obj.SegmentResults=value.SegmentResults;
            obj.InitializerHistory=value.InitializerHistory;
            obj.ContinuationHistory=value.ContinuationHistory;
            obj.Checkpoints=value.Checkpoints;obj.Diagnostics=value.Diagnostics;
        end

        function value=toStruct(obj)
            segments=cell(numel(obj.SegmentResults),1);
            for index=1:numel(segments)
                segments{index}=plain(obj.SegmentResults{index});
            end
            value=struct('Solution',obj.SolveResult.Solution.toStruct(), ...
                'ExitFlag',obj.SolveResult.ExitFlag, ...
                'Output',plain(obj.SolveResult.Output), ...
                'Options',plain(obj.SolveResult.Options), ...
                'SourceSeed',plain(obj.SolveResult.SourceSeed), ...
                'RandomSeed',obj.SolveResult.RandomSeed, ...
                'Provenance',plain(obj.SolveResult.Provenance), ...
                'Horizon',obj.Horizon.toStruct(), ...
                'FeasibilityReport',obj.FeasibilityReport.toStruct(), ...
                'SegmentResults',{segments}, ...
                'InitializerHistory',{plain(obj.InitializerHistory)}, ...
                'ContinuationHistory',{plain(obj.ContinuationHistory)}, ...
                'Checkpoints',{plain(obj.Checkpoints)}, ...
                'Diagnostics',plain(obj.Diagnostics));
        end

        function artifact=toArtifact(obj)
            solution=obj.SolveResult.Solution;
            artifact=solution.toArtifact();
            artifact.artifactType='multiple-shooting-run';
            contract=obj.Diagnostics.ProblemContract;
            artifact.shootingResult=obj.toStruct();
            artifact.shootingHorizon=obj.Horizon.toStruct();
            artifact.shootingProblemContract=plain(contract);
            artifact.feasibilityReport=obj.FeasibilityReport.toStruct();
            artifact.shootingHorizonHash=lmz.io.ArtifactStore.dataHash( ...
                artifact.shootingHorizon);
            artifact.shootingProblemContractHash= ...
                lmz.io.ArtifactStore.dataHash(artifact.shootingProblemContract);
            configuration=artifact.shootingProblemContract.Configuration;
            artifact.problemConfigurationHash= ...
                lmz.io.ArtifactStore.dataHash(configuration);
            artifact.diagnostics=struct('ExitFlag',obj.SolveResult.ExitFlag, ...
                'Classification',obj.FeasibilityReport.Classification, ...
                'Success',obj.FeasibilityReport.Success, ...
                'Rank',obj.FeasibilityReport.JacobianRank, ...
                'Nullity',obj.FeasibilityReport.Nullity, ...
                'SingularValues',obj.FeasibilityReport.SingularValues, ...
                'ConditionEstimate',obj.FeasibilityReport.ConditionEstimate, ...
                'FirstOrderOptimality', ...
                obj.FeasibilityReport.FirstOrderOptimality, ...
                'ScaledResidualNorm',obj.FeasibilityReport.ScaledResidualNorm, ...
                'SolverMode',fieldOr(obj.SolveResult.Output, ...
                'SolverSelected','unknown'));
            artifact.lineage=struct('InitializerHistory', ...
                {plain(obj.InitializerHistory)},'ContinuationHistory', ...
                {plain(obj.ContinuationHistory)},'Checkpoints', ...
                {plain(obj.Checkpoints)});
            sourceHashes=fieldOr(configuration,'SourceDataHashes',struct());
            if ~isstruct(sourceHashes)||~isscalar(sourceHashes)
                error('lmz:Shooting:SourceDataHashes', ...
                    'Shooting source-data hashes must be a scalar struct.');
            end
            sourceHashes.ProblemConfiguration= ...
                artifact.problemConfigurationHash;
            details=struct('Options',plain(obj.SolveResult.Options), ...
                'SourceSeed',plain(obj.SolveResult.SourceSeed), ...
                'RandomSeed',obj.SolveResult.RandomSeed, ...
                'Provenance',plain(obj.SolveResult.Provenance), ...
                'ElapsedTime',numericField(obj.SolveResult.Provenance, ...
                'elapsedTime',NaN),'FunctionEvaluations', ...
                numericField(obj.SolveResult.Provenance,'evaluations', ...
                numericField(obj.SolveResult.Output,'funcCount',NaN)), ...
                'TerminationReason',termination(obj.SolveResult.ExitFlag, ...
                obj.FeasibilityReport),'Warnings',{{}}, ...
                'SourceDataHashes',plain(sourceHashes));
            artifact=lmz.io.ArtifactStore.withRunMetadata(artifact,details);
            artifact.problemMetadata.configuration=configuration;
        end
    end

    methods (Static)
        function obj=fromArtifact(artifact)
            lmz.io.ArtifactStore.validate(artifact);
            if ~strcmp(artifact.artifactType,'multiple-shooting-run')
                error('lmz:Shooting:ArtifactType', ...
                    'Artifact is not a multiple-shooting run.');
            end
            record=artifact.shootingResult;
            solution=lmz.data.Solution.fromStruct(record.Solution);
            feasibility=solution.Feasibility;
            physical=true;
            if isstruct(feasibility)&&isfield(feasibility,'Valid')
                physical=logical(feasibility.Valid);
            end
            evaluation=lmz.data.ProblemEvaluation( ...
                solution.ResidualBlocks,'Feasibility',feasibility, ...
                'PhysicalValidity',physical, ...
                'Diagnostics',solution.Diagnostics);
            source=record.SourceSeed;
            if isstruct(source)&&isfield(source,'DecisionSchema')
                source=lmz.data.Solution.fromStruct(source);
            end
            solved=lmz.data.SolveResult(solution,evaluation, ...
                record.ExitFlag,record.Output,record.Options,source, ...
                record.RandomSeed,record.Provenance);
            horizon=lmz.shooting.ShootingHorizon.fromStruct(record.Horizon);
            report=lmz.shooting.FeasibilityReport( ...
                record.FeasibilityReport);
            obj=lmz.shooting.ShootingResult(solved,horizon,report, ...
                'SegmentResults',record.SegmentResults, ...
                'InitializerHistory',record.InitializerHistory, ...
                'ContinuationHistory',record.ContinuationHistory, ...
                'Checkpoints',record.Checkpoints, ...
                'Diagnostics',record.Diagnostics);
        end
    end
end

function value=plain(source)
if isa(source,'function_handle')
    error('lmz:Shooting:ExecutableArtifactData', ...
        'Shooting artifacts cannot contain function handles.');
elseif isobject(source)
    if ~ismethod(source,'toStruct')
        error('lmz:Shooting:ExecutableArtifactData', ...
            'Shooting artifacts require plain serializable data.');
    end
    value=plain(source.toStruct());
elseif isstruct(source)
    value=source;names=fieldnames(source);
    for item=1:numel(source)
        for index=1:numel(names)
            value(item).(names{index})=plain(source(item).(names{index}));
        end
    end
elseif iscell(source)
    value=cell(size(source));
    for index=1:numel(source),value{index}=plain(source{index});end
else
    value=source;
end
end
function value=fieldOr(source,name,fallback)
if isstruct(source)&&isfield(source,name),value=source.(name);else,value=fallback;end
end
function value=numericField(source,name,fallback)
value=fallback;
if isstruct(source)&&isfield(source,name)&&isnumeric(source.(name))&& ...
        isscalar(source.(name))
    value=source.(name);
end
end
function value=termination(exitFlag,report)
if report.Success
    value='converged';
elseif any(strcmp(report.Classification,{'best_known_residual', ...
        'local_infeasibility_evidence','numerical_failure', ...
        'physical_validation_failure'}))
    value=report.Classification;
elseif exitFlag==0
    value='iteration-or-evaluation-limit';
else
    value='solver-failure';
end
end
