classdef HorizonContinuationService
    %HORIZONCONTINUATIONSERVICE Solve an explicit sequence of horizon sizes.
    methods
        function result=run(~,model,problemId,configurations,seed, ...
                options,context)
            if nargin<6,options=struct();end
            if nargin<7,context=lmz.api.RunContext.synchronous(0);end
            if ~isa(model,'lmz.api.LeggedModel')||~ischar(problemId)
                error('lmz:Services:HorizonContinuationModel', ...
                    'Horizon continuation requires a model and problem ID.');
            end
            if isstruct(configurations)
                configurations=num2cell(configurations);
            end
            if ~iscell(configurations)||isempty(configurations)|| ...
                    ~all(cellfun(@(item)isstruct(item)&&isscalar(item), ...
                    configurations))
                error('lmz:Services:HorizonContinuationProtocol', ...
                    'Configurations must be a nonempty plain record list.');
            end
            assertPlain(configurations,'configurations');
            solverOptions=fieldOr(options,'SolverOptions',struct());
            continueOnFailure=logical(fieldOr(options, ...
                'ContinueOnQualifiedFailure',false));
            useHomotopy=logical(fieldOr(options, ...
                'UseAdaptiveHomotopy',true));
            history=cell(numel(configurations),1);
            checkpoints=cell(0,1);
            previousSchema=[];previousDecision=[];
            final=[];
            for index=1:numel(configurations)
                context.check();configuration=configurations{index};
                problem=model.createProblem(problemId,configuration);
                if ~isa(problem,'lmz.shooting.MultipleShootingProblem')
                    error('lmz:Services:HorizonContinuationProblem', ...
                        'Every protocol step must create a shooting problem.');
                end
                if index==1
                    candidate=seed;
                    if isa(candidate,'lmz.data.Solution')
                        candidate=candidate.DecisionValues;
                    end
                    embedding=struct('Kind','initial_seed', ...
                        'OldDimension',numel(candidate), ...
                        'NewDimension',numel(candidate),'MappedNames',{{}}, ...
                        'AddedNames',{{}},'RemovedNames',{{}});
                else
                    [candidate,embedding]= ...
                        lmz.shooting.HorizonContinuation().embedDecision( ...
                        previousSchema,previousDecision, ...
                        problem.ShootingSchema);
                end
                sourceDecision=candidate(:);
                homotopy=struct('Completed',true,'Lambda',1, ...
                    'Decision',sourceDecision,'Attempts',{{}}, ...
                    'Checkpoints',{{}},'TerminationReason','not-required', ...
                    'Adaptive',false);
                if index>1&&useHomotopy
                    homotopyOptions=mergeHomotopyOptions( ...
                        solverOptions,options);
                    homotopy=lmz.shooting.HorizonContinuation(). ...
                        traceHomotopy(problem,candidate, ...
                        homotopyOptions,context);
                    checkpoints=[checkpoints; ...
                        homotopy.Checkpoints(:)]; %#ok<AGROW>
                    if ~homotopy.Completed
                        history{index}=struct('Step',index, ...
                            'Configuration',configuration, ...
                            'SegmentCount',problem.Horizon.segmentCount(), ...
                            'SourceDecision',sourceDecision, ...
                            'Decision',homotopy.Decision, ...
                            'Embedding',embedding,'Homotopy',homotopy, ...
                            'Feasibility',struct('Success',false, ...
                            'Classification','numerical_failure', ...
                            'TerminationReason', ...
                            homotopy.TerminationReason, ...
                            'PartialHorizonPreserved',true));
                        history=history(1:index);
                        break
                    end
                    candidate=homotopy.Decision;
                end
                final=lmz.services.MultipleShootingService().solve( ...
                    problem,candidate,solverOptions,context);
                previousSchema=problem.ShootingSchema;
                previousDecision=final.SolveResult.Solution.DecisionValues;
                history{index}=struct('Step',index, ...
                    'Configuration',configuration, ...
                    'SegmentCount',problem.Horizon.segmentCount(), ...
                    'SourceDecision',sourceDecision, ...
                    'Decision',previousDecision, ...
                    'Embedding',embedding,'Homotopy',homotopy, ...
                    'Feasibility',final.FeasibilityReport.toStruct());
                checkpoints{end+1,1}=lmz.shooting. ...
                    HorizonContinuation().checkpoint(problem, ...
                    previousDecision,history(1:index),'completed_step'); %#ok<AGROW>
                context.progress(index/numel(configurations), ...
                    sprintf('Horizon continuation step %d/%d', ...
                    index,numel(configurations)));
                if ~final.FeasibilityReport.Success&&~continueOnFailure
                    history=history(1:index);
                    break
                end
            end
            result=lmz.shooting.ShootingResult(final.SolveResult, ...
                final.Horizon,final.FeasibilityReport, ...
                'SegmentResults',final.SegmentResults, ...
                'InitializerHistory',final.InitializerHistory, ...
                'ContinuationHistory',history, ...
                'Checkpoints',checkpoints, ...
                'Diagnostics',final.Diagnostics);
        end

        function artifact=toArtifact(~,result,modelId,problemId, ...
                configurations,initialSeed,options)
            if ~isa(result,'lmz.shooting.ShootingResult')
                error('lmz:Services:HorizonContinuationResult', ...
                    'Continuation artifact requires a ShootingResult.');
            end
            if nargin<7,options=struct();end
            assertPlain(configurations,'configurations');
            assertPlain(options,'options');
            artifact=result.toArtifact();
            artifact.artifactType='horizon-continuation-run';
            artifact.horizonContinuation=struct('SchemaVersion','1.0.0', ...
                'ModelId',modelId,'ProblemId',problemId, ...
                'Configurations',{configurations}, ...
                'InitialSeed',plain(initialSeed), ...
                'Options',options,'History', ...
                {result.ContinuationHistory});
            termination=continuationTermination( ...
                result.ContinuationHistory,numel(configurations));
            details=struct('Options',options, ...
                'SourceSeed',plain(initialSeed), ...
                'RandomSeed',result.SolveResult.RandomSeed, ...
                'Provenance',result.SolveResult.Provenance, ...
                'ElapsedTime',numericField( ...
                result.SolveResult.Provenance,'elapsedTime',NaN), ...
                'FunctionEvaluations',numericField( ...
                result.SolveResult.Provenance,'evaluations',NaN), ...
                'TerminationReason',termination, ...
                'Warnings',{{}});
            artifact=lmz.io.ArtifactStore.withRunMetadata(artifact,details);
        end

        function result=resumeHomotopy(~,model,problemId,configuration, ...
                anchor,checkpoint,options,context)
            %RESUMEHOMOTOPY Continue one hash-bound adaptive horizon step.
            if nargin<7||isempty(options),options=struct();end
            if nargin<8||isempty(context)
                context=lmz.api.RunContext.synchronous(0);
            end
            if ~isa(model,'lmz.api.LeggedModel')||~ischar(problemId)|| ...
                    ~isstruct(configuration)||~isscalar(configuration)|| ...
                    ~isstruct(options)||~isscalar(options)
                error('lmz:Services:HorizonContinuationResume', ...
                    'Homotopy resume inputs are invalid.');
            end
            problem=model.createProblem(problemId,configuration);
            if ~isa(problem,'lmz.shooting.MultipleShootingProblem')
                error('lmz:Services:HorizonContinuationProblem', ...
                    'Homotopy resume requires a shooting problem.');
            end
            options.ResumeCheckpoint=checkpoint;
            result=lmz.shooting.HorizonContinuation().traceHomotopy( ...
                problem,anchor,options,context);
        end
    end
end

function value=mergeHomotopyOptions(solverOptions,options)
value=solverOptions;
names={'HomotopyInitialStep','HomotopyMinimumStep', ...
    'HomotopyMaximumStep','HomotopyStepGrowth', ...
    'HomotopyStepReduction','HomotopyMaximumAttempts'};
for index=1:numel(names)
    if isfield(options,names{index})
        value.(names{index})=options.(names{index});
    end
end
end

function value=fieldOr(source,name,fallback)
if isstruct(source)&&isfield(source,name),value=source.(name);else,value=fallback;end
end
function assertPlain(source,path)
if isa(source,'function_handle')||isobject(source)
    error('lmz:Services:HorizonContinuationExecutableData', ...
        '%s must contain plain inert data.',path);
elseif isstruct(source)
    names=fieldnames(source);
    for item=1:numel(source)
        for index=1:numel(names)
            assertPlain(source(item).(names{index}),[path '.' names{index}]);
        end
    end
elseif iscell(source)
    for index=1:numel(source)
        assertPlain(source{index},sprintf('%s{%d}',path,index));
    end
end
end
function value=plain(source)
if isa(source,'lmz.data.Solution'),value=source.toStruct();else,value=source;end
assertPlain(value,'value');
end
function value=numericField(source,name,fallback)
value=fallback;
if isstruct(source)&&isfield(source,name)&&isnumeric(source.(name))&& ...
        isscalar(source.(name)),value=source.(name);end
end

function value=continuationTermination(history,requestedCount)
value='horizon-continuation-complete';
if isempty(history)||numel(history)<requestedCount
    value='horizon-continuation-partial';
end
if isempty(history),return,end
last=history{end};
if isstruct(last)&&isfield(last,'Homotopy')&& ...
        isstruct(last.Homotopy)&&isfield(last.Homotopy,'Completed')&& ...
        ~logical(last.Homotopy.Completed)
    value=['horizon-continuation-partial:' ...
        fieldOr(last.Homotopy,'TerminationReason','homotopy-failure')];
elseif isstruct(last)&&isfield(last,'Feasibility')&& ...
        isstruct(last.Feasibility)&&isfield(last.Feasibility,'Success')&& ...
        ~logical(last.Feasibility.Success)
    value='horizon-continuation-qualified-failure';
end
end
