classdef AffineTimingFamilyProvider < lmz.schedule.ContactConstraintProvider
    %AFFINETIMINGFAMILYPROVIDER Minimal public timing-family extension example.
    properties (SetAccess=private)
        TargetEventTime = 0.4
    end

    methods
        function value=eventNames(~)
            value={'impact'};
        end

        function value=evaluate(obj,initialState,~,schedule,context, ...
                includeSimulation)
            if nargin<6,includeSimulation=false;end
            context.check();
            eventTime=schedule.namedTimes({'impact'});
            terminal=initialState(:);
            crossing=struct('SectionId',schedule.StopSectionId, ...
                'SectionValue',0,'DirectionalDerivative',-1, ...
                'CrossingDirection',-1,'Grazing',false,'EventId','', ...
                'ModeBefore','flight','ModeAfter','flight', ...
                'Time',schedule.ReturnTime,'PreState',terminal, ...
                'PostState',terminal,'State',terminal,'StateSide','post', ...
                'Occurrence',1,'Accepted',true,'RejectionReason','');
            simulation=[];
            if includeSimulation
                simulation=struct('Time',[0;schedule.ReturnTime], ...
                    'State',[terminal.';terminal.']);
            end
            value=struct('ContactResidual', ...
                eventTime-obj.TargetEventTime,'SectionResidual',zeros(0,1), ...
                'TerminalState',terminal,'SectionCrossing',crossing, ...
                'Simulation',simulation,'Diagnostics',struct( ...
                'Provider','lmzexamples.AffineTimingFamilyProvider', ...
                'EnergyValid',true,'PeriodicityRowsIncluded',false));
        end
    end
end
