classdef PoincareReturnResult
    %POINCARERETURNRESULT Return trajectory, crossing, and periodic residual.
    properties (SetAccess = private)
        InitialState
        TerminalState
        AlignedTerminalState
        InitialCoordinates
        ReturnCoordinates
        PeriodicResidual
        ReturnTime
        StartCrossing
        StopCrossing
        Simulation
        Diagnostics
        StrideDefinition
        StartSectionDescriptor
        StopSectionDescriptor
        SymmetryDescriptor
    end

    methods
        function obj = PoincareReturnResult(value)
            if nargin == 0
                return
            end
            required = {'InitialState','TerminalState','AlignedTerminalState', ...
                'InitialCoordinates','ReturnCoordinates','PeriodicResidual', ...
                'ReturnTime','StartCrossing','StopCrossing','Simulation', ...
                'Diagnostics','StrideDefinition','StartSectionDescriptor', ...
                'StopSectionDescriptor','SymmetryDescriptor'};
            if ~isstruct(value) || ~isscalar(value) || ...
                    ~all(isfield(value, required))
                error('lmz:Poincare:ReturnResultFields', ...
                    'Poincare return result is missing required fields.');
            end
            vectors = {'InitialState','TerminalState','AlignedTerminalState', ...
                'InitialCoordinates','ReturnCoordinates','PeriodicResidual'};
            for index = 1:numel(vectors)
                item = value.(vectors{index});
                if ~isnumeric(item) || ~isvector(item) || ...
                        ~isreal(item) || any(~isfinite(item(:)))
                    error('lmz:Poincare:ReturnResultVector', ...
                        '%s must be a finite real vector.', vectors{index});
                end
                value.(vectors{index}) = item(:);
            end
            if numel(value.InitialState) ~= numel(value.TerminalState) || ...
                    numel(value.InitialState) ~= numel(value.AlignedTerminalState) || ...
                    numel(value.InitialCoordinates) ~= numel(value.ReturnCoordinates) || ...
                    numel(value.PeriodicResidual) ~= numel(value.ReturnCoordinates)
                error('lmz:Poincare:ReturnResultDimension', ...
                    'Poincare return result dimensions are inconsistent.');
            end
            if ~isnumeric(value.ReturnTime) || ~isscalar(value.ReturnTime) || ...
                    ~isfinite(value.ReturnTime) || value.ReturnTime < 0
                error('lmz:Poincare:ReturnTime', ...
                    'Poincare return time must be finite and nonnegative.');
            end
            if ~isa(value.StartCrossing, 'lmz.poincare.SectionCrossing') || ...
                    ~isa(value.StopCrossing, 'lmz.poincare.SectionCrossing')
                error('lmz:Poincare:ReturnCrossing', ...
                    'Poincare return crossings have invalid types.');
            end
            if ~isempty(value.Simulation) && ...
                    ~isa(value.Simulation, 'lmz.api.SimulationResult')
                error('lmz:Poincare:ReturnSimulation', ...
                    'Poincare simulation must be a SimulationResult or empty.');
            end
            if ~isstruct(value.Diagnostics) || ~isscalar(value.Diagnostics) || ...
                    ~isa(value.StrideDefinition, ...
                    'lmz.poincare.StrideDefinition') || ...
                    ~isstruct(value.StartSectionDescriptor) || ...
                    ~isstruct(value.StopSectionDescriptor) || ...
                    ~isstruct(value.SymmetryDescriptor)
                error('lmz:Poincare:ReturnMetadata', ...
                    'Poincare return metadata has invalid types.');
            end
            for index = 1:numel(required)
                obj.(required{index}) = value.(required{index});
            end
        end

        function value = toStruct(obj)
            simulation = [];
            if ~isempty(obj.Simulation)
                simulation = obj.Simulation.toStruct();
            end
            value = struct('initialState', obj.InitialState, ...
                'terminalState', obj.TerminalState, ...
                'alignedTerminalState', obj.AlignedTerminalState, ...
                'initialCoordinates', obj.InitialCoordinates, ...
                'returnCoordinates', obj.ReturnCoordinates, ...
                'periodicResidual', obj.PeriodicResidual, ...
                'returnTime', obj.ReturnTime, ...
                'startCrossing', obj.StartCrossing.toStruct(), ...
                'stopCrossing', obj.StopCrossing.toStruct(), ...
                'simulation', simulation, 'diagnostics', obj.Diagnostics, ...
                'strideDefinition', obj.StrideDefinition.toStruct(), ...
                'startSectionDescriptor', obj.StartSectionDescriptor, ...
                'stopSectionDescriptor', obj.StopSectionDescriptor, ...
                'symmetryDescriptor', obj.SymmetryDescriptor);
        end
    end
end
