classdef ScientificPeriodicOrbitEvaluator
    %SCIENTIFICPERIODICORBITEVALUATOR Closure at catalog event sections.
    %   The scientific decision codecs remain apex based.  For a different
    %   section, this evaluator propagates two consecutive apex-to-apex
    %   candidates and compares the requested crossings.  Consequently the
    %   residual is a genuine return residual away from a solution; it is
    %   not obtained by rotating a trajectory and forcing its endpoint.
    methods
        function result = evaluate(~, model, apexProblem, u, p, ...
                configuration, stateDecisionCount, context, includeSimulation)
            if nargin < 9
                includeSimulation = false;
            end
            localValidateInputs(model, apexProblem, configuration, ...
                stateDecisionCount, context);
            [catalog, startSection, stopSection, symmetry] = ...
                localConfiguration(model, configuration);
            localValidateCoordinateDimensions( ...
                startSection, stopSection, model.getPhysicalStateSchema());

            apexEquivalent = localApexEquivalent( ...
                startSection, stopSection, symmetry, configuration);
            if apexEquivalent
                base = apexProblem.evaluate(u, p, context, includeSimulation);
                result = struct('ApexEquivalent', true, ...
                    'BaseEvaluation', base, 'NextEvaluation', [], ...
                    'PeriodicResidual', [], 'Simulation', base.Simulation, ...
                    'StartCrossing', [], 'StopCrossing', [], ...
                    'CatalogHash', catalog.CatalogHash, ...
                    'Diagnostics', localDiagnostics(configuration, catalog, ...
                    startSection, stopSection, symmetry, true, false));
                return
            end

            base = apexProblem.evaluate(u, p, context, true);
            uNext = u(:);
            terminal = base.Simulation.States(end, :).';
            if numel(terminal) ~= stateDecisionCount + 1
                error('lmz:Poincare:ScientificStateCodec', ...
                    ['The scientific state codec must omit exactly one ' ...
                    'translational state.']);
            end
            uNext(1:stateDecisionCount) = terminal(2:end);
            next = apexProblem.evaluate(uNext, p, context, true);
            startCrossing = localCrossing(startSection, ...
                base.Simulation.EventRecords);
            stopCrossing = localCrossing(stopSection, ...
                next.Simulation.EventRecords);
            schema = base.Simulation.StateSchema;
            aligned = symmetry.align(stopCrossing.State, ...
                startCrossing.State, schema);
            initialCoordinates = startSection.coordinates( ...
                startCrossing.State, schema);
            terminalCoordinates = stopSection.coordinates(aligned, schema);
            periodic = terminalCoordinates - initialCoordinates;

            simulation = [];
            rephased = false;
            transferError = NaN;
            if includeSimulation
                simulation = base.Simulation;
                if strcmp(startSection.Id, stopSection.Id) && ...
                        base.ScaledResidualNorm <= 1e-6
                    [simulation, ~, transferError] = ...
                        lmz.services.SectionTransferService. ...
                        rephaseSimulationToSection(base.Simulation, ...
                        startSection, symmetry);
                    rephased = true;
                end
            end
            diagnostics = localDiagnostics(configuration, catalog, ...
                startSection, stopSection, symmetry, false, rephased);
            diagnostics.PhysicalOrbitMaxError = transferError;
            diagnostics.BaseApexResidualNorm = base.ScaledResidualNorm;
            diagnostics.NextApexResidualNorm = next.ScaledResidualNorm;
            diagnostics.StartCrossing = startCrossing.toStruct();
            diagnostics.StopCrossing = stopCrossing.toStruct();
            diagnostics.InitialSectionCoordinates = initialCoordinates;
            diagnostics.ReturnSectionCoordinates = terminalCoordinates;
            result = struct('ApexEquivalent', false, ...
                'BaseEvaluation', base, 'NextEvaluation', next, ...
                'PeriodicResidual', periodic, 'Simulation', simulation, ...
                'StartCrossing', startCrossing, ...
                'StopCrossing', stopCrossing, ...
                'CatalogHash', catalog.CatalogHash, ...
                'Diagnostics', diagnostics);
        end
    end
end

function localValidateInputs(model, problem, configuration, stateCount, context)
if ~isa(model, 'lmz.api.LeggedModel') || ...
        ~isa(problem, 'lmz.api.NonlinearEquationProblem') || ...
        ~isstruct(configuration) || ~isscalar(configuration) || ...
        ~isnumeric(stateCount) || ~isscalar(stateCount) || ...
        stateCount < 1 || stateCount ~= fix(stateCount) || ...
        ~isa(context, 'lmz.api.RunContext')
    error('lmz:Poincare:ScientificPeriodicInput', ...
        'Scientific periodic-orbit evaluator inputs are invalid.');
end
strideCount = localField(configuration, 'StrideCount', 1);
if ~isnumeric(strideCount) || ~isscalar(strideCount) || strideCount ~= 1
    error('lmz:Poincare:ScientificStrideCount', ...
        ['Scientific periodic_orbit uses one return. Use an N-stride ' ...
        'problem for StrideCount other than one.']);
end
end

function [catalog, startSection, stopSection, symmetry] = ...
        localConfiguration(model, configuration)
registry = lmz.registry.ModelRegistry.discover();
modelId = model.getManifest().id;
catalog = registry.getPoincareSectionRegistry(modelId);
startId = localField(configuration, 'StartSectionId', 'apex');
stopId = localField(configuration, 'StopSectionId', startId);
startSection = localConfiguredSection( ...
    catalog.section(startId), configuration, 'Start');
stopSection = localConfiguredSection( ...
    catalog.section(stopId), configuration, 'Stop');
symmetry = catalog.symmetryFor(stopId);
requested = localField(configuration, 'SymmetryId', symmetry.Id);
if strcmp(requested, 'identity')
    symmetry = lmz.poincare.IdentitySymmetry();
elseif ~strcmp(requested, symmetry.Id)
    error('lmz:Poincare:ScientificSymmetry', ...
        'SymmetryId must be identity or the section catalog symmetry.');
end
end

function section = localConfiguredSection(section, configuration, prefix)
value = section.toStruct();
fields = {'StateSide','CrossingDirection','MinimumReturnTime', ...
    'RequiredEventSequence','ReturnOccurrence'};
targets = {'stateSide','crossingDirection','minimumReturnTime', ...
    'requiredEventSequence','returnOccurrence'};
for index = 1:numel(fields)
    name = [prefix fields{index}];
    if isfield(configuration, name)
        value.(targets{index}) = configuration.(name);
    elseif strcmp(prefix, 'Stop') && isfield(configuration, fields{index})
        value.(targets{index}) = configuration.(fields{index});
    end
end
descriptor = lmz.poincare.PoincareSectionDescriptor(value);
if ~strcmp(descriptor.Kind, 'named_event')
    error('lmz:Poincare:ScientificSectionKind', ...
        ['The migrated scientific periodic codecs currently support ' ...
        'catalog named-event sections.']);
end
section = lmz.poincare.NamedEventSection(descriptor);
end

function localValidateCoordinateDimensions(startSection, stopSection, schema)
sample = zeros(schema.count(), 1);
first = startSection.coordinates(sample, schema);
second = stopSection.coordinates(sample, schema);
if numel(first) ~= numel(second)
    error('lmz:Poincare:ScientificCoordinateDimension', ...
        'Start and stop section coordinate dimensions must agree.');
end
end

function valid = localApexEquivalent(startSection, stopSection, ...
        symmetry, configuration)
valid = strcmp(startSection.Id, 'apex') && ...
    strcmp(stopSection.Id, 'apex') && ...
    strcmp(startSection.StateSide, 'post') && ...
    strcmp(stopSection.StateSide, 'post') && ...
    strcmp(symmetry.Id, 'planar_translation');
fields = {'StartCrossingDirection','StopCrossingDirection', ...
    'CrossingDirection','StartMinimumReturnTime','StopMinimumReturnTime', ...
    'MinimumReturnTime','StartRequiredEventSequence', ...
    'StopRequiredEventSequence','RequiredEventSequence', ...
    'StartReturnOccurrence','StopReturnOccurrence','ReturnOccurrence'};
valid = valid && ~any(isfield(configuration, fields));
end

function crossing = localCrossing(section, records)
history = {};
occurrence = 0;
for index = 1:numel(records)
    record = records(index);
    if section.matches(record)
        occurrence = occurrence + 1;
        candidate = section.crossingFromRecord(record, ...
            'Occurrence', occurrence, 'EventHistory', history);
        if candidate.Accepted
            crossing = candidate;
            return
        end
    end
    history{end + 1} = localEventId(record); %#ok<AGROW>
end
error('lmz:Poincare:ScientificCrossingNotFound', ...
    'No accepted crossing was found for section %s.', section.Id);
end

function value = localEventId(record)
if isfield(record, 'Id')
    value = record.Id;
elseif isfield(record, 'Name')
    value = record.Name;
else
    value = '';
end
end

function diagnostics = localDiagnostics(configuration, catalog, ...
        startSection, stopSection, symmetry, equivalent, rephased)
diagnostics = struct( ...
    'Formulation', 'catalog-scientific-periodic-orbit-v1', ...
    'StartSectionId', startSection.Id, ...
    'StopSectionId', stopSection.Id, ...
    'StartStateSide', startSection.StateSide, ...
    'StopStateSide', stopSection.StateSide, ...
    'SymmetryId', symmetry.Id, ...
    'StrideCount', localField(configuration, 'StrideCount', 1), ...
    'SectionCatalogHash', catalog.CatalogHash, ...
    'StartSectionHash', startSection.Descriptor.fingerprint(), ...
    'StopSectionHash', stopSection.Descriptor.fingerprint(), ...
    'ApexPresetEquivalent', equivalent, ...
    'SourceApexPhaseGaugePreserved', true, ...
    'RephasedSimulation', rephased, ...
    'HiddenTimingSolve', false);
end

function value = localField(source, name, fallback)
if isfield(source, name)
    value = source.(name);
else
    value = fallback;
end
end
