classdef MultipleShootingFactory
    %MULTIPLESHOOTINGFACTORY Registered analytic hopper horizon builder.
    methods (Static)
        function problem=create(model,configuration)
            if nargin<2,configuration=struct();end
            if isfield(configuration,'Horizon')
                horizon=configuration.Horizon;
                if isstruct(horizon)
                    horizon=lmz.shooting.ShootingHorizon.fromStruct(horizon);
                end
            else
                horizon=lmzmodels.tutorial_hopper. ...
                    MultipleShootingFactory.horizon(configuration);
            end
            if isfield(configuration,'ShootingDecisionSchema')
                shootingSchema=configuration.ShootingDecisionSchema;
                if isstruct(shootingSchema)
                    shootingSchema=lmz.shooting.ShootingDecisionSchema. ...
                        fromStruct(shootingSchema);
                end
            else
                shootingSchema=lmz.shooting.ShootingDecisionSchema. ...
                    fromHorizon(horizon);
            end
            stored=configuration;
            removable={'Horizon','ShootingDecisionSchema'};
            for index=1:numel(removable)
                if isfield(stored,removable{index})
                    stored=rmfield(stored,removable{index});
                end
            end
            stored.ProblemId='multiple_shooting';
            stored.Formulation=horizon.Formulation;
            adapter=lmzmodels.tutorial_hopper. ...
                HopperSectionSimulationAdapter();
            parameters=lmzmodels.tutorial_hopper.ParameterSchema.create();
            if strcmp(horizon.Formulation,'periodic')
                problem=lmz.shooting.PeriodicMultipleShootingProblem( ...
                    model,shootingSchema,parameters,parameters.defaults(), ...
                    horizon,adapter,stored);
            elseif strcmp(horizon.Formulation,'transition')
                problem=lmz.shooting.TransitionMultipleShootingProblem( ...
                    model,shootingSchema,parameters,parameters.defaults(), ...
                    horizon,adapter,stored);
            else
                problem=lmz.shooting.MultipleShootingProblem(model, ...
                    'multiple_shooting',shootingSchema,parameters, ...
                    parameters.defaults(),horizon,adapter,stored);
            end
        end

        function horizon=horizon(configuration)
            count=fieldOr(configuration,'HorizonLength',2);
            if ~isnumeric(count)||~isscalar(count)||count<1||count~=fix(count)
                error('lmz:tutorial_hopper:ShootingHorizonLength', ...
                    'HorizonLength must be a positive integer.');
            end
            gravity=fieldOr(configuration,'Gravity',9.81);
            returnTime=fieldOr(configuration,'ReturnTime',sqrt(8/gravity));
            impulse=fieldOr(configuration,'Impulse',gravity*returnTime);
            mask=logical(fieldOr(configuration,'InterfaceStateMask', ...
                true(2,count+1)));
            if isscalar(mask)
                mask=repmat(mask,2,count+1);
            elseif isvector(mask)&&numel(mask)==2
                mask=repmat(mask(:),1,count+1);
            end
            if ~isequal(size(mask),[2 count+1])
                error('lmz:tutorial_hopper:ShootingInterfaceMask', ...
                    'InterfaceStateMask must be 2-by-(N+1).');
            end
            eventFree=logical(fieldOr(configuration,'EventFreeMask', ...
                [true true]));
            if numel(eventFree)~=2
                error('lmz:tutorial_hopper:ShootingEventMask', ...
                    'EventFreeMask must select impact and return time.');
            end
            controlsFree=logical(fieldOr(configuration, ...
                'ControlFreeMask',false));
            physical=lmzmodels.tutorial_hopper.PhysicalStateSchema.create();
            stateSchema=lmz.shooting.SectionStateSchema(physical,{'vx','y'});
            nodes=cell(count+1,1);
            for index=1:numel(nodes)
                full=[(index-1)*returnTime;1;1;0];
                nodes{index}=lmz.shooting.ShootingNode( ...
                    'SectionId','apex','StateSide','post', ...
                    'StateSchema',stateSchema,'FullState',full, ...
                    'WorldTranslation',(index-1)*returnTime, ...
                    'FreeCoordinateMask',mask(:,index), ...
                    'Symmetry',struct('Id','planar_translation'), ...
                    'Lineage',struct('Source','analytic-tutorial-hopper'));
            end
            segments=cell(count,1);
            energyMode=fieldOr(configuration,'EnergyWorkMode', ...
                'diagnostic_only');
            energy=struct('Mode',energyMode,'DeclaredWork',0, ...
                'Tolerance',1e-9);
            for index=1:count
                occurrence=lmz.schedule.EventOccurrence('impact', ...
                    returnTime/2,'Fixed',~eventFree(1));
                schedule=lmz.schedule.EventSchedule(occurrence,returnTime, ...
                    'ReturnTimeFixed',~eventFree(2), ...
                    'MinimumGap',1e-9,'StartSectionId','apex', ...
                    'StopSectionId','apex');
                controls=struct('impulse',impulse);
                if controlsFree,controls=impulse;end
                segments{index}=lmz.shooting.ShootingSegment( ...
                    'Index',index,'StartNode',nodes{index}, ...
                    'StopNode',nodes{index+1}, ...
                    'EventSchedule',schedule, ...
                    'ContactConstraints',{'ground_contact'}, ...
                    'PhysicalParameters',struct('gravity',gravity), ...
                    'ControlParameters',controls, ...
                    'EnergyWorkSpecification',energy, ...
                    'SourceLineage',struct( ...
                    'Source','analytic-tutorial-hopper'));
            end
            formulation=fieldOr(configuration,'Formulation','periodic');
            target=fieldOr(configuration,'Target',struct());
            horizon=lmz.shooting.ShootingHorizon( ...
                'ModelId','tutorial_hopper', ...
                'ProblemId','multiple_shooting','Nodes',nodes, ...
                'Segments',segments,'Formulation',formulation, ...
                'Target',target,'Lineage',struct( ...
                'Source','analytic-tutorial-hopper', ...
                'HorizonLength',count));
        end
    end
end

function value=fieldOr(source,name,fallback)
if isstruct(source)&&isfield(source,name),value=source.(name); ...
else,value=fallback;end
end
