classdef PeriodicHopProblem < lmz.api.NonlinearEquationProblem
    %PERIODICHOPPROBLEM Analytic periodic hop with one free family direction.
    methods
        function obj = PeriodicHopProblem(model, configuration)
            gravity = 9.81;
            period = sqrt(8 / gravity);
            decision = lmz.schema.VariableSchema([ ...
                lmz.schema.VariableSpec('apex_height', 'Unit', 'm', ...
                'DefaultValue', 1, 'LowerBound', 0.2, 'UpperBound', 3, ...
                'Scale', 1, 'Topology', 'bounded'); ...
                lmz.schema.VariableSpec('stride_period', 'Unit', 's', ...
                'DefaultValue', period, 'LowerBound', 0.2, ...
                'UpperBound', 2, 'Scale', 1, 'Topology', 'bounded'); ...
                lmz.schema.VariableSpec('impulse', 'Unit', 'm/s', ...
                'DefaultValue', gravity * period, 'LowerBound', 1, ...
                'UpperBound', 30, 'Scale', 10, 'Topology', 'bounded'); ...
                lmz.schema.VariableSpec('horizontal_speed', 'Unit', 'm/s', ...
                'DefaultValue', 1, 'LowerBound', 0.1, 'UpperBound', 4, ...
                'Scale', 1, 'Topology', 'bounded'); ...
                lmz.schema.VariableSpec('stride_length', 'Unit', 'm', ...
                'DefaultValue', period, 'LowerBound', 0.05, ...
                'UpperBound', 5, 'Scale', 1, 'Topology', 'bounded')]);
            parameters = ...
                lmzmodels.tutorial_hopper.ParameterSchema.create();
            obj@lmz.api.NonlinearEquationProblem(model, 'periodic_hop', ...
                'nonlinear_equation', decision, parameters, ...
                parameters.defaults(), configuration);
        end

        function evaluation = evaluate(obj, u, p, context, includeSimulation)
            obj.DecisionSchema.validateVector(u);
            obj.ParameterSchema.validateVector(p);
            simulation = obj.simulateDecision(u, p, context);
            decision = obj.DecisionSchema.unpack(u);
            impact = simulation.EventRecords(1);
            residual = [decision.apex_height - 1; ...
                impact.PreState(3); ...
                simulation.States(end, 4); ...
                simulation.States(end, 1) - decision.stride_length];
            blocks = [ ...
                lmz.data.ResidualBlock( ...
                'fixed_apex_height', residual(1), 1); ...
                lmz.data.ResidualBlock('ground_impact', residual(2), 1); ...
                lmz.data.ResidualBlock( ...
                'periodic_vertical_speed', residual(3), 1); ...
                lmz.data.ResidualBlock( ...
                'stride_translation', residual(4), 1)];
            feasibility = struct( ...
                'Valid', min(simulation.States(:, 3)) >= -1e-8, ...
                'MinimumHeight', min(simulation.States(:, 3)));
            if includeSimulation
                returnedSimulation = simulation;
            else
                returnedSimulation = [];
            end
            evaluation = lmz.data.ProblemEvaluation(blocks, ...
                'Simulation', returnedSimulation, ...
                'Feasibility', feasibility, ...
                'PhysicalValidity', feasibility.Valid, ...
                'Diagnostics', struct( ...
                'formulation', 'analytic-hopper-tutorial-v1'));
        end

        function value = optionalJacobian(obj, u, p, varargin)
            decision = obj.DecisionSchema.unpack(u);
            parameters = obj.ParameterSchema.unpack(p);
            value = [1 0 0 0 0; ...
                1 -parameters.gravity * decision.stride_period / 4 0 0 0; ...
                0 -parameters.gravity 1 0 0; ...
                0 decision.horizontal_speed 0 decision.stride_period -1];
        end

        function result = simulateDecision(obj, u, p, context, problemId)
            if nargin < 5
                problemId = obj.Id;
            end
            decision = obj.DecisionSchema.unpack(u);
            parameters = obj.ParameterSchema.unpack(p);
            hybridParameters = struct( ...
                'gravity', parameters.gravity, ...
                'impulse', decision.impulse);
            request = struct( ...
                'TimeSpan', [0 decision.stride_period], ...
                'Parameters', hybridParameters, ...
                'Decision', decision, ...
                'ProblemId', problemId);
            result = lmz.simulation.HybridSimulator().simulate( ...
                lmzmodels.tutorial_hopper.HopperSystem(), ...
                request, context, struct( ...
                'MaximumStep', decision.stride_period / 80));
        end
    end
end
