classdef PeriodicOrbitProblem < lmz.api.NonlinearEquationProblem
    %PERIODICORBITPROBLEM Catalog-configured tutorial return-map problem.
    properties (SetAccess=private)
        ApexProblem
    end
    methods
        function obj=PeriodicOrbitProblem(model,configuration)
            if nargin<2,configuration=struct();end
            apex=lmzmodels.tutorial_hopper.PeriodicHopProblem(model,struct());
            obj@lmz.api.NonlinearEquationProblem(model,'periodic_orbit', ...
                'nonlinear_equation',apex.getDecisionSchema(), ...
                apex.getParameterSchema(),apex.getParameterSchema().defaults(), ...
                configuration);
            obj.Version='1.0.0';obj.ApexProblem=apex;
        end
        function evaluation=evaluate(obj,u,p,context,includeSimulation)
            if nargin<5,includeSimulation=false;end
            base=obj.ApexProblem.evaluate(u,p,context,true);
            source=obj.ApexProblem.makeSolution(u,p,base);
            startId=fieldOr(obj.Configuration,'StartSectionId','apex');
            stopId=fieldOr(obj.Configuration,'StopSectionId',startId);
            if strcmp(startId,stopId)&&~strcmp(startId,'apex')
                registry=lmz.registry.ModelRegistry.discover();
                catalog=registry.getPoincareSectionRegistry('tutorial_hopper');
                section=catalog.section(startId);symmetry=catalog.symmetryFor(startId);
                [simulation,crossing,physicalError,preserved,displacement]= ...
                    lmz.services.SectionTransferService. ...
                    rephaseSimulationToSection(base.Simulation,section,symmetry);
                initial=simulation.States(1,:).';terminal=simulation.States(end,:).';
                aligned=symmetry.align(terminal,initial,simulation.StateSchema);
                periodic=section.coordinates(aligned,simulation.StateSchema)- ...
                    section.coordinates(initial,simulation.StateSchema);
                returnDiagnostics=struct('TransferredToSection',true, ...
                    'PhysicalOrbitMaxError',physicalError, ...
                    'PhaseInvariantObservablesPreserved',preserved, ...
                    'SymmetryDisplacement',displacement, ...
                    'TargetCrossing',crossing.toStruct());
            else
                returned=lmz.services.PoincareReturnService().simulate( ...
                    obj.Model,source,struct('StartSectionId',startId, ...
                    'StopSectionId',stopId),context);
                simulation=returned.Simulation;periodic=returned.PeriodicResidual;
                returnDiagnostics=returned.Diagnostics;
            end
            decision=obj.DecisionSchema.unpack(u);
            impact=base.Simulation.EventRecords(1);
            translation=base.Simulation.States(end,1)-decision.stride_length;
            blocks=[lmz.data.ResidualBlock('section_periodicity', ...
                periodic(:),ones(numel(periodic),1)); ...
                lmz.data.ResidualBlock('ground_contact',impact.PreState(3),1); ...
                lmz.data.ResidualBlock('apex_height_gauge', ...
                decision.apex_height-1,1); ...
                lmz.data.ResidualBlock('translation_gauge',translation,1)];
            feasibility=struct('Valid',all(isfinite([periodic(:); ...
                impact.PreState(3);translation]))&& ...
                min(simulation.States(:,3))>=-1e-8);
            if ~includeSimulation,simulation=[];end
            evaluation=lmz.data.ProblemEvaluation(blocks, ...
                'Simulation',simulation,'Feasibility',feasibility, ...
                'PhysicalValidity',feasibility.Valid,'Diagnostics',struct( ...
                'Formulation','catalog-poincare-periodic-orbit-v1', ...
                'StartSectionId',startId,'StopSectionId',stopId, ...
                'ReturnDiagnostics',returnDiagnostics, ...
                'HiddenTimingSolve',false));
        end
    end
end

function value=fieldOr(source,name,fallback)
if isfield(source,name),value=source.(name);else,value=fallback;end
end
