classdef TutorialShootingAdapter < lmz.shooting.SectionSimulationAdapter
    %TUTORIALSHOOTINGADAPTER Analytic apex-to-apex hopper segment map.
    methods
        function value=simulateSegment(~,request,~,includeSimulation)
            if nargin<4,includeSimulation=false;end
            schedule=request.EventSchedule;
            if ~isa(schedule,'lmz.schedule.EventSchedule')|| ...
                    schedule.count()~=1|| ...
                    ~strcmp(schedule.Occurrences(1).Name,'impact')
                error('lmz:tutorial_hopper:ShootingSchedule', ...
                    'Tutorial shooting requires one named impact event.');
            end
            initial=request.StartNode.FullState(:);
            gravity=request.PhysicalParameters.ProblemValues(1);
            controls=request.ControlParameters;
            if isnumeric(controls)
                impulse=controls(1);
            else
                impulse=controls.impulse;
            end
            impactTime=schedule.Occurrences(1).Time;
            returnTime=schedule.ReturnTime;
            preImpact=[initial(1)+initial(2)*impactTime;initial(2); ...
                initial(3)+initial(4)*impactTime- ...
                0.5*gravity*impactTime^2; ...
                initial(4)-gravity*impactTime];
            postVelocity=preImpact(4)+impulse;
            remaining=returnTime-impactTime;
            terminal=[preImpact(1)+preImpact(2)*remaining;preImpact(2); ...
                preImpact(3)+postVelocity*remaining- ...
                0.5*gravity*remaining^2; ...
                postVelocity-gravity*remaining];
            coordinates=request.StopNode.StateSchema.extract(terminal);
            ordered=impactTime>schedule.MinimumGap&& ...
                remaining>schedule.MinimumGap;
            finite=all(isfinite([initial;terminal;gravity;impulse]));
            crossing=struct('Accepted',ordered&&gravity>0, ...
                'Grazing',false,'Time',returnTime, ...
                'DirectionalDerivative',-gravity);
            [energyResidual,energyDiagnostics]=energyAudit( ...
                initial,terminal,gravity,request.Segment);
            simulation=[];
            if includeSimulation
                simulation=struct('Time',[0;impactTime;returnTime], ...
                    'States',[initial.';preImpact.';terminal.'], ...
                    'Modes',{{'flight_down';'flight_up';'flight_down'}}, ...
                    'EventRecords',struct('Name','impact', ...
                    'Time',impactTime,'PreState',preImpact.', ...
                    'PostState',[preImpact(1:3);postVelocity].'), ...
                    'Diagnostics',struct('ModelId','tutorial_hopper', ...
                    'Formulation','analytic-multiple-shooting-v1'));
            end
            value=struct('TerminalState',terminal, ...
                'TerminalCoordinates',coordinates, ...
                'ContactResiduals',preImpact(3), ...
                'SectionResidual',terminal(4), ...
                'EnergyResidual',energyResidual,'Crossing',crossing, ...
                'Simulation',simulation,'PhysicalValidity', ...
                finite&&gravity>0&&ordered, ...
                'Diagnostics',struct('EventOrderValid',ordered, ...
                'ImpactTime',impactTime,'ReturnTime',returnTime, ...
                'Impulse',impulse,'HiddenTimingSolve',false, ...
                'SegmentSimulationCount',1,'Energy',energyDiagnostics, ...
                'EnergyValid',energyDiagnostics.Accepted));
        end
    end
end

function [residual,diagnostics]=energyAudit(initial,terminal,gravity,segment)
specification=segment.EnergyWorkSpecification;
initialEnergy=.5*(initial(2)^2+initial(4)^2)+gravity*initial(3);
terminalEnergy=.5*(terminal(2)^2+terminal(4)^2)+gravity*terminal(3);
delta=terminalEnergy-initialEnergy;
switch specification.Mode
    case 'energy_neutral'
        residual=delta;
    case 'bounded_work'
        residual=max(0,abs(delta)-abs(specification.DeclaredWork));
    case {'prescribed_work','diagnostic_only'}
        residual=delta-specification.DeclaredWork;
    otherwise
        error('lmz:Shooting:TutorialEnergyMode', ...
            'Unsupported tutorial energy/work mode %s.',specification.Mode);
end
accepted=strcmp(specification.Mode,'diagnostic_only')|| ...
    all(abs(residual)<=specification.Tolerance);
diagnostics=struct('Mode',specification.Mode,'Available',true, ...
    'EnergyDelta',delta,'DeclaredWork',specification.DeclaredWork, ...
    'Residual',residual,'Tolerance',specification.Tolerance, ...
    'Accepted',accepted);
end
