function check_readme_contract
%CHECK_README_CONTRACT Validate public naming, commands, and model table.
root = lmz.util.ProjectPaths.root();
readme = fileread(fullfile(root, 'README.md'));
requiredSections = {'Project overview','Features','Requirements', ...
    'Standalone installation','Launch the GUI','GUI walkthrough', ...
    'SLIP Quadruped RoadMap Tutorial','SLIP Biped GaitMap Tutorial', ...
    'SLIP Quadruped-with-Load Fitting Tutorial', ...
    'Available models','Built-in examples','Command-line quick start', ...
    'Simulating each model','Loading and saving data', ...
    'Solving periodic solutions','Numerical continuation', ...
    'Parameter homotopy and branch-family scans', ...
    'Optimization and data fitting','Visualization, animation, and recording', ...
    'Artifact format','Legacy MAT import/export','Adding a new model', ...
    'Testing','Troubleshooting','Project structure', ...
    'License and provenance','Current verified status'};
positions = zeros(size(requiredSections));
for index = 1:numel(requiredSections)
    positions(index) = strfind(readme, ['## ' requiredSections{index}]);
end
if any(positions == 0) || any(diff(positions) <= 0)
    error('lmz:Documentation:SectionContract', ...
        'README required sections are missing or out of order.');
end
requiredText = {'legged_model_zoo', ...
    'registry = lmz.registry.ModelRegistry.discover()', ...
    'slip_biped','slip_quadruped','slip_quad_load', ...
    '<!-- LMZ:MODEL_TABLE:BEGIN -->','<!-- LMZ:MODEL_TABLE:END -->', ...
    '<!-- LMZ:PROBLEM_TABLE:BEGIN -->','<!-- LMZ:PROBLEM_TABLE:END -->', ...
    'source-equivalent','tutorial','validated','REDISTRIBUTION_STATUS.md'};
for index = 1:numel(requiredText)
    if isempty(strfind(readme, requiredText{index})) %#ok<STREMP>
        error('lmz:Documentation:MissingCommand', ...
            'README is missing required text: %s', requiredText{index});
    end
end
examples = {'demo_gui.m','demo_registry.m','demo_slip_biped.m', ...
    'demo_slip_quadruped.m','demo_slip_quad_load.m', ...
    'demo_branch_explorer.m','demo_solution_inspector.m', ...
    'demo_slip_biped_solve.m','demo_slip_biped_continuation.m', ...
    'demo_slip_biped_fit.m','demo_slip_quadruped_solve.m', ...
    'demo_slip_quadruped_continuation.m','demo_parameter_homotopy.m', ...
    'demo_branch_family_scan.m','demo_slip_quad_load_fit.m', ...
    'demo_full_gui_workflow.m','demo_slip_quadruped_roadmap_workflow.m'};
for index = 1:numel(examples)
    if exist(fullfile(root,'examples',examples{index}),'file') ~= 2
        error('lmz:Documentation:MissingExample', ...
            'Documented example is missing: %s', examples{index});
    end
end
registry = lmz.registry.ModelRegistry.discover();
ids = registry.listModels();
if ~isequal(ids, {'slip_biped','slip_quad_load','slip_quadruped'})
    error('lmz:Documentation:ModelNames','Canonical model list is stale.');
end
tables = generate_readme_tables(false);
rows = [tables.ModelRows;tables.ProblemRows];
for index = 1:numel(rows)
    if isempty(strfind(readme, rows{index})) %#ok<STREMP>
        error('lmz:Documentation:GeneratedTable', ...
            'README generated capability/maturity row is stale: %s',rows{index});
    end
end
provenancePosition = strfind(readme, '## License and provenance');
normalUsage = readme(1:provenancePosition(1)-1);
prohibited = {'SLIP_Model_Zoo','2022_A_Template_Model_Explains_Jerboa_Gait_Transitions', ...
    '2025_Gait_Transitions_in_Load_Pulling_Quadrupeds_Insights'};
for index = 1:numel(prohibited)
    if ~isempty(strfind(normalUsage, prohibited{index})) %#ok<STREMP>
        error('lmz:Documentation:ExternalInstallReference', ...
            'README normal usage references an external source repository.');
    end
end
fprintf('README contract valid for %d canonical models.\n', numel(ids));
end
