function entries = code_quality_allowlist
%CODE_QUALITY_ALLOWLIST Narrow, explained Code Analyzer exceptions.
timestampPaths = exactPaths({ ...
    'models/+lmzmodels/+slip_biped/PeriodicApexProblem.m', ...
    'models/+lmzmodels/+slip_biped/Results14Adapter.m', ...
    'models/+lmzmodels/+slip_quadruped/PeriodicApexProblem.m', ...
    'models/+lmzmodels/+slip_quadruped/Results29Adapter.m', ...
    'src/+lmz/+api/BaseProblem.m', ...
    'src/+lmz/+compat/Timestamp.m', ...
    'src/+lmz/+continuation/PseudoArclengthContinuation.m', ...
    'src/+lmz/+data/SolutionBranch.m', ...
    'src/+lmz/+gui/+components/StatusPanel.m', ...
    'src/+lmz/+gui/+tabs/ContinuationTab.m', ...
    'src/+lmz/+gui/+tabs/SolutionTab.m', ...
    'src/+lmz/+gui/AppController.m', ...
    'src/+lmz/+gui/PresentationEventBus.m', ...
    'src/+lmz/+services/ContinuationService.m', ...
    'src/+lmz/+util/Ids.m'});
entries = [ ...
    entry('NOCOMMA', exactPaths({ ...
    'src/+lmz/+api/BaseProblem.m', ...
    'src/+lmz/+continuation/PseudoArclengthContinuation.m', ...
    'src/+lmz/+gui/+tabs/BaseTab.m', ...
    'src/+lmz/+gui/+tabs/BranchTab.m', ...
    'src/+lmz/+gui/+tabs/ContinuationTab.m', ...
    'src/+lmz/+gui/+tabs/SimulationTab.m', ...
    'src/+lmz/+gui/+tabs/SolutionTab.m', ...
    'src/+lmz/+gui/+tabs/SolveTab.m', ...
    'src/+lmz/+gui/LeggedModelZooApp.m', ...
    'src/+lmz/+services/RecorderService.m', ...
    'src/+lmz/+solvers/RootSolver.m'}), ...
    'Formatting-only finding limited to the listed compact classes.'); ...
    entry('ALIGN', exactPaths({ ...
    'models/+lmzmodels/+slip_biped/PeriodicApexProblem.m', ...
    'models/+lmzmodels/+slip_quad_load/LaterStrideLayout.m', ...
    'models/+lmzmodels/+slip_quad_load/QuadLoadPlotProvider.m', ...
    'models/+lmzmodels/+slip_quad_load/QuadLoadRenderer.m', ...
    'models/+lmzmodels/+slip_quad_load/XAccumAdapter.m', ...
    'models/+lmzmodels/+slip_quadruped/QuadrupedRenderer.m', ...
    'src/+lmz/+continuation/BranchFamilyScan.m', ...
    'src/+lmz/+continuation/PseudoArclengthContinuation.m', ...
    'src/+lmz/+gui/+tabs/BranchTab.m', ...
    'src/+lmz/+gui/+tabs/ContinuationTab.m', ...
    'src/+lmz/+gui/+tabs/SimulationTab.m', ...
    'src/+lmz/+gui/+tabs/SolutionTab.m', ...
    'src/+lmz/+gui/+tabs/SolveTab.m', ...
    'src/+lmz/+gui/AppController.m'}), ...
    'Formatting-only END alignment limited to the listed maintained files.'); ...
    entry('MSNU', exactPaths({ ...
    'models/+lmzmodels/+slip_biped/FeasibilityPolicy.m', ...
    'models/+lmzmodels/+slip_quad_load/LoadParameterSchema.m', ...
    'models/+lmzmodels/+slip_quad_load/MultiStrideDecisionSchema.m', ...
    'models/+lmzmodels/+slip_quad_load/MultiStrideSimulator.m', ...
    'models/+lmzmodels/+slip_quad_load/ObjectiveWeightSchema.m', ...
    'models/+lmzmodels/+slip_quad_load/QuadrupedParameterSchema.m', ...
    'models/+lmzmodels/+slip_quad_load/QuadrupedStateSchema.m', ...
    'models/+lmzmodels/+slip_quadruped/FeasibilityPolicy.m', ...
    'src/+lmz/+api/BaseProblem.m', ...
    'src/+lmz/+api/NonlinearEquationProblem.m', ...
    'src/+lmz/+api/OptimizationProblem.m', ...
    'src/+lmz/+continuation/PseudoArclengthContinuation.m', ...
    'src/+lmz/+data/SolutionBranch.m', ...
    'src/+lmz/+schema/VariableSchema.m', ...
    'src/+lmz/+services/BranchService.m'}), ...
    'Stale analyzer pragmas are retained only in the listed migrated contracts.'); ...
    entry('DATST', timestampPaths, ...
    'datestr is limited to explicit R2019b-compatible timestamp paths.'); ...
    entry('TNOW1', timestampPaths, ...
    'now is paired with datestr only in the listed R2019b-compatible paths.'); ...
    entry('STREMP', exactPaths({ ...
    'models/+lmzmodels/+slip_quad_load/MultiStrideDecisionSchema.m'}), ...
    'strfind preserves intentional character-vector behavior in this schema.'); ...
    entry('AGROW', exactPaths({ ...
    'models/+lmzmodels/+slip_biped/PeriodicDecisionSchema.m', ...
    'models/+lmzmodels/+slip_biped/PhysicalStateSchema.m', ...
    'models/+lmzmodels/+slip_quadruped/ParameterSchema.m', ...
    'models/+lmzmodels/+slip_quadruped/PeriodicDecisionSchema.m', ...
    'models/+lmzmodels/+slip_quadruped/PhysicalStateSchema.m'}), ...
    'The listed schema builders append small, statically bounded specifications.'); ...
    entry('ISCL', exactPaths({ ...
    'src/+lmz/+gui/AppController.m', ...
    'models/+lmzmodels/+slip_quad_load/+ObjectiveTerms/LoadingForceMismatch.m'}), ...
    'Existing scalar validation is correct; this is a micro-optimization.'); ...
    entry('ISMAT', exactPaths({ ...
    'models/+lmzmodels/+slip_biped/Results14Layout.m'}), ...
    'The explicit ndims/size contract documents the legacy matrix boundary.'); ...
    entry('NASGU', exactPaths({ ...
    'src/+lmz/+continuation/PseudoArclengthContinuation.m'}), ...
    'Initialization protects rejection and exception paths before correction.'); ...
    entry('NASGU', exactPaths({ ...
    'models/+lmzmodels/+slip_quadruped/RoadMapCatalog.m'}), ...
    'Output initialization makes the exceptional no-match path explicit.')];
end

function value = entry(identifier, scopePattern, rationale)
value = struct('Identifier', identifier, ...
    'ScopePattern', scopePattern, 'Rationale', rationale);
end

function value = exactPaths(paths)
escaped = cellfun(@(path) regexptranslate('escape', path), paths, ...
    'UniformOutput', false);
value = ['^(?:' strjoin(escaped, '|') ')$'];
end
