classdef TestSceneContracts < matlab.unittest.TestCase
    methods (Test)
        function validatesEveryPrimitiveAndLegacyAliases(testCase)
            frames = {'world','body','foot','load'};
            primitives = { ...
                struct('type','ground','frame','world'); ...
                struct('type','body','frame','body','vertices',[-1 0;1 0;0 1]); ...
                struct('type','point_mass','frame','body'); ...
                struct('type','link','from','body','to','foot'); ...
                struct('type','spring','from','body','to','foot'); ...
                struct('type','rope','from','body','to','load'); ...
                struct('type','force_vector','frame','foot','vector','ground_force'); ...
                struct('type','trail','frame','body'); ...
                struct('type','text','frame','body','text','safe label')};
            spec = lmz.viz.SceneSpec(struct('schemaVersion','1.0.0', ...
                'frames',{frames},'primitives',{primitives}));
            testCase.verifyEqual(numel(spec.Primitives), 9);
            testCase.verifyEqual(spec.Primitives{2}.type, 'polygon');
            testCase.verifyEqual(spec.Primitives{3}.type, 'marker');
            testCase.verifyEqual(spec.Primitives{4}.type, 'line');
            restored = lmz.viz.SceneSpec(spec.toStruct());
            testCase.verifyEqual(restored.Frames, frames);
        end

        function rejectsExpressionsUnknownFramesAndUnknownTypes(testCase)
            badBinding = struct('schemaVersion','1.0.0', ...
                'frames',{{'world'}},'primitives',{{ ...
                struct('type','marker','frame','system_call()')}});
            testCase.verifyError(@() lmz.viz.SceneSpec(badBinding), ...
                'lmz:Scene:Binding');
            badFrame = struct('schemaVersion','1.0.0', ...
                'frames',{{'world'}},'primitives',{{ ...
                struct('type','marker','frame','missing')}});
            testCase.verifyError(@() lmz.viz.SceneSpec(badFrame), ...
                'lmz:Scene:UnknownFrame');
            badType = struct('schemaVersion','1.0.0', ...
                'frames',{{'world'}},'primitives',{{ ...
                struct('type','matlab_expression','frame','world')}});
            testCase.verifyError(@() lmz.viz.SceneSpec(badType), ...
                'lmz:Scene:PrimitiveType');
            badOffset = struct('schemaVersion','1.0.0', ...
                'frames',{{'world'}},'primitives',{{ ...
                struct('type','text','frame','world','text','label', ...
                'offset',[0 0 0])}});
            testCase.verifyError(@() lmz.viz.SceneSpec(badOffset), ...
                'lmz:Scene:NumericStyle');
        end

        function kinematicsFrameRequiresFiniteNamedGeometry(testCase)
            frame = lmz.viz.KinematicsFrame(0, 1, ...
                struct('body',[1 2 0]), 'Vectors', struct('force',[0 1]));
            testCase.verifyEqual(frame.position('body'), [1 2]);
            testCase.verifyEqual(frame.vector('force'), [0 1]);
            testCase.verifyError(@() lmz.viz.KinematicsFrame(0, 1, ...
                struct('body',[NaN 0])), 'lmz:Scene:FrameValue');
        end
    end
end
