classdef TestNamedEventPrePostSection < matlab.unittest.TestCase
    methods (Test)
        function selectsExplicitResetSideAndRetainsBothStates(testCase)
            record = struct('Name', 'impact', 'Time', 0.4, ...
                'FromMode', 'flight_down', 'ToMode', 'flight_up', ...
                'PreState', [1;2;-3], 'PostState', [1;2;4], ...
                'Metadata', struct());
            pre = lmz.poincare.NamedEventSection( ...
                localDescriptor('impact_pre', 'pre'));
            post = lmz.poincare.NamedEventSection( ...
                localDescriptor('impact_post', 'post'));

            preCrossing = pre.crossingFromRecord(record);
            postCrossing = post.crossingFromRecord(record);
            testCase.verifyEqual(preCrossing.State, record.PreState);
            testCase.verifyEqual(postCrossing.State, record.PostState);
            testCase.verifyEqual(preCrossing.PreState, record.PreState);
            testCase.verifyEqual(preCrossing.PostState, record.PostState);
            testCase.verifyTrue(preCrossing.Accepted);
            testCase.verifyTrue(postCrossing.Accepted);
            testCase.verifyEqual( ...
                preCrossing.Metadata.TransversalityStatus, 'unavailable');
        end

        function acceptsNativeHybridEventId(testCase)
            record = struct('Id', 'impact', 'Time', 0.4, ...
                'FromMode', 'flight_down', 'ToMode', 'flight_up', ...
                'PreState', [0;0], 'PostState', [0;1], ...
                'DirectionalDerivative', -2, 'Metadata', struct());
            section = lmz.poincare.NamedEventSection( ...
                localDescriptor('impact_post', 'post'));
            crossing = section.crossingFromRecord(record);
            testCase.verifyEqual(crossing.EventId, 'impact');
            testCase.verifyEqual(crossing.CrossingDirection, -1);
            testCase.verifyEqual( ...
                crossing.Metadata.TransversalityStatus, 'transverse');
        end
    end
end

function value = localDescriptor(id, side)
value = lmz.poincare.PoincareSectionDescriptor(struct( ...
    'id', id, 'label', 'Impact', 'kind', 'named_event', ...
    'eventId', 'impact', 'crossingDirection', -1, ...
    'stateSide', side, 'minimumReturnTime', 0, ...
    'requiredEventSequence', {{}}, 'returnOccurrence', 1, ...
    'coordinateNames', {{}}, ...
    'symmetryClass', 'lmz.poincare.IdentitySymmetry', ...
    'maturities', {{'tutorial'}}, 'validationStatus', 'tested'));
end
