classdef TestSectionLocalContinuation < matlab.unittest.TestCase
    methods (Test)
        function transferredPairContinuesInTouchdownChart(testCase)
            context=lmz.api.RunContext.synchronous(1150);
            registry=lmz.registry.ModelRegistry.discover();
            model=registry.createModel('slip_quadruped');
            apex=model.createProblem('periodic_apex',struct());
            catalog=lmzmodels.slip_quadruped.RoadMapCatalog.default();
            branch=lmz.services.BranchService().loadRoadMapBranch( ...
                apex,catalog.defaultBranchPath());
            seedIndex=catalog.recommendedSeedIndex( ...
                catalog.defaultBranchPath());
            sourcePair=lmz.services.SeedService().adjacentBranchPair( ...
                apex,branch,seedIndex,1,struct(),context);
            first=lmz.services.SectionTransferService().transfer( ...
                model,sourcePair.First,'back_left_touchdown',context);
            second=lmz.services.SectionTransferService().transfer( ...
                model,sourcePair.Second,'back_left_touchdown',context);
            problem=model.createProblem('periodic_orbit', ...
                first.Solution.Lineage.Configuration);
            metric=lmz.schema.DiagonalMetric( ...
                problem.scale(second.Solution.DecisionValues));
            achieved=metric.norm(problem.difference( ...
                second.Solution.DecisionValues, ...
                first.Solution.DecisionValues));
            pair=lmz.data.SolutionPair(first.Solution,second.Solution, ...
                achieved,achieved,struct('SectionLocal',true));
            result=lmz.services.ContinuationService().run(problem,pair, ...
                struct('MaximumPoints',3,'BothDirections',false, ...
                'InitialStep',achieved,'MaximumStep',achieved),context);
            testCase.verifyEqual(result.Branch.pointCount(),3);
            for index=1:result.Branch.pointCount()
                point=result.Branch.point(index);
                testCase.verifyNumElements(point.DecisionValues,21);
                testCase.verifyEqual( ...
                    point.Lineage.Configuration.StartSectionId, ...
                    'back_left_touchdown');
                testCase.verifyEqual( ...
                    point.Lineage.Configuration.StopSectionId, ...
                    'back_left_touchdown');
                testCase.verifyLessThan(norm(problem.residual( ...
                    point.DecisionValues,point.ParameterValues,context)), ...
                    1e-8);
            end
        end
    end
end
