classdef TestTimingSolverSelection < matlab.unittest.TestCase
    methods (Test)
        function rejectsIncompatibleOrUnknownSolver(testCase)
            problem=lmztest.makeRectangularTimingProblem( ...
                'square',.4,true,1,false,struct( ...
                'FixedRowPolicy', ...
                'include_fixed_rows_in_least_squares'));
            service=lmz.services.ContactTimingService();
            testCase.verifyError(@()service.solve(problem, ...
                problem.InputSchedule,struct('Solver','fsolve'), ...
                lmz.api.RunContext.synchronous(1009)), ...
                'lmz:Solver:DimensionModeMismatch');
            testCase.verifyError(@()service.solve(problem, ...
                problem.InputSchedule,struct('Solver','mystery'), ...
                lmz.api.RunContext.synchronous(1010)), ...
                'lmz:Solver:UnknownSolver');
        end

        function validatedAutoSelectionIsRecorded(testCase)
            problem=lmztest.makeRectangularTimingProblem( ...
                'square',.4,true,1,false,struct( ...
                'FixedRowPolicy', ...
                'include_fixed_rows_in_least_squares'));
            result=lmz.services.ContactTimingService().solve(problem, ...
                problem.InputSchedule,struct(), ...
                lmz.api.RunContext.synchronous(1011));
            diagnostics=result.SolverDiagnostics.RankDiagnostics;
            testCase.verifyEqual(diagnostics.SolverRequested,'auto');
            testCase.verifyEqual(diagnostics.SolverSelected,'lsqnonlin');
            testCase.verifyEqual(diagnostics.SelectionReason, ...
                'validated_overdetermined_system');
        end


        function explicitFeasibilityModeAndAlgorithmsAreValidated(testCase)
            problem=lmztest.makeRectangularTimingProblem( ...
                'square',.45,false,1.05,false,struct());
            result=lmz.services.ContactTimingService().solve(problem, ...
                problem.InputSchedule,struct('Solver', ...
                'fmincon_feasibility','Algorithm','interior-point'), ...
                lmz.api.RunContext.synchronous(1014));
            testCase.verifyEqual(result.SolverDiagnostics. ...
                RankDiagnostics.SolverSelected,'fmincon_feasibility');
            testCase.verifyTrue(result.SolverDiagnostics.Success);
            testCase.verifyError(@()lmz.services.ContactTimingService().solve( ...
                problem,problem.InputSchedule,struct('Solver','lsqnonlin', ...
                'Algorithm','interior-point'), ...
                lmz.api.RunContext.synchronous(1015)), ...
                'lmz:Solver:Algorithm');
        end
    end
end
