classdef TestHeterogeneousStridePlan < matlab.unittest.TestCase
    %TESTHETEROGENEOUSSTRIDEPLAN Exercise two explicit, non-identical strides.
    methods (Test)
        function simulatesConsecutiveTutorialStrideSpecifications(testCase)
            gravity=9.81;
            firstPeriod=sqrt(8/gravity);
            secondPeriod=1.03*firstPeriod;
            specs(1,1)=makeSpec(1,firstPeriod,gravity, ...
                gravity*firstPeriod,'specified');
            specs(2,1)=makeSpec(2,secondPeriod,gravity, ...
                0.98*gravity*secondPeriod,'previous_terminal_state');
            energyPolicy=lmz.multistride.EnergyConsistencyPolicy( ...
                'Id','allow_non_neutral');
            plan=lmz.multistride.StridePlan( ...
                'ModelId','tutorial_hopper', ...
                'ProblemId','n_stride_simulation', ...
                'RequestedStrideCount',2, ...
                'InitialState',[0;1;1;0], ...
                'DefaultPhysicalParameters',struct('gravity',gravity), ...
                'StrideSpecs',specs,'EnergyPolicy',energyPolicy);
            request=lmz.multistride.MultiStrideRequest( ...
                'NumberOfStrides',2,'StridePlan',plan, ...
                'EnergyNeutralOnly',false,'EnergyPolicy',energyPolicy);

            result=lmz.services.MultiStrideSimulationService().simulate( ...
                lmzmodels.tutorial_hopper.Model(),request, ...
                lmz.api.RunContext.synchronous(1701));

            testCase.verifyEqual(result.CompletionStatus,'complete');
            testCase.verifyEqual(result.CompletedStrideCount,2);
            testCase.verifyTrue(result.Diagnostics.HeterogeneousStridePlan);
            testCase.verifyTrue(result.Diagnostics.StrictlyIncreasingTime);
            testCase.verifyFalse(result.Diagnostics.HiddenTimingSolve);
            testCase.verifyEqual(result.Diagnostics.ControlSequence, ...
                [gravity*firstPeriod;0.98*gravity*secondPeriod], ...
                'AbsTol',1e-12);
            testCase.verifyEqual( ...
                result.Diagnostics.StrideBoundaries(2).StartIndex, ...
                result.Diagnostics.StrideBoundaries(1).EndIndex+1);
            testCase.verifyTrue(isstruct( ...
                result.Diagnostics.StrideBoundaries));
            testCase.verifyEqual(result.Diagnostics.StrideBoundaries, ...
                result.Diagnostics.PerStrideBoundaries);
            testCase.verifyTrue(all(isfinite(result.Simulation.States(:))));
        end
    end
end

function value=makeSpec(index,period,gravity,impulse,source)
schedule=struct('Names',{{'impact','apex'}}, ...
    'Times',[period/2;period],'ReturnTime',period);
value=lmz.multistride.StrideSpec('Index',index, ...
    'StartSectionId','apex','StopSectionId','apex', ...
    'StopStateSide','post','EventSchedule',schedule, ...
    'PhysicalParameters',struct('gravity',gravity), ...
    'ControlParameters',struct('impulse',impulse), ...
    'InitialStateSource',source,'CompletionStatus','completed');
end
