classdef TestScientificMixedSectionTransitions < matlab.unittest.TestCase
    methods (Test)
        function routeIsRegisteredAndSolveOnly(testCase)
            registry=lmz.registry.ModelRegistry.discover();
            models={'slip_quadruped','slip_biped'};
            starts={'back_left_touchdown','left_touchdown'};
            for index=1:numel(models)
                descriptor=registry.getProblemDescriptor( ...
                    models{index},'section_transition');
                model=registry.createModel(models{index});
                testCase.verifyTrue(any(strcmp( ...
                    model.listProblems(),'section_transition')));
                testCase.verifyEqual(descriptor.maturity,'experimental');
                testCase.verifyEqual(descriptor.validationStatus,'tested');
                testCase.verifyEqual(descriptor.workflowKind, ...
                    'multiple_shooting');
                testCase.verifyTrue(descriptor.capabilities.solve);
                testCase.verifyFalse(descriptor.capabilities.continue);
                testCase.verifyFalse(descriptor.capabilities.simulate);
                sections=registry.getPoincareSectionRegistry(models{index});
                defaults=sections.DefaultSectionByProblem;
                testCase.verifyEqual(defaults.section_transition, ...
                    starts{index});
                testCase.verifyEqual(defaults.multiple_shooting, ...
                    starts{index});
            end
        end

        function registeredDefaultsCompleteRealServiceSolves(testCase)
            cases={ ...
                'slip_quadruped','back_left_touchdown', ...
                    'descending_y_0_9',1e-8; ...
                'slip_biped','left_touchdown', ...
                    'descending_y_0_95',1e-9};
            registry=lmz.registry.ModelRegistry.discover();
            options=struct('Solver','auto','Display','off', ...
                'MaxIterations',3,'MaxFunctionEvaluations',200, ...
                'ResidualTolerance',1e-7);
            for index=1:size(cases,1)
                model=registry.createModel(cases{index,1});
                problem=model.createProblem('section_transition',struct());
                seed=problem.makeSolution( ...
                    problem.getDecisionSchema().defaults(), ...
                    problem.getParameterSchema().defaults(),[]);
                result=lmz.services.MultipleShootingService().solve( ...
                    problem,seed,options, ...
                    lmz.api.RunContext.synchronous(1380+index));

                testCase.verifyEqual(problem.Configuration.StartSectionId, ...
                    cases{index,2});
                testCase.verifyEqual(problem.Configuration.StopSectionId, ...
                    cases{index,3});
                testCase.verifyEqual(problem.Formulation,'transition');
                testCase.verifyEqual(result.SolveResult.Output. ...
                    SolverSelected,'lsqnonlin');
                testCase.verifyEqual(result.FeasibilityReport. ...
                    Classification,'least_squares_feasible');
                testCase.verifyTrue(result.FeasibilityReport.Success);
                testCase.verifyLessThan(result.FeasibilityReport. ...
                    ScaledResidualNorm,cases{index,4});
                testCase.verifyFalse(problem.Horizon.Target.PeriodicClosure);
            end
        end

        function namedEventsReachDescendingPlanesAsTargets(testCase)
            cases={ ...
                'slip_quadruped','back_left_touchdown', ...
                    'descending_y_0_9',1e-9; ...
                'slip_biped','left_touchdown', ...
                    'descending_y_0_95',1e-10};
            registry=lmz.registry.ModelRegistry.discover();
            expected={'segment_1_contact_constraints'; ...
                'segment_1_section_residual';'interface_1_defect'; ...
                'final_transition_target'};
            for index=1:size(cases,1)
                model=registry.createModel(cases{index,1});
                problem=model.createProblem('section_transition',struct( ...
                    'StartSectionId',cases{index,2}, ...
                    'StopSectionId',cases{index,3}, ...
                    'EventFreeMask',false));
                u=problem.getDecisionSchema().defaults();
                p=problem.getParameterSchema().defaults();
                context=lmz.api.RunContext.synchronous(1300+index);
                evaluation=problem.evaluate(u,p,context,true);
                shooting=problem.evaluateShooting(u,p,context,false);
                names=arrayfun(@(item)item.Name, ...
                    evaluation.ResidualBlocks,'UniformOutput',false);

                testCase.verifyClass(problem, ...
                    'lmz.shooting.TransitionMultipleShootingProblem');
                testCase.verifyEqual(problem.Id,'section_transition');
                testCase.verifyEqual(problem.Formulation,'transition');
                testCase.verifyEqual(names,expected);
                testCase.verifyFalse(any(strcmp(names, ...
                    'final_section_closure')));
                testCase.verifyLessThan( ...
                    evaluation.ScaledResidualNorm,cases{index,4});
                testCase.verifyTrue(evaluation.PhysicalValidity);
                testCase.verifyTrue(evaluation.Feasibility.ResidualValid);
                testCase.verifyTrue(evaluation.Feasibility.CrossingsAccepted);
                crossing=shooting.SegmentResults{1}.Crossing;
                testCase.verifyTrue(crossing.Accepted);
                testCase.verifyFalse(crossing.Grazing);
                testCase.verifyEqual(crossing.CrossingDirection,-1);
                testCase.verifyLessThan(crossing.DirectionalDerivative,0);
                testCase.verifyEqual(problem.Horizon.Target.SectionId, ...
                    cases{index,3});
                testCase.verifyEqual(shooting.Diagnostics. ...
                    FinalResidualName,'final_transition_target');
                testCase.verifyEqual(shooting.Diagnostics.FinalResidualNorm,0, ...
                    'AbsTol',1e-12);
                testCase.verifyTrue(shooting.SegmentResults{1}. ...
                    Diagnostics.DirectSectionIntegration);
                testCase.verifyFalse(shooting.SegmentResults{1}. ...
                    Diagnostics.ApexOracleUsed);
            end
        end

        function reverseAndNamedEventPathsStayNonperiodic(testCase)
            cases={ ...
                'slip_quadruped','descending_y_0_9', ...
                    'back_left_touchdown'; ...
                'slip_quadruped','back_left_touchdown', ...
                    'front_left_touchdown'; ...
                'slip_quadruped','back_left_touchdown_descending', ...
                    'front_left_touchdown'; ...
                'slip_biped','descending_y_0_95','right_touchdown'; ...
                'slip_biped','left_touchdown','right_touchdown'; ...
                'slip_biped','left_touchdown_descending', ...
                    'right_touchdown'};
            registry=lmz.registry.ModelRegistry.discover();
            for index=1:size(cases,1)
                model=registry.createModel(cases{index,1});
                problem=model.createProblem('section_transition',struct( ...
                    'StartSectionId',cases{index,2}, ...
                    'StopSectionId',cases{index,3}));
                u=problem.getDecisionSchema().defaults();
                p=problem.getParameterSchema().defaults();
                context=lmz.api.RunContext.synchronous(1320+index);
                evaluation=problem.evaluate(u,p,context,false);
                shooting=problem.evaluateShooting(u,p,context,false);
                names=arrayfun(@(item)item.Name, ...
                    evaluation.ResidualBlocks,'UniformOutput',false);
                testCase.verifyTrue(evaluation.PhysicalValidity);
                testCase.verifyTrue( ...
                    shooting.SegmentResults{1}.Crossing.Accepted);
                testCase.verifyEqual( ...
                    shooting.SegmentResults{1}.Crossing.CrossingDirection,-1);
                testCase.verifyTrue(any(strcmp(names, ...
                    'final_transition_target')));
                testCase.verifyFalse(any(strcmp(names, ...
                    'final_section_closure')));
                testCase.verifyFalse(problem.Horizon.Target.PeriodicClosure);
            end
        end

        function safeCompositeStopsAreDirectAndAccepted(testCase)
            cases={ ...
                'slip_quadruped','back_left_touchdown', ...
                    'back_left_touchdown_descending',1e-9; ...
                'slip_biped','left_touchdown', ...
                    'left_touchdown_descending',1e-9};
            registry=lmz.registry.ModelRegistry.discover();
            for index=1:size(cases,1)
                model=registry.createModel(cases{index,1});
                problem=model.createProblem('section_transition',struct( ...
                    'StartSectionId',cases{index,2}, ...
                    'StopSectionId',cases{index,3}));
                u=problem.getDecisionSchema().defaults();
                p=problem.getParameterSchema().defaults();
                context=lmz.api.RunContext.synchronous(1340+index);
                evaluation=problem.evaluate(u,p,context,false);
                shooting=problem.evaluateShooting(u,p,context,false);
                crossing=shooting.SegmentResults{1}.Crossing;
                testCase.verifyLessThan( ...
                    evaluation.ScaledResidualNorm,cases{index,4});
                testCase.verifyTrue(evaluation.PhysicalValidity);
                testCase.verifyTrue(crossing.Accepted);
                testCase.verifyEqual(crossing.SectionId,cases{index,3});
                testCase.verifyLessThan(crossing.State(4),0);
            end
        end

        function terminalTargetResidualIsIndependentOfInterface(testCase)
            model=lmz.registry.ModelRegistry.discover(). ...
                createModel('slip_biped');
            problem=model.createProblem('section_transition',struct( ...
                'StartSectionId','left_touchdown', ...
                'StopSectionId','descending_y_0_95'));
            u=problem.getDecisionSchema().defaults();
            bindings=problem.ShootingSchema.Bindings;
            target=find(strcmp({bindings.Kind},'node_coordinate')& ...
                [bindings.OwnerIndex]==2,1);
            testCase.assertNotEmpty(target);
            u(target)=u(target)+0.01;
            evaluation=problem.evaluate(u, ...
                problem.getParameterSchema().defaults(), ...
                lmz.api.RunContext.synchronous(1360),false);
            names=arrayfun(@(item)item.Name,evaluation.ResidualBlocks, ...
                'UniformOutput',false);
            final=evaluation.ResidualBlocks(strcmp(names, ...
                'final_transition_target'));
            interface=evaluation.ResidualBlocks(strcmp(names, ...
                'interface_1_defect'));
            testCase.verifyEqual(final.Values(1),0.01,'AbsTol',1e-12);
            testCase.verifyEqual(interface.Values(1),-0.01,'AbsTol',1e-12);
        end

        function storedContractRebuildsTheSameTransition(testCase)
            model=lmz.registry.ModelRegistry.discover(). ...
                createModel('slip_quadruped');
            problem=model.createProblem('section_transition',struct( ...
                'StartSectionId','back_left_touchdown', ...
                'StopSectionId','descending_y_0_9'));
            contract=problem.contract();
            configuration=contract.Configuration;
            configuration.Horizon=problem.Horizon;
            configuration.ShootingDecisionSchema=problem.ShootingSchema;
            rebuilt=model.createProblem('section_transition',configuration);
            testCase.verifyEqual(lmz.io.ArtifactStore.dataHash( ...
                rebuilt.contract()),lmz.io.ArtifactStore.dataHash(contract));
        end

        function sameSectionClosureStillUsesPeriodicRoute(testCase)
            model=lmz.registry.ModelRegistry.discover(). ...
                createModel('slip_quadruped');
            periodic=model.createProblem('multiple_shooting',struct( ...
                'HorizonLength',1,'StartSectionId', ...
                'back_left_touchdown'));
            evaluation=periodic.evaluate( ...
                periodic.getDecisionSchema().defaults(), ...
                periodic.getParameterSchema().defaults(), ...
                lmz.api.RunContext.synchronous(1370),false);
            names=arrayfun(@(item)item.Name,evaluation.ResidualBlocks, ...
                'UniformOutput',false);
            testCase.verifyTrue(any(strcmp(names,'final_section_closure')));
            testCase.verifyFalse(any(strcmp(names, ...
                'final_transition_target')));
            testCase.verifyError(@()model.createProblem( ...
                'section_transition',struct('StartSectionId', ...
                'back_left_touchdown','StopSectionId', ...
                'back_left_touchdown')), ...
                'lmz:Shooting:TransitionDistinctSections');
        end
    end
end
