classdef TestShootingInitializerIntegration < matlab.unittest.TestCase
    methods (Test)
        function declaredStrategyDataAndReproducibleMultistartAreHonest(testCase)
            [~,~,schema]=lmztest.makeAnalyticShootingProblem(1);
            defaults=schema.defaults();
            undecorated=struct('Id','decision_only','Decision', ...
                defaults+[.1;-.1]);
            [fallback,emptyHistory]=lmz.shooting.ShootingInitializer(). ...
                initialize(schema,{undecorated},struct());
            testCase.verifyEqual(fallback,{defaults});
            testCase.verifyFalse(historyItem(emptyHistory, ...
                'nearest_compatible_template').Accepted);
            testCase.verifyFalse(historyItem(emptyHistory, ...
                'section_state_interpolation').Accepted);
            testCase.verifyFalse(historyItem(emptyHistory, ...
                'schema_scaled_secant').Accepted);

            exact=struct('Id','exact','Decision',defaults+[.2;-.2], ...
                'ExactHorizon',true,'Compatible',false);
            interpolated=struct('Id','interpolated', ...
                'InterpolatedDecision',defaults+[.3;-.3], ...
                'Compatible',false);
            pair=[defaults-[.4;-.2],defaults+[.2;.4]];
            secant=struct('Id','secant','DecisionPair',pair, ...
                'Compatible',false);
            options=struct('SecantFactor',.5,'MultistartCount',2, ...
                'MultistartScale',0,'RandomSeed',29);
            [candidates,history]=lmz.shooting.ShootingInitializer(). ...
                initialize(schema,{exact,interpolated,secant},options);

            testCase.verifyEqual(numel(candidates),5);
            testCase.verifyEqual(candidates{1},exact.Decision,'AbsTol',0);
            testCase.verifyEqual(candidates{2}, ...
                interpolated.InterpolatedDecision,'AbsTol',0);
            expected=pair(:,2)+.5*(pair(:,2)-pair(:,1));
            testCase.verifyEqual(candidates{3},expected,'AbsTol',0);
            testCase.verifyEqual(candidates{4},exact.Decision,'AbsTol',0);
            testCase.verifyEqual(candidates{5},exact.Decision,'AbsTol',0);
            testCase.verifyTrue(historyItem(history, ...
                'exact_source_horizon').Accepted);
            testCase.verifyFalse(historyItem(history, ...
                'nearest_compatible_template').Accepted);
            testCase.verifyFalse(historyItem(history, ...
                'phase_compatible_repeat').Accepted);
            testCase.verifyTrue(historyItem(history, ...
                'section_state_interpolation').Accepted);
            testCase.verifyTrue(historyItem(history, ...
                'schema_scaled_secant').Accepted);
            testCase.verifyEqual(sum(cellfun(@(item)strcmp( ...
                item.Strategy,'reproducible_multistart'),history)),2);
        end

        function explicitSeedAndProblemLineagePersistWithoutOptionLeak(testCase)
            sourceHistory={struct('StrideIndex',1, ...
                'Method','exact_source_horizon')};
            configuration=struct('InitializerDiagnostics',struct( ...
                'InitializationHistory',{sourceHistory}));
            [problem,~,~,seed]=lmztest.makeAnalyticShootingProblem(1, ...
                'Configuration',configuration);
            options=struct('Solver','fsolve','Display','off', ...
                'UseInitializer',false,'InitializerTemplates',{{}}, ...
                'InitializerOptions',struct('MultistartCount',4), ...
                'MultistartCount',3,'MultistartScale',.02, ...
                'RandomSeed',31,'SecantFactor',.5, ...
                'TemplateWeights',ones(numel(seed),1));
            result=lmz.services.MultipleShootingService().solve( ...
                problem,seed,options,lmz.api.RunContext.synchronous(31));

            testCase.verifyEqual(numel(result.InitializerHistory),2);
            testCase.verifyEqual(result.InitializerHistory{1}, ...
                sourceHistory{1});
            provided=result.InitializerHistory{2};
            testCase.verifyEqual(provided.Strategy,'provided_seed');
            testCase.verifyTrue(provided.SolverAttempted);
            testCase.verifyTrue(provided.SolverCompleted);
            testCase.verifyTrue(provided.Selected);
            testCase.verifyFalse(result.Diagnostics.Initializer.UseInitializer);
            forbidden={'UseInitializer','InitializerTemplates', ...
                'InitializerOptions','MultistartCount','MultistartScale', ...
                'RandomSeed','SecantFactor','TemplateWeights'};
            testCase.verifyFalse(any(isfield(result.SolveResult.Options, ...
                forbidden)));

            restored=lmz.shooting.ShootingResult.fromArtifact( ...
                result.toArtifact());
            testCase.verifyEqual(restored.InitializerHistory{1}, ...
                sourceHistory{1});
            testCase.verifyEqual(restored.InitializerHistory{2}.Strategy, ...
                'provided_seed');
            testCase.verifyTrue(restored.InitializerHistory{2}.Selected);
        end

        function emptyOrOptedInSeedRunsEveryGeneratedCandidate(testCase)
            [problem,~,~,seed]=lmztest.makeAnalyticShootingProblem(1);
            exact=struct('Id','exact','Decision',seed+[.2;-.2], ...
                'ExactHorizon',true,'Compatible',false);
            options=struct('Solver','fsolve','Display','off', ...
                'InitializerTemplates',{{exact}}, ...
                'InitializerOptions',struct('MultistartCount',2, ...
                'MultistartScale',0,'RandomSeed',37));
            generated=lmz.services.MultipleShootingService().solve( ...
                problem,[],options,lmz.api.RunContext.synchronous(37));
            testCase.verifyTrue(generated.Diagnostics.Initializer.UseInitializer);
            testCase.verifyEqual( ...
                generated.Diagnostics.Initializer.CandidateCount,3);
            testCase.verifyEqual( ...
                generated.Diagnostics.Initializer.CompletedSolveCount,3);
            testCase.verifyEqual(sum(cellfun(@solverAttempted, ...
                generated.InitializerHistory)),3);
            testCase.verifyEqual(sum(cellfun(@selected, ...
                generated.InitializerHistory)),1);

            options.UseInitializer=true;
            options.InitializerOptions.MultistartCount=0;
            optedIn=lmz.services.MultipleShootingService().solve( ...
                problem,seed,options,lmz.api.RunContext.synchronous(38));
            testCase.verifyTrue(optedIn.Diagnostics.Initializer.UseInitializer);
            testCase.verifyEqual(optedIn.Diagnostics.Initializer.CandidateCount,2);
            strategies=cellfun(@(item)fieldOr(item,'Strategy',''), ...
                optedIn.InitializerHistory,'UniformOutput',false);
            testCase.verifyTrue(any(strcmp(strategies,'provided_seed')));
            testCase.verifyTrue(any(strcmp(strategies, ...
                'exact_source_horizon')));
            testCase.verifyEqual(sum(cellfun(@solverAttempted, ...
                optedIn.InitializerHistory)),2);
        end
    end
end

function value=historyItem(history,strategy)
matches=cellfun(@(item)strcmp(item.Strategy,strategy),history);
value=history{find(matches,1)};
end

function value=solverAttempted(item)
value=isstruct(item)&&isfield(item,'SolverAttempted')&& ...
    item.SolverAttempted;
end

function value=selected(item)
value=isstruct(item)&&isfield(item,'Selected')&&item.Selected;
end

function value=fieldOr(source,name,fallback)
if isstruct(source)&&isfield(source,name),value=source.(name);else,value=fallback;end
end
