classdef TestTimingFamilyContinuation < matlab.unittest.TestCase
    methods (Test)
        function tracesOneDimensionalUngaugedFamily(testCase)
            base=lmztest.makeRectangularTimingProblem( ...
                'underdetermined',.4,false,1,false,struct());
            problem=lmz.schedule.TimingFamilyProblem(base, ...
                lmz.schedule.TimingGauge.empty(0,1),struct( ...
                'ExpectedLocalDimension',1));
            seed=problem.getDecisionSchema().defaults();
            options=struct('SecondSeedRadius',.01, ...
                'ContinuationOptions',struct('MaximumPoints',4, ...
                'BothDirections',false,'InitialStep',.01, ...
                'MaximumStep',.02));
            result=lmz.services.TimingContinuationService().run( ...
                problem,seed,options,lmz.api.RunContext.synchronous(1008));
            testCase.verifyEqual(result.Branch.pointCount(),4);
            returns=zeros(4,1);
            for index=1:4
                point=result.Branch.point(index);
                evaluation=problem.evaluate(point.DecisionValues,[], ...
                    lmz.api.RunContext.synchronous(0),false);
                testCase.verifyLessThan(evaluation.ScaledResidualNorm,1e-9);
                returns(index)=problem.scheduleFromDecision( ...
                    point.DecisionValues).ReturnTime;
            end
            testCase.verifyGreaterThan(max(returns)-min(returns),1e-4);
        end

        function artifactBindsConfigurationAndRejectsTampering(testCase)
            [artifact,original,pathCleanup]=publicTimingFamilyArtifact(); %#ok<ASGLU>
            lmz.io.ArtifactStore.validate(artifact);
            configuration=artifact.problemMetadata.configuration;
            expected=lmz.io.ArtifactStore.dataHash(configuration);
            testCase.verifyEqual(artifact.problemConfigurationHash,expected);
            testCase.verifyEqual(artifact.sourceDataHashes. ...
                ProblemConfiguration,expected);

            [reproduced,report]=lmz.services.reproduceRun(artifact,struct( ...
                'Context',lmz.api.RunContext.synchronous(1009)));
            testCase.verifyEqual(reproduced.Branch.pointCount(), ...
                original.Branch.pointCount());
            names={report.HashChecks.Name};
            location=find(strcmp(names,'ProblemConfiguration'));
            testCase.verifyEqual(numel(location),1);
            testCase.verifyTrue(report.HashChecks(location).Verified);
            testCase.verifyEqual(report.HashChecks(location).Status, ...
                'verified-payload');

            badConfiguration=artifact;
            badConfiguration.problemMetadata.configuration. ...
                ExpectedLocalDimension=0;
            testCase.verifyError( ...
                @()lmz.io.ArtifactStore.validate(badConfiguration), ...
                'lmz:Artifact:ProblemConfigurationHash');
            testCase.verifyError( ...
                @()lmz.services.reproduceRun(badConfiguration), ...
                'lmz:Artifact:ProblemConfigurationHash');

            rebasedConfiguration=badConfiguration;
            rebasedHash=lmz.io.ArtifactStore.dataHash( ...
                rebasedConfiguration.problemMetadata.configuration);
            rebasedConfiguration.problemConfigurationHash=rebasedHash;
            rebasedConfiguration.sourceDataHashes. ...
                ProblemConfiguration=rebasedHash;
            testCase.verifyError( ...
                @()lmz.io.ArtifactStore.validate(rebasedConfiguration), ...
                'lmz:Artifact:ProblemConfigurationPayload');

            badPayload=artifact;
            badPayload.continuationResult.Provenance. ...
                ProblemConfiguration.ExpectedLocalDimension=0;
            testCase.verifyError( ...
                @()lmz.io.ArtifactStore.validate(badPayload), ...
                'lmz:Artifact:ProblemConfigurationPayload');

            downgraded=artifact;
            downgraded.workflow.TimingFamily=false;
            testCase.verifyError( ...
                @()lmz.io.ArtifactStore.validate(downgraded), ...
                'lmz:Artifact:TimingFamilyWorkflow');

            executableConfiguration=artifact;
            executableConfiguration.problemMetadata.configuration. ...
                Callback=@sin;
            testCase.verifyError( ...
                @()lmz.io.ArtifactStore.validate( ...
                executableConfiguration), ...
                'lmz:Artifact:ExecutableWorkflowData');

            legacy=rmfield(artifact,'problemConfigurationHash');
            legacy.sourceDataHashes=rmfield(legacy.sourceDataHashes, ...
                'ProblemConfiguration');
            [loaded,artifactCleanup]=saveRawAndLoad(legacy); %#ok<ASGLU>
            testCase.verifyEqual(loaded.schemaVersion,'1.0.0');
            testCase.verifyEqual(loaded.problemConfigurationHash,expected);
            testCase.verifyEqual(loaded.sourceDataHashes. ...
                ProblemConfiguration,expected);
            clear artifactCleanup pathCleanup
        end
    end
end

function [artifact,result,cleanup]=publicTimingFamilyArtifact()
examplesRoot=fullfile(lmz.util.ProjectPaths.root(),'examples');
originalPath=path;addpath(examplesRoot);
cleanup=onCleanup(@()path(originalPath));
model=lmz.registry.ModelRegistry.discover().createModel('tutorial_hopper');
schedule=lmz.schedule.EventSchedule.fromCyclic({'impact'},0.4,1.0, ...
    'FixedMask',false,'ReturnTimeFixed',false,'MinimumGap',1e-8, ...
    'StartSectionId','apex','StopSectionId','apex');
provider=lmzexamples.AffineTimingFamilyProvider();
base=lmz.schedule.SectionReturnTimingProblem(model, ...
    'section_return_timing',provider,[0;1;1;0],9.81,schedule, ...
    struct('FixedRowPolicy','validate_fixed_rows'));
family=lmz.schedule.TimingFamilyProblem(base, ...
    lmz.schedule.TimingGauge.empty(0,1),struct( ...
    'ExpectedLocalDimension',1));
options=struct('SecondSeedRadius',0.01,'ResidualTolerance',1e-9, ...
    'ContinuationOptions',struct('MaximumPoints',3, ...
    'BothDirections',false,'InitialStep',0.01,'MinimumStep',1e-5, ...
    'MaximumStep',0.02,'CorrectorTolerance',1e-10));
result=lmz.services.TimingContinuationService().run(family, ...
    family.getDecisionSchema().defaults(),options, ...
    lmz.api.RunContext.synchronous(1009));
artifact=result.toArtifact();
end

function [loaded,cleanup]=saveRawAndLoad(artifact)
path=[tempname(tempdir) '.mat'];
cleanup=onCleanup(@()deleteIfPresent(path));
save(path,'artifact');
loaded=lmz.io.ArtifactStore.load(path);
end

function deleteIfPresent(path)
if exist(path,'file')==2,delete(path);end
end
