classdef TestShootingRunReproduction < matlab.unittest.TestCase
    methods (Test)
        function registeredModelRebuildsHashBoundProblem(testCase)
            model=lmz.registry.ModelRegistry.discover(). ...
                createModel('tutorial_hopper');
            problem=model.createProblem('multiple_shooting', ...
                struct('HorizonLength',2));
            source=lmz.services.MultipleShootingService().solve(problem, ...
                problem.getDecisionSchema().defaults(), ...
                struct('Solver','fsolve','Display','off'), ...
                lmz.api.RunContext.synchronous(1021));
            [reproduced,report]=lmz.services.reproduceRun( ...
                source.toArtifact());
            testCase.verifyClass(reproduced, ...
                'lmz.shooting.ShootingResult');
            testCase.verifyTrue(reproduced.FeasibilityReport.Success);
            testCase.verifyEqual(report.ArtifactType, ...
                'multiple-shooting-run');
            testCase.verifyEqual( ...
                reproduced.FeasibilityReport.ScaledResidualNorm, ...
                source.FeasibilityReport.ScaledResidualNorm, ...
                'AbsTol',1e-12);
        end
    end
end
