classdef TestMultiStrideFoundation < matlab.unittest.TestCase
    methods (Test)
        function exactOneTwoThreeFiveCodecAndTruncation(testCase)
            catalog=lmzmodels.slip_quad_load.ScientificDatasetCatalog.default();
            single=catalog.load('individual_1_tr_single');
            transition=catalog.load('individual_1_tr_to_rl');
            one=lmzmodels.slip_quad_load.XAccumPlanAdapter.toPlan(single.XAccum);
            two=lmzmodels.slip_quad_load.XAccumPlanAdapter.toPlan(transition.XAccum);
            testCase.verifyEqual( ...
                lmzmodels.slip_quad_load.XAccumPlanAdapter.encode(one),single.XAccum);
            testCase.verifyEqual( ...
                lmzmodels.slip_quad_load.XAccumPlanAdapter.encode(two),transition.XAccum);

            request=lmz.multistride.MultiStrideRequest('NumberOfStrides',5, ...
                'InitialDecision',transition.XAccum, ...
                'CompletionPolicy','predictor_corrector');
            result=lmzmodels.slip_quad_load.QuadLoadStridePlanBuilder().build( ...
                request,lmz.api.RunContext.synchronous(910));
            testCase.verifyEqual(result.CompletionStatus,'complete');
            testCase.verifyEqual(result.CompletedStrideCount,5);
            five=lmzmodels.slip_quad_load.XAccumPlanAdapter.encode(result.Plan);
            testCase.verifyEqual(numel(five),96);
            testCase.verifyEqual(five(1:57),transition.XAccum);
            testCase.verifyLessThan(find(five(54:57)<0,1),5);
            testCase.verifyEqual(lmzmodels.slip_quad_load.XAccumPlanAdapter.encode( ...
                lmzmodels.slip_quad_load.XAccumPlanAdapter.toPlan(five)),five);

            threePlan=result.Plan.truncate(3);
            three=lmzmodels.slip_quad_load.XAccumPlanAdapter.encode(threePlan);
            testCase.verifyEqual(numel(three),70);
            testCase.verifyEqual(lmzmodels.slip_quad_load.XAccumPlanAdapter.encode( ...
                lmzmodels.slip_quad_load.XAccumPlanAdapter.toPlan(three)),three);
            [twoAgain,twoDiagnostics]= ...
                lmzmodels.slip_quad_load.XAccumPlanAdapter.truncate(five,2);
            [oneAgain,oneDiagnostics]= ...
                lmzmodels.slip_quad_load.XAccumPlanAdapter.truncate(five,1);
            testCase.verifyEqual(twoAgain,transition.XAccum);
            testCase.verifyEqual(oneAgain,transition.XAccum(1:44));
            testCase.verifyTrue(twoDiagnostics.ExplicitTruncation);
            testCase.verifyEqual(oneDiagnostics.RetainedLength,44);
        end

        function completionPoliciesRemainExplicit(testCase)
            transition=loadTransition();builder= ...
                lmzmodels.slip_quad_load.QuadLoadStridePlanBuilder();
            base=lmzmodels.slip_quad_load.XAccumPlanAdapter.toPlan( ...
                transition.XAccum).withRequestedStrideCount(3);
            errorPlan=base.withPolicies('error_if_missing', ...
                base.EnergyPolicy,'return_partial');
            service=lmz.multistride.StridePlanCompletionService();
            testCase.verifyError(@()service.complete(builder,errorPlan,struct(), ...
                lmz.api.RunContext.synchronous(911)), ...
                'lmz:MultiStride:MissingStrideSpecification');
            userPlan=base.withPolicies('request_user',base.EnergyPolicy,'return_partial');
            missing=service.complete(builder,userPlan,struct(), ...
                lmz.api.RunContext.synchronous(912));
            testCase.verifyEqual(missing.CompletionStatus, ...
                'missing_stride_specification');
            testCase.verifyEqual(missing.Diagnostics.Code,'MissingStrideSpecification');
            testCase.verifyEqual(missing.CompletedStrideCount,2);
            testCase.verifyError(@()lmz.multistride.MissingStridePolicy('invent'), ...
                'lmz:MultiStride:MissingStridePolicy');
        end

        function carryForwardCopiesExactParametersAndControls(testCase)
            transition=loadTransition();request=lmz.multistride.MultiStrideRequest( ...
                'NumberOfStrides',5,'InitialDecision',transition.XAccum, ...
                'CompletionPolicy','carry_forward');
            checkpoints={};
            plan=lmzmodels.slip_quad_load.XAccumPlanAdapter.toPlan(transition.XAccum);
            plan=plan.withRequestedStrideCount(5).withPolicies( ...
                'carry_forward',plan.EnergyPolicy,'error');
            options=struct('CheckpointFcn',@captureCheckpoint);
            result=lmz.multistride.StridePlanCompletionService().complete( ...
                lmzmodels.slip_quad_load.QuadLoadStridePlanBuilder(),plan, ...
                options,lmz.api.RunContext.synchronous(913));
            testCase.verifyEqual(result.CompletedStrideCount,request.NumberOfStrides);
            testCase.verifyEqual(numel(checkpoints),3);
            for index=3:5
                previous=result.Plan.StrideSpecs(index-1);
                current=result.Plan.StrideSpecs(index);
                testCase.verifyEqual(current.PhysicalParameters, ...
                    previous.PhysicalParameters);
                testCase.verifyEqual(current.ControlParameters.PreSwingStiffness, ...
                    previous.ControlParameters.PostSwingStiffness);
                testCase.verifyEqual(current.ControlParameters.PostSwingStiffness, ...
                    previous.ControlParameters.PostSwingStiffness);
                testCase.verifyEqual(current.Diagnostics.Energy.EnergyDelta,0);
            end
            function captureCheckpoint(value),checkpoints{end+1}=value;end
        end

        function eventOrderChangeUsesRecordedPredictorFallback(testCase)
            transition=loadTransition();request=lmz.multistride.MultiStrideRequest( ...
                'NumberOfStrides',3,'InitialDecision',transition.XAccum, ...
                'CompletionPolicy','predictor_corrector');
            result=lmzmodels.slip_quad_load.QuadLoadStridePlanBuilder().build( ...
                request,lmz.api.RunContext.synchronous(914));
            prediction=result.Plan.StrideSpecs(3).Diagnostics.Prediction;
            testCase.verifyEqual(prediction.Method, ...
                'carry_forward_after_incompatible_chart');
            testCase.verifyEqual(prediction.FallbackReason,'event_order_changed');
            testCase.verifyFalse(prediction.UsedSecant);
        end

        function stiffnessChangeRequiresEnergyOrDeclaredWork(testCase)
            transition=loadTransition();plan= ...
                lmzmodels.slip_quad_load.XAccumPlanAdapter.toPlan(transition.XAccum);
            plan=plan.withRequestedStrideCount(3).withPolicies( ...
                'carry_forward',plan.EnergyPolicy,'error');
            previous=plan.StrideSpecs(2);changed= ...
                previous.ControlParameters.PostSwingStiffness+[2;-3;4;-5];
            options=struct('ParameterOverrides',struct( ...
                'PostSwingStiffness',changed), ...
                'TransitionState',plan.InitialState);
            builder=lmzmodels.slip_quad_load.QuadLoadStridePlanBuilder();
            testCase.verifyError(@()builder.completeNext(plan,options, ...
                lmz.api.RunContext.synchronous(915)), ...
                'lmz:MultiStride:EnergyTransition');

            candidate=makeCandidate(previous,changed);
            policy=lmzmodels.slip_quad_load.QuadLoadEnergyPolicy();
            [work,details]=policy.parameterTransitionEnergy( ...
                plan.InitialState,previous,candidate);
            options.DeclaredWork=work;
            completed=builder.completeNext(plan,options, ...
                lmz.api.RunContext.synchronous(916));
            energy=completed.StrideSpecs(3).Diagnostics.Energy;
            testCase.verifyEqual(energy.DeclaredWork,work,'AbsTol',1e-12);
            testCase.verifyEqual(energy.EnergyModel.PerLegDelta, ...
                details.PerLegDelta,'AbsTol',1e-12);
            testCase.verifyTrue(energy.Accepted);
            options.ParameterOverrides=struct('UnknownGain',1);
            testCase.verifyError(@()builder.completeNext(plan,options, ...
                lmz.api.RunContext.synchronous(917)), ...
                'lmz:MultiStride:UnknownEnergyEffect');
        end

        function sourceLocalTransitionAndWorldTranslationAreExact(testCase)
            map=lmzmodels.slip_quad_load.QuadLoadStrideTransitionMap();
            terminal=(1:18).';physical=struct('LoadVector',[.8;.5;.1;2;8;0]);
            local=map.map(terminal,physical);
            testCase.verifyEqual(local,[0;terminal(2:14);14;16;.8;0]);
            rows=[local.';local.'];world=map.toWorld(rows,14);
            testCase.verifyEqual(world(:,1),[14;14]);
            testCase.verifyEqual(world(:,15),[28;28]);
            diagnostics=map.mapWithDiagnostics(terminal,physical);
            testCase.verifyEqual(diagnostics.WorldTranslation,terminal(1));
            testCase.verifyEqual(diagnostics.LoadRelativePosition,14);
        end

        function artifactCloneAndCoreContainNoInteractiveCalls(testCase)
            transition=loadTransition();plan= ...
                lmzmodels.slip_quad_load.XAccumPlanAdapter.toPlan(transition.XAccum);
            restored=lmz.multistride.StridePlan.fromArtifact(plan.toArtifact());
            testCase.verifyEqual( ...
                lmzmodels.slip_quad_load.XAccumPlanAdapter.encode(restored), ...
                transition.XAccum);
            testCase.verifyEqual(plan.clone().toStruct(),plan.toStruct());
            roots={fullfile(lmz.util.ProjectPaths.root(),'src','+lmz','+multistride'), ...
                fullfile(lmz.util.ProjectPaths.root(),'models','+lmzmodels', ...
                '+slip_quad_load')};
            names={'StrideSpec.m','StridePlan.m','MultiStrideRequest.m', ...
                'MultiStrideResult.m','StridePlanValidator.m','StridePlanBuilder.m', ...
                'StridePlanCompletionService.m','MissingStridePolicy.m', ...
                'ParameterTransitionPolicy.m','EnergyConsistencyPolicy.m', ...
                'StrideTransitionMap.m','XAccumPlanAdapter.m', ...
                'QuadLoadStrideTransitionMap.m','QuadLoadEnergyPolicy.m', ...
                'QuadLoadStridePlanBuilder.m'};
            expression='(^|[^A-Za-z0-9_])(input|uigetfile|uigetdir|uiputfile|uialert|figure)\s*\(';
            for index=1:numel(names)
                root=roots{1};if index>11,root=roots{2};end
                source=fileread(fullfile(root,names{index}));
                testCase.verifyEmpty(regexp(source,expression,'once'),names{index});
            end
        end
    end
end

function value=loadTransition()
value=lmzmodels.slip_quad_load.ScientificDatasetCatalog.default().load( ...
    'individual_1_tr_to_rl');
end
function value=makeCandidate(previous,post)
controls=struct('PreSwingStiffness', ...
    previous.ControlParameters.PostSwingStiffness, ...
    'PostSwingStiffness',post(:));
value=lmz.multistride.StrideSpec('Index',previous.Index+1, ...
    'StartSectionId',previous.StartSectionId, ...
    'StopSectionId',previous.StopSectionId, ...
    'StartStateSide',previous.StartStateSide, ...
    'StopStateSide',previous.StopStateSide, ...
    'EventSchedule',previous.EventSchedule, ...
    'PhysicalParameters',previous.PhysicalParameters, ...
    'ControlParameters',controls,'CompletionStatus','completed');
end
