classdef TestSectionTransferOrbitEquivalence < matlab.unittest.TestCase
    methods (Test)
        function tutorialRephasePreservesClosedPhysicalOrbit(testCase)
            registry=lmz.registry.ModelRegistry.discover();
            model=registry.createModel('tutorial_hopper');
            problem=model.createProblem('periodic_hop',struct());
            context=lmz.api.RunContext.synchronous(930);
            u=problem.getDecisionSchema().defaults();
            p=problem.getParameterSchema().defaults();
            evaluation=problem.evaluate(u,p,context,true);
            source=problem.makeSolution(u,p,evaluation);

            result=lmz.services.SectionTransferService().transfer( ...
                model,source,'ground_impact_post',context);
            testCase.verifyEqual(result.Crossing.SectionId, ...
                'ground_impact_post');
            testCase.verifyEqual(result.Lineage.SourceSectionId,'apex');
            testCase.verifyEqual(result.Lineage.TargetSectionId, ...
                'ground_impact_post');
            testCase.verifyLessThanOrEqual(result.PhysicalOrbitMaxError, ...
                10*eps);
            testCase.verifyTrue(result.PhaseInvariantObservablesPreserved);
            testCase.verifyTrue(result.DecisionCodecRephased);
            testCase.verifyEqual(result.Solution.ProblemId, ...
                'periodic_orbit');
            testCase.verifyEqual( ...
                result.Solution.Lineage.Configuration.StartSectionId, ...
                'ground_impact_post');
            testCase.verifyEqual( ...
                result.Solution.Lineage.Configuration.StopSectionId, ...
                'ground_impact_post');
            targetProblem=model.createProblem(result.Solution.ProblemId, ...
                result.Solution.Lineage.Configuration);
            reproduced=targetProblem.evaluate( ...
                result.Solution.DecisionValues, ...
                result.Solution.ParameterValues,context,true);
            testCase.verifyEqual(reproduced.Simulation.Time, ...
                result.Simulation.Time,'AbsTol',1e-12);
            testCase.verifyEqual(reproduced.Simulation.States, ...
                result.Simulation.States,'AbsTol',1e-12);
            testCase.verifyGreaterThan(min(diff(result.Simulation.Time)),0);
        end
    end
end
