classdef TestRankAwareBoundedSquareSelection < matlab.unittest.TestCase
    methods (Test)
        function autoUsesBoundedLeastSquaresForSquareProblem(testCase)
            problem=lmztest.BoundedSquareProblem();
            context=lmz.api.RunContext.synchronous(1910);
            [result,diagnostics]=lmz.solvers. ...
                RankAwareNonlinearSolver().solve(problem,0.25,[], ...
                struct('Solver','auto','Display','off', ...
                'ResidualTolerance',1e-10),context);

            testCase.verifyEqual(diagnostics.M,1);
            testCase.verifyEqual(diagnostics.N,1);
            testCase.verifyEqual(diagnostics.SolverSelected,'lsqnonlin');
            testCase.verifyEqual(diagnostics.SelectionReason, ...
                'bounded_square_system');
            testCase.verifyEqual(diagnostics.AlgorithmSelected, ...
                'trust-region-reflective');
            testCase.verifyGreaterThanOrEqual( ...
                result.Solution.DecisionValues,0);
            testCase.verifyLessThanOrEqual( ...
                result.Solution.DecisionValues,1);
            testCase.verifyLessThan( ...
                result.Evaluation.ScaledResidualNorm,1e-10);
        end

        function explicitFsolveRejectsIgnoredBounds(testCase)
            problem=lmztest.BoundedSquareProblem();
            testCase.verifyError(@()lmz.solvers. ...
                RankAwareNonlinearSolver().solve(problem,0.25,[], ...
                struct('Solver','fsolve'), ...
                lmz.api.RunContext.synchronous(1911)), ...
                'lmz:Solver:BoundedFsolveUnsupported');
        end
    end
end
