classdef TestFixedContactResidualValidated < matlab.unittest.TestCase
    methods (Test)
        function fixedEventAndReturnRemainPhysicalConditions(testCase)
            eventFixed=lmztest.makeRectangularTimingProblem( ...
                'square',.4,true,1,false,struct());
            first=lmz.services.ContactTimingService().solve(eventFixed, ...
                eventFixed.InputSchedule,struct(), ...
                lmz.api.RunContext.synchronous(1002));
            testCase.verifyTrue(first.SolverDiagnostics.Success);
            testCase.verifyTrue(first.SolverDiagnostics. ...
                SuccessCriteria.FixedRowsValid);

            returnFixed=lmztest.makeRectangularTimingProblem( ...
                'square',.4,false,1,true,struct());
            second=lmz.services.ContactTimingService().solve(returnFixed, ...
                returnFixed.InputSchedule,struct(), ...
                lmz.api.RunContext.synchronous(1003));
            testCase.verifyTrue(second.SolverDiagnostics.Success);
            testCase.verifyTrue(second.SolverDiagnostics. ...
                SuccessCriteria.FixedRowsValid);
        end


        function allFixedScheduleUsesValidationWithoutSolver(testCase)
            problem=lmztest.makeRectangularTimingProblem( ...
                'square',.4,true,1,true,struct());
            testCase.verifyEqual(problem.unknownDimension(),0);
            testCase.verifyEqual(problem.residualDimension(),0);
            result=lmz.services.ContactTimingService().solve(problem, ...
                problem.InputSchedule,struct(), ...
                lmz.api.RunContext.synchronous(1017));
            testCase.verifyTrue(result.SolverDiagnostics.Success);
            testCase.verifyEqual(result.SolverDiagnostics. ...
                RankDiagnostics.SolverSelected, ...
                'fixed-decision-validation');
        end
    end
end
