classdef TestXAccumFirstStrideLayout < matlab.unittest.TestCase
    methods (Test)
        function exactFortyFourEntryContract(testCase)
            expected={'quad_dx','quad_y','quad_dy','quad_phi','quad_dphi', ...
                'alphaBL','dalphaBL','alphaFL','dalphaFL','alphaBR','dalphaBR', ...
                'alphaFR','dalphaFR','tBL_TD','tBL_LO','tFL_TD','tFL_LO', ...
                'tBR_TD','tBR_LO','tFR_TD','tFR_LO','tAPEX','leg_stiffness', ...
                'swing_pre_BL','swing_pre_FL','swing_pre_BR','swing_pre_FR', ...
                'swing_post_BL','swing_post_FL','swing_post_BR','swing_post_FR', ...
                'torso_inertia','leg_length','swing_neutral_angle', ...
                'back_attachment_ratio','back_front_stiffness_ratio','load_x', ...
                'load_dx','load_height','load_mass','load_friction', ...
                'tugline_rest_length','tugline_stiffness','slope_angle'};
            testCase.verifyEqual(lmzmodels.slip_quad_load.FirstStrideLayout.names(),expected);
            indices=lmzmodels.slip_quad_load.FirstStrideLayout.indices();
            testCase.verifyEqual(indices.QuadrupedState,1:13);
            testCase.verifyEqual(indices.EventTiming,14:22);
            testCase.verifyEqual(indices.QuadrupedParameters,23:36);
            testCase.verifyEqual(indices.LoadState,37:38);
            testCase.verifyEqual(indices.LoadParameters,39:44);
            dataset=lmzmodels.slip_quad_load.ScientificDatasetCatalog.default().load( ...
                'individual_1_tr_single');decoded=dataset.Decoded.FirstStride;
            testCase.verifyEqual(decoded.Vector,dataset.XAccum);
            testCase.verifyEqual(decoded.QuadrupedState,dataset.XAccum(1:13));
            testCase.verifyEqual(decoded.EventTiming,dataset.XAccum(14:22));
            testCase.verifyEqual(decoded.QuadrupedParameters,dataset.XAccum(23:36));
            testCase.verifyEqual(decoded.LoadState,dataset.XAccum(37:38));
            testCase.verifyEqual(decoded.LoadParameters,dataset.XAccum(39:44));
        end
    end
end
