classdef TestContinuationMinimumStep < matlab.unittest.TestCase
    methods (Test)
        function repeatedRejectionStopsBeforeSubminimumAttempt(testCase)
            [problem,pair,context]=makeAnalyticContinuationCase(730);
            result=lmz.services.ContinuationService().run(problem,pair, ...
                struct('MaximumPoints',5,'BothDirections',false, ...
                'InitialStep',0.04,'MinimumStep',0.03,'MaximumStep',0.04, ...
                'ShrinkFactor',0.5,'MaxBacktracks',10, ...
                'AcceptanceFcn',@(~,~)false),context);
            testCase.verifyEqual(result.TerminationReason,'minimum_step');
            testCase.verifyEqual(result.Diagnostics.rejectedAttempts,1);
            testCase.verifyEqual(result.Snapshots(end).StepSize,0.04, ...
                'AbsTol',1e-12);
            testCase.verifyEqual(result.Snapshots(end).Diagnostics. ...
                TerminationCandidate,'minimum_step');
        end
    end
end
