classdef TestQuadLoadEnergyNeutralControlSolve < matlab.unittest.TestCase
    methods (Test)
        function explicitHyperplaneProjectionIsExactButSearchRemainsUnresolved(testCase)
            mask=false(3,4);mask(3,:)=true;
            configuration=struct('NumberOfStrides',3, ...
                'EnergyMode',{{'diagnostic_only','diagnostic_only', ...
                'energy_neutral'}},'FreeControlMask',mask, ...
                'UnboundedControls',true,'ExpectedLocalDimension',3);
            problem=lmzmodels.slip_quad_load. ...
                QuadLoadMultipleShootingProblem([],configuration);
            continuation=lmzmodels.slip_quad_load. ...
                QuadLoadHorizonContinuation();
            [decision,projection]=continuation.projectEnergyNeutral( ...
                problem,3,problem.Codec.decisionDefaults());
            residual=problem.evaluateShooting(decision,[], ...
                lmz.api.RunContext.synchronous(0),false);
            testCase.verifyTrue(projection.ExactWithinTolerance);
            testCase.verifyLessThan(abs( ...
                residual.SegmentResults{3}.EnergyResidual),1e-10);

            evidence=lmzmodels.slip_quad_load.QuadLoadFeasibilityEvidence();
            record=evidence.caseRecord( ...
                'case_b_energy_neutral_controls_best_known');
            testCase.verifyEqual(record.jacobianRankEstimate,70);
            testCase.verifyEqual(record.nullity,3);
            [candidateProblem,~]=evidence.problemFor(record.id);
            testCase.verifyEqual(candidateProblem.expectedLocalDimension(),3);
            testCase.verifyEqual(numel(record.changedControls),4);
            testCase.verifyEqual(record.controlChangeReport.finalControls, ...
                record.changedControls,'AbsTol',0);
            testCase.verifyEqual(record.controlChangeReport. ...
                deltaFromBaseline,record.controlChangeReport.finalControls- ...
                record.controlChangeReport.baselineControls,'AbsTol',1e-12);
            testCase.verifyEqual(record.controlChangeReport.lowerBounds, ...
                {'-Inf';'-Inf';'-Inf';'-Inf'});
            testCase.verifyEqual(record.controlChangeReport.upperBounds, ...
                {'Inf';'Inf';'Inf';'Inf'});
            testCase.verifyEmpty(record.activeLowerBounds);
            testCase.verifyEmpty(record.activeUpperBounds);
            testCase.verifyGreaterThan(abs(record.energyConstraintResidual), ...
                1e-8);
            testCase.verifyFalse(record.rootFound);
            testCase.verifyFalse(record.globalInfeasibilityClaimed);
        end

        function strictEnergyAcceptanceOverridesLooseGlobalTolerance(testCase)
            mask=false(2,4);mask(2,1)=true;
            configuration=struct('NumberOfStrides',2, ...
                'SectionId','stride_boundary', ...
                'EventFreeMask',[true false], ...
                'EnergyMode',{{'diagnostic_only','energy_neutral'}}, ...
                'FreeControlMask',mask,'EnergyScale',1, ...
                'EnergyTolerance',1e-12,'ResidualTolerance',1e6);
            problem=lmzmodels.slip_quad_load. ...
                QuadLoadMultipleShootingProblem([],configuration);
            decision=problem.Codec.decisionDefaults();
            names=problem.Codec.DecisionSchema.names();
            index=find(strcmp(names,'segment_2_post_swing_1'),1);
            testCase.assertNotEmpty(index);
            decision(index)=decision(index)+1;
            residual=problem.evaluateShooting(decision,[], ...
                lmz.api.RunContext.synchronous(0),false);

            testCase.verifyTrue(residual.Feasibility.ResidualValid);
            testCase.verifyFalse(residual.SegmentResults{2}. ...
                Diagnostics.Energy.Accepted);
            testCase.verifyFalse(residual.Feasibility.EnergyValid);
            testCase.verifyFalse(residual.Feasibility.PhysicalValidity);
            testCase.verifyFalse( ...
                residual.Feasibility.PhysicalConditionsValid);
            testCase.verifyFalse(residual.Feasibility.Valid);
            report=problem.analyze(decision, ...
                lmz.api.RunContext.synchronous(0),struct( ...
                'ComputeJacobian',false,'SolverExitFlag',1));
            testCase.verifyEqual(report.Classification, ...
                'physical_validation_failure');
        end
    end
end
