classdef TestContinuationHistoricalLoopClosure < matlab.unittest.TestCase
    methods (Test)
        function candidateOnHistoricalSegmentClosesLoop(testCase)
            [problem,pair,context]=makeAnalyticContinuationCase(733);
            firstRun=lmz.services.ContinuationService().run(problem,pair, ...
                struct('MaximumPoints',3,'BothDirections',false, ...
                'InitialStep',0.05,'MaximumStep',0.05),context);
            candidate=firstRun.Branch.point(3).DecisionValues;
            offset=[0.02;0];
            history=[candidate+offset,candidate-offset, ...
                pair.First.DecisionValues,pair.Second.DecisionValues];
            [problem,pair,context]=makeAnalyticContinuationCase(734);
            result=lmz.services.ContinuationService().run(problem,pair, ...
                struct('MaximumPoints',4,'BothDirections',false, ...
                'InitialStep',0.05,'MaximumStep',0.05, ...
                'HistoryDecisionValues',history, ...
                'DuplicateTolerance',1e-7,'LoopClosureTolerance',1e-9),context);
            testCase.verifyEqual(result.TerminationReason,'loop_closure');
            testCase.verifyEqual(result.Branch.pointCount(),3);
            testCase.verifyEqual(result.Snapshots(end).Diagnostics. ...
                TerminationCandidate,'loop_closure');
        end
    end
end
