classdef TestQuadLoadTemplateSelection < matlab.unittest.TestCase
    methods (Test)
        function exactCompatibleSegmentWinsScaledSelection(testCase)
            context=lmz.api.RunContext.synchronous(0);
            library=lmzmodels.slip_quad_load.StrideTemplateLibrary();
            source=library.load('individual_1_identical_tr_to_rl',context);
            expected=source.Segments(2);
            query=struct('InitialSectionState',expected.InitialSectionState, ...
                'EventSchedule',expected.EventSchedule, ...
                'ControlParameters',expected.ControlParameters, ...
                'PhysicalParameters',expected.PhysicalParameters, ...
                'GaitLabel',source.GaitLabel);
            [actual,diagnostics]=library.select(query,context);
            testCase.verifyEqual(actual.TemplateId,source.Id);
            testCase.verifyEqual(actual.StrideIndex,2);
            testCase.verifyEqual(diagnostics.CandidateCount,7);
            testCase.verifyEqual(diagnostics.Method, ...
                'scaled_state_schedule_control_physics_gait_v1');
        end

        function phaseRepeatAndEventMaskAreApplied(testCase)
            configuration=struct('NumberOfStrides',3, ...
                'TemplateId','individual_1_tr_to_rl', ...
                'InitializationStrategy','phase_compatible_repeat', ...
                'EventFreeMask',[false true]);
            [horizon,diagnostics]=lmzmodels.slip_quad_load. ...
                QuadLoadHorizonInitializer().create(configuration, ...
                lmz.api.RunContext.synchronous(17));

            testCase.verifyEqual(horizon.segmentCount(),3);
            testCase.verifyEqual( ...
                diagnostics.InitializationHistory{3}.Method, ...
                'phase_compatible_repeat');
            testCase.verifyEqual( ...
                diagnostics.InitializationHistory{3}.Attempts{2}.Strategy, ...
                'phase_compatible_repeat');
            testCase.verifyTrue( ...
                diagnostics.InitializationHistory{3}.Attempts{2}.Accepted);
            schedule=horizon.Segments{3}.EventSchedule;
            testCase.verifyTrue(all(schedule.fixedMask()));
            testCase.verifyFalse(schedule.ReturnTimeFixed);
            testCase.verifyEqual(schedule.times(), ...
                horizon.Segments{2}.EventSchedule.times(),'AbsTol',0);
        end
    end
end
