classdef TestScientificSectionLocalShooting < matlab.unittest.TestCase
    methods (Test)
        function touchdownProblemsOwnTargetSectionCharts(testCase)
            cases={ ...
                'slip_quadruped','back_left_touchdown',21,1e-8; ...
                'slip_biped','left_touchdown',11,1e-9};
            registry=lmz.registry.ModelRegistry.discover();
            for index=1:size(cases,1)
                model=registry.createModel(cases{index,1});
                configuration=localConfiguration(cases{index,2});
                problem=model.createProblem('periodic_orbit',configuration);
                u=problem.getDecisionSchema().defaults();
                p=problem.getParameterSchema().defaults();
                evaluation=problem.evaluate(u,p, ...
                    lmz.api.RunContext.synchronous(1000+index),true);
                testCase.verifyNumElements(u,cases{index,3});
                testCase.verifyNumElements(evaluation.Residual,cases{index,3});
                testCase.verifyLessThan( ...
                    evaluation.ScaledResidualNorm,cases{index,4});
                testCase.verifyTrue( ...
                    evaluation.Diagnostics.DirectSectionIntegration);
                testCase.verifyFalse( ...
                    evaluation.Diagnostics.SourceApexPhaseGaugePreserved);
                testCase.verifyFalse( ...
                    evaluation.Diagnostics.PostProcessedTrajectoryRephase);
                testCase.verifyEqual(evaluation.Simulation.Time(1),0);
                testCase.verifyEqual(evaluation.Simulation.Time(end), ...
                    problem.SectionCodec.decode(u).ReturnTime,'AbsTol',1e-12);
                testCase.verifyEqual(evaluation.Simulation.States(1,:).', ...
                    problem.SectionCodec.decode(u).InitialState,'AbsTol',1e-12);
                names=arrayfun(@(x)x.Name,evaluation.ResidualBlocks, ...
                    'UniformOutput',false);
                testCase.verifyFalse(any(contains(names,'apex_phase_gauge')));
            end
        end

        function preResetAndCompositeSectionsArePhysical(testCase)
            cases={ ...
                'slip_quadruped','back_left_touchdown_pre',1e-8,'pre'; ...
                'slip_quadruped','back_left_touchdown_descending',1e-8,'post'; ...
                'slip_biped','left_touchdown_pre',1e-9,'pre'; ...
                'slip_biped','left_touchdown_descending',1e-9,'post'};
            registry=lmz.registry.ModelRegistry.discover();
            for index=1:size(cases,1)
                model=registry.createModel(cases{index,1});
                problem=model.createProblem('periodic_orbit', ...
                    localConfiguration(cases{index,2}));
                evaluation=problem.evaluate( ...
                    problem.getDecisionSchema().defaults(), ...
                    problem.getParameterSchema().defaults(), ...
                    lmz.api.RunContext.synchronous(1010+index),true);
                testCase.verifyLessThan( ...
                    evaluation.ScaledResidualNorm,cases{index,3});
                testCase.verifyTrue(evaluation.Diagnostics.StopCrossing.accepted);
                testCase.verifyEqual( ...
                    evaluation.Diagnostics.StopCrossing.stateSide, ...
                    cases{index,4});
                testCase.verifyTrue(isfinite(evaluation.Diagnostics. ...
                    StopCrossing.directionalDerivative));
            end
        end

        function descendingPlaneProblemsCorrectToTransverseReturns(testCase)
            cases={ ...
                'slip_quadruped','descending_y_0_9',21; ...
                'slip_biped','descending_y_0_95',11};
            registry=lmz.registry.ModelRegistry.discover();
            for index=1:size(cases,1)
                model=registry.createModel(cases{index,1});
                problem=model.createProblem('periodic_orbit', ...
                    localConfiguration(cases{index,2}));
                seed=problem.makeSolution( ...
                    problem.getDecisionSchema().defaults(), ...
                    problem.getParameterSchema().defaults(),[]);
                solved=lmz.services.SolveService().solve(problem,seed, ...
                    struct('FunctionTolerance',1e-10, ...
                    'StepTolerance',1e-10,'MaximumIterations',100), ...
                    lmz.api.RunContext.synchronous(1020+index));
                testCase.verifyGreaterThan(solved.ExitFlag,0);
                testCase.verifyLessThan( ...
                    solved.Evaluation.ScaledResidualNorm,1e-9);
                testCase.verifyTrue(solved.Evaluation.PhysicalValidity);
                testCase.verifyEqual(solved.Evaluation.Diagnostics. ...
                    StopCrossing.crossingDirection,-1);
                testCase.verifyFalse(solved.Evaluation.Diagnostics. ...
                    StopCrossing.grazing);
                testCase.verifyNumElements( ...
                    solved.Solution.DecisionValues,cases{index,3});
            end
        end

        function touchdownTimingBindsEndpointToReturnTime(testCase)
            cases={ ...
                'slip_quadruped','back_left_touchdown',8,7; ...
                'slip_biped','left_touchdown',4,3};
            registry=lmz.registry.ModelRegistry.discover();
            for index=1:size(cases,1)
                model=registry.createModel(cases{index,1});
                problem=model.createProblem('section_return_timing', ...
                    localConfiguration(cases{index,2}));
                u=problem.getDecisionSchema().defaults();
                evaluation=problem.evaluate(u,[], ...
                    lmz.api.RunContext.synchronous(1030+index),true);
                bindings=evaluation.Diagnostics.ContactRowBindings;
                testCase.verifyNumElements(u,cases{index,3});
                testCase.verifyNumElements(evaluation.Residual,cases{index,3});
                testCase.verifyEqual(problem.InputSchedule.count(), ...
                    cases{index,4});
                testCase.verifyEqual(sum(strcmp({bindings.Kind},'return')),1);
                testCase.verifyTrue(evaluation.PhysicalValidity);
                testCase.verifyTrue(evaluation.Diagnostics. ...
                    ProviderDiagnostics.DirectSectionIntegration);
                testCase.verifyLessThan(evaluation.ScaledResidualNorm,1e-8);
            end
        end

        function transferProducesReproducibleTargetLocalSolutions(testCase)
            cases={ ...
                'slip_quadruped','back_left_touchdown',21; ...
                'slip_biped','left_touchdown',11};
            registry=lmz.registry.ModelRegistry.discover();
            for index=1:size(cases,1)
                model=registry.createModel(cases{index,1});
                apex=model.createProblem('periodic_apex',struct());
                u=apex.getDecisionSchema().defaults();
                p=apex.getParameterSchema().defaults();
                context=lmz.api.RunContext.synchronous(1040+index);
                sourceEvaluation=apex.evaluate(u,p,context,true);
                source=apex.makeSolution(u,p,sourceEvaluation);
                transferred=lmz.services.SectionTransferService().transfer( ...
                    model,source,cases{index,2},context);
                testCase.verifyTrue(transferred.DecisionCodecRephased);
                testCase.verifyEqual(transferred.Solution.ProblemId, ...
                    'periodic_orbit');
                testCase.verifyNumElements( ...
                    transferred.Solution.DecisionValues,cases{index,3});
                target=model.createProblem('periodic_orbit', ...
                    transferred.Solution.Lineage.Configuration);
                reproduced=target.evaluate( ...
                    transferred.Solution.DecisionValues, ...
                    transferred.Solution.ParameterValues,context,true);
                testCase.verifyEqual(reproduced.Simulation.Time, ...
                    transferred.Simulation.Time,'AbsTol',1e-12);
                testCase.verifyEqual(reproduced.Simulation.States, ...
                    transferred.Simulation.States,'AbsTol',1e-12);
                testCase.verifyEqual(reproduced.Simulation.States(1,:).', ...
                    transferred.Crossing.State,'AbsTol',2e-12);
                apexAgain=lmz.services.SectionTransferService().transfer( ...
                    model,transferred.Solution,'apex',context);
                testCase.verifyTrue(apexAgain.DecisionCodecRephased);
                testCase.verifyNumElements( ...
                    apexAgain.Solution.DecisionValues, ...
                    apex.getDecisionSchema().count());
                apexResidual=vertcat( ...
                    apexAgain.Solution.ResidualBlocks.Values);
                testCase.verifyLessThan(norm(apexResidual),1e-8);
            end
        end

        function mixedPeriodicEndpointsRequireTransitionProblem(testCase)
            registry=lmz.registry.ModelRegistry.discover();
            model=registry.createModel('slip_quadruped');
            configuration=struct('StartSectionId', ...
                'back_left_touchdown','StopSectionId','descending_y_0_9');
            testCase.verifyError(@()model.createProblem( ...
                'periodic_orbit',configuration), ...
                'lmz:Shooting:TransitionProblemRequired');
            testCase.verifyError(@()model.createProblem( ...
                'section_return_timing',configuration), ...
                'lmz:Timing:UnsupportedSection');
        end
    end
end

function value=localConfiguration(sectionId)
value=struct('StartSectionId',sectionId,'StopSectionId',sectionId, ...
    'SymmetryId','planar_translation');
end
