classdef TestHorizonContinuationArtifactReproduction < matlab.unittest.TestCase
    methods (Test)
        function adaptiveProtocolRoundTripsAndReplays(testCase)
            registry=lmz.registry.ModelRegistry.discover();
            model=registry.createModel('tutorial_hopper');
            initialProblem=model.createProblem('multiple_shooting', ...
                struct('HorizonLength',2));
            seed=initialProblem.getDecisionSchema().defaults();
            configurations={struct('HorizonLength',2), ...
                struct('HorizonLength',3)};
            options=struct('SolverOptions',struct( ...
                'ResidualTolerance',1e-8), ...
                'UseAdaptiveHomotopy',true, ...
                'HomotopyInitialStep',0.5, ...
                'HomotopyMaximumStep',0.5);
            context=lmz.api.RunContext.synchronous(2201);
            service=lmz.services.HorizonContinuationService();
            result=service.run(model,'multiple_shooting', ...
                configurations,seed,options,context);
            artifact=service.toArtifact(result,'tutorial_hopper', ...
                'multiple_shooting',configurations,seed,options);

            lmz.io.ArtifactStore.validate(artifact);
            [reproduced,report]=lmz.services.reproduceRun(artifact,struct( ...
                'Registry',registry,'Context', ...
                lmz.api.RunContext.synchronous(2201)));
            testCase.verifyEqual(artifact.artifactType, ...
                'horizon-continuation-run');
            testCase.verifyEqual(artifact.terminationReason, ...
                'horizon-continuation-complete');
            testCase.verifyEqual(reproduced.Horizon.segmentCount(),3);
            testCase.verifyTrue( ...
                reproduced.ContinuationHistory{2}.Homotopy.Completed);
            testCase.verifyEqual( ...
                reproduced.SolveResult.Solution.DecisionValues, ...
                result.SolveResult.Solution.DecisionValues,'AbsTol',1e-10);
            testCase.verifyEqual(report.ArtifactType, ...
                'horizon-continuation-run');
        end
    end
end
