classdef TestPoincareSectionDescriptor < matlab.unittest.TestCase
    methods (Test)
        function roundTripAndFingerprintAreStable(testCase)
            value = struct('id', 'apex', 'label', 'Apex', ...
                'kind', 'state_plane', 'stateName', 'vy', ...
                'threshold', 0, 'crossingDirection', -1, ...
                'stateSide', 'post', 'minimumReturnTime', 1e-6, ...
                'requiredEventSequence', {{'impact'}}, ...
                'returnOccurrence', 1, ...
                'coordinateNames', {{'vx','y'}}, ...
                'symmetryClass', ...
                'lmz.poincare.PlanarTranslationSymmetry', ...
                'symmetryParameters', struct( ...
                'id', 'planar_translation', ...
                'positionStateNames', {{'x'}}), ...
                'modeRestriction', 'flight_up', ...
                'maturities', {{'tutorial'}}, ...
                'validationStatus', 'tested');
            descriptor = lmz.poincare.PoincareSectionDescriptor(value);
            restored = lmz.poincare.PoincareSectionDescriptor( ...
                descriptor.toStruct());

            testCase.verifyEqual(restored.Id, 'apex');
            testCase.verifyEqual(restored.RequiredEventSequence, {'impact'});
            testCase.verifyEqual(restored.CoordinateNames, {'vx','y'});
            testCase.verifyEqual(restored.fingerprint(), ...
                descriptor.fingerprint());
            testCase.verifyLength(descriptor.fingerprint(), 64);
        end

        function rejectsInvalidDirectionAndExecutableClassText(testCase)
            value = struct('id', 'impact', 'label', 'Impact', ...
                'kind', 'named_event', 'eventId', 'impact', ...
                'crossingDirection', 2);
            testCase.verifyError(@() ...
                lmz.poincare.PoincareSectionDescriptor(value), ...
                'lmz:Poincare:CrossingDirection');

            value.crossingDirection = -1;
            value.implementationClass = 'system(''unsafe'')';
            testCase.verifyError(@() ...
                lmz.poincare.PoincareSectionDescriptor(value), ...
                'lmz:Poincare:DescriptorClass');
        end
    end
end
