classdef TestQuadrupedWorkflowDescriptor < matlab.unittest.TestCase
    methods (Test)
        function registeredReferenceMetadataIsSourceEquivalent(testCase)
            registry=lmz.registry.ModelRegistry.discover();
            cleanup=onCleanup(@()delete(registry));
            workflows=lmz.workflow.WorkflowRegistry.fromModelRegistry(registry);
            descriptor=workflows.get( ...
                'slip_quadruped','roadmap_root_continuation');

            testCase.verifyEqual(descriptor.SchemaVersion,'1.0.0');
            testCase.verifyEqual(descriptor.ModelId,'slip_quadruped');
            testCase.verifyEqual(descriptor.ProblemId,'periodic_apex');
            testCase.verifyEqual(descriptor.Maturity,'validated');
            testCase.verifyEqual( ...
                descriptor.ValidationStatus,'source-equivalent');
            testCase.verifyEqual(descriptor.DataSourceId,'roadmap');
            testCase.verifyEqual(descriptor.DefaultDatasetId,'PK_20_2');
            testCase.verifyEqual(descriptor.DefaultPointIndex,267);
            testCase.verifyEqual(descriptor.AxisPresetId,'roadmap_top');
            testCase.verifyEqual( ...
                descriptor.VisualizationProfileId,'research_legacy');
            testCase.verifyEqual( ...
                descriptor.LayoutProfileId,'scientific_workbench');
            testCase.verifyEqual(descriptor.AxisPreset.X,'dx');
            testCase.verifyEqual(descriptor.AxisPreset.Y,'dphi');
            testCase.verifyEqual(descriptor.AxisPreset.Z,'y');
            testCase.verifyEqual(descriptor.AxisPreset.Dimension,'2-D');
            testCase.verifyEqual(descriptor.AxisPreset.Elevation,90);
            testCase.verifyEqual( ...
                descriptor.SeedPreset.FirstSeed,'locked_roadmap_point');
            testCase.verifyEqual(descriptor.SeedPreset.SecondSeedOptions, ...
                {'adjacent_next','adjacent_previous','generated_corrected'});
            testCase.verifyEqual( ...
                descriptor.ContinuationPreset.DirectionMode,'both');
            testCase.verifyTrue( ...
                descriptor.ContinuationPreset.CheckpointEnabled);
            testCase.verifyEqual(descriptor.ContinuationPreset. ...
                DirectionLabels.backward,'decreasing dx');
            testCase.verifyEqual(descriptor.ContinuationPreset. ...
                DirectionLabels.forward,'increasing dx');
            testCase.verifyTrue(all(ismember({'physical_simulation', ...
                'torso_trajectory','back_leg_trajectories', ...
                'front_leg_trajectories','ground_reaction_forces', ...
                'oscillator'},descriptor.AnalysisViews)));
            testCase.verifyEqual(descriptor.Provenance.sourceCommit, ...
                '2c106101383ecee1b2a9d695efe09fbd72d5718a');
            testCase.verifyEqual(descriptor.Provenance.sourceSHA256, ...
                ['45835bb5024b1dc9b875c7b8f7b205769f537a4f' ...
                'f4144c763058537f44dbf401']);
            testCase.verifyClass(descriptor.createDataSourceProvider(), ...
                'lmzmodels.slip_quadruped.RoadMapDataSourceProvider');
            clear cleanup
        end

        function touchdownWorkflowDeclaresSectionTransfer(testCase)
            registry=lmz.registry.ModelRegistry.discover();
            cleanup=onCleanup(@()delete(registry));
            workflows=lmz.workflow.WorkflowRegistry.fromModelRegistry(registry);
            descriptor=workflows.get( ...
                'slip_quadruped','touchdown_root_continuation');
            testCase.verifyEqual(descriptor.ProblemId,'periodic_orbit');
            testCase.verifyEqual( ...
                descriptor.DataSource.ProblemId,'periodic_apex');
            testCase.verifyTrue(descriptor.allows('section_transfer'));
            testCase.verifyEqual( ...
                descriptor.ProblemConfiguration.StartSectionId, ...
                'back_left_touchdown');
            testCase.verifyEqual( ...
                descriptor.ProblemConfiguration.StopSectionId, ...
                'back_left_touchdown');
            clear cleanup
        end
    end
end
