classdef TestHorizonFeasibilityArtifactReproduction < matlab.unittest.TestCase
    methods (Test)
        function persistsAndReplaysAnalysisOnlyEvidence(testCase)
            registry=lmz.registry.ModelRegistry.discover();
            model=registry.createModel('tutorial_hopper');
            problem=model.createProblem('multiple_shooting',struct( ...
                'NumberOfSegments',2));
            seed=problem.getDecisionSchema().defaults();
            service=lmz.services.FeasibilityAnalysisService();
            artifact=service.toArtifact(problem,seed,[], ...
                struct('ResidualTolerance',1e-9), ...
                lmz.api.RunContext.synchronous(1801));

            lmz.io.ArtifactStore.validate(artifact);
            testCase.verifyEqual(artifact.artifactType, ...
                'horizon-feasibility-run');
            testCase.verifyTrue(artifact.horizonFeasibility.AnalysisOnly);
            testCase.verifyFalse( ...
                artifact.horizonFeasibility.GlobalInfeasibilityProven);

            [reproduced,reproduction]=lmz.services.reproduceRun( ...
                artifact,struct('Registry',registry,'Context', ...
                lmz.api.RunContext.synchronous(1801)));
            testCase.verifyClass(reproduced, ...
                'lmz.shooting.FeasibilityReport');
            testCase.verifyEqual(reproduced.Classification, ...
                artifact.feasibilityReport.Classification);
            testCase.verifyEqual(reproduced.ScaledResidualNorm, ...
                artifact.feasibilityReport.ScaledResidualNorm, ...
                'AbsTol',1e-12);
            testCase.verifyEqual(reproduction.ArtifactType, ...
                'horizon-feasibility-run');
        end
    end
end
