classdef TestNoHiddenTimingSolveInObjective < matlab.unittest.TestCase
    %TESTNOHIDDENTIMINGSOLVEINOBJECTIVE Guard the fixed-timing objective.
    methods (Test)
        function objectiveSourceContainsNoTimingSolverCall(testCase)
            path=which('lmzmodels.slip_quad_load.MultiStrideFitProblem');
            source=fileread(path);
            testCase.verifyEmpty(regexp(source, ...
                'ContactTimingService|SolveService|\<fsolve\s*\(', ...
                'once'));
        end

        function diagnosticsDeclareFixedPrecompletedTiming(testCase)
            problem=lmzmodels.slip_quad_load.Model().createProblem( ...
                'n_stride_fit',struct());
            [~,~,diagnostics]=problem.evaluateObjective( ...
                problem.getDecisionSchema().defaults(), ...
                problem.getParameterSchema().defaults(), ...
                lmz.api.RunContext.synchronous(0));
            testCase.verifyEqual(diagnostics.TimingMode, ...
                'fixed_precompleted');
            testCase.verifyFalse(diagnostics.HiddenTimingSolve);
        end


        function legacyOracleIsExplicitlyLabeled(testCase)
            problem=lmzmodels.slip_quad_load.Model().createProblem( ...
                'multi_stride_fit',struct());
            [~,~,diagnostics]=problem.evaluateObjective( ...
                problem.getDecisionSchema().defaults(), ...
                problem.getParameterSchema().defaults(), ...
                lmz.api.RunContext.synchronous(0));
            testCase.verifyEqual(diagnostics.TimingMode, ...
                'legacy_source_timing_projection');
            testCase.verifyTrue(diagnostics.HiddenTimingSolve);
            testCase.verifyTrue(diagnostics.SourceEquivalent);
        end
    end
end
