classdef TestChangingPeriodRetraction < matlab.unittest.TestCase
    methods (Test)
        function usesCandidatePeriod(testCase)
            specs = [ ...
                lmz.schema.VariableSpec('period', 'DefaultValue', 10, ...
                    'Topology', 'positive', 'LowerBound', 0); ...
                lmz.schema.VariableSpec('event', 'DefaultValue', 9, ...
                    'Topology', 'cyclic_time', 'PeriodSource', 'period')];
            chart = lmz.schema.VariableChart( ...
                lmz.schema.VariableSchema(specs));
            candidate = chart.retract([10; 9], [-4; 0]);
            testCase.verifyEqual(candidate, [6; 3], 'AbsTol', 1e-12);
        end
    end
end
