classdef TestQuadLoadGRFEquivalence < matlab.unittest.TestCase
    methods (Test)
        function allTwelveChannelsMatchCapturedSource(testCase)
            fixture=loadFixture();expected=fixture.Entries(2);tolerance=fixture.Tolerances;
            dataset=lmzmodels.slip_quad_load.ScientificDatasetCatalog.default().load( ...
                'individual_1_tr_to_rl');
            actual=lmzmodels.slip_quad_load.MultiStrideSimulator().runRaw( ...
                dataset.XAccum,lmz.api.RunContext.synchronous(504),false);
            testCase.verifySize(actual.LegacyGroundReactionForces,[numel(actual.LegacyTime) 12]);
            testCase.verifyEqual(actual.LegacyGroundReactionForces, ...
                expected.GroundReactionForces,'AbsTol',tolerance.GRFAbsolute, ...
                'RelTol',tolerance.GRFRelative);
            testCase.verifyEqual(abs(actual.GroundReactionForces(:,1:4)), ...
                sqrt(actual.GroundReactionForces(:,5:8).^2+ ...
                actual.GroundReactionForces(:,9:12).^2), ...
                'AbsTol',10*tolerance.GRFAbsolute,'RelTol',10*tolerance.GRFRelative);
        end
    end
end
function baseline=loadFixture()
loaded=load(fullfile(lmz.util.ProjectPaths.tests(),'fixtures','baselines', ...
    'slip_quad_load','source_baselines.mat'),'baseline');baseline=loaded.baseline;
end
