classdef TestGrazingSectionDiagnostic < matlab.unittest.TestCase
    methods (Test)
        function tangentialCrossingIsDiagnosedAndRejected(testCase)
            schema = lmz.schema.VariableSchema([ ...
                lmz.schema.VariableSpec('x'); ...
                lmz.schema.VariableSpec('y')]);
            descriptor = lmz.poincare.PoincareSectionDescriptor(struct( ...
                'id', 'plane', 'label', 'Plane', ...
                'kind', 'state_plane', 'stateName', 'y', ...
                'threshold', 0, 'crossingDirection', 0, ...
                'stateSide', 'post', 'minimumReturnTime', 0, ...
                'requiredEventSequence', {{}}, 'returnOccurrence', 1, ...
                'coordinateNames', {{'x'}}, ...
                'symmetryClass', 'lmz.poincare.IdentitySymmetry', ...
                'maturities', {{'experimental'}}, ...
                'validationStatus', 'tested'));
            section = lmz.poincare.StateFunctionSection( ...
                descriptor, schema);

            crossing = section.crossingAt(1, [2;0], [1;0]);
            testCase.verifyTrue(crossing.Grazing);
            testCase.verifyFalse(crossing.Accepted);
            testCase.verifyEqual(crossing.RejectionReason, 'grazing');
            testCase.verifyEqual( ...
                crossing.Metadata.TransversalityStatus, 'grazing');
        end
    end
end
