classdef TestNonApexQuadrupedTiming < matlab.unittest.TestCase
    methods (Test)
        function touchdownReturnExecutesWithExplicitRankQualification(testCase)
            model=lmz.registry.ModelRegistry.discover(). ...
                createModel('slip_quadruped');
            problem=model.createProblem('section_return_timing', ...
                localConfiguration('back_left_touchdown'));
            context=lmz.api.RunContext.synchronous(1170);
            result=lmz.services.ContactTimingService().solve(problem, ...
                problem.InputSchedule,struct('Display','off', ...
                'ResidualTolerance',1e-8),context);
            rank=result.SolverDiagnostics.RankDiagnostics;
            bindings=problem.evaluate( ...
                problem.getDecisionSchema().defaults(),[],context,false). ...
                Diagnostics.ContactRowBindings;
            testCase.verifyEqual([rank.M rank.N],[8 8]);
            testCase.verifyLessThan(norm(result.ContactResiduals),1e-8);
            testCase.verifyTrue(result.SolverDiagnostics.Feasibility.Valid);
            testCase.verifyTrue(result.SolverDiagnostics. ...
                InitialStateBitwiseUnchanged);
            testCase.verifyTrue(result.SolverDiagnostics. ...
                PhysicalParametersBitwiseUnchanged);
            testCase.verifyEqual(sum(strcmp({bindings.Kind},'return')),1);
            testCase.verifyTrue(result.SolverDiagnostics. ...
                SuccessCriteria.ActiveResidualValid);
            testCase.verifyTrue(result.SolverDiagnostics.Success);
            testCase.verifyEqual(result.SolverDiagnostics.Status, ...
                'converged');
            testCase.verifyFalse(result.SolverDiagnostics. ...
                SuccessCriteria.RankConditionRequired);
            testCase.verifyFalse(result.SolverDiagnostics. ...
                SuccessCriteria.UniquenessValidated);
            testCase.verifyGreaterThan(rank.Nullity,0);
            testCase.verifyEqual(result.SolverDiagnostics. ...
                SuccessCriteria.RankQualification, ...
                'rank_deficient_root_not_a_unique_parameterization');
        end
    end
end

function value=localConfiguration(sectionId)
value=struct('StartSectionId',sectionId,'StopSectionId',sectionId, ...
    'SymmetryId','planar_translation');
end
