classdef TestQuadLoadProblemCountRouting < matlab.unittest.TestCase
    %TESTQUADLOADPROBLEMCOUNTROUTING Count-aware legacy/N-stride routing.
    methods (Test)
        function bareLegacyProblemsRemainExact(testCase)
            model=lmzmodels.slip_quad_load.Model();
            single=model.createProblem('single_stride',struct());
            fit=model.createProblem('multi_stride_fit',struct());

            testCase.verifyClass(single, ...
                'lmzmodels.slip_quad_load.SingleStrideProblem');
            testCase.verifyEqual(single.Id,'single_stride');
            testCase.verifyEqual(single.getDecisionSchema().count(),44);
            testCase.verifyTrue(single.SourceEquivalent);
            testCase.verifyClass(fit, ...
                'lmzmodels.slip_quad_load.MultiStrideFitProblem');
            testCase.verifyEqual(fit.Id,'multi_stride_fit');
            testCase.verifyEqual(fit.getDecisionSchema().count(),57);
            testCase.verifyEqual(fit.ObjectiveTimingMode, ...
                'legacy_source_timing_projection');
            testCase.verifyTrue(fit.SourceEquivalent);
        end

        function explicitCountsDelegateToNStrideForms(testCase)
            model=lmzmodels.slip_quad_load.Model();
            simulation=model.createProblem('single_stride', ...
                struct('NumberOfStrides',2));
            fit=model.createProblem('multi_stride_fit', ...
                struct('NumberOfStrides',1,'InitialPerturbation',0));

            testCase.verifyClass(simulation, ...
                'lmz.multistride.NStrideSimulationProblem');
            testCase.verifyEqual(simulation.Id,'n_stride_simulation');
            testCase.verifyEqual(simulation.getRequest().NumberOfStrides,2);
            testCase.verifyEqual(numel( ...
                simulation.getRequest().InitialDecision),57);
            testCase.verifyClass(fit, ...
                'lmzmodels.slip_quad_load.MultiStrideFitProblem');
            testCase.verifyEqual(fit.Id,'n_stride_fit');
            testCase.verifyEqual(fit.getDecisionSchema().count(),44);
            testCase.verifyEqual(fit.ObjectiveTimingMode, ...
                'fixed_precompleted');
            testCase.verifyFalse(fit.SourceEquivalent);
            request=lmz.api.SimulationRequest('slip_quad_load', ...
                'single_stride',struct(),struct('NumberOfStrides',2));
            trajectory=model.simulate(request, ...
                lmz.api.RunContext.synchronous(0));
            testCase.verifyClass(trajectory,'lmz.api.SimulationResult');
            testCase.verifyEqual(max(trajectory.Modes.stride_index),2);
        end

        function singleStrideTruncatesSuppliedPlanAndVector(testCase)
            model=lmzmodels.slip_quad_load.Model();
            dataset=multiDataset();
            plan=lmzmodels.slip_quad_load.XAccumPlanAdapter.toPlan( ...
                dataset.XAccum);
            fromPlan=model.createProblem('single_stride',struct( ...
                'NumberOfStrides',1,'StridePlan',plan));
            fromVector=model.createProblem('single_stride',struct( ...
                'NumberOfStrides',1,'InitialDecision',dataset.XAccum));

            testCase.verifyClass(fromPlan, ...
                'lmzmodels.slip_quad_load.SingleStrideProblem');
            testCase.verifyEqual(numel(fromPlan.SourceDecision),44);
            testCase.verifyTrue(fromPlan.InputTruncationDiagnostics. ...
                ExplicitTruncation);
            testCase.verifyEqual(fromPlan.InputTruncationDiagnostics.Source, ...
                'StridePlan');
            testCase.verifyEqual(fromVector.SourceDecision, ...
                fromPlan.SourceDecision,'AbsTol',0);
            testCase.verifyEqual(fromVector.InputTruncationDiagnostics.Source, ...
                'InitialDecision');
            evaluation=fromPlan.evaluate(fromPlan.SourceDecision, ...
                fromPlan.getParameterSchema().defaults(), ...
                lmz.api.RunContext.synchronous(0),false);
            testCase.verifyTrue(evaluation.Diagnostics.InputTruncated);
            testCase.verifyEqual(evaluation.Diagnostics.InputTruncation. ...
                OriginalStrideCount,2);
            testCase.verifyEqual(evaluation.Diagnostics.InputTruncation. ...
                RetainedStrideCount,1);
        end

        function generalizedFitTruncatesSuppliedPlanAndVector(testCase)
            model=lmzmodels.slip_quad_load.Model();
            dataset=multiDataset();
            plan=lmzmodels.slip_quad_load.XAccumPlanAdapter.toPlan( ...
                dataset.XAccum);
            fromPlan=model.createProblem('multi_stride_fit',struct( ...
                'NumberOfStrides',1,'StridePlan',plan, ...
                'InitialPerturbation',0));
            fromVector=model.createProblem('multi_stride_fit',struct( ...
                'NumberOfStrides',1,'InitialDecision',dataset.XAccum, ...
                'InitialPerturbation',0));
            fromIncompletePlan=model.createProblem('multi_stride_fit',struct( ...
                'NumberOfStrides',1, ...
                'StridePlan',plan.withRequestedStrideCount(3), ...
                'InitialPerturbation',0));

            testCase.verifyEqual(fromPlan.Id,'n_stride_fit');
            testCase.verifyEqual(fromPlan.getDecisionSchema().count(),44);
            testCase.verifyTrue(fromPlan.InputTruncationDiagnostics. ...
                ExplicitTruncation);
            testCase.verifyEqual(fromPlan.InputTruncationDiagnostics.Source, ...
                'StridePlan');
            testCase.verifyEqual(fromVector.InputTruncationDiagnostics.Source, ...
                'InitialDecision');
            testCase.verifyEqual(fromIncompletePlan. ...
                InputTruncationDiagnostics.OriginalRequestedStrideCount,3);
            testCase.verifyEqual( ...
                fromIncompletePlan.StridePlan.RequestedStrideCount,1);
            [~,~,diagnostics]=fromVector.evaluateObjective( ...
                fromVector.sourceSeed(), ...
                fromVector.getParameterSchema().defaults(), ...
                lmz.api.RunContext.synchronous(0));
            testCase.verifyTrue(diagnostics.InputTruncated);
            testCase.verifyEqual(diagnostics.InputTruncation.OriginalLength,57);
            testCase.verifyEqual(diagnostics.InputTruncation.RetainedLength,44);
            testCase.verifyFalse(diagnostics.HiddenTimingSolve);
        end

        function optimizationRejectsUndersuppliedPlan(testCase)
            dataset=multiDataset();
            action=@()lmzmodels.slip_quad_load.Model().createProblem( ...
                'multi_stride_fit',struct('NumberOfStrides',3, ...
                'InitialDecision',dataset.XAccum, ...
                'ReferenceExtensionPolicy','repeat_final_reference'));
            testCase.verifyError(action, ...
                'lmz:MultiStride:OptimizationPlanIncomplete');
        end
    end
end

function value=multiDataset()
catalog=lmzmodels.slip_quad_load.ScientificDatasetCatalog.default();
value=lmzmodels.slip_quad_load.XAccumAdapter.loadDataset( ...
    catalog.defaultMultiPath());
end
