classdef TestScientificHomogeneousN2MultipleShooting < ...
        matlab.unittest.TestCase
    %TESTSCIENTIFICHOMOGENEOUSN2MULTIPLESHOOTING Executed Q/B evidence.
    methods (Test)
        function quadrupedN2IsQualifiedLeastSquaresFeasible(testCase)
            verifySolve(testCase,lmzmodels.slip_quadruped.Model(),55,13,7201);
        end

        function bipedN2IsQualifiedLeastSquaresFeasible(testCase)
            verifySolve(testCase,lmzmodels.slip_biped.Model(),29,7,7202);
        end

        function factoryHonorsApplicableGenericMasks(testCase)
            problem=lmzmodels.slip_quadruped.Model().createProblem( ...
                'multiple_shooting',struct('HorizonLength',2, ...
                'InterfaceStateMask',false, ...
                'EventFreeMask',[false true], ...
                'ControlFreeMask',false, ...
                'EnergyWorkMode','bounded_work'));
            for index=1:problem.Horizon.nodeCount()
                testCase.verifyFalse(any( ...
                    problem.Horizon.Nodes{index}.FreeCoordinateMask));
            end
            for index=1:problem.Horizon.segmentCount()
                segment=problem.Horizon.Segments{index};
                testCase.verifyTrue(all( ...
                    segment.EventSchedule.fixedMask()));
                testCase.verifyFalse(segment.EventSchedule.ReturnTimeFixed);
                testCase.verifyEqual( ...
                    segment.EnergyWorkSpecification.Mode,'bounded_work');
            end
            testCase.verifyEqual(problem.getDecisionSchema().count(),2);

            active=lmzmodels.slip_biped.Model().createProblem( ...
                'multiple_shooting',struct( ...
                'EnergyWorkMode','energy_neutral'));
            evaluation=active.evaluate( ...
                active.getDecisionSchema().defaults(), ...
                active.getParameterSchema().defaults(), ...
                lmz.api.RunContext.synchronous(7203),false);
            testCase.verifyEqual(numel( ...
                evaluation.Diagnostics.EnergyWorkResidualNorms),2);
            testCase.verifyEqual(numel(evaluation.ScaledResidual),31);
        end

        function freeControlsAreRejectedExplicitly(testCase)
            testCase.verifyError(@() ...
                lmzmodels.slip_biped.Model().createProblem( ...
                'multiple_shooting',struct('ControlFreeMask',true)), ...
                'lmz:Shooting:ScientificControlDecisionsUnavailable');
        end


        function unavailableQuadrupedEnergyRowFailsClearly(testCase)
            problem=lmzmodels.slip_quadruped.Model().createProblem( ...
                'multiple_shooting',struct( ...
                'EnergyWorkMode','energy_neutral'));
            testCase.verifyError(@()problem.evaluate( ...
                problem.getDecisionSchema().defaults(), ...
                problem.getParameterSchema().defaults(), ...
                lmz.api.RunContext.synchronous(7204),false), ...
                'lmz:Shooting:ScientificEnergyResidualUnavailable');
        end

        function bipedEnergyModesHaveDistinctSemantics(testCase)
            model=lmzmodels.slip_biped.Model();
            bounded=model.createProblem('multiple_shooting',struct( ...
                'EnergyWorkMode','bounded_work','DeclaredWork',1e6));
            prescribed=model.createProblem('multiple_shooting',struct( ...
                'EnergyWorkMode','prescribed_work','DeclaredWork',1e6));
            context=lmz.api.RunContext.synchronous(7205);
            boundedValue=bounded.evaluateShooting( ...
                bounded.getDecisionSchema().defaults(), ...
                bounded.getParameterSchema().defaults(),context,false);
            prescribedValue=prescribed.evaluateShooting( ...
                prescribed.getDecisionSchema().defaults(), ...
                prescribed.getParameterSchema().defaults(),context,false);

            boundedEnergy=boundedValue.SegmentResults{1}.Diagnostics.Energy;
            prescribedEnergy= ...
                prescribedValue.SegmentResults{1}.Diagnostics.Energy;
            testCase.verifyEqual(boundedEnergy.Mode,'bounded_work');
            testCase.verifyEqual(prescribedEnergy.Mode,'prescribed_work');
            testCase.verifyEqual(boundedEnergy.Residual,0,'AbsTol',1e-12);
            testCase.verifyEqual(prescribedEnergy.Residual, ...
                prescribedEnergy.EnergyDelta-1e6,'AbsTol',1e-8);
            testCase.verifyGreaterThan(abs(prescribedEnergy.Residual),9e5);
            testCase.verifyTrue(boundedEnergy.Accepted);
            testCase.verifyFalse(prescribedEnergy.Accepted);
            testCase.verifyTrue(boundedValue.Feasibility.EnergyValid);
            testCase.verifyFalse(prescribedValue.Feasibility.EnergyValid);
        end
    end
end

function verifySolve(testCase,model,residualCount,decisionCount,seed)
problem=model.createProblem('multiple_shooting', ...
    struct('HorizonLength',2,'ResidualTolerance',1e-7));
result=lmz.services.MultipleShootingService().solve(problem, ...
    problem.getDecisionSchema().defaults(),struct( ...
    'ResidualTolerance',1e-7,'MaxIterations',30, ...
    'MaxFunctionEvaluations',500), ...
    lmz.api.RunContext.synchronous(seed));
report=result.FeasibilityReport;
testCase.verifyEqual(problem.Horizon.segmentCount(),2);
testCase.verifyEqual(numel(result.SegmentResults),2);
testCase.verifyEqual(report.Classification,'least_squares_feasible');
testCase.verifyTrue(report.Success);
testCase.verifyEqual(report.ResidualDimension,residualCount);
testCase.verifyEqual(report.DecisionDimension,decisionCount);
testCase.verifyEqual(report.JacobianRank,decisionCount);
testCase.verifyEqual(report.Nullity,0);
testCase.verifyLessThanOrEqual(report.MaximumScaledResidual,1e-7);
for index=1:2
    segment=result.SegmentResults{index};
    testCase.verifyTrue(segment.Diagnostics.DirectSectionIntegration);
    testCase.verifyFalse(segment.Diagnostics.ApexOracleUsed);
    testCase.verifyNotEmpty(segment.ContactResiduals);
    testCase.verifyNotEmpty(segment.TerminalCoordinates);
end
testCase.verifyFalse(problem.Configuration.HomogeneousClosedStrideRepetition);
end
