classdef TestWorkflowRegistryBuiltIns < matlab.unittest.TestCase
    methods (Test)
        function discoversAllBuiltInContributions(testCase)
            registry=lmz.registry.ModelRegistry.discover();
            cleanup=onCleanup(@()delete(registry));
            workflows=lmz.workflow.WorkflowRegistry.fromModelRegistry(registry);
            expected={ ...
                'slip_biped',{'gaitmap'},'scientific_workbench'; ...
                'slip_quad_load', ...
                    {'scientific_load','scientific_load_single'}, ...
                    'scientific_workbench'; ...
                'slip_quadruped',{'roadmap'},'scientific_workbench'; ...
                'tutorial_hopper',{'generated_tutorial'},'classic_tabs'};
            for row=1:size(expected,1)
                modelId=expected{row,1};
                sources=workflows.listDataSources(modelId);
                sourceIds=expected{row,2};
                testCase.verifyNumElements(sources,numel(sourceIds));
                testCase.verifyEqual({sources.Id},sourceIds);
                testCase.verifyEqual( ...
                    workflows.getWorkbench(modelId).Id,expected{row,3});
                for sourceIndex=1:numel(sources)
                    provider=sources(sourceIndex).createProvider();
                    testCase.verifyClass(provider, ...
                        sources(sourceIndex).ProviderClass);
                    testCase.verifyNotEmpty(provider.list( ...
                        sources(sourceIndex),registry));
                end
                manifest=registry.getManifest(modelId);
                testCase.verifyEqual(numel(manifest.dataSourcesHash),64);
                testCase.verifyEqual(numel(manifest.workbenchHash),64);
            end
            testCase.verifyEqual(workflows.list('slip_quadruped'), ...
                {'roadmap_explore','roadmap_root_continuation', ...
                'touchdown_root_continuation'});
            testCase.verifyEmpty(workflows.list('slip_biped'));
            testCase.verifyEmpty(workflows.list('slip_quad_load'));
            testCase.verifyEmpty(workflows.list('tutorial_hopper'));
            quadruped=workflows.createDataSourceProvider( ...
                'slip_quadruped','roadmap');
            testCase.verifyNumElements(quadruped.list( ...
                workflows.getDataSource('slip_quadruped','roadmap'), ...
                registry),9);
            loadSources=workflows.listDataSources('slip_quad_load');
            testCase.verifyEqual({loadSources.ProblemId}, ...
                {'multi_stride_fit','single_stride'});
            service=lmz.services.BranchService();
            multi=service.loadAllDataSource(workflows,'slip_quad_load', ...
                'scientific_load');
            single=service.loadAllDataSource(workflows,'slip_quad_load', ...
                'scientific_load_single');
            testCase.verifyEqual(multi{1}.Branch.ProblemId, ...
                'multi_stride_fit');
            testCase.verifyEqual(single{1}.Branch.ProblemId, ...
                'single_stride');
            tutorial=lmz.services.BranchService().loadBuiltInBranch( ...
                registry,'tutorial_hopper');
            testCase.verifyEqual(tutorial.pointCount(),3);
            clear cleanup
        end
    end
end
