classdef TestSectionChangeInvalidatesSeedPair < matlab.unittest.TestCase
    methods (Test)
        function rejectsSeedFromDifferentConfiguredSection(testCase)
            registry=lmz.registry.ModelRegistry.discover();
            model=registry.createModel('slip_quadruped');
            sourceProblem=model.createProblem('periodic_orbit',struct( ...
                'StartSectionId','apex','StopSectionId','apex'));
            targetProblem=model.createProblem('periodic_orbit',struct( ...
                'StartSectionId','back_left_touchdown', ...
                'StopSectionId','back_left_touchdown'));
            seed=sourceProblem.makeSolution( ...
                sourceProblem.getDecisionSchema().defaults(), ...
                sourceProblem.getParameterSchema().defaults(),[]);
            service=lmz.services.SeedService();
            testCase.verifyError(@()service.makeSecondSeed( ...
                targetProblem,seed,1e-3,struct(), ...
                lmz.api.RunContext.synchronous(928)), ...
                'lmz:Seed:SectionConfigurationMismatch');
        end

        function branchPreservesSectionLineage(testCase)
            registry=lmz.registry.ModelRegistry.discover();
            problem=registry.createModel('slip_biped').createProblem( ...
                'periodic_orbit',struct('StartSectionId','apex', ...
                'StopSectionId','apex'));
            first=problem.makeSolution( ...
                problem.getDecisionSchema().defaults(), ...
                problem.getParameterSchema().defaults(),[]);
            second=first.withDecisionValues(first.DecisionValues+ ...
                1e-3*problem.scale(first.DecisionValues));
            branch=lmz.data.SolutionBranch.fromSolutions([first second]);
            testCase.verifyEqual(branch.Lineage,first.Lineage);
            testCase.verifyEqual(branch.point(1).Lineage,first.Lineage);
        end

        function continuationRejectsPairAfterSectionChange(testCase)
            registry=lmz.registry.ModelRegistry.discover();
            model=registry.createModel('slip_quadruped');
            sourceProblem=model.createProblem('periodic_orbit',struct( ...
                'StartSectionId','apex','StopSectionId','apex'));
            targetProblem=model.createProblem('periodic_orbit',struct( ...
                'StartSectionId','back_left_touchdown', ...
                'StopSectionId','back_left_touchdown'));
            first=sourceProblem.makeSolution( ...
                sourceProblem.getDecisionSchema().defaults(), ...
                sourceProblem.getParameterSchema().defaults(),[]);
            second=first.withDecisionValues(first.DecisionValues+ ...
                1e-4*sourceProblem.scale(first.DecisionValues));
            pair=lmz.data.SolutionPair(first,second,1e-4,1e-4,struct());

            testCase.verifyError(@()lmz.services.ContinuationService().run( ...
                targetProblem,pair,struct('MaximumPoints',2), ...
                lmz.api.RunContext.synchronous(929)), ...
                'lmz:Seed:SectionConfigurationMismatch');
        end
    end
end
