classdef TestCompositePoincareSection < matlab.unittest.TestCase
    methods (Test)
        function catalogConditionAcceptsAndReturnMapLocates(testCase)
            schema = localSchema();
            registry = lmz.poincare.PoincareSectionRegistry( ...
                localCatalog(0.5), 'ModelId', 'composite_test', ...
                'StateSchema', schema);
            section = registry.section('descending_positive');
            testCase.verifyClass(section, 'lmz.poincare.CompositeSection');
            testCase.verifyClass(section.Conditions{1}, ...
                'lmz.poincare.CompositeAcceptanceCondition');

            simulation = localSimulation(schema);
            returnMap = lmz.poincare.PoincareReturnMap(section, section, ...
                lmz.poincare.IdentitySymmetry(), schema);
            result = returnMap.evaluate(simulation.States(1, :).', ...
                struct(), @(~,~,~,~) simulation, ...
                lmz.api.RunContext.synchronous(951));

            testCase.verifyTrue(result.StopCrossing.Accepted);
            testCase.verifyEqual(result.StopCrossing.SectionId, ...
                'descending_positive');
            testCase.verifyEqual( ...
                result.StopCrossing.Metadata.PrimarySectionId, 'height');
            testCase.verifyEqual(result.PeriodicResidual, [0;0], ...
                'AbsTol', 10 * eps);
            testCase.verifyEqual(result.Simulation.Time(end), ...
                result.StopCrossing.Time, 'AbsTol', 10 * eps);

            [rephased, crossing, errorValue, preserved] = ...
                lmz.services.SectionTransferService. ...
                rephaseSimulationToSection(simulation, section, ...
                lmz.poincare.IdentitySymmetry());
            testCase.verifyEqual(crossing.SectionId, 'descending_positive');
            testCase.verifyEqual(rephased.Time(1), 0);
            testCase.verifyLessThanOrEqual(errorValue, 10 * eps);
            testCase.verifyTrue(preserved);
        end

        function rejectingConditionIsDiagnosed(testCase)
            schema = localSchema();
            registry = lmz.poincare.PoincareSectionRegistry( ...
                localCatalog(2), 'ModelId', 'composite_test', ...
                'StateSchema', schema);
            section = registry.section('descending_positive');
            simulation = localSimulation(schema);

            [detected, crossing] = section.detectCrossing( ...
                simulation.Time(2), simulation.States(2, :).', ...
                simulation.Time(3), simulation.States(3, :).', ...
                'ModeId', 'flight', 'Occurrence', 1, ...
                'EventHistory', {'PREP'});
            testCase.verifyTrue(detected);
            testCase.verifyFalse(crossing.Accepted);
            testCase.verifyEqual(crossing.RejectionReason, ...
                'composite-state-comparison');

            returnMap = lmz.poincare.PoincareReturnMap(section, section, ...
                lmz.poincare.IdentitySymmetry(), schema);
            testCase.verifyError(@() returnMap.evaluate( ...
                simulation.States(1, :).', struct(), ...
                @(~,~,~,~) simulation, ...
                lmz.api.RunContext.synchronous(952)), ...
                'lmz:Poincare:ReturnNotFound');
        end

        function catalogRejectsCompositeWithoutConditions(testCase)
            data = localCatalog(0.5);
            data.sections{2}.parameters = ...
                struct('primarySectionId', 'height');
            testCase.verifyError(@() ...
                lmz.poincare.PoincareSectionRegistry(data, ...
                'ModelId', 'composite_test', ...
                'StateSchema', localSchema()), ...
                'lmz:Poincare:CompositeConditions');
        end
    end
end

function data = localCatalog(threshold)
condition = struct('kind', 'state_comparison', ...
    'stateName', 'vx', 'comparator', 'gt', ...
    'threshold', threshold, 'stateSide', 'selected');
parameters = struct('primarySectionId', 'height', ...
    'conditions', {{condition}});
base = struct('id', 'height', 'label', 'Height', ...
    'kind', 'state_plane', 'stateName', 'y', 'threshold', 0.5, ...
    'crossingDirection', -1, 'stateSide', 'post', ...
    'minimumReturnTime', 0.1, 'requiredEventSequence', {{'PREP'}}, ...
    'returnOccurrence', 1, 'coordinateNames', {{'x','vx'}}, ...
    'symmetryClass', 'lmz.poincare.IdentitySymmetry', ...
    'maturities', {{'experimental'}}, 'validationStatus', 'tested');
composite = struct('id', 'descending_positive', ...
    'label', 'Descending with positive speed', 'kind', 'composite', ...
    'crossingDirection', -1, 'stateSide', 'post', ...
    'minimumReturnTime', 0.1, 'requiredEventSequence', {{'PREP'}}, ...
    'returnOccurrence', 1, 'coordinateNames', {{'x','vx'}}, ...
    'symmetryClass', 'lmz.poincare.IdentitySymmetry', ...
    'maturities', {{'experimental'}}, 'validationStatus', 'tested', ...
    'parameters', parameters);
data = struct('schemaVersion', '1.0.0', ...
    'defaultSectionByProblem', struct('periodic_orbit', ...
    'descending_positive'), 'sections', {{base, composite}});
end

function simulation = localSimulation(schema)
time = [0;0.4;0.8;1.2];
states = [0 1 0.5 -1;0 1 1 1;0 1 0.4 -1;0 1 0.5 -1];
record = struct('Id', 'PREP', 'Time', 0.2, ...
    'FromMode', 'flight', 'ToMode', 'flight', ...
    'PreState', states(1, :).', 'PostState', states(1, :).', ...
    'DirectionalDerivative', 1, 'Metadata', struct());
simulation = lmz.api.SimulationResult(time, schema, states, ...
    {'flight';'flight';'flight';'flight'}, struct(), struct(), ...
    struct(), struct(), 'EventRecords', record);
end

function schema = localSchema()
schema = lmz.schema.VariableSchema([ ...
    lmz.schema.VariableSpec('x'); ...
    lmz.schema.VariableSpec('vx'); ...
    lmz.schema.VariableSpec('y'); ...
    lmz.schema.VariableSpec('vy')]);
end
