classdef TestQuadLoadHorizonContinuation < matlab.unittest.TestCase
    methods (Test)
        function explicitNToNPlusOneEmbeddingPreservesNamedVariables(testCase)
            evidence=lmzmodels.slip_quad_load.QuadLoadFeasibilityEvidence();
            [previous,decision]=evidence.problemFor( ...
                'n2_transition_feasibility_root');
            configuration=struct('EnergyMode','diagnostic_only', ...
                'PreviousDecision',decision);
            [next,embedded,diagnostics]=lmzmodels.slip_quad_load. ...
                QuadLoadHorizonContinuation().extend(previous,3, ...
                configuration,lmz.api.RunContext.synchronous(0));
            testCase.verifyEqual(numel(decision),46);
            testCase.verifyEqual(numel(embedded),69);
            testCase.verifyEqual(diagnostics.PreservedVariableCount,46);
            testCase.verifyEqual(diagnostics.AddedVariableCount,23);
            oldNames=previous.Codec.DecisionSchema.names();
            newNames=next.Codec.DecisionSchema.names();
            [~,locations]=ismember(oldNames,newNames);
            testCase.verifyEqual(embedded(locations),decision,'AbsTol',0);
            testCase.verifyFalse(diagnostics.PhysicalRootClaimed);
        end

        function unresolvedSolveStopsByDefaultButStructuralGrowthRemainsAvailable(testCase)
            evidence=lmzmodels.slip_quad_load.QuadLoadFeasibilityEvidence();
            [~,decision]=evidence.problemFor( ...
                'n2_transition_feasibility_root');
            configuration=struct('StartStrideCount',2, ...
                'TargetStrideCount',5,'EnergyMode','diagnostic_only', ...
                'InitialDecisionForContinuation',decision);
            result=lmzmodels.slip_quad_load. ...
                QuadLoadHorizonContinuation().continueTo( ...
                configuration,struct('SolveEachHorizon',false, ...
                'InitialCompletedPhysicalStrideCount',2), ...
                lmz.api.RunContext.synchronous(0));
            testCase.verifyTrue(result.StopOnUnresolved);
            testCase.verifyEqual(result.CompletedStrideCount,5);
            testCase.verifyEqual(result.CompletedPhysicalStrideCount,2);
        end

        function n2StiffnessFamilyRetainsOneShootingChart(testCase)
            context=lmz.api.RunContext.synchronous(1004);
            evidence=lmzmodels.slip_quad_load.QuadLoadFeasibilityEvidence();
            sourceCaseId='n2_transition_feasibility_root';
            [sourceProblem,sourceDecision]=evidence.problemFor(sourceCaseId);
            configuration=evidence.configuration( ...
                evidence.caseRecord(sourceCaseId));
            freeControlMask=false(2,4);freeControlMask(2,1)=true;
            configuration.FreeControlMask=freeControlMask;
            configuration.ExpectedLocalDimension=1;
            problem=lmzmodels.slip_quad_load. ...
                QuadLoadMultipleShootingProblem([],configuration);
            [decision,embedding]=lmz.shooting.HorizonContinuation(). ...
                embedDecision(sourceProblem.ShootingSchema,sourceDecision, ...
                problem.ShootingSchema);
            evaluation=problem.evaluate(decision,[],context,false);
            first=problem.makeSolution(decision,[],evaluation);
            pair=lmz.services.SeedService().makeSecondSeed( ...
                problem,first,1e-4, ...
                struct('ExpectedLocalDimension',1),context);
            options=struct('MaximumPoints',3,'BothDirections',false, ...
                'InitialStep',pair.AchievedRadius,'MinimumStep',1e-6, ...
                'MaximumStep',pair.AchievedRadius, ...
                'CorrectorTolerance',1e-9,'RequireFeasible',true);
            family=lmz.services.ContinuationService().run( ...
                problem,pair,options,context);

            selected='segment_2_post_swing_1';
            names=problem.getDecisionSchema().names();
            selectedIndex=find(strcmp(names,selected),1);
            points=arrayfun(@(index)family.Branch.point(index), ...
                1:family.Branch.pointCount());
            dimensions=arrayfun(@(point)numel(point.DecisionValues),points);
            controls=arrayfun(@(point) ...
                point.DecisionValues(selectedIndex),points);
            residuals=arrayfun(@(point) ...
                point.Feasibility.MaximumScaledResidual,points);
            valid=arrayfun(@(point)point.Feasibility.Valid,points);
            physical=arrayfun(@(point) ...
                point.Feasibility.PhysicalValidity,points);
            crossings=arrayfun(@(point) ...
                point.Feasibility.CrossingsAccepted,points);
            eventOrder=arrayfun(@(point) ...
                point.Feasibility.EventOrderValid,points);

            testCase.verifyEqual(embedding.OldDimension,46);
            testCase.verifyEqual(embedding.NewDimension,47);
            testCase.verifyEqual(embedding.AddedNames,{selected});
            testCase.verifyEqual(problem.ExpectedDimension,1);
            testCase.verifyEqual(pair.Diagnostics.JacobianRank,46);
            testCase.verifyEqual(pair.Diagnostics.LocalDimension,1);
            testCase.verifyEqual(pair.AchievedRadius,1e-4, ...
                'AbsTol',1e-12);
            testCase.verifyEqual(family.Branch.pointCount(),3);
            testCase.verifyEqual(dimensions,[47 47 47]);
            for index=1:numel(points)
                testCase.verifyEqual(points(index).DecisionSchema.names(), ...
                    names);
            end
            testCase.verifyEqual(controls,[ ...
                25.881221830170297 25.880923234958146 ...
                25.88062464009689],'AbsTol',1e-10);
            testCase.verifyLessThan(max(residuals),1e-8);
            testCase.verifyTrue(all(valid&physical&crossings&eventOrder));
            testCase.verifyEqual(family.TerminationReason,'maximum_points');
            modes=cellfun(@(segment) ...
                segment.EnergyWorkSpecification.Mode, ...
                problem.Horizon.Segments,'UniformOutput',false);
            testCase.verifyEqual(modes, ...
                {'diagnostic_only';'diagnostic_only'});
        end
    end
end
