classdef TestQuadLoadFiveStrideCompletion < matlab.unittest.TestCase
    %TESTQUADLOADFIVESTRIDECOMPLETION Verify honest partial failure evidence.
    methods (Test)
        function infeasibleThirdTimingSeedReturnsPartialWithoutSimulation(testCase)
            model=lmzmodels.slip_quad_load.Model();
            problem=model.createProblem('n_stride_simulation',struct( ...
                'NumberOfStrides',5, ...
                'CompletionPolicy','predictor_corrector', ...
                'FailurePolicy','return_partial'));
            result=problem.simulate(lmz.api.RunContext.synchronous(0));
            testCase.verifyEqual(result.RequestedStrideCount,5);
            testCase.verifyEqual(result.CompletedStrideCount,2);
            testCase.verifyTrue(result.Partial);
            testCase.verifyEqual(result.CompletionStatus,'failed');
            testCase.verifyEmpty(result.Simulation);
            testCase.verifyEqual(result.Failure.StrideIndex,3);
            testCase.verifyEqual(result.Failure.Identifier, ...
                'lmz:MultiStride:TimingSeedOutsideTrustRegion');
            attempts=result.Failure.RecoveryAttempts;
            testCase.verifyEqual({attempts.Strategy}, ...
                {'baseline','step_reduction','parameter_homotopy', ...
                'deterministic_multistart'});
            testCase.verifyFalse(any([attempts.Succeeded]));
            testCase.verifyEqual({attempts.TerminationStage},repmat( ...
                {'timing_seed_trust_region_gate'},1,4));
            testCase.verifyTrue(result.Failure.RecoveryLadderExhausted);
            testCase.verifyTrue(result.Diagnostics.RecoveryLadderExhausted);
            testCase.verifyEqual(result.Checkpoints{end}. ...
                CompletedStrideCount,2);
            testCase.verifyEqual(result.Checkpoints{end}.Kind, ...
                'recovery_ladder_exhausted');
        end

        function failureCheckpointResumeIsDeterministic(testCase)
            model=lmzmodels.slip_quad_load.Model();
            configuration=struct('NumberOfStrides',5, ...
                'CompletionPolicy','predictor_corrector', ...
                'FailurePolicy','return_partial');
            original=model.createProblem('n_stride_simulation', ...
                configuration).simulate(lmz.api.RunContext.synchronous(42));
            checkpoint=original.Failure.ResumeCheckpoint;
            configuration.StridePlan= ...
                lmz.multistride.StridePlan.fromStruct(checkpoint.Plan);
            resumed=model.createProblem('n_stride_simulation', ...
                configuration).simulate(lmz.api.RunContext.synchronous(42));

            testCase.verifyEqual(resumed.CompletedStrideCount,2);
            testCase.verifyTrue(resumed.Partial);
            testCase.verifyEqual(resumed.Failure.RecoveryAttempts, ...
                original.Failure.RecoveryAttempts);
            testCase.verifyEqual( ...
                lmzmodels.slip_quad_load.XAccumPlanAdapter.encode( ...
                resumed.Plan.truncate(resumed.CompletedStrideCount)), ...
                lmzmodels.slip_quad_load.XAccumPlanAdapter.encode( ...
                original.Plan.truncate(original.CompletedStrideCount)), ...
                'AbsTol',0);
        end

        function completedStrideCheckpointResumesToIdenticalPlan(testCase)
            catalog=lmzmodels.slip_quad_load.ScientificDatasetCatalog.default();
            dataset=catalog.load('individual_1_tr_to_rl');
            plan=lmzmodels.slip_quad_load.XAccumPlanAdapter.toPlan( ...
                dataset.XAccum).withRequestedStrideCount(5);
            plan=plan.withPolicies('carry_forward',plan.EnergyPolicy,'error');
            builder=lmzmodels.slip_quad_load.QuadLoadStridePlanBuilder();
            service=lmz.multistride.StridePlanCompletionService();
            context=lmz.api.RunContext.synchronous(43);
            completed=service.complete(builder,plan,struct(),context);
            checkpoint=completed.Checkpoints{1};
            resumed=service.resume(builder,checkpoint,struct(), ...
                lmz.api.RunContext.synchronous(43));

            testCase.verifyEqual(checkpoint.CompletedStrideCount,3);
            testCase.verifyEqual(resumed.CompletedStrideCount,5);
            testCase.verifyEqual(resumed.Plan.toStruct(), ...
                completed.Plan.toStruct());
            testCase.verifyEqual( ...
                lmzmodels.slip_quad_load.XAccumPlanAdapter.encode( ...
                resumed.Plan), ...
                lmzmodels.slip_quad_load.XAccumPlanAdapter.encode( ...
                completed.Plan),'AbsTol',0);
        end

        function serviceContainsNoSyntheticTimingFallback(testCase)
            path=which('lmz.services.MultiStrideSimulationService');
            source=fileread(path);
            testCase.verifyEmpty(regexp(source, ...
                'safetySchedule|SafetyFallback|short_horizon', 'once'));
        end
    end
end
