classdef TestHopperSectionSimulationAdapter < matlab.unittest.TestCase
    methods (Test)
        function tutorialFactoryPublishesNamedStableAdapter(testCase)
            model=lmz.registry.ModelRegistry.discover(). ...
                createModel('tutorial_hopper');
            problem=model.createProblem('multiple_shooting',struct( ...
                'HorizonLength',1,'Formulation','periodic'));
            contract=problem.contract();
            evaluation=problem.evaluate(problem.ShootingSchema.defaults(), ...
                problem.getParameterSchema().defaults(), ...
                lmz.api.RunContext.synchronous(1190),true);
            testCase.verifyEqual(contract.SegmentEvaluator.Class, ...
                ['lmzmodels.tutorial_hopper.' ...
                'HopperSectionSimulationAdapter']);
            testCase.verifyLessThan(evaluation.ScaledResidualNorm,1e-10);
            testCase.verifyTrue(evaluation.PhysicalValidity);
            testCase.verifyEqual( ...
                evaluation.Diagnostics.SegmentEvaluationCount,1);
        end
    end
end
