classdef TestFixedContactResidualFailure < matlab.unittest.TestCase
    methods (Test)
        function lowActiveResidualCannotHideBadFixedEvent(testCase)
            problem=lmztest.makeRectangularTimingProblem( ...
                'square',.5,true,1,false,struct());
            result=lmz.services.ContactTimingService().solve(problem, ...
                problem.InputSchedule,struct(), ...
                lmz.api.RunContext.synchronous(1004));
            testCase.verifyLessThan(result.SolverDiagnostics.ResidualNorm,1e-10);
            testCase.verifyFalse(result.SolverDiagnostics.Success);
            testCase.verifyEqual(result.SolverDiagnostics.Status,'infeasible');
            testCase.verifyFalse(result.SolverDiagnostics. ...
                SuccessCriteria.FixedRowsValid);
            testCase.verifyEqual(result.ContactResiduals,.1,'AbsTol',1e-12);
        end

        function diagnosticOnlyStillDoesNotClaimConvergence(testCase)
            problem=lmztest.makeRectangularTimingProblem( ...
                'square',.5,true,1,false,struct( ...
                'FixedRowPolicy','diagnostic_only'));
            result=lmz.services.ContactTimingService().solve(problem, ...
                problem.InputSchedule,struct(), ...
                lmz.api.RunContext.synchronous(1005));
            testCase.verifyFalse(result.SolverDiagnostics.Success);
            testCase.verifyEqual(result.SolverDiagnostics.Status,'infeasible');
        end


        function includedBadFixedRowIsStillPhysicalInfeasibility(testCase)
            problem=lmztest.makeRectangularTimingProblem( ...
                'square',.5,true,1,false,struct('FixedRowPolicy', ...
                'include_fixed_rows_in_least_squares'));
            result=lmz.services.ContactTimingService().solve(problem, ...
                problem.InputSchedule,struct('Solver','lsqnonlin'), ...
                lmz.api.RunContext.synchronous(1018));
            testCase.verifyFalse(result.SolverDiagnostics.Success);
            testCase.verifyFalse(result.SolverDiagnostics. ...
                SuccessCriteria.FixedRowsValid);
            testCase.verifyEqual(result.SolverDiagnostics.Status,'infeasible');
        end
    end
end
