classdef TestQuadLoadDirectSections < matlab.unittest.TestCase
    methods (Test)
        function apexBoundaryAndTouchdownUseDirectSectionIntegration(testCase)
            context=lmz.api.RunContext.synchronous(0);
            cases={{'apex',1},{'stride_boundary',1}, ...
                {'back_left_touchdown',2}};
            for index=1:numel(cases)
                item=cases{index};
                codec=lmzmodels.slip_quad_load. ...
                    QuadLoadSectionDecisionCodec.fromTemplate(item{1}, ...
                    'individual_1_tr_to_rl',item{2},context);
                result=lmzmodels.slip_quad_load. ...
                    QuadLoadSectionSimulationAdapter(codec).evaluate( ...
                    codec.DecisionSchema.defaults(),[],context,true);
                testCase.verifyTrue( ...
                    result.Diagnostics.DirectSectionIntegration);
                testCase.verifyFalse(result.Diagnostics. ...
                    FullApexTrajectoryLookupDuringEvaluation);
                testCase.verifyEqual(result.Diagnostics.StopSectionId,item{1});
                testCase.verifyNotEmpty(result.Simulation);
                testCase.verifyEqual(result.Simulation.States(1,:).', ...
                    codec.BaseState,'AbsTol',1e-12);
                testCase.verifyTrue(result.Crossing.Accepted);
                decisionNames=codec.DecisionSchema.names();
                testCase.verifyFalse(any(ismember( ...
                    {'load_y','load_dy'},decisionNames)));
                testCase.verifyEqual(result.Diagnostics. ...
                    SourceFixedCoordinateNames,{'load_y','load_dy'});
                testCase.verifyEqual(numel(result.TerminalCoordinates), ...
                    codec.TerminalStateCoordinates.count());
            end
        end
    end
end
