classdef TestRequiredEventSequence < matlab.unittest.TestCase
    methods (Test)
        function acceptsOnlyCrossingsWithOrderedHistory(testCase)
            descriptor=lmz.poincare.PoincareSectionDescriptor(struct( ...
                'id','return_event','label','Return event', ...
                'kind','named_event','eventId','RETURN', ...
                'crossingDirection',-1,'stateSide','post', ...
                'minimumReturnTime',0.1, ...
                'requiredEventSequence',{{'TOUCHDOWN','LIFTOFF'}}, ...
                'returnOccurrence',1,'coordinateNames',{{}}, ...
                'symmetryClass','lmz.poincare.IdentitySymmetry', ...
                'maturities',{{'experimental'}}, ...
                'validationStatus','tested'));
            section=lmz.poincare.NamedEventSection(descriptor);
            record=struct('Id','RETURN','Time',1, ...
                'FromMode','flight','ToMode','flight', ...
                'PreState',[0;1],'PostState',[0;1], ...
                'DirectionalDerivative',-1,'Metadata',struct());

            missing=section.crossingFromRecord(record, ...
                'EventHistory',{'TOUCHDOWN'});
            ordered=section.crossingFromRecord(record, ...
                'EventHistory',{'START','TOUCHDOWN','LIFTOFF'});
            reversed=section.crossingFromRecord(record, ...
                'EventHistory',{'LIFTOFF','TOUCHDOWN'});

            testCase.verifyFalse(missing.Accepted);
            testCase.verifyFalse(reversed.Accepted);
            testCase.verifyTrue(ordered.Accepted);
            testCase.verifyEmpty(ordered.RejectionReason);
        end
    end
end
