classdef TestQuadLoadHorizonCheckpointResume < matlab.unittest.TestCase
    methods (Test)
        function evaluationCheckpointResumesWithIdenticalEmbedding(testCase)
            evidence=lmzmodels.slip_quad_load.QuadLoadFeasibilityEvidence();
            [~,n2]=evidence.problemFor('n2_transition_feasibility_root');
            configuration=struct('StartStrideCount',2, ...
                'TargetStrideCount',3,'EnergyMode','diagnostic_only', ...
                'InitialDecisionForContinuation',n2);
            continuation=lmzmodels.slip_quad_load. ...
                QuadLoadHorizonContinuation();
            original=continuation.continueTo(configuration,struct( ...
                'InitialCompletedPhysicalStrideCount',2), ...
                lmz.api.RunContext.synchronous(0));
            checkpoint=original.Checkpoints{1};
            resumed=continuation.resume(checkpoint,struct(), ...
                lmz.api.RunContext.synchronous(0));
            testCase.verifyEqual(resumed.CompletedStrideCount,3);
            testCase.verifyEqual(resumed.FinalDecision, ...
                original.FinalDecision,'AbsTol',0);
            testCase.verifyEqual( ...
                resumed.FinalProblem.Codec.DecisionSchema.names(), ...
                original.FinalProblem.Codec.DecisionSchema.names());
            testCase.verifyEqual(checkpoint.SchemaVersion,'1.0.0');
            testCase.verifyEqual(checkpoint.ProblemContractHash, ...
                lmz.io.ArtifactStore.dataHash( ...
                checkpoint.ProblemContract));
            testCase.verifyEqual(checkpoint.ConfigurationHash, ...
                lmz.io.ArtifactStore.dataHash(checkpoint.Configuration));
            testCase.verifyEqual(checkpoint.DecisionHash, ...
                lmz.io.ArtifactStore.dataHash(checkpoint.Decision));
        end

        function checkpointRejectsTamperingExecutableDataAndFutureVersion(testCase)
            checkpoint=makeCheckpoint();
            continuation=lmzmodels.slip_quad_load. ...
                QuadLoadHorizonContinuation();
            context=lmz.api.RunContext.synchronous(0);

            tampered=checkpoint;tampered.Decision(1)= ...
                tampered.Decision(1)+1e-3;
            testCase.verifyError(@()continuation.resume( ...
                tampered,struct(),context), ...
                'lmz:QuadLoad:HorizonCheckpointIntegrity');

            executable=checkpoint;executable.Homotopy.Callback=@()true;
            testCase.verifyError(@()continuation.resume( ...
                executable,struct(),context), ...
                'lmz:QuadLoad:HorizonContinuationCheckpoint');

            future=checkpoint;future.FrameworkVersion='9.0.0';
            testCase.verifyError(@()continuation.resume( ...
                future,struct(),context), ...
                'lmz:QuadLoad:HorizonCheckpointFramework');

            incompatible=checkpoint;
            incompatible.Configuration.ResidualTolerance=1e-6;
            incompatible.ConfigurationHash=lmz.io.ArtifactStore. ...
                dataHash(incompatible.Configuration);
            payload=rmfield(incompatible,'CheckpointHash');
            incompatible.CheckpointHash=lmz.io.ArtifactStore. ...
                dataHash(payload);
            testCase.verifyError(@()continuation.resume( ...
                incompatible,struct(),context), ...
                'lmz:QuadLoad:HorizonCheckpointProblemContract');
        end

        function unresolvedCheckpointPreservesValidatedPhysicalPrefix(testCase)
            evidence=lmzmodels.slip_quad_load.QuadLoadFeasibilityEvidence();
            [~,n2]=evidence.problemFor('n2_transition_feasibility_root');
            configuration=struct('StartStrideCount',2, ...
                'TargetStrideCount',3,'EnergyMode','diagnostic_only', ...
                'InitialDecisionForContinuation',n2);
            continuation=lmzmodels.slip_quad_load. ...
                QuadLoadHorizonContinuation();
            original=continuation.continueTo(configuration,struct( ...
                'InitialCompletedPhysicalStrideCount',2), ...
                lmz.api.RunContext.synchronous(0));
            checkpoint=original.Checkpoints{end};
            testCase.verifyEqual(checkpoint.CompletedStrideCount,3);
            testCase.verifyEqual( ...
                checkpoint.CompletedPhysicalStrideCount,2);

            resumed=continuation.resume(checkpoint,struct(), ...
                lmz.api.RunContext.synchronous(0));
            testCase.verifyEqual(resumed.CompletedStrideCount,3);
            testCase.verifyEqual(resumed.CompletedPhysicalStrideCount,2);
            testCase.verifyFalse(resumed.FinalReport.RootFound);
        end
    end
end

function checkpoint=makeCheckpoint()
evidence=lmzmodels.slip_quad_load.QuadLoadFeasibilityEvidence();
[~,n2]=evidence.problemFor('n2_transition_feasibility_root');
configuration=struct('StartStrideCount',2,'TargetStrideCount',3, ...
    'EnergyMode','diagnostic_only', ...
    'InitialDecisionForContinuation',n2);
result=lmzmodels.slip_quad_load.QuadLoadHorizonContinuation(). ...
    continueTo(configuration,struct( ...
    'InitialCompletedPhysicalStrideCount',2), ...
    lmz.api.RunContext.synchronous(0));
checkpoint=result.Checkpoints{1};
end
