classdef TestUnderdeterminedTimingRequiresGauge < matlab.unittest.TestCase
    methods (Test)
        function explicitIndependentGaugeClosesPointSolve(testCase)
            base=lmztest.makeRectangularTimingProblem( ...
                'underdetermined',.4,false,1,false,struct());
            testCase.verifyEqual(base.unknownDimension(),2);
            testCase.verifyEqual(base.residualDimension(),1);
            action=@()lmz.services.ContactTimingService().solve(base, ...
                base.InputSchedule,struct(), ...
                lmz.api.RunContext.synchronous(1006));
            testCase.verifyError(action,'lmz:Timing:GaugeRequired');

            gauge=lmz.schedule.TimingGauge.fixedReturnTime(1);
            problem=lmz.schedule.TimingFamilyProblem(base,gauge,struct());
            result=lmz.services.ContactTimingService().solve(problem, ...
                problem.InputSchedule,struct(), ...
                lmz.api.RunContext.synchronous(1007));
            testCase.verifyTrue(result.SolverDiagnostics.Success);
            testCase.verifyTrue(result.SolverDiagnostics. ...
                GaugeDiagnostics.Independent);
            testCase.verifyEqual(result.SolverDiagnostics. ...
                GaugeDiagnostics.RankIncrement,1);
            testCase.verifyEqual(result.SolverDiagnostics. ...
                RankDiagnostics.Nullity,0);
        end


        function gaugeContractIsDeclarativeAndDimensionChecked(testCase)
            testCase.verifyError(@()lmz.schedule.TimingGauge(struct( ...
                'Id','unsafe','Kind','callback','Target',0)), ...
                'lmz:Timing:GaugeKind');
            testCase.verifyError(@()lmz.schedule.TimingGauge(struct( ...
                'Id','extra','Kind','fixed_return_time','Target',1, ...
                'Callback',@sin)), 'lmz:Timing:GaugeField');
            gauge=lmz.schedule.TimingGauge.linearPhase( ...
                'phase',[1;0;0],0);
            schedule=lmz.schedule.EventSchedule.fromCyclic( ...
                {'impact'},.4,1);
            testCase.verifyError(@()gauge.evaluate(schedule), ...
                'lmz:Timing:GaugeDimension');
        end
    end
end
