classdef TestBipedTouchdownSectionShooting < matlab.unittest.TestCase
    methods (Test)
        function leftAndRightPrePostReturnsUseLocalCharts(testCase)
            sections={ ...
                'left_touchdown','post'; ...
                'left_touchdown_pre','pre'; ...
                'right_touchdown','post'; ...
                'right_touchdown_pre','pre'};
            model=lmz.registry.ModelRegistry.discover(). ...
                createModel('slip_biped');
            for index=1:size(sections,1)
                problem=model.createProblem('periodic_orbit', ...
                    localConfiguration(sections{index,1}));
                u=problem.getDecisionSchema().defaults();
                p=problem.getParameterSchema().defaults();
                evaluation=problem.evaluate(u,p, ...
                    lmz.api.RunContext.synchronous(1130+index),true);
                decoded=problem.SectionCodec.decode(u);
                testCase.verifyNumElements(u,11);
                testCase.verifyNumElements(evaluation.Residual,11);
                testCase.verifyLessThan( ...
                    evaluation.ScaledResidualNorm,1e-9);
                testCase.verifyTrue(evaluation.PhysicalValidity);
                testCase.verifyTrue( ...
                    evaluation.Diagnostics.DirectSectionIntegration);
                testCase.verifyFalse(evaluation.Diagnostics. ...
                    SourceApexPhaseGaugePreserved);
                testCase.verifyEqual(evaluation.Diagnostics. ...
                    StopCrossing.stateSide,sections{index,2});
                testCase.verifyTrue(evaluation.Diagnostics. ...
                    StopCrossing.accepted);
                testCase.verifyEqual(evaluation.Simulation.Time(end), ...
                    decoded.ReturnTime,'AbsTol',1e-12);
                testCase.verifyEqual(evaluation.Diagnostics. ...
                    StartCrossing.state,decoded.InitialState, ...
                    'AbsTol',1e-12);
                if strcmp(sections{index,2},'post')
                    testCase.verifyEqual( ...
                        evaluation.Simulation.States(1,:).', ...
                        decoded.InitialState,'AbsTol',1e-12);
                end
            end
        end
    end
end

function value=localConfiguration(sectionId)
value=struct('StartSectionId',sectionId,'StopSectionId',sectionId, ...
    'SymmetryId','planar_translation');
end
