classdef TestQuadLoadR2Equivalence < matlab.unittest.TestCase
    methods (Test)
        function allMetricsMatchCapturedSourceAndGuardsAreFinite(testCase)
            loaded=load(fullfile(lmz.util.ProjectPaths.tests(),'fixtures','baselines', ...
                'slip_quad_load','source_baselines.mat'),'baseline');
            expected=loaded.baseline.Entries(2);tolerance=loaded.baseline.Tolerances;
            dataset=lmzmodels.slip_quad_load.ScientificDatasetCatalog.default().load( ...
                'individual_1_tr_to_rl');
            problem=lmzmodels.slip_quad_load.MultiStrideFitProblem( ...
                lmzmodels.slip_quad_load.Model(),struct('DatasetPath',dataset.Path, ...
                'InitialPerturbation',0));
            [~,~,diagnostics]=problem.evaluateObjective(dataset.XAccum, ...
                problem.getParameterSchema().defaults(),lmz.api.RunContext.synchronous(510));
            actual=diagnostics.R2;
            testCase.verifyEqual(actual.strideduration,expected.R2.strideduration, ...
                'AbsTol',tolerance.R2Absolute);
            testCase.verifyEqual(actual.footfalltiming,expected.R2.footfalltiming, ...
                'AbsTol',tolerance.R2Absolute);
            testCase.verifyEqual(actual.loadingforce,expected.R2.loadingforce, ...
                'AbsTol',tolerance.R2Absolute);
            testCase.verifyEqual(actual.weighted,expected.R2.weighted, ...
                'AbsTol',tolerance.R2Absolute);
            constant=struct('Source',ones(1,4),'Target',ones(1,4), ...
                'Diagnostics',struct('R2Target',ones(1,4)));
            [guarded,guardDiagnostics]= ...
                lmzmodels.slip_quad_load.ObjectiveTerms.R2Metrics.compute( ...
                constant,constant,constant,[0 0 0]);
            testCase.verifyEqual([guarded.strideduration guarded.footfalltiming ...
                guarded.loadingforce guarded.weighted],[1 1 1 1]);
            testCase.verifyTrue(guardDiagnostics.ZeroVarianceGuard.ZeroWeight);
        end
    end
end
