classdef TestPoincareReturnMap < matlab.unittest.TestCase
    methods (Test)
        function evaluatesReturnAndExplicitTranslationQuotient(testCase)
            schema = localSchema();
            section = lmz.poincare.StateFunctionSection( ...
                localPlaneDescriptor(), schema);
            symmetry = lmz.poincare.PlanarTranslationSymmetry( ...
                'planar_translation', {'x'});
            returnMap = lmz.poincare.PoincareReturnMap( ...
                section, section, symmetry, schema);
            initial = [0;2;1;0];
            output = struct('TerminalState', [3;2;1;0], ...
                'ReturnTime', 1, 'Diagnostics', struct());

            result = returnMap.evaluate(initial, struct(), ...
                @(~,~,~,~) output, lmz.api.RunContext.synchronous(901));
            testCase.verifyEqual(result.TerminalState, [3;2;1;0]);
            testCase.verifyEqual(result.AlignedTerminalState, initial);
            testCase.verifyEqual(result.PeriodicResidual, [0;0]);
            testCase.verifyEqual( ...
                result.Diagnostics.SymmetryDisplacement, 3);
            testCase.verifyTrue(result.StopCrossing.Accepted);
            testCase.verifyEqual(result.ReturnTime, 1);

            residual = returnMap.periodicResidual( ...
                initial, [3;2;1.25;0]);
            testCase.verifyEqual(residual, [0;0.25], ...
                'AbsTol', 10 * eps);
            stored = result.toStruct();
            testCase.verifyEqual(stored.returnTime, 1);
        end

        function simulationLocatorPreservesEventHistoryAcceptance(testCase)
            schema = localSchema();
            start = lmz.poincare.NamedEventSection( ...
                localEventDescriptor('start', 'START', {}));
            stop = lmz.poincare.NamedEventSection( ...
                localEventDescriptor('stop', 'RETURN', {'PREP'}));
            symmetry = lmz.poincare.IdentitySymmetry();
            returnMap = lmz.poincare.PoincareReturnMap( ...
                start, stop, symmetry, schema);
            states = [0 2 1 0; 0 2 1 0];
            records = [localRecord('PREP', 0.5, states(1, :).'); ...
                localRecord('RETURN', 1, states(2, :).')];
            simulation = lmz.api.SimulationResult([0;1], schema, ...
                states, {'mode';'mode'}, struct(), struct(), struct(), ...
                struct(), 'EventRecords', records);

            result = returnMap.evaluate(states(1, :).', struct(), ...
                @(~,~,~,~) simulation, ...
                lmz.api.RunContext.synchronous(902));
            testCase.verifyTrue(result.StopCrossing.Accepted);
            testCase.verifyEqual(result.StopCrossing.EventId, 'RETURN');
            testCase.verifyEqual(result.ReturnTime, 1);
        end
    end
end

function value = localPlaneDescriptor()
value = lmz.poincare.PoincareSectionDescriptor(struct( ...
    'id', 'apex', 'label', 'Apex', 'kind', 'state_plane', ...
    'stateName', 'vy', 'threshold', 0, 'crossingDirection', -1, ...
    'stateSide', 'post', 'minimumReturnTime', 0.1, ...
    'requiredEventSequence', {{}}, 'returnOccurrence', 1, ...
    'coordinateNames', {{'vx','y'}}, ...
    'symmetryClass', 'lmz.poincare.PlanarTranslationSymmetry', ...
    'symmetryParameters', struct('id', 'planar_translation', ...
    'positionStateNames', {{'x'}}), ...
    'maturities', {{'tutorial'}}, 'validationStatus', 'tested'));
end

function value = localEventDescriptor(id, eventId, requiredEvents)
value = lmz.poincare.PoincareSectionDescriptor(struct( ...
    'id', id, 'label', id, 'kind', 'named_event', ...
    'eventId', eventId, 'crossingDirection', -1, ...
    'stateSide', 'post', 'minimumReturnTime', 0.1, ...
    'requiredEventSequence', {requiredEvents}, 'returnOccurrence', 1, ...
    'coordinateNames', {{'vx','y'}}, ...
    'symmetryClass', 'lmz.poincare.IdentitySymmetry', ...
    'maturities', {{'experimental'}}, 'validationStatus', 'tested'));
end

function value = localRecord(id, time, state)
value = struct('Id', id, 'Time', time, ...
    'FromMode', 'mode', 'ToMode', 'mode', ...
    'PreState', state, 'PostState', state, ...
    'DirectionalDerivative', -1, 'Metadata', struct());
end

function value = localSchema()
value = lmz.schema.VariableSchema([ ...
    lmz.schema.VariableSpec('x'); ...
    lmz.schema.VariableSpec('vx'); ...
    lmz.schema.VariableSpec('y'); ...
    lmz.schema.VariableSpec('vy')]);
end
