classdef TestScientificHeterogeneousStridePlan < matlab.unittest.TestCase
    %TESTSCIENTIFICHETEROGENEOUSSTRIDEPLAN Direct, non-identical Q/B plans.
    methods (Test)
        function quadrupedConsumesTwoDistinctSpecifications(testCase)
            model=lmzmodels.slip_quadruped.Model();
            result=runPlan(model,'back_left_touchdown', ...
                'k_swing',20.0000001,7101);
            verifyDirectPlan(testCase,result,'k_swing',20.0000001);
        end

        function bipedConsumesTwoDistinctSpecifications(testCase)
            model=lmzmodels.slip_biped.Model();
            result=runPlan(model,'left_touchdown', ...
                'omega_swing',6.50000001,7102);
            verifyDirectPlan(testCase,result,'omega_swing',6.50000001);
            testCase.verifyTrue(all(cellfun(@(item) ...
                item.EnergyAvailable,result.EnergyDiagnostics)));
        end

        function sourcePeriodicFastPathRemainsDistinct(testCase)
            request=lmz.multistride.MultiStrideRequest( ...
                'NumberOfStrides',2);
            result=lmz.services.MultiStrideSimulationService().simulate( ...
                lmzmodels.slip_quadruped.Model(),request, ...
                lmz.api.RunContext.synchronous(7103));
            testCase.verifyTrue( ...
                result.Diagnostics.HomogeneousClosedStrideRepetition);
            testCase.verifyEqual(result.Diagnostics.SourceProblemId, ...
                'periodic_apex');
            testCase.verifyFalse(result.Diagnostics.HiddenTimingSolve);
            testCase.verifyTrue(result.Diagnostics.StrictlyIncreasingTime);
        end
    end
end

function result=runPlan(model,sectionId,controlName,controlValue,seed)
problem=model.createProblem('periodic_orbit',struct( ...
    'StartSectionId',sectionId,'StopSectionId',sectionId));
decoded=problem.SectionCodec.decode( ...
    problem.getDecisionSchema().defaults());
firstSchedule=decoded.EventSchedule;
secondSchedule=firstSchedule.withTimes( ...
    1.00000001*firstSchedule.times(), ...
    1.00000001*firstSchedule.ReturnTime);
parameters=problem.getParameterSchema().defaults();
controls=struct();controls.(controlName)=controlValue;
specs(1,1)=lmz.multistride.StrideSpec('Index',1, ...
    'StartSectionId',sectionId,'StopSectionId',sectionId, ...
    'StartStateSide',problem.StartSection.StateSide, ...
    'StopStateSide',problem.StopSection.StateSide, ...
    'EventSchedule',firstSchedule,'PhysicalParameters',parameters, ...
    'InitialStateSource','specified', ...
    'InitialSectionState',decoded.InitialState, ...
    'CompletionStatus','completed');
specs(2,1)=lmz.multistride.StrideSpec('Index',2, ...
    'StartSectionId',sectionId,'StopSectionId',sectionId, ...
    'StartStateSide',problem.StartSection.StateSide, ...
    'StopStateSide',problem.StopSection.StateSide, ...
    'EventSchedule',secondSchedule,'PhysicalParameters',parameters, ...
    'ControlParameters',controls, ...
    'InitialStateSource','previous_terminal_state', ...
    'CompletionStatus','completed');
policy=lmz.multistride.EnergyConsistencyPolicy('Id','allow_non_neutral');
plan=lmz.multistride.StridePlan('ModelId',model.getManifest().id, ...
    'ProblemId','n_stride_simulation','RequestedStrideCount',2, ...
    'InitialState',decoded.InitialState, ...
    'DefaultPhysicalParameters',parameters,'StrideSpecs',specs, ...
    'EnergyPolicy',policy,'Provenance',struct( ...
    'Source','explicit-scientific-two-stride-test'));
request=lmz.multistride.MultiStrideRequest('NumberOfStrides',2, ...
    'StridePlan',plan,'EnergyPolicy',policy,'EnergyNeutralOnly',false);
result=lmz.services.MultiStrideSimulationService().simulate( ...
    model,request,lmz.api.RunContext.synchronous(seed));
end

function verifyDirectPlan(testCase,result,controlName,controlValue)
diagnostics=result.Diagnostics;
testCase.verifyEqual(result.CompletionStatus,'complete');
testCase.verifyEqual(result.CompletedStrideCount,2);
testCase.verifyTrue(diagnostics.HeterogeneousStridePlan);
testCase.verifyFalse(diagnostics.HomogeneousClosedStrideRepetition);
testCase.verifyTrue(diagnostics.DirectSectionIntegration);
testCase.verifyFalse(diagnostics.ApexOracleUsedDuringStridePropagation);
testCase.verifyTrue(diagnostics.StrictlyIncreasingTime);
testCase.verifyFalse(diagnostics.HiddenTimingSolve);
testCase.verifyTrue(diagnostics.AllInterfaceStatesContinuous);
testCase.verifyTrue(diagnostics.AllSectionsAccepted);
testCase.verifyTrue(diagnostics.AllContactTimingsFeasible);
testCase.verifyLessThanOrEqual(max(diagnostics.InterfaceDefectNorms),1e-8);
testCase.verifyNotEqual( ...
    diagnostics.PerStrideSchedules{1}.ReturnTime, ...
    diagnostics.PerStrideSchedules{2}.ReturnTime);
testCase.verifyEqual( ...
    diagnostics.AppliedControlOverrides{2}.(controlName), ...
    controlValue,'AbsTol',1e-12);
testCase.verifyEqual(numel(result.EnergyDiagnostics),2);
testCase.verifyTrue(all(cellfun(@(item)item.Accepted, ...
    result.EnergyDiagnostics)));
testCase.verifyEqual( ...
    diagnostics.StrideBoundaries(2).StartIndex, ...
    diagnostics.StrideBoundaries(1).EndIndex+1);
end
