classdef TestPoincareCatalogValidation < matlab.unittest.TestCase
    methods (Test)
        function builtInCatalogsValidateAgainstPhysicalStates(testCase)
            modelIds = {'slip_quadruped','slip_biped', ...
                'slip_quad_load','tutorial_hopper'};
            schemas = { ...
                lmzmodels.slip_quadruped.PhysicalStateSchema.create(), ...
                lmzmodels.slip_biped.PhysicalStateSchema.create(), ...
                lmzmodels.slip_quad_load.PhysicalStateSchema.create(), ...
                lmzmodels.tutorial_hopper.PhysicalStateSchema.create()};
            % Round 10 adds validated pre-reset, state-plane, and composite
            % charts to the unloaded scientific models.
            expectedCounts = [13 9 10 4];
            for index = 1:numel(modelIds)
                path = fullfile(lmz.util.ProjectPaths.catalog(), ...
                    modelIds{index}, 'poincare_sections.json');
                registry = lmz.poincare.PoincareSectionRegistry.fromJson( ...
                    path, 'ModelId', modelIds{index}, ...
                    'StateSchema', schemas{index});
                testCase.verifyEqual(numel(registry.listSections()), ...
                    expectedCounts(index), modelIds{index});
                testCase.verifyTrue(registry.hasSection('apex'), ...
                    modelIds{index});
                testCase.verifyLength(registry.fingerprint(), 64, ...
                    modelIds{index});
            end
        end

        function defaultsAndTranslationStatesAreExplicit(testCase)
            path = fullfile(lmz.util.ProjectPaths.catalog(), ...
                'slip_quad_load', 'poincare_sections.json');
            registry = lmz.poincare.PoincareSectionRegistry.fromJson( ...
                path, 'ModelId', 'slip_quad_load', 'StateSchema', ...
                lmzmodels.slip_quad_load.PhysicalStateSchema.create());

            section = registry.defaultSection('n_stride_periodic');
            symmetry = registry.symmetryFor(section.Id);
            testCase.verifyEqual(section.Id, 'apex');
            testCase.verifyClass(symmetry, ...
                'lmz.poincare.PlanarTranslationSymmetry');
            testCase.verifyEqual(symmetry.PositionStateNames, ...
                {'quad_x','load_x'});
        end
    end
end
